java_test(
    name = "test-synthesized",
    srcs = [
        "SynthesizedFirefoxDriverTests.java",
    ],
    vm_args = [
        "-Dselenium.browser=ff",
        "-Dwebdriver.firefox.marionette=false",
    ],
    deps = [
        ":tests",
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/test/org/openqa/selenium:large-tests",
        "//java/client/test/org/openqa/selenium/testing:test-base",
        "//third_party/java/junit:junit",
    ],
)

java_test(
    name = "marionette",
    srcs = [
        "SynthesizedFirefoxDriverTests.java",
    ],
    vm_args = [
        "-Dselenium.browser=ff",
        "-Dwebdriver.firefox.marionette=true",
    ],
    deps = [
        ":tests",
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/test/org/openqa/selenium:large-tests",
        "//java/client/test/org/openqa/selenium/testing:test-base",
        "//third_party/java/junit:junit",
    ],
)

java_library(
    name = "tests",
    srcs = glob(["*Test.java"]) + [
        "FirefoxSpecificTests.java",
    ],
    resources = [
        ":firebug",
    ],
    deps = [
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/src/org/openqa/selenium/firefox:firefox",
        "//java/client/src/org/openqa/selenium/firefox/xpi:firefox-xpi",
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/client/src/org/openqa/selenium/support/ui:wait",
        "//java/client/test/org/openqa/selenium:helpers",
        "//java/client/test/org/openqa/selenium:tests",
        "//java/client/test/org/openqa/selenium/build:build",
        "//java/client/test/org/openqa/selenium/testing:test-base",
        "//java/client/test/org/openqa/selenium/testing/drivers:drivers",
        "//third_party/java/guava:guava",
        "//third_party/java/assertj:assertj",
        "//third_party/java/junit:junit",
        "//third_party/java/mockito:mockito-core",
    ],
)

export_file(
    name = "firebug",
    src = "//third_party/firebug:firebug",
    out = "firebug-1.5.0-fx.xpi",
)
