java_test(name = 'test-synthesized',
  srcs = [
    'SynthesizedFirefoxDriverTests.java'
  ],
  vm_args = [
    '-Dselenium.browser=ff',
  ],
  deps = [
    ':tests',
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/test/org/openqa/selenium/testing:test-base',
    '//java/client/test/org/openqa/selenium:large-tests',
    '//third_party/java/junit:junit',
  ],
)

java_library(name = 'tests',
  srcs = glob(['*Test.java', 'internal/*.java']) + [
    'FirefoxSpecificTests.java',
  ],
  deps = [
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/src/org/openqa/selenium/firefox:firefox',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//java/client/src/org/openqa/selenium/support/ui:wait',
    '//java/client/test/org/openqa/selenium:tests',
    '//java/client/test/org/openqa/selenium/testing:test-base',
    '//java/client/test/org/openqa/selenium/testing/drivers:drivers',
    '//third_party/java/guava:guava',
    '//third_party/java/hamcrest:hamcrest',
    '//third_party/java/junit:junit',
    '//third_party/java/mockito:mockito',
  ],
)
