java_test(
    name = "edge",
    srcs = [
        "EdgeDriverTests.java",
    ],
    vm_args = [
        "-Dselenium.browser=edge",
        "-Dwebdriver.edge.edgehtml=false"
    ],
    deps = [
        ":tests",
        "//java/client/test/org/openqa/selenium:large-tests",
        "//third_party/java/junit:junit",
    ],
)

java_test(
    name = "edgehtml",
    srcs = [
        "EdgeDriverTests.java",
    ],
    vm_args = [
        "-Dselenium.browser=edge"
    ],
    deps = [
        ":tests",
        "//java/client/test/org/openqa/selenium:large-tests",
        "//third_party/java/junit:junit",
    ],
)

java_library(
    name = "tests",
    srcs = glob(["*Test.java"]),
    deps = [
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/src/org/openqa/selenium/chrome:chrome",
        "//java/client/src/org/openqa/selenium/edge:edge",
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/client/src/org/openqa/selenium/support/ui:wait",
        "//java/client/test/org/openqa/selenium/build:build",
        "//java/client/test/org/openqa/selenium/testing:test-base",
        "//third_party/java/assertj:assertj",
        "//third_party/java/guava:guava",
        "//third_party/java/junit:junit",
    ],
)
