export_file(name = 'hub',
  src = 'hub.html',
  out = 'hub.html',
  visibility = [
    '//java/server/src/org/openqa/selenium/remote/server:hub',
  ],
)

export_file(name = 'style',
  src = 'style.css',
  out = 'style.css',
  visibility = [
    '//java/server/src/org/openqa/selenium/remote/server:style',
  ],
)

browsers = {
  'firefox': 'ff',
  'chrome': 'chrome',
  'ie': 'ie'}
for browser in browsers.keys():
  java_test(
    name = 'remote-%s' % browser,
    vm_args = [
      '-Dselenium.browser=%s' % browsers[browser],
      '-Dwebdriver.firefox.marionette=false',
      '-Djs.test.timeout=20',
      '-Djs.test.dir=%s' % get_base_path(),
    ],
    test_classes = [
      'org.openqa.selenium.javascript.ClosureTestSuite',
    ],
    deps = [
      '//java/client/test/org/openqa/selenium/javascript:javascript',
      '//java/client/src/org/openqa/selenium/chrome:chrome',
      '//java/client/src/org/openqa/selenium/edge:edge',
      '//java/client/src/org/openqa/selenium/ie:ie',
      '//java/client/src/org/openqa/selenium/firefox:firefox',
    ],
  )


js_binary(name = 'client',
  srcs = glob(['*.js', 'ui/*.js',]),
  deps = [
    '//javascript/atoms:errors',
    '//javascript/webdriver:http',
    '//third_party/closure:closure',
  ],
  flags = [
    '--jscomp_error=accessControls',
    '--jscomp_error=ambiguousFunctionDecl',
    '--jscomp_error=checkRegExp',
    '--jscomp_error=checkTypes',
    '--jscomp_error=checkVars',
    '--jscomp_error=constantProperty',
    '--jscomp_error=deprecated',
    '--jscomp_error=duplicateMessage',
    '--jscomp_error=es5Strict',
    '--jscomp_error=externsValidation',
    '--jscomp_error=fileoverviewTags',
    '--jscomp_error=globalThis',
    '--jscomp_error=invalidCasts',
    '--jscomp_error=missingProperties',
    '--jscomp_error=nonStandardJsDocs',
    '--jscomp_error=strictModuleDepCheck',
    '--jscomp_error=typeInvalidation',
    '--jscomp_error=undefinedVars',
    '--jscomp_error=unknownDefines',
    '--jscomp_error=uselessCode',
    '--jscomp_error=visibility',

    '--language_in=ECMASCRIPT6_STRICT',
    '--language_out=ECMASCRIPT5_STRICT',
    '--third_party=false',

    '--compilation_level=ADVANCED_OPTIMIZATIONS',
  ],
  visibility = [
    '//java/server/src/org/openqa/selenium/remote/server:client',
  ],
)
