export_file(
  name = 'noblur32',
  out = 'i386/x_ignore_nofocus.so',
  src = 'i386/libnoblur.so',
  visibility = [
    '//java/client/src/org/openqa/selenium/firefox:i386',
  ],
)

export_file(
  name = 'noblur64',
  out = 'amd64/x_ignore_nofocus.so',
  src = 'amd64/libnoblur64.so',
  visibility = [
    '//java/client/src/org/openqa/selenium/firefox:amd64',
  ],
)

