export_file(name = 'nsINativeEvents.xpt',
  visibility = [
    '//cpp/webdriver-firefox:native-events-xpt',
  ],
)

export_file(name = 'nsINativeMouse.xpt',
  visibility = [
    '//cpp/webdriver-firefox:native-mouse-xpt',
  ],
)

export_file(name = 'nsINativeKeyboard.xpt',
  visibility = [
    '//cpp/webdriver-firefox:native-keyboard-xpt',
  ],
)

export_file(name = 'nsINativeIME.xpt',
  visibility = [
    '//cpp/webdriver-firefox:native-ime-xpt',
  ],
)

export_file(name = "imehandler-dll",
  out = 'imehandler.dll',
  src = 'Win32/Release/imehandler.dll',
  visibility = [ '//javascript/firefox-driver:win-components' ],
)
