java_library(
    name = "browser",
    srcs = [
        "Browser.java",
    ],
    visibility = [
        "//java/client/test/...",
        "//java/server/test/...",
    ],
)

java_library(
    name = "drivers",
    srcs = glob(["*Driver.java", "*Supplier.java"]) + [
        "OutOfProcessSeleniumServer.java",
        "WebDriverBuilder.java",
    ],
    deps = [
        ":browser",
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/src/org/openqa/selenium/chrome:chrome",
        "//java/client/src/org/openqa/selenium/edge/edgehtml:edgehtml",
        "//java/client/src/org/openqa/selenium/firefox:firefox",
        "//java/client/src/org/openqa/selenium/ie:ie",
        "//java/client/src/org/openqa/selenium/opera:opera",
        "//java/client/src/org/openqa/selenium/safari:safari",
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/client/src/org/openqa/selenium/support:support",
        "//java/client/test/org/openqa/selenium:helpers",
        "//java/client/test/org/openqa/selenium/build:build",
        "//java/client/test/org/openqa/selenium/testing:annotations",
        "//third_party/java/guava:guava",
        "//third_party/java/selenium:htmlunit-driver",
        "//third_party/java/junit:junit",
    ],
    visibility = [
        "//java/client/test/...",
        "//java/server/test/...",
    ],
)
