SUITES = glob([
  'internal/**/*Tests.java',
  'plugin/**/*Tests.java',
])

java_test(name = 'grid',
  srcs = SUITES,
  deps = [
    ':test',
    '//java/server/src/org/openqa/grid:grid',
    '//java/server/src/org/openqa/grid/common:common',
    '//java/client/src/org/openqa/selenium/net:net',
    '//java/client/src/org/openqa/selenium/remote:capabilities',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//third_party/java/junit:junit',
    '//third_party/java/httpcomponents:httpclient',
    '//third_party/java/gson:gson',
    '//third_party/java/servlet:servlet-api',
  ],
)

java_library(name = 'test',
  srcs = glob([
    'internal/**/*.java',
    'plugin/**/*.java',
  ], excludes = SUITES),
  resources = [
    'internal/configuration/grid_configuration_test1.yml',
    'internal/configuration/grid_configuration_test2.yml',
  ],
  deps = [
    '//java/client/src/com/thoughtworks/selenium:selenium',
    '//java/server/src/org/openqa/grid:grid',
    '//java/server/src/org/openqa/grid/common:common',
    '//java/client/src/org/openqa/selenium:webdriver-api',
    '//java/client/src/org/openqa/selenium/net:net',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//third_party/java/gson:gson',
    '//third_party/java/httpcomponents:httpclient',
    '//third_party/java/junit:junit',
    '//third_party/java/mockito:mockito',
    '//third_party/java/servlet:servlet-api',
  ],
)
