SUITES = glob([
  'internal/**/*Tests.java',
  'plugin/**/*Tests.java',
])

java_test(name = 'grid',
  srcs = SUITES,
  deps = [
    ':test',
    '//java/server/src/org/openqa/grid:grid',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//third_party/java/beust:jcommander',
    '//third_party/java/junit:junit',
    '//third_party/java/httpcomponents:httpclient',
    '//third_party/java/gson:gson',
    '//third_party/java/servlet:servlet-api',
  ],
)

java_library(name = 'test',
  srcs = glob([
    'internal/**/*.java',
    'plugin/**/*.java',
  ], excludes = SUITES),
  deps = [
    '//java/client/src/com/thoughtworks/selenium:leg-rc',
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//java/server/src/org/openqa/grid:grid',
    '//java/server/src/org/openqa/selenium/remote/server:server',
    '//third_party/java/beust:jcommander',
    '//third_party/java/gson:gson',
    '//third_party/java/httpcomponents:httpclient',
    '//third_party/java/junit:junit',
    '//third_party/java/mockito:mockito',
    '//third_party/java/servlet:servlet-api',
  ],
)
