# Licensed to the Software Freedom Conservancy (SFC) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The SFC licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.


module Selenium
  module WebDriver
    class BiDi
      class Browser
        @bidi: BiDi
        @window: Window?

        def initialize: (BiDi bidi) -> void

        def create_user_context: () -> Hash[String, String]

        def user_contexts: () -> Hash[String, Array[Hash[String, String]]]

        def remove_user_context: (String user_context) -> Hash[untyped, untyped]

        def windows: () -> Array[Window]

        def window: () -> Window?
      end
    end
  end
end
