module Selenium
  module WebDriver
    class BiDi
      class BrowsingContext
        @bidi: BiDi

        READINESS_STATE: Hash[String, String]

        def initialize: (Remote::Bridge bridge) -> void

        def navigate: (String url, String? context_id) -> void

        def traverse_history: (Integer delta, String? context_id) -> void

        def reload: (String? context_id, ?ignore_cache: bool) -> void

        def close: (String? context_id) -> void

        def create: (?type: Symbol | String | nil, ?context_id: String | nil) -> String
      end
    end
  end
end
