
java_test(
    name = "sessionmap",
    srcs = glob(["*.java"]),
    labels = [
        "small",
    ],
    deps = [
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/client/src/org/openqa/selenium/remote/tracing:tracing",
        "//java/server/src/org/openqa/selenium/events/zeromq:zeromq",
        "//java/server/src/org/openqa/selenium/grid/data:data",
        "//java/server/src/org/openqa/selenium/grid/sessionmap:sessionmap",
        "//java/server/src/org/openqa/selenium/grid/sessionmap/local:local",
        "//java/server/src/org/openqa/selenium/grid/sessionmap/remote:remote",
        "//java/server/src/org/openqa/selenium/grid/web:web",
        "//java/server/test/org/openqa/selenium/grid/web:utils",
        "//third_party/java/assertj:assertj",
        "//third_party/java/junit:junit",
    ],
)