java_test(
    name = "chrome",
    srcs = [
        "ChromeDriverTests.java",
    ],
    vm_args = [
        "-Dselenium.browser=chrome",
    ],
    deps = [
        ":tests",
        "//java/client/test/org/openqa/selenium:large-tests",
        "//java/client/test/org/openqa/selenium/devtools:devtools",
        "//third_party/java/junit:junit",
    ],
)

java_library(
    name = "tests",
    srcs = glob(["*Test.java"]),
    deps = [
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/src/org/openqa/selenium/chrome:chrome",
        "//java/client/src/org/openqa/selenium/devtools:devtools",
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/client/src/org/openqa/selenium/support/ui:wait",
        "//java/client/test/org/openqa/selenium/build:build",
        "//java/client/test/org/openqa/selenium/testing:test-base",
        "//third_party/java/assertj:assertj",
        "//third_party/java/guava:guava",
        "//third_party/java/junit:junit",
    ],
)
