java_library(name = 'cybervillains',
  srcs = glob(['ca/*.java']),
  deps = [
    '//java/server/src/org/openqa/selenium/server/security:security',
    '//third_party/java/bouncycastle:bouncycastle',
  ],
  visibility = [
    '//java/server/src/org/openqa/selenium/server:server',
  ],
)

