java_library(name = 'safari',
  srcs = glob(['*.java']),
  resources = [
    ':client',
    ':extension',
  ],
  deps = [
    '//java/client/src/org/openqa/selenium:codecs',
    '//java/client/src/org/openqa/selenium:webdriver-api',
    '//java/client/src/org/openqa/selenium/io:io',
    '//java/client/src/org/openqa/selenium/browserlaunchers/locators:locators',
    '//java/client/src/org/openqa/selenium/net:net',
    '//java/client/src/org/openqa/selenium/os:os',
    '//java/client/src/org/openqa/selenium/remote:capabilities',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//third_party/java/guava-libraries:guava-libraries',
    '//third_party/java/gson:gson',
    '//third_party/java/netty:netty',
  ],
  visibility = ['PUBLIC'],
)

export_file(name = 'client',
  src = '//javascript/safari-driver:client',
  out = 'client.js',
)
