java_test(
    name = "chrome-rc-test",
    srcs = [
        "WebDriverSeleniumTestSuite.java",
    ],
    vm_args = [
        "-Dselenium.browser=chrome",
    ],
    deps = [
        ":tests",
        "//third_party/java/junit:junit",
    ],
)

java_test(
    name = "firefox-rc-test",
    srcs = [
        "WebDriverSeleniumTestSuite.java",
    ],
    vm_args = [
        "-Dselenium.browser=ff",
    ],
    deps = [
        ":tests",
        "//third_party/java/junit:junit",
    ],
)

java_test(
    name = "ie-rc-test",
    srcs = [
        "WebDriverSeleniumTestSuite.java",
    ],
    vm_args = [
        "-Dselenium.browser=ie",
    ],
    deps = [
        ":tests",
        "//third_party/java/junit:junit",
    ],
)

java_library(
    name = "tests",
    srcs = glob([
        "*.java",
        "condition/*.java",
        "corebased/*.java",
        "testing/*.java",
    ]),
    resources = [
        "testHelpers.js",
    ],
    deps = [
        "//java/client/src/com/thoughtworks/selenium:leg-rc",
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/src/org/openqa/selenium/chrome:chrome",
        "//java/client/src/org/openqa/selenium/edge/edgehtml:edgehtml",
        "//java/client/src/org/openqa/selenium/firefox:firefox",
        "//java/client/src/org/openqa/selenium/ie:ie",
        "//java/client/src/org/openqa/selenium/opera:opera",
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/client/src/org/openqa/selenium/safari:safari",
        "//java/client/test/org/openqa/selenium:helpers",
        "//java/server/test/org/openqa/selenium:server-with-tests",
        "//java/client/test/org/openqa/selenium/build:build",
        "//java/client/test/org/openqa/selenium/environment:environment",
        "//java/client/test/org/openqa/selenium/testing:test-base",
        "//java/client/test/org/openqa/selenium/testing/drivers:browser",
        "//java/client/test/org/openqa/selenium/testing/drivers:drivers",
        "//third_party/java/guava:guava",
        "//third_party/java/jetty:jetty",
        "//third_party/java/junit:junit",
        "//third_party/java/mockito:mockito-core",
        "//third_party/java/servlet:javax.servlet-api",
    ],
    visibility = [
        "//java/server/test/org/openqa/selenium/server/htmlrunner:",
    ],
)
