java_test(
    name = "proxy",
    srcs = glob(["*.java"]),
    deps = [
        "//java/server/src/org/openqa/grid:grid",
        "//java/server/src/org/openqa/grid/selenium:classes",
        "//third_party/java/beust:jcommander",
        "//third_party/java/junit:junit",
        "//third_party/java/guava:guava",
    ],
)
