module Selenium
  module WebDriver
    module FedCM
      module Dialog
        DIALOG_TYPE_ACCOUNT_LIST: untyped
        DIALOG_TYPE_AUTO_REAUTH: untyped

        def open?: -> untyped

        def title: -> untyped

        def type: -> untyped
      end
    end
  end
end
