java_library(
    name = "devtools",
    srcs = glob(["**/*.java"]),
    deps = [
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/src/org/openqa/selenium/json:json",
        "//java/client/src/org/openqa/selenium/remote/http:http",
        "//third_party/java/guava:guava",
    ],
    visibility = [
        "//java/client/src/org/openqa/selenium/remote:",
        "//java/client/test/...",
    ],
)
