java_library(
  name = 'service',
  srcs = glob(['*.java']),
  deps = [
    '//java/client/src/org/openqa/selenium:webdriver-api',
    '//java/client/src/org/openqa/selenium/io:io',
    '//java/client/src/org/openqa/selenium/logging:logging',
    '//java/client/src/org/openqa/selenium/net:net',
    '//java/client/src/org/openqa/selenium/os:os',
    '//java/client/src/org/openqa/selenium/remote:api',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//third_party/java/guava-libraries:guava-libraries',
  ],
  visibility = ['PUBLIC'],
)
