# Licensed to the Software Freedom Conservancy (SFC) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The SFC licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.


module Selenium
  module WebDriver
    module Support
      class EventFiringBridge
        @delegate: untyped

        @listener: untyped

        @driver: untyped

        def initialize: (untyped delegate, untyped listener) -> void

        def get: (untyped url) -> untyped

        def go_forward: () -> untyped

        def go_back: () -> untyped

        def click_element: (untyped ref) -> untyped

        def clear_element: (untyped ref) -> untyped

        def send_keys_to_element: (untyped ref, untyped keys) -> untyped

        def find_element_by: (untyped how, untyped what, ?untyped? parent) -> untyped

        def find_elements_by: (untyped how, untyped what, ?untyped? parent) -> untyped

        def execute_script: (untyped script, *untyped args) -> untyped

        def quit: () -> untyped

        def close: () -> untyped

        private

        def create_element: (untyped ref) -> untyped

        def driver: () -> untyped

        def dispatch: (untyped name, *untyped args) { () -> untyped } -> untyped

        def method_missing: (untyped meth, *untyped args) { () -> untyped } -> untyped
      end
    end
  end
end
