using System;
using System.Collections.Generic;
using System.Text;

namespace OpenQA.Selenium.Remote
{
    public enum DriverCommand
    {
        NewSession,
        DeleteSession,
        Close,
        Quit,
        Get,
        GoBack,
        GoForward,
        Refresh,
        AddCookie,
        GetCookie,
        GetAllCookies,
        DeleteCookie,
        DeleteAllCookies,
        FindElement,
        FindElements,
        FindChildElement,
        FindChildElements,
        ClearElement,
        ClickElement,
        HoverOverElement,
        SendKeysToElement,
        SubmitElement,
        ToggleElement,
        GetCurrentWindowHandle,
        GetWindowHandles,
        SwitchToWindow,
        SwitchToFrame,
        SwitchToFrameByIndex,
        SwitchToFrameByName,
        SwitchToDefaultContent,
        GetActiveElement,
        GetCurrentUrl,
        GetPageSource,
        GetTitle,
        ExecuteScript,
        GetSpeed,
        SetSpeed,
        SetBrowserVisible,
        IsBrowserVisible,
        GetElementText,
        GetElementValue,
        GetElementTagName,
        SetElementSelected,
        DragElement,
        IsElementSelected,
        IsElementEnabled,
        IsElementDisplayed,
        GetElementLocation,
        GetElementLocationOnceScrolledIntoView,
        GetElementSize,
        GetElementAttribute,
        GetElementValueOfCssProperty,
        ElementEquals,
        Screenshot
    }
}
