java_library(
    name = "jmx",
    srcs = glob(["*.java"]),
    deps = [
    ],
    visibility = [
        "//java/server/src/org/openqa/selenium/grid/...",
        "//java/server/test/...",
    ],
)
