load("@rules_python//python:defs.bzl", "py_library")
load("@rules_python//python:packaging.bzl", "py_wheel")
load("//common:defs.bzl", "copy_file")

SM_VERSION = "4.45.0"

copy_file(
    name = "manager-binary",
    src = "//common/manager:selenium-manager-windows",
    out = "selenium_manager_windows/bin/selenium-manager.exe",
)

py_library(
    name = "lib",
    srcs = ["selenium_manager_windows/__init__.py"],
    data = [":manager-binary"],
    imports = ["."],
)

py_wheel(
    name = "selenium-manager-windows-wheel",
    abi = "none",
    classifiers = [
        "Operating System :: Microsoft :: Windows",
        "Programming Language :: Python",
        "Topic :: Software Development :: Testing",
    ],
    description_content_type = "text/plain",
    distribution = "selenium_manager_windows",
    entry_points = {
        "console_scripts": {
            "selenium-manager": "selenium_manager_windows:main",
        },
    },
    homepage = "https://www.selenium.dev",
    license = "Apache-2.0",
    platform = "win32",
    python_requires = ">=3.9",
    python_tag = "py3",
    strip_path_prefixes = ["py/selenium-manager-windows/"],
    summary = "Selenium Manager binary for Windows (ia32 + x64)",
    tags = ["release-artifact"],
    version = SM_VERSION,
    visibility = ["//visibility:public"],
    deps = [":lib"],
)
