[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "selenium-manager-windows"
version = "4.45.0"
license = "Apache-2.0"
license-files = ["LICENSE", "NOTICE"]
description = "Selenium Manager binary for Windows (ia32 + x64)"
requires-python = ">=3.9"
classifiers = [
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python",
    "Topic :: Software Development :: Testing",
]

[project.urls]
homepage = "https://www.selenium.dev"
source = "https://github.com/SeleniumHQ/selenium/tree/trunk/py/selenium-manager-windows"
issues = "https://github.com/SeleniumHQ/selenium/issues"

[project.scripts]
selenium-manager = "selenium_manager_windows:main"

[tool.setuptools.package-data]
selenium_manager_windows = ["bin/selenium-manager.exe"]
