java_library(
    name = "package-lib",
    srcs = [
        "PackageParser.java",
    ],
    deps = [
        "//third_party/java/javaparser:javaparser-core",
        "//third_party/java/guava:guava",
    ],
)

java_binary(
    name = "package",
    main_class = "org.openqa.selenium.tools.PackageParser",
    deps = [
        ":package-lib",
    ],
    visibility = [
        "//java/client/src/org/openqa/selenium:client-combined-sources",
        "//java/server/src/org/openqa/selenium/grid:selenium-server-sources",
    ],
)

java_library(
    name = "module-maker-lib",
    srcs = [
        "ModuleMaker.java",
    ],
    deps = [
        "//third_party/java/bytebuddy:byte-buddy",
        "//third_party/java/javaparser:javaparser-core",
    ],
)

java_binary(
    name = "module-maker",
    main_class = "org.openqa.selenium.tools.ModuleMaker",
    deps = [
        ":module-maker-lib",
    ],
    visibility = [
        "PUBLIC",
    ],
)
