# BUILD FILE SYNTAX: SKYLARK
java_library(
  name = "package-lib",
  srcs = [
    "PackageParser.java",
  ],
  deps = [
    "//third_party/java/javaparser:javaparser-core",
  ],
)

java_binary(
  name = "package",
  main_class = "org.openqa.selenium.tools.PackageParser",
  deps = [
    ":package-lib",
  ],
  visibility = [
    "//java/client/src/org/openqa/selenium:client-combined-sources",
    "//java/server/src/org/openqa/grid/selenium:selenium-server-sources",
  ],
)
