java_library(
    name = "annotations",
    srcs = [
        "Ignore.java",
        "IgnoreList.java",
        "NeedsLocalEnvironment.java",
        "NeedsFreshDriver.java",
        "NoDriverAfterTest.java",
        "NoDriverBeforeTest.java",
        "NotYetImplemented.java",
        "NotYetImplementedList.java",
        "SwitchToTopAfterTest.java",
    ],
    deps = [
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/test/org/openqa/selenium/testing/drivers:browser",
    ],
    visibility = [
        "//java/client/test/...",
    ],
)

java_library(
    name = "test-base",
    srcs = [
        "IgnoreComparator.java",
        "JUnit4TestBase.java",
        "NotificationRule.java",
        "Pages.java",
        "Safely.java",
        "SeleniumTestRunner.java",
        "StaticResources.java",
        "TearDownFixture.java",
        "TestIgnorance.java",
        "TestUtilities.java",
    ],
    exported_deps = [
        ":annotations",
        "//java/client/test/org/openqa/selenium/environment:environment",
        "//java/client/test/org/openqa/selenium/testing/drivers:browser",
    ],
    deps = [
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/src/org/openqa/selenium/json:json",
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/client/src/org/openqa/selenium/support/ui:wait",
        "//java/client/test/org/openqa/selenium/build:build",
        "//java/client/test/org/openqa/selenium/testing/drivers:drivers",
        "//third_party/java/github:org.eclipse.egit.github.core",
        "//third_party/java/guava:guava",
        "//third_party/java/assertj:assertj",
        "//third_party/java/junit:junit",
        "//third_party/java/selenium:htmlunit-driver",
    ],
    visibility = [
        "//java/client/test/...",
        "//java/server/test/...",
    ],
)

java_library(
    name = "small-tests",
    srcs = [
        "IgnoreComparatorUnitTest.java",
    ],
    deps = [
        ":test-base",
        "//java/client/test/org/openqa/selenium/testing/drivers:browser",
        "//java/client/test/org/openqa/selenium/testing/drivers:drivers",
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/test/org/openqa/selenium/testing:annotations",
        "//third_party/java/guava:guava",
        "//third_party/java/junit:junit",
        "//third_party/java/mockito:mockito-core",
    ],
    visibility = [
        "//java/client/test/org/openqa/selenium:small-tests",
    ],
)
