java_library(name = 'annotations',
  srcs = [
    'Ignore.java',
    'JavascriptEnabled.java',
    'NativeEventsRequired.java',
    'NeedsLocalEnvironment.java',
    'NotYetImplemented.java',
  ],
  deps = [
    '//java/client/src/org/openqa/selenium:platform',
  ],
  visibility = [
    '//java/client/test/...',
  ],
)

java_library(name = 'helpers',
  srcs = [
    'DevMode.java',
    'InProject.java',
  ],
  deps = [
    '//java/client/src/org/openqa/selenium:exceptions',
  ],
  visibility = [
    '//java/client/test/...',
    '//java/server/test/...',
  ],
)

java_library(name = 'test-base',
  srcs = [
    'JUnit4TestBase.java',
    'ParallelSuite.java',
    'ProxyServer.java',
    'SeleniumTestRunner.java',
    'TestUtilities.java',
  ],
  exported_deps = [
    ':annotations',
    ':helpers',
    '//java/client/test/org/openqa/selenium:annotations',
    '//java/client/test/org/openqa/selenium:helpers',
    '//java/client/test/org/openqa/selenium/testing/drivers:browser',
    '//java/client/test/org/openqa/selenium/environment:environment',
  ],
  deps = [
    '//java/client/src/org/openqa/selenium:webdriver-api',
    '//java/client/src/org/openqa/selenium/htmlunit:htmlunit',
    '//java/client/src/org/openqa/selenium/net:net',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//java/client/src/org/openqa/selenium/support/ui:wait',
    '//java/client/test/org/openqa/selenium/testing/drivers:drivers',
    '//third_party/java/guava:guava',
    '//third_party/java/hamcrest:hamcrest',
    '//third_party/java/junit:junit',
    '//third_party/java/little_proxy:little_proxy',
    '//third_party/java/netty:netty',
  ],
  visibility = [
    '//java/client/test/...',
    '//java/server/test/...',
  ],
)
