java_binary(
  name = 'main',
  main_class = 'com.thoughtworks.selenium.corerunner.Main',
  deps = [
    ':corerunner',
  ],
)

java_library(
  name = 'corerunner',
  srcs = glob(['*.java']),
  deps = [
    '//java/client/src/com/thoughtworks/selenium:selenium',
    '//java/client/src/com/thoughtworks/selenium/webdriven:webdriven',
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/src/org/openqa/selenium/chrome:chrome',
    '//java/client/src/org/openqa/selenium/edge:edge',
    '//java/client/src/org/openqa/selenium/firefox:firefox',
    '//java/client/src/org/openqa/selenium/ie:ie',
    '//java/client/src/org/openqa/selenium/opera:opera',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//java/client/src/org/openqa/selenium/safari:safari',
    '//third_party/java/guava:guava',
  ],
  visibility = [
  ],
)
