java_library(name = 'lift',
  srcs = glob(['**/*.java']),
  deps = [
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/src/org/openqa/selenium/support/ui:clock',
    '//java/client/src/org/openqa/selenium/support/ui:wait',
    '//third_party/java/guava:guava',
    '//third_party/java/hamcrest:hamcrest',
    '//third_party/java/junit:junit',
  ],
  visibility = ['PUBLIC'],
)
