java_library(name = 'lift',
  srcs = glob(['**/*.java']),
  deps = [
    '//java/client/src/org/openqa/selenium:webdriver-api',
    '//java/client/src/org/openqa/selenium/support/ui:wait',
    '//java/client/src/org/openqa/selenium/support/ui:clock',
    '//third_party/java/guava-libraries:guava-libraries',
    '//third_party/java/hamcrest:hamcrest',
    '//third_party/java/junit:junit',
  ],
  visibility = ['PUBLIC'],
)
