java_library(
    name = "rc-emulation-servlet",
    srcs = [
        "WebDriverBackedSeleniumHandler.java",
    ],
    deps = [
        "//java/client/src/com/thoughtworks/selenium:leg-rc",
        "//java/client/src/org/openqa/selenium/chrome:chrome",
        "//java/client/src/org/openqa/selenium/edge/edgehtml:edgehtml",
        "//java/client/src/org/openqa/selenium/firefox:firefox",
        "//java/client/src/org/openqa/selenium/ie:ie",
        "//java/client/src/org/openqa/selenium/opera:opera",
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/client/src/org/openqa/selenium/safari:safari",
        "//java/server/src/org/openqa/selenium/grid:grid",
        "//java/server/src/org/openqa/selenium/remote/server:server",
        "//java/server/src/org/openqa/selenium/remote/server:sessions",
        "//java/server/src/org/openqa/selenium/remote/server:webdriver-servlet",
        "//third_party/java/guava:guava",
    ],
    provided_deps = [
        "//third_party/java/servlet:javax.servlet-api",
    ],
    visibility = [
        "//java/server/src/com/thoughtworks/selenium:leg-rc",
        "//java/server/src/org/openqa/selenium/remote/server:standalone-server",
        "//java/server/test/com/thoughtworks/selenium/webdriven:webdriven",
    ],
)
