
java_library(name = 'rc-emulation-servlet',
  srcs = [
    'WebDriverBackedSeleniumServlet.java',
  ],
  deps = [
    '//java/client/src/com/thoughtworks/selenium:leg-rc',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//java/server/src/org/openqa/selenium/remote/server:server',
    '//java/server/src/org/openqa/selenium/remote/server:sessions',
    '//third_party/java/guava:guava',
  ],
  provided_deps = [
    '//third_party/java/servlet:servlet-api',
  ],
  visibility = [
    '//java/server/src/com/thoughtworks/selenium:leg-rc',
    '//java/server/src/org/openqa/selenium/remote/server:standalone-server',
    '//java/server/test/com/thoughtworks/selenium/webdriven:webdriven',
  ],
)
