java_test(
    name = "small-tests",
    srcs = [
        "SmallTests.java",
    ],
    labels = [
        "small",
    ],
    deps = [
        ":tests",
        "//third_party/java/junit:junit",
    ],
    visibility = [
        "//java/client/test/org/openqa/selenium:small-tests",
    ],
)

java_test(
    name = "large-tests",
    srcs = [
        "LargeTests.java",
    ],
    vm_args = [
        "-Dselenium.browser=ff",
    ],
    deps = [
        ":tests",
        "//java/client/src/org/openqa/selenium/firefox:firefox",
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/client/test/org/openqa/selenium/testing:test-base",
        "//third_party/java/guava:guava",
        "//third_party/java/junit:junit",
    ],
)

java_library(
    name = "tests",
    srcs = glob(["**/*Test.java"], exclude = ["devtools/*Test.java"]),
    deps = [
        ":clock",
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/client/src/org/openqa/selenium/support:page-factory",
        "//java/client/src/org/openqa/selenium/support:support",
        "//java/client/src/org/openqa/selenium/support/events:events",
        "//java/client/src/org/openqa/selenium/support/ui:clock",
        "//java/client/src/org/openqa/selenium/support/ui:components",
        "//java/client/src/org/openqa/selenium/support/ui:elements",
        "//java/client/src/org/openqa/selenium/support/ui:wait",
        "//java/client/test/org/openqa/selenium:helpers",
        "//java/client/test/org/openqa/selenium/testing:test-base",
        "//third_party/java/guava:guava",
        "//third_party/java/assertj:assertj",
        "//third_party/java/junit:junit",
        "//third_party/java/mockito:mockito-core",
    ],
    visibility = [
        "//java/client/test/org/openqa/selenium/...",
    ],
)

java_library(
    name = "clock",
    srcs = [
        "ui/TickingClock.java",
    ],
    exported_deps = [
        # Transitively exposes Sleeper
        "//java/client/src/org/openqa/selenium/support/ui:clock",
    ],
    visibility = [
        "//java/client/test/...",
        "//java/server/test/...",
    ],
)
