<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <AssemblyName>Testing.NUnit</AssemblyName>
    <RootNamespace>OpenQA.Selenium.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="4.6.0" />
    <PackageReference Include="NUnit.Analyzers" Version="4.13.0" />
    <PackageReference Include="Runfiles" Version="0.14.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\webdriver\Selenium.WebDriver.csproj" />
    <ProjectReference Include="..\testing.webserver\Selenium.Testing.WebServer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appconfig.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
