java_test(
  name = 'htmlrunner',
  srcs = glob(['*.java']),
  deps = [
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/test/com/thoughtworks/selenium:tests',
    '//java/client/test/org/openqa/selenium/environment:environment',
    '//java/server/src/org/openqa/selenium/server/htmlrunner:htmlrunner',
    '//third_party/java/guava:guava',
    '//third_party/java/junit:junit',
  ],
)
