java_test(
    name = "htmlrunner-firefox",
    srcs = ["CoreSelfTest.java"],
    vm_args = ["-Dselenium.browser=*firefox"],
    deps = [
        ":tests",
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/test/com/thoughtworks/selenium:tests",
        "//java/client/test/org/openqa/selenium/environment:environment",
        "//java/server/src/org/openqa/selenium/server/htmlrunner:htmlrunner",
        "//third_party/java/guava:guava",
        "//third_party/java/junit:junit",
    ],
)

java_test(
    name = "htmlrunner-chrome",
    srcs = ["CoreSelfTest.java"],
    vm_args = ["-Dselenium.browser=*googlechrome"],
    deps = [
        ":tests",
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/test/com/thoughtworks/selenium:tests",
        "//java/client/test/org/openqa/selenium/environment:environment",
        "//java/server/src/org/openqa/selenium/server/htmlrunner:htmlrunner",
        "//third_party/java/guava:guava",
        "//third_party/java/junit:junit",
    ],
)

java_test(
    name = "tests",
    srcs = glob(["*UnitTest.java"]),
    deps = [
        "//java/server/src/org/openqa/selenium/server/htmlrunner:htmlrunner",
        "//third_party/java/guava:guava",
        "//third_party/java/junit:junit",
    ],
)
