module Selenium
  module WebDriver
    module IE
      class Driver < WebDriver::Driver
        EXTENSIONS: Array[String]

        include LocalDriver

        def initialize: (?options: untyped?, ?service: untyped?, ?url: untyped?, ?http_client: untyped?, ?client_config: ClientConfig?, **untyped opts) -> void

        def browser: () -> Symbol
      end
    end
  end
end
