module Selenium
  module WebDriver
    module IE
      class Driver < WebDriver::Driver
        EXTENSIONS: ::Array[untyped]

        include LocalDriver

        def initialize: (?options: untyped?, ?service: untyped?, ?url: untyped?, **untyped opts) -> void

        def browser: () -> :internet_explorer
      end
    end
  end
end
