module Selenium
  module WebDriver
    module IE
      module Features
        COMMANDS: untyped

        def command_list: () -> untyped

        def commands: (untyped command) -> untyped
      end
    end
  end
end
