module Selenium
  module WebDriver
    module IE
      class Options < WebDriver::Options
        @args: untyped

        KEY: "se:ieOptions"

        SCROLL_TOP: 0

        SCROLL_BOTTOM: 1

        CAPABILITIES: Hash[Symbol, String]

        BROWSER: "internet explorer"

        attr_reader args: untyped

        def initialize: (**untyped opts) -> void

        def add_argument: (untyped arg) -> untyped

        private

        def process_browser_options: (untyped browser_options) -> untyped
      end
    end
  end
end
