java_library(
    name = "remote",
    srcs = glob(["*.java"]),
    deps = [
        "//java/client/src/org/openqa/selenium/remote/tracing:tracing",
        "//java/server/src/org/openqa/selenium/grid/data:data",
        "//java/server/src/org/openqa/selenium/grid/node:node",
        "//java/server/src/org/openqa/selenium/grid/web:web",
        "//third_party/java/guava:guava",
    ],
    visibility = [
        "//java/server/src/org/openqa/selenium/grid/...",
        "//java/server/test/org/openqa/selenium/grid/...",
    ],
)
