java_test(name = 'small-tests',
  srcs = [
    'BeanToJsonConverterTest.java',
    'JsonToBeanConverterTest.java',
  ],
  deps = [
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//third_party/java/gson:gson',
    '//third_party/java/guava:guava',
    '//third_party/java/hamcrest:hamcrest-library',
    '//third_party/java/httpcomponents:httpclient',
    '//third_party/java/junit:junit',
  ],
)