SUITES = glob(['*Tests.java'])

java_test(name = 'common',
  srcs = SUITES,
  deps = [
    ':tests',
    '//third_party/java/junit:junit',
  ],
)

java_library(name = 'tests',
  srcs = glob(['*.java'], excludes = SUITES),
  deps = [
    '//java/server/src/org/openqa/grid:grid',
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//third_party/java/beust:jcommander',
    '//third_party/java/gson:gson',
    '//third_party/java/junit:junit',
  ],
)
