SUITES = glob(['*Tests.java'])

java_test(name = 'common',
  srcs = SUITES,
  deps = [
    ':tests',
    '//third_party/java/junit:junit',
  ],
)

java_library(name = 'tests',
  srcs = glob(['*.java'], excludes = SUITES),
  deps = [
    '//java/server/src/org/openqa/grid/common:common',
    '//java/client/src/org/openqa/selenium:platform',
    '//java/client/src/org/openqa/selenium:webdriver-api',
    '//java/client/src/org/openqa/selenium/remote:capabilities',
    '//third_party/java/junit:junit',
  ],
)
