java_test(name = 'SmallTests',
  srcs = [
    'SmallTests.java',
  ],
  deps = [
    ':tests',
    '//java/client/test/org/openqa/selenium/testing/drivers:SmallTests',
    '//java/client/test/org/openqa/selenium/v1:SmallTests',
    '//third_party/java/junit:junit',
  ],
)

java_library(name = 'annotations',
  srcs = [
    'NeedsFreshDriver.java',
    'NoDriverAfterTest.java',
  ],
  deps = [
  ],
  visibility = [
    '//java/client/test/org/openqa/selenium/testing:test-base',
  ],
)

java_library(name = 'doubles',
  srcs = [
    'StubDriver.java',
    'StubElement.java',
  ],
  deps = [
    '//java/client/src/org/openqa/selenium:webdriver-api',
  ],
  visibility = [
    '//java/client/test/...',
    '//java/server/test/...',
  ],
)

java_library(name = 'helpers',
  srcs = [
    'Build.java',
    'Pages.java',
    'StubElement.java',
    'StubRenderedWebElement.java',
    'WaitingConditions.java',
  ],
  deps = [
    '//java/client/src/org/openqa/selenium:webdriver-api',
    '//java/client/src/org/openqa/selenium/support/ui:wait',
    '//java/client/test/org/openqa/selenium/environment:environment',
    '//java/client/test/org/openqa/selenium/testing:helpers',
    '//third_party/java/guava-libraries:guava-libraries',
    '//third_party/java/junit:junit',
  ],
  visibility = [
    '//java/client/test/...',
    '//java/server/test/...',
  ],
)

java_library(name = 'tests',
  srcs = glob([
    '*Test.java',
    'internal/*Test.java',
    'interactions/*Test.java',
    'interactions/touch/*Test.java',
    'io/*Test.java',
    'logging/*.java',
    'net/*Test.java',
    'os/*Test.java',]) +
  [
    'Messages.java',
    'interactions/StubInputDeviceDriver.java',
    'interactions/touch/TouchTestBase.java',
    'net/StubNetworkInterfaceProvider.java',
  ],
  resources = [
    'messages.properties',
  ],
  deps = [
    ':doubles',
    ':helpers',
    '//java/client/src/org/openqa/selenium:webdriver-api',
    '//java/client/src/org/openqa/selenium/browserlaunchers:proxies',
    '//java/client/src/org/openqa/selenium/ie:ie',
    '//java/client/src/org/openqa/selenium/io:io',
    '//java/client/src/org/openqa/selenium/net:net',
    '//java/client/src/org/openqa/selenium/os:os',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//java/client/src/org/openqa/selenium/support:support',
    '//java/client/src/org/openqa/selenium/support/ui:wait',
    '//java/client/test/org/openqa/selenium/testing:test-base',
    '//java/client/test/org/openqa/selenium/testing/drivers:drivers',
    '//third_party/java/guava-libraries:guava-libraries',
    '//third_party/java/hamcrest:hamcrest',
    '//third_party/java/junit:junit',
    '//third_party/java/mockito:mockito',
    '//third_party/java/webbit:webbit',
  ],
)