java_test(name = 'small-tests',
  srcs = [
    'SmallTests.java',
  ],
  deps = [
    ':tests',
    '//java/client/test/com/thoughtworks/selenium/webdriven:small-tests',
    '//java/client/test/org/openqa/selenium/support:small-tests',
    '//java/client/test/org/openqa/selenium/testing/drivers:small-tests',
    '//third_party/java/junit:junit',
  ],
)

java_library(name = 'large-tests',
  srcs = [
    'StandardSeleniumTests.java',
  ],
  deps = [
    ':tests',
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/test/org/openqa/selenium/environment:environment',
    '//java/client/test/org/openqa/selenium/testing:test-base',
    '//third_party/java/junit:junit',
  ],
  visibility = [
    '//java/client/test/...',
  ],
)

java_library(name = 'helpers',
  srcs = [
    'BuckBuild.java',
    'Build.java',
    'Pages.java',
    'ParallelTestRunner.java',
    'StubDriver.java',
    'WaitingConditions.java',
  ],
  deps = [
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/src/org/openqa/selenium/support/ui:wait',
    '//java/client/test/org/openqa/selenium/environment:environment',
    '//java/client/test/org/openqa/selenium/testing:helpers',
    '//third_party/java/guava:guava',
    '//third_party/java/junit:junit',
  ],
  visibility = [
    '//java/client/test/...',
    '//java/server/test/...',
  ],
)

java_library(name = 'tests',
  srcs = glob([
    '*Test.java',
    'html5/*.java',
    'internal/*Test.java',
    'interactions/*.java',
    'interactions/touch/*Test.java',
    'io/*Test.java',
    'logging/*.java',
    'net/*Test.java',
    'os/*Test.java',]) +
  [
    'Messages.java',
    'interactions/touch/TouchTestBase.java',
    'net/StubNetworkInterfaceProvider.java',
  ],
  resources = [
    'messages.properties',
  ],
  exported_deps = [
    '//java/client/test/org/openqa/selenium/support:tests',
  ],
  deps = [
    ':helpers',
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/src/org/openqa/selenium/ie:ie',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//java/client/src/org/openqa/selenium/support:support',
    '//java/client/src/org/openqa/selenium/support/ui:wait',
    '//java/client/test/org/openqa/selenium/testing:test-base',
    '//java/client/test/org/openqa/selenium/testing/drivers:drivers',
    '//third_party/java/guava:guava',
    '//third_party/java/hamcrest:hamcrest',
    '//third_party/java/jetty:jetty',
    '//third_party/java/junit:junit',
    '//third_party/java/mockito:mockito',
    '//third_party/java/servlet:servlet-api',
  ],
  visibility = [
    '//java/client/test/...',
  ],
)

java_binary(name = 'dump-ignores',
  main_class = 'org.openqa.selenium.internal.IgnoredTestPrinter',
  deps = [
    ':ignored-test-printer',
  ],
)

java_library(name = 'ignored-test-printer',
  srcs = [
    'internal/IgnoreCollector.java',
    'internal/IgnoredTestCallback.java',
    'internal/IgnoredTestPrinter.java',
  ],
  deps = [
    ':large-tests',
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/test/org/openqa/selenium/testing:test-base',
    '//java/client/test/org/openqa/selenium/testing/drivers:browser',
    '//java/client/test/org/openqa/selenium/testing/drivers:drivers',
    '//third_party/java/gson:gson',
    '//third_party/java/guava:guava',
    '//third_party/java/junit:junit',
  ],
)
