MISSING_LIBRARIES_MESSAGE = <<EOL
Please make sure you\'ve installed following gems before running Rake tasks:
  gem install builder
    
EOL

require 'fileutils'
require 'pathname'
require 'rubygems'

begin
  require 'builder'
rescue Exception => e
  puts "#{e.message}\n#{MISSING_LIBRARIES_MESSAGE}"
  raise "required library cannot be found"
end

$:.unshift('buildscript')

require 'javascripttest'

$stderr.sync = true

desc "Default Task"
task :default => [ :test ]

desc "Clean"
task :clean do 
  rm_rf 'build'
  rm_rf 'logs'
end

class Dir
  def copy_to(dest_dir)
    src_dir = Pathname.new(self.path)
    dest_dir = Pathname.new(dest_dir)
    FileList["#{src_dir}/**/*"].each do |src|
      next if File.directory?(src)
      dest = dest_dir + Pathname.new(src).relative_path_from(src_dir)
      mkdir_p dest.dirname.to_s unless dest.dirname.directory?
      cp(src, dest) unless uptodate?(dest, src)
    end
  end
end

desc "Copy files to build/image"
task :image do
  Dir.new('javascript').copy_to('build/image')
end

task :test => [:internal_tests, :unit_tests, :functional_tests]

desc "Test the testing infrastructure"
task :internal_tests do 
  ruby "-I buildscript buildscript/internal_test_suite.rb"
end

@browser = Firefox

desc "Runs all the JSunit tests"
JavaScriptTestTask.new(:unit_tests) do |t|
  timestamp = "%.6f" % Time.now.to_f
  jsunit_tests ="/javascript/jsunit/testRunner.html?autoRun=true&testPage=/javascript/unittest/browserbot/suite.html&submitResults=ROOT/jsunitResults&t=#{timestamp}" 
  t.mount("/javascript")
  t.run jsunit_tests
  t.browser(@browser)
end

desc "Runs all the functional tests"
JavaScriptTestTask.new(:functional_tests) do |t|
  timestamp = "%.6f" % Time.now.to_f
  functional_tests="/javascript/core/TestRunner.html?auto=true&test=../tests/TestSuite.html&resultsUrl=/seleniumResults&t=#{timestamp}"
  t.mount("/javascript")
  t.run functional_tests
  t.browser(@browser)
end
