module Selenium
  module WebDriver
    module Remote
      module Http
        class Common
          MAX_REDIRECTS: Integer

          CONTENT_TYPE: String

          DEFAULT_HEADERS: Hash[String, untyped]

          BINARY_ENCODINGS: Array[Encoding]

          @common_headers: Hash[String, untyped]

          attr_accessor self.extra_headers: Hash[String, untyped]

          attr_writer self.user_agent: String

          def self.user_agent: -> String

          attr_writer server_url: String

          def quit_errors: () -> Array[untyped]

          def close: () -> nil

          def call: (untyped verb, untyped url, untyped command_hash) -> untyped

          private

          def common_headers: -> Hash[String, untyped]

          def server_url: () -> String

          def request: (*untyped) -> untyped

          def create_response: (Integer code, Hash[String, untyped] body, String content_type) -> Remote::Response

          def ensure_utf8_encoding: (untyped obj) -> untyped

          def encode_string_to_utf8: (String str) -> String
        end
      end
    end
  end
end
