module Selenium
  module WebDriver
    module Remote
      module Http
        # @api private
        class Default < Common
          @open_timeout: Integer

          @read_timeout: Integer

          @http: untyped

          @proxy: Proxy

          attr_writer proxy: Proxy?

          attr_accessor open_timeout: Integer

          attr_accessor read_timeout: Integer

          def initialize: (?open_timeout: Integer?, ?read_timeout: Integer?) -> void

          def close: () -> untyped

          private

          def http: () -> untyped

          def start: (untyped http) -> untyped

          MAX_RETRIES: Integer

          def request: (untyped verb, untyped url, untyped headers, untyped payload, ?::Integer redirects) -> untyped

          def new_request_for: (untyped verb, untyped url, untyped headers, untyped payload) -> untyped

          def response_for: (untyped request) -> untyped

          def new_http_client: () -> untyped

          def proxy: () -> untyped

          def use_proxy?: () -> bool
        end
      end
    end
  end
end
