module Selenium
  module WebDriver
    module Remote
      module Http
        # @api private
        class Default < Common
          @http: untyped

          def initialize: (?client_config: ClientConfig?, ?open_timeout: Numeric?, ?read_timeout: Numeric?) -> void

          def open_timeout: () -> Numeric?

          def read_timeout: () -> Numeric?

          def open_timeout=: (Numeric? value) -> void

          def read_timeout=: (Numeric? value) -> void

          def proxy=: (Proxy? value) -> void

          def close: () -> untyped

          private

          def http: () -> untyped

          def start: (untyped http) -> untyped

          MAX_RETRIES: Integer

          def request: (untyped verb, untyped url, untyped headers, untyped payload, ?::Integer redirects) -> untyped

          def follow_redirect: (untyped response, ::Integer redirects) -> untyped

          def new_request_for: (untyped verb, untyped url, untyped headers, untyped payload) -> untyped

          def response_for: (untyped request) -> untyped

          def new_http_client: () -> untyped

          def proxy: () -> untyped

          def use_proxy?: () -> bool
        end
      end
    end
  end
end
