java_library(
    name = "cli",
    srcs = glob(["*.java"]),
    deps = [
        "//third_party/java/guava:guava",
    ],
    visibility = [
        "//java/server/src/org/openqa/...",
        "//java/server/test/org/openqa/...",
    ],
)
