java_library(
    name = "testing",
    srcs = glob(["*.java"]),
    deps = [
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/server/src/org/openqa/selenium/grid/node:node",
        "//java/server/src/org/openqa/selenium/grid/web:web",
    ],
    visibility = [
        "//java/server/test/...",
    ],
)