java_library(name = 'javascript',
  srcs = glob(['*.java']),
  deps = [
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/test/org/openqa/selenium/environment:environment',
    '//java/client/test/org/openqa/selenium/testing:helpers',
    '//java/client/test/org/openqa/selenium/testing/drivers:drivers',
    '//third_party/java/hamcrest:hamcrest',
    '//third_party/java/junit:junit',
    '//third_party/java/guava:guava',
  ],
  visibility = [
    '//javascript/...',
  ],
)
