java_library(
    name = "javascript",
    srcs = glob(["*.java"]),
    deps = [
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/test/org/openqa/selenium/build:build",
        "//java/client/test/org/openqa/selenium/environment:environment",
        "//java/client/test/org/openqa/selenium/testing:test-base",
        "//java/client/test/org/openqa/selenium/testing/drivers:drivers",
        "//third_party/java/guava:guava",
        "//third_party/java/assertj:assertj",
        "//third_party/java/junit:junit",
    ],
    visibility = [
        "//javascript/...",
    ],
)
