query {
	grid {
		uri
		nodes {
			id
			uri
			status
			maxSession
			stereotypes
			version
			sessionCount
			osInfo {
				version
				name
				arch
			}
		}
		totalSlots
		usedSlots
		version
	}
}
