query GetSessions {
    sessionsInfo {
        sessions {
            id
            capabilities
            startTime
            uri
            nodeId
            nodeUri
            sessionDurationMillis
            slot {
                id
                stereotype
                lastStarted
            }
        }
        sessionQueueRequests
    }
}
