java_test(
    name = "small-tests",
    srcs = [
        "RemoteServerTests.java",
    ],
    vm_args = [
        "-Dselenium.browser=htmlunit",
        "-Dselenium.browser.remote=true",
    ],
    labels = [
        "small",
    ],
    deps = [
        ":tests",
        "//third_party/java/junit:junit",
    ],
)

java_library(
    name = "tests",
    srcs = glob([
        "*.java",
        "commandhandler/*.java",
        "handler/**/*.java",
        "rest/*.java",
        "xdrpc/*.java",
    ]),
    deps = [
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/client/test/org/openqa/selenium:helpers",
        "//java/client/test/org/openqa/selenium/testing:test-base",
        "//java/client/test/org/openqa/selenium/testing/drivers:drivers",
        "//java/server/src/org/openqa/selenium/grid/node:node",
        "//java/server/src/org/openqa/selenium/grid/session:session",
        "//java/server/src/org/openqa/selenium/remote/server:server",
        "//java/server/src/org/openqa/selenium/remote/server:sessions",
        "//java/server/src/org/openqa/selenium/remote/server:webdriver-servlet",
        "//java/server/test/org/openqa/testing:test-base",
        "//third_party/java/guava:guava",
        "//third_party/java/assertj:assertj",
        "//third_party/java/jetty:jetty",
        "//third_party/java/junit:junit",
        "//third_party/java/mockito:mockito-core",
        "//third_party/java/servlet:javax.servlet-api",
    ],
)
