java_library(
    name = "httpd",
    srcs = glob(["*.java"]),
    deps = [
        "//java/client/src/org/openqa/selenium/remote/tracing:tracing",
        "//java/server/src/org/openqa/selenium/cli:cli",
        "//java/server/src/org/openqa/selenium/grid/config:config",
        "//java/server/src/org/openqa/selenium/grid/server:server",
        "//java/server/src/org/openqa/selenium/grid/sessionmap:sessionmap",
        "//java/server/src/org/openqa/selenium/grid/sessionmap/local:local",
        "//java/server/src/org/openqa/selenium/grid/web:web",
        "//third_party/java/beust:jcommander",
    ],
    provided_deps = [
        "//third_party/java/service:auto-service",
    ],
    annotation_processor_deps = [
        "//third_party/java/auto:auto-common",
        "//third_party/java/service:auto-service",
        "//third_party/java/guava:guava",
    ],
    annotation_processors = [
        "com.google.auto.service.processor.AutoServiceProcessor",
    ],
    visibility = [
        "//java/server/src/org/openqa/selenium/grid:",
    ],
)
