java_test(
    name = "safari",
    srcs = ["SafariDriverTests.java"],
    vm_args = [
        "-Dselenium.browser=safari",
    ],
    deps = [
        ":tests",
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/test/org/openqa/selenium:large-tests",
        "//java/client/test/org/openqa/selenium/testing:test-base",
        "//third_party/java/junit:junit",
    ],
)

java_library(
    name = "tests",
    srcs = glob(["*Test.java"]),
    deps = [
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/client/src/org/openqa/selenium/safari:safari",
        "//java/client/src/org/openqa/selenium/support/ui:wait",
        "//java/client/test/org/openqa/selenium:helpers",
        "//java/client/test/org/openqa/selenium:tests",
        "//java/client/test/org/openqa/selenium/environment:environment",
        "//java/client/test/org/openqa/selenium/testing:annotations",
        "//java/client/test/org/openqa/selenium/testing:test-base",
        "//third_party/java/assertj:assertj",
        "//third_party/java/guava:guava",
        "//third_party/java/junit:junit",
        "//third_party/java/mockito:mockito-core",
    ],
)
