# Licensed to the Software Freedom Conservancy (SFC) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The SFC licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.


"""Generate selenium/webdriver/__init__.pyi from the runtime lazy imports."""

from __future__ import annotations

import importlib
from pathlib import Path

PACKAGE = "selenium.webdriver"
OUTPUT_FILE = Path(__file__).resolve().parent / "selenium" / "webdriver" / "__init__.pyi"


def main() -> None:
    pkg = importlib.import_module(PACKAGE)

    lazy_imports: dict[str, tuple[str, str]] = getattr(pkg, "_LAZY_IMPORTS")
    lazy_submodules: dict[str, str] = getattr(pkg, "_LAZY_SUBMODULES")

    lines: list[str] = []
    lines.append("# This file is auto-generated. DO NOT EDIT.")
    lines.append("# Generated by py/generate_webdriver_stub.py")
    lines.append("# ruff: noqa: F401, I001")
    lines.append("")

    # Generate re-exported symbols
    for public_name in sorted(lazy_imports):
        module_path, attr_name = lazy_imports[public_name]

        if public_name == attr_name:
            line = f"from {module_path} import {attr_name}"
        else:
            line = f"from {module_path} import {attr_name} as {public_name}"

        lines.append(line)

    lines.append("")

    # Generate submodule re-exports
    if lazy_submodules:
        lines.append("from . import (")
        for name in sorted(lazy_submodules):
            lines.append(f"    {name},")
        lines.append(")")
        lines.append("")

    lines.append("__all__: list[str]")

    OUTPUT_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"Stub written to: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
