#!/usr/bin/env python3
"""
Generate Python WebDriver BiDi command modules from CDDL specification.

This generator reads CDDL (Concise Data Definition Language) specification files
and produces Python type definitions and command classes that conform to the
WebDriver BiDi protocol.

Usage:
    python generate_bidi.py <cddl_file> <output_dir> <spec_version>

Example:
    python generate_bidi.py local.cddl ./selenium/webdriver/common/bidi 1.0
"""

import argparse
import importlib.util
import logging
import re
import sys
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from textwrap import indent as tw_indent
from typing import Any

__version__ = "1.0.0"

# Logging setup
log_level = logging.INFO
logging.basicConfig(level=log_level)
logger = logging.getLogger("generate_bidi")

# File headers
SHARED_HEADER = """# Licensed to the Software Freedom Conservancy (SFC) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The SFC licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# DO NOT EDIT THIS FILE!
#
# This file is generated from the WebDriver BiDi specification. If you need to make
# changes, edit the generator and regenerate all of the modules."""

MODULE_HEADER = f"""{SHARED_HEADER}
#
# WebDriver BiDi module: {{}}
from __future__ import annotations

from typing import Any
"""


def indent(s: str, n: int) -> str:
    """Indent a string by n spaces."""
    return tw_indent(s, n * " ")


def load_enhancements_manifest(manifest_path: str | None) -> dict[str, Any]:
    """Load enhancement manifest from a Python file.

    Args:
        manifest_path: Path to Python file containing ENHANCEMENTS dict

    Returns:
        Dictionary with enhancement rules, or empty dict if no manifest provided
    """
    if not manifest_path:
        return {}

    manifest_file = Path(manifest_path)
    if not manifest_file.exists():
        logger.warning(f"Enhancement manifest not found: {manifest_path}")
        return {}

    try:
        spec = importlib.util.spec_from_file_location(
            "bidi_enhancements", manifest_file
        )
        if spec is None or spec.loader is None:
            logger.warning(f"Could not load manifest: {manifest_path}")
            return {}

        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)

        enhancements = getattr(module, "ENHANCEMENTS", {})
        dataclass_methods = getattr(module, "DATACLASS_METHOD_TEMPLATES", {})
        method_docstrings = getattr(module, "DATACLASS_METHOD_DOCSTRINGS", {})

        logger.info(f"Loaded enhancement manifest from: {manifest_path}")
        logger.debug(f"Enhancements for modules: {list(enhancements.keys())}")

        return {
            "enhancements": enhancements,
            "dataclass_methods": dataclass_methods,
            "method_docstrings": method_docstrings,
        }
    except Exception as e:
        logger.error(f"Failed to load enhancement manifest: {e}", exc_info=True)
        return {}


class CddlType(Enum):
    """CDDL type mappings to Python types."""

    TSTR = "str"  # text string
    TEXT = "str"  # text (alias)
    UINT = "int"  # unsigned integer
    INT = "int"  # signed integer
    NINT = "int"  # negative integer
    BOOL = "bool"  # boolean
    NULL = "None"  # null
    ANY = "Any"  # any type

    @classmethod
    def get_annotation(cls, cddl_type: str) -> str:
        """Get Python type annotation for a CDDL type."""
        cddl_type = cddl_type.strip().lower()

        # Handle basic types
        for member in cls:
            if cddl_type == member.name.lower():
                return member.value

        # Handle composite types
        if cddl_type.startswith("["):  # Array
            inner = cddl_type.strip("[]+ ")
            inner_type = cls.get_annotation(inner)
            return f"list[{inner_type}]"

        if cddl_type.startswith("{"):  # Map/Dict
            return "dict[str, Any]"

        # Default to Any for unknown types
        return "Any"


@dataclass
class CddlCommand:
    """Represents a CDDL command definition."""

    module: str
    name: str
    params: dict[str, str] = field(default_factory=dict)
    result: str | None = None
    description: str = ""

    def to_python_method(self, enhancements: dict[str, Any] | None = None) -> str:
        """Generate Python method code for this command.

        Args:
            enhancements: Dictionary with enhancement rules for this method
        """
        enhancements = enhancements or {}
        method_name = self._camel_to_snake(self.name)

        # Build parameter list with type hints
        # Check if there's a params_override for user-friendly named arguments
        params_to_use = self.params
        if "params_override" in enhancements:
            params_to_use = enhancements["params_override"]

        param_strs = []
        param_names = []  # Keep track of parameter names for later use
        for param_name, param_type in params_to_use.items():
            if param_type in ["bool", "str", "int"]:
                python_type = param_type
            else:
                python_type = CddlType.get_annotation(param_type)
            snake_param = self._camel_to_snake(param_name)
            param_names.append((param_name, snake_param))
            param_strs.append(f"{snake_param}: {python_type} | None = None")

        if param_strs:
            param_list = "self, " + ", ".join(param_strs)
        else:
            param_list = "self"

        # Build method body - wrap long signatures over multiple lines if needed
        sig_line = f"    def {method_name}({param_list}):"
        if len(sig_line) > 120 and param_strs:
            body = f"    def {method_name}(\n        self,\n"
            for p in param_strs:
                body += f"        {p},\n"
            body += "    ):\n"
        else:
            body = sig_line + "\n"
        body += f'        """{self.description or "Execute " + self.module + "." + self.name}."""\n'

        # Add validation if specified
        if "validate" in enhancements:
            validate_func = enhancements["validate"]
            # Build parameter list for validation function
            param_args = ", ".join(f"{snake}={snake}" for _, snake in param_names)
            body += f"        {validate_func}({param_args})\n"
            body += "\n"

        # Add transformation and preprocessing
        # First, check if any transform is needed
        if "transform" in enhancements:
            transform_spec = enhancements["transform"]
            if isinstance(transform_spec, dict):
                # New format with explicit function and result parameter
                transform_func = transform_spec.get("func")
                result_param = transform_spec.get("result_param", "params")
                input_params = [
                    transform_spec.get(k)
                    for k in ["allowed", "destination_folder"]
                    if transform_spec.get(k)
                ]

                if transform_func and result_param:
                    body += f"        {result_param} = None\n"
                    param_args = ", ".join(input_params)
                    body += f"        {result_param} = {transform_func}({param_args})\n"
                    body += "\n"
            else:
                # Legacy format for backward compatibility
                transform_func = transform_spec
                if self.name == "setDownloadBehavior":
                    body += "        download_behavior = None\n"
                    body += f"        download_behavior = {transform_func}(allowed, destination_folder)\n"
                    body += "\n"

        # Add preprocessing for serialization (check for to_bidi_dict method)
        if "preprocess" in enhancements:
            preprocess_rules = enhancements["preprocess"]
            for param_name, preprocess_type in preprocess_rules.items():
                snake_param = self._camel_to_snake(param_name)
                if preprocess_type == "check_serialize_method":
                    body += f"        if {snake_param} and hasattr({snake_param}, 'to_bidi_dict'):\n"
                    body += (
                        f"            {snake_param} = {snake_param}.to_bidi_dict()\n"
                    )
                    body += "\n"

        # Build params dict
        body += "        params = {\n"

        # If there's a transform with a result parameter, map it to the BiDi protocol name
        if "transform" in enhancements and isinstance(enhancements["transform"], dict):
            transform_spec = enhancements["transform"]
            result_param = transform_spec.get("result_param")

            # Map the result parameter to the original CDDL parameter name
            if result_param == "download_behavior":
                body += '            "downloadBehavior": download_behavior,\n'
                # Add remaining parameters that weren't part of the transform
                for cddl_param_name in self.params:
                    if cddl_param_name not in ["downloadBehavior"]:
                        snake_name = self._camel_to_snake(cddl_param_name)
                        body += f'            "{cddl_param_name}": {snake_name},\n'
        else:
            # Standard parameter mapping from CDDL
            for param_name, snake_param in param_names:
                body += f'            "{param_name}": {snake_param},\n'

        body += "        }\n"
        body += "        params = {k: v for k, v in params.items() if v is not None}\n"
        body += f'        cmd = command_builder("{self.module}.{self.name}", params)\n'
        body += "        result = self._conn.execute(cmd)\n"

        # Add response handling for extraction/deserialization
        if "extract_field" in enhancements:
            extract_field = enhancements["extract_field"]
            extract_property = enhancements.get("extract_property")

            # Check if we also need to deserialize the extracted field
            deserialize_rules = enhancements.get("deserialize", {})

            if extract_property:
                # Extract property from list items
                body += f'        if result and "{extract_field}" in result:\n'
                body += f'            items = result.get("{extract_field}", [])\n'
                body += "            return [\n"
                body += f'                item.get("{extract_property}")\n'
                body += "                for item in items\n"
                body += "                if isinstance(item, dict)\n"
                body += "            ]\n"
                body += "        return []\n"
            elif extract_field in deserialize_rules:
                # Extract field and deserialize to typed objects
                type_name = deserialize_rules[extract_field]
                body += f'        if result and "{extract_field}" in result:\n'
                body += f'            items = result.get("{extract_field}", [])\n'
                body += "            return [\n"
                body += f"                {type_name}(\n"
                body += self._generate_field_args(extract_field, type_name)
                body += "                )\n"
                body += "                for item in items\n"
                body += "                if isinstance(item, dict)\n"
                body += "            ]\n"
                body += "        return []\n"
            else:
                # Simple field extraction (return the value directly, not wrapped in result dict)
                body += f'        if result and "{extract_field}" in result:\n'
                body += f'            extracted = result.get("{extract_field}")\n'
                body += "            return extracted\n"
                body += "        return result\n"
        elif "deserialize" in enhancements:
            # Deserialize response to typed objects (legacy, without extract_field)
            deserialize_rules = enhancements["deserialize"]
            for response_field, type_name in deserialize_rules.items():
                body += f'        if result and "{response_field}" in result:\n'
                body += f'            items = result.get("{response_field}", [])\n'
                body += "            return [\n"
                body += f"                {type_name}(\n"
                body += self._generate_field_args(response_field, type_name)
                body += "                )\n"
                body += "                for item in items\n"
                body += "                if isinstance(item, dict)\n"
                body += "            ]\n"
                body += "        return []\n"
        else:
            # No special response handling, just return the result
            body += "        return result\n"

        return body

    def _generate_field_args(self, response_field: str, type_name: str) -> str:
        """Generate constructor arguments for deserializing response objects.

        For now, this handles ClientWindowInfo and Info specifically.
        Could be extended to be more generic.
        """
        if type_name == "ClientWindowInfo":
            return (
                '                    active=item.get("active"),\n'
                '                    client_window=item.get("clientWindow"),\n'
                '                    height=item.get("height"),\n'
                '                    state=item.get("state"),\n'
                '                    width=item.get("width"),\n'
                '                    x=item.get("x"),\n'
                '                    y=item.get("y")\n'
            )
        elif type_name == "Info":
            return (
                '                    children=_deserialize_info_list(item.get("children", [])),\n'
                '                    client_window=item.get("clientWindow"),\n'
                '                    context=item.get("context"),\n'
                '                    original_opener=item.get("originalOpener"),\n'
                '                    url=item.get("url"),\n'
                '                    user_context=item.get("userContext"),\n'
                '                    parent=item.get("parent")\n'
            )
        # For other types, return empty
        return ""

    @staticmethod
    def _camel_to_snake(name: str) -> str:
        """Convert camelCase to snake_case."""
        name = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", name)
        return re.sub("([a-z0-9])([A-Z])", r"\1_\2", name).lower()


@dataclass
class CddlTypeDefinition:
    """Represents a CDDL type definition."""

    module: str
    name: str
    fields: dict[str, str] = field(default_factory=dict)
    description: str = ""

    def to_python_dataclass(self, enhancements: dict[str, Any] | None = None) -> str:
        """Generate Python dataclass code for this type.

        Args:
            enhancements: Dictionary containing dataclass_methods and method_docstrings
        """
        enhancements = enhancements or {}
        dataclass_methods = enhancements.get("dataclass_methods", {})
        method_docstrings = enhancements.get("method_docstrings", {})

        # Generate class name from type name.
        # CDDL type names that start with a lowercase letter (e.g. camelCase
        # command-parameter types like "setNetworkConditionsParameters") are
        # capitalised so that the resulting Python class follows PascalCase.
        class_name = self.name[0].upper() + self.name[1:] if self.name else self.name
        code = "@dataclass\n"
        code += f"class {class_name}:\n"
        code += f'    """{class_name} type definition."""\n\n'

        if not self.fields:
            code += "    pass\n"
        else:
            for field_name, field_type in self.fields.items():
                # Convert CDDL type to Python type
                python_type = self._get_python_type(field_type)
                snake_name = CddlCommand._camel_to_snake(field_name)

                # Check if the CDDL field type is a quoted string literal (e.g., type: "key")
                # These are discriminant fields: auto-populate and exclude from __init__
                # so callers don't need to pass them as positional or keyword arguments.
                literal_match = re.match(r'^"([^"]+)"$', field_type.strip())
                if literal_match:
                    literal_value = literal_match.group(1)
                    code += f'    {snake_name}: str = field(default="{literal_value}", init=False)\n'
                # Check if this field is a list type
                elif "list[" in python_type:
                    code += f"    {snake_name}: {python_type} = field(default_factory=list)\n"
                else:
                    code += f"    {snake_name}: {python_type} = None\n"

            # Add custom methods if defined for this class
            if class_name in dataclass_methods:
                code += "\n"
                methods_dict = dataclass_methods[class_name]
                docstrings_dict = method_docstrings.get(class_name, {})

                for method_name in methods_dict:
                    method_impl = methods_dict[method_name]
                    docstring = docstrings_dict.get(method_name, "")
                    code += f"    def {method_name}(self):\n"
                    if docstring:
                        code += f'        """{docstring}"""\n'
                    code += f"        {method_impl}\n"
                    code += "\n"

        return code

    @staticmethod
    def _get_python_type(cddl_type: str) -> str:
        """Convert CDDL type to Python type annotation using Python 3.10+ syntax."""
        cddl_type = cddl_type.strip().lower()

        # Handle basic types
        type_mapping = {
            "tstr": "str",
            "text": "str",
            "uint": "int",
            "int": "int",
            "nint": "int",
            "bool": "bool",
            "null": "None",
        }

        for cddl, python in type_mapping.items():
            if cddl_type == cddl:
                # Use Python 3.10+ union syntax: type | None
                return f"{python} | None"

        # Handle arrays
        if cddl_type.startswith("["):
            inner = cddl_type.strip("[]+ ")
            inner_type = CddlTypeDefinition._get_python_type(inner)
            # Remove " | None" from inner type since it might be wrapped
            if " | None" in inner_type:
                inner_base = inner_type.replace(" | None", "")
                return f"list[{inner_base} | None] | None"
            return f"list[{inner_type}] | None"

        # Handle maps/dicts
        if cddl_type.startswith("{"):
            return "dict[str, Any] | None"

        # Default to Any for unknown/complex types
        return "Any | None"


@dataclass
class CddlEnum:
    """Represents a CDDL enum definition (string union)."""

    module: str
    name: str
    values: list[str] = field(default_factory=list)
    description: str = ""

    def to_python_class(self) -> str:
        """Generate Python enum class code.

        Generates a simple class with string constants to match the existing
        pattern in the codebase (e.g., ClientWindowState).
        """
        class_name = self.name[0].upper() + self.name[1:] if self.name else self.name
        code = f"class {class_name}:\n"
        code += f'    """{class_name}."""\n\n'

        for value in self.values:
            # Convert value to UPPER_SNAKE_CASE constant name
            const_name = self._value_to_const_name(value)
            code += f'    {const_name} = "{value}"\n'

        return code

    @staticmethod
    def _value_to_const_name(value: str) -> str:
        """Convert enum string value to constant name.

        Examples:
            "none" -> "NONE"
            "portrait-primary" -> "PORTRAIT_PRIMARY"
            "interactive" -> "INTERACTIVE"
        """
        # Replace hyphens with underscores
        const_name = value.replace("-", "_")
        # Convert to uppercase
        return const_name.upper()


@dataclass
class CddlEvent:
    """Represents a CDDL event definition (incoming message from browser)."""

    module: str
    name: str
    method: str
    params_type: str
    description: str = ""

    def to_python_dataclass(self) -> str:
        """Generate Python dataclass code for the event info type.

        Returns a dataclass code that attempts to use globals().get() for safety.
        """
        class_name = self.name

        # Extract the type name from params_type (e.g., "browsingContext.Info" -> "Info")
        # The params_type comes from the CDDL and includes module prefix
        type_name = (
            self.params_type.split(".")[-1]
            if "." in self.params_type
            else self.params_type
        )

        # Special case: if the type is BaseNavigationInfo, use BaseNavigationInfo directly
        # (NavigationInfo will be created as an alias to it)
        if type_name == "NavigationInfo":
            type_name = "BaseNavigationInfo"

        # Generate type alias using globals().get() for safety
        code = f"# Event: {self.method}\n"
        code += f"{class_name} = globals().get('{type_name}', dict)  # Fallback to dict if type not defined\n"

        return code


@dataclass
class CddlModule:
    """Represents a CDDL module (e.g., script, network, browsing_context)."""

    name: str
    commands: list[CddlCommand] = field(default_factory=list)
    types: list[CddlTypeDefinition] = field(default_factory=list)
    enums: list[CddlEnum] = field(default_factory=list)
    events: list[CddlEvent] = field(default_factory=list)

    @staticmethod
    def _convert_method_to_event_name(method_suffix: str) -> str:
        """Convert BiDi method suffix to friendly event name.

        Examples:
            "contextCreated" -> "context_created"
            "navigationStarted" -> "navigation_started"
            "userPromptOpened" -> "user_prompt_opened"
        """
        # Convert camelCase to snake_case
        s1 = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", method_suffix)
        return re.sub("([a-z0-9])([A-Z])", r"\1_\2", s1).lower()

    def _needs_field_import(self, enhancements: dict[str, Any] | None = None) -> bool:
        """Check if any type definition in this module requires the 'field' import.

        Respects the same type exclusions applied during code generation.
        """
        enhancements = enhancements or {}
        extra_cls_names: set[str] = set()
        for extra_cls in enhancements.get("extra_dataclasses", []):
            m = re.search(r"^class\s+(\w+)", extra_cls, re.MULTILINE)
            if m:
                extra_cls_names.add(m.group(1))
        exclude_types = set(enhancements.get("exclude_types", [])) | extra_cls_names

        for type_def in self.types:
            if type_def.name in exclude_types:
                continue
            for field_type in type_def.fields.values():
                # Literal string discriminants use field(default=..., init=False)
                if re.match(r'^"', field_type.strip()):
                    return True
                # List-typed fields use field(default_factory=list)
                python_type = CddlTypeDefinition._get_python_type(field_type)
                if python_type.startswith("list["):
                    return True
        return False

    def generate_code(self, enhancements: dict[str, Any] | None = None) -> str:
        """Generate Python code for this module.

        Args:
            enhancements: Dictionary with module-level enhancements
        """
        enhancements = enhancements or {}
        code = MODULE_HEADER.format(self.name)

        # Add imports if needed
        if self.commands:
            code += "from .common import command_builder\n"
        dataclass_imported = False
        if self.commands or self.types:
            code += "from dataclasses import dataclass\n"
            dataclass_imported = True
        if self.types and self._needs_field_import(enhancements):
            code += "from dataclasses import field\n"

        # Add imports for event handling if needed
        if self.events:
            code += "from selenium.webdriver.common.bidi._event_manager import EventConfig, _EventWrapper, _EventManager\n"

        code += "\n\n"

        # Add helper function definitions from enhancements
        # Collect all referenced helper functions (validate, transform)
        helper_funcs_to_add = set()
        for cmd in self.commands:
            method_name_snake = cmd._camel_to_snake(cmd.name)
            method_enhancements = enhancements.get(method_name_snake, {})
            if "validate" in method_enhancements:
                helper_funcs_to_add.add(("validate", method_enhancements["validate"]))
            if "transform" in method_enhancements and isinstance(
                method_enhancements["transform"], dict
            ):
                transform_spec = method_enhancements["transform"]
                if "func" in transform_spec:
                    helper_funcs_to_add.add(("transform", transform_spec["func"]))

        # Generate helper functions if needed
        if helper_funcs_to_add:
            for func_type, func_name in sorted(helper_funcs_to_add):
                if (
                    func_type == "validate"
                    and func_name == "validate_download_behavior"
                ):
                    code += """def validate_download_behavior(
    allowed: bool | None,
    destination_folder: str | None,
    user_contexts: Any | None = None,
) -> None:
    \"\"\"Validate download behavior parameters.

    Args:
        allowed: Whether downloads are allowed
        destination_folder: Destination folder for downloads
        user_contexts: Optional list of user contexts

    Raises:
        ValueError: If parameters are invalid
    \"\"\"
    if allowed is True and not destination_folder:
        raise ValueError("destination_folder is required when allowed=True")
    if allowed is False and destination_folder:
        raise ValueError("destination_folder should not be provided when allowed=False")


"""
                elif (
                    func_type == "transform"
                    and func_name == "transform_download_params"
                ):
                    code += """def transform_download_params(
    allowed: bool | None,
    destination_folder: str | None,
) -> dict[str, Any] | None:
    \"\"\"Transform download parameters into download_behavior object.

    Args:
        allowed: Whether downloads are allowed
        destination_folder: Destination folder for downloads (accepts str or
            pathlib.Path; will be coerced to str)

    Returns:
        Dictionary representing the download_behavior object, or None if allowed is None
    \"\"\"
    if allowed is True:
        return {
            "type": "allowed",
            # Coerce pathlib.Path (or any path-like) to str so the BiDi
            # protocol always receives a plain JSON string.
            "destinationFolder": str(destination_folder) if destination_folder is not None else None,
        }
    elif allowed is False:
        return {"type": "denied"}
    else:  # None — reset to browser default (sent as JSON null)
        return None


"""

        # Collect names of extra_dataclasses so we can skip CDDL-generated
        # enums and types that are overridden by manual definitions.
        extra_cls_names = set()
        for extra_cls in enhancements.get("extra_dataclasses", []):
            m = re.search(r"^class\s+(\w+)", extra_cls, re.MULTILINE)
            if m:
                extra_cls_names.add(m.group(1))
        exclude_types = set(enhancements.get("exclude_types", [])) | extra_cls_names

        # Generate enums first, skipping any that are overridden via extra_dataclasses
        for enum_def in self.enums:
            if enum_def.name in exclude_types:
                continue
            code += enum_def.to_python_class()
            code += "\n\n"

        # Emit module-level aliases from enhancement manifest (e.g. LogLevel = Level)
        for alias, target in enhancements.get("aliases", {}).items():
            code += f"{alias} = {target}\n\n"

        # Generate type dataclasses, skipping any overridden by extra_dataclasses
        for type_def in self.types:
            if type_def.name in exclude_types:
                continue
            code += type_def.to_python_dataclass(enhancements)
            code += "\n\n"

        # Emit extra dataclasses from enhancement manifest (non-CDDL additions)
        for extra_cls in enhancements.get("extra_dataclasses", []):
            code += extra_cls
            code += "\n\n"

        # NOTE: Don't generate event type aliases here - they reference types that may not be defined yet
        # They will be generated after the class definition instead

        # Generate EVENT_NAME_MAPPING for the module (before the module class)
        if self.events:
            # Generate EVENT_NAME_MAPPING for the module
            code += "# BiDi Event Name to Parameter Type Mapping\n"
            code += "EVENT_NAME_MAPPING = {\n"
            # Collect event keys from extra_events so we skip CDDL duplicates
            extra_event_keys = {
                evt["event_key"] for evt in enhancements.get("extra_events", [])
            }
            for event_def in self.events:
                # Convert method name to user-friendly event name
                # e.g., "browsingContext.contextCreated" -> "context_created"
                method_parts = event_def.method.split(".")
                if len(method_parts) == 2:
                    event_name = self._convert_method_to_event_name(method_parts[1])
                    if event_name not in extra_event_keys:
                        code += f'    "{event_name}": "{event_def.method}",\n'
            # Extra events not in the CDDL spec (e.g. Chromium-specific events)
            for extra_evt in enhancements.get("extra_events", []):
                code += (
                    f'    "{extra_evt["event_key"]}": "{extra_evt["bidi_event"]}",\n'
                )
            code += "}\n\n"

        # Add custom method function definitions before the class (for browsingContext)
        if self.name == "browsingContext":
            # Add helper function for recursive Info deserialization
            code += """def _deserialize_info_list(items: list) -> list | None:
    \"\"\"Recursively deserialize a list of dicts to Info objects.

    Args:
        items: List of dicts from the API response

    Returns:
        List of Info objects with properly nested children, or None if empty
    \"\"\"
    if not items or not isinstance(items, list):
        return None

    result = []
    for item in items:
        if isinstance(item, dict):
            # Recursively deserialize children only if the key exists in response
            children_list = None
            if "children" in item:
                children_list = _deserialize_info_list(item.get("children", []))
            info = Info(
                children=children_list,
                client_window=item.get("clientWindow"),
                context=item.get("context"),
                original_opener=item.get("originalOpener"),
                url=item.get("url"),
                user_context=item.get("userContext"),
                parent=item.get("parent"),
            )
            result.append(info)
    return result if result else None


"""
            code += "\n\n"

        # EventConfig, _EventWrapper, and _EventManager are imported from
        # ._event_manager (see the import block above); nothing to emit here.

        # Generate class
