# Licensed to the Software Freedom Conservancy (SFC) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The SFC licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.


module Selenium
  module WebDriver

    class ClientConfig
      def self.default_user_agent: -> String
      def self.default_user_agent=: (String? value) -> void
      attr_accessor self.default_extra_headers: Hash[String, String]?

      attr_accessor open_timeout: Numeric?
      attr_accessor read_timeout: Numeric?
      attr_accessor max_redirects: Integer
      attr_accessor proxy: Selenium::WebDriver::Proxy?
      def extra_headers: -> Hash[String, String]?
      attr_writer extra_headers: Hash[String, String]?
      def user_agent: -> String
      attr_writer user_agent: String?
      attr_reader server_url: URI?

      def server_url=: ((String | URI)? url) -> void

      def initialize: (
          ?open_timeout: Numeric?,
          ?read_timeout: Numeric?,
          ?max_redirects: Integer,
          ?proxy: Selenium::WebDriver::Proxy?,
          ?extra_headers: Hash[String, String]?,
          ?user_agent: String?,
          ?server_url: (String | URI)?
        ) -> void

      private

      def proxy_from_environment: () -> Selenium::WebDriver::Proxy?
    end
  end
end
