module Selenium
  module WebDriver
    class DriverFinder
      @options: untyped

      @paths: untyped
      @service: untyped

      def initialize: (untyped options,untyped  service) -> void

      def self.path: (untyped options, untyped klass) -> untyped

      def browser_path: -> untyped

      def browser_path?: -> untyped

      def driver_path: -> untyped

      private

      def paths: -> untyped

      def resolve_class_path: -> String?

      def paths_from_service: (String path) -> Hash[Symbol, String]

      def paths_from_manager: -> Hash[Symbol, String]

      def to_args: -> Array[String]
    end
  end
end
