# Licensed to the Software Freedom Conservancy (SFC) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The SFC licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.


module Selenium
  module WebDriver
    class Driver
      include SearchContext

      include TakesScreenshot

      @devtools: untyped
      @navigate: untyped

      @script: untyped
      @service_manager: untyped

      def self.for: (untyped browser, Hash[untyped, untyped] opts) -> untyped

      def initialize: (?bridge: Support::EventFiringBridge? bridge, ?listener: Support::AbstractEventListener? listener, **untyped opts) -> void

      def inspect: () -> String

      def network: -> Network

      def status: () -> Hash[untyped, untyped]

      def navigate: () -> Navigation

      def switch_to: () -> TargetLocator

      def manage: () -> Manager

      def action: (**untyped opts) -> ActionBuilder

      def get: (String url) -> untyped

      def current_url: () -> String

      def title: () -> String

      def page_source: () -> String

      def quit: () -> WebDriver::Remote::Response?

      def close: () -> WebDriver::Remote::Response?

      def window_handles: () -> Array[String]

      def window_handle: () -> String

      def execute_script: (String script, *untyped args) -> untyped

      def execute_async_script: (String script, *untyped args) -> untyped

      def add_virtual_authenticator: (untyped options) -> VirtualAuthenticator

      alias first find_element

      alias all find_elements

      alias script execute_script

      def []: (String | Hash[untyped, untyped] sel) -> Element

      def browser: () -> Symbol

      def capabilities: () -> untyped

      def ref: () -> ::Array[:driver | nil]

      private

      attr_reader bridge: untyped

      def create_bridge: (caps: Remote::Capabilities, http_client: Remote::Http::Common) -> Remote::Bridge

      def service_url: (untyped service) -> untyped

      def screenshot: () -> untyped

      def add_extensions: (String browser) -> void
    end
  end
end
