module Selenium
  module WebDriver
    module FileReaper
      self.@reap: (bool | nil)

      self.@tmp_files: (Hash[Integer, Array[String]] | nil)

      attr_writer self.reap: (bool | nil)

      def self.reap?: () -> (bool | nil)

      def self.tmp_files: () -> Array[String]

      def self.<<: (untyped file) -> untyped

      def self.reap: (untyped file) -> untyped?

      def self.reap!: () -> bool
    end
  end
end
