module Selenium
  module WebDriver
    module LocalDriver
      def initialize_local_driver: (untyped options, untyped service, untyped url) -> ::Array[untyped]

      def process_options: (untyped options, untyped service) -> untyped
    end
  end
end
