# Licensed to the Software Freedom Conservancy (SFC) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The SFC licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.


module Selenium
  module WebDriver
    class Logger

      @allowed: Array[Symbol]
      @first_warning: bool
      @level_forced: bool
      @output_forced: bool

      @ignored: Array[Symbol]
      @logger: ::Logger

      def initialize: (?::String progname, ?default_level: Symbol? default_level, ?ignored: Array[Symbol]? ignored, ?allowed: Array[Symbol]? allowed) -> void

      def debug!: () -> void

      def stderr!: () -> void

      def level=: (Symbol level) -> Symbol?

      def output=: (String io) -> ::Logger?

      def io: () -> IO

      def ignore: (*Symbol | Array[Symbol] ids) -> Array[Symbol]

      def allow: (*Symbol | Array[Symbol] ids) -> Array[Symbol]

      def debug: (String ?message, ?id: Symbol | Array[Symbol] id) ?{ () -> void  } -> void

      def info: (String message, ?id: Symbol | Array[Symbol] id) ?{ () -> void } -> void

      def error: (String message, ?id: Symbol | Array[Symbol] id) ?{ () -> void } -> void

      def warn: (String message, ?id: Symbol | Array[Symbol] id) ?{ () -> void } -> void

      def deprecate: (String old, ?String? new, ?id: Symbol | Array[Symbol] id, ?reference: String reference) ?{ () -> void } -> untyped

      def debug?: () -> bool

      private

      def create_logger: (String name, level: Symbol level) -> ::Logger

      def discard_or_log: (Symbol level, String message, (Symbol | Array[::Symbol]) | [(Symbol | Array[Symbol])] id) ?{ () -> void } -> untyped
    end
  end
end
