module Selenium
  module WebDriver
    class Network
      AUTH_CALLBACKS: Hash[String, String]

      @network: BiDi::Network

      def initialize: (Remote::Bridge bridge) -> void

      def add_auth_handler: (String username, String password) -> String

      def clear_auth_handlers: -> Hash[nil, nil]

      def remove_auth_handler: (String id) -> nil
    end
  end
end
