# Licensed to the Software Freedom Conservancy (SFC) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The SFC licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.


module Selenium
  module WebDriver
    class Proxy
      include _Proxy

      @ftp: untyped

      @http: untyped

      @no_proxy: untyped

      @ssl: untyped

      @pac: untyped

      @auto_detect: untyped

      @socks: untyped

      @socks_username: untyped

      @socks_password: untyped

      @socks_version: untyped

      @type: untyped

      TYPES: Hash[Symbol, String]

      ALLOWED: Hash[Symbol, String]

      def self.json_create: (untyped data) -> untyped?

      def initialize: (?::Hash[untyped, untyped] opts) -> void

      def ==: (untyped other) -> untyped

      alias eql? ==

      def ftp=: (untyped value) -> untyped

      def http=: (untyped value) -> untyped

      def no_proxy=: (untyped value) -> untyped

      def ssl=: (untyped value) -> untyped

      def pac=: (untyped url) -> untyped

      def auto_detect=: (untyped bool) -> untyped

      def socks=: (untyped value) -> untyped

      def socks_username=: (untyped value) -> untyped

      def socks_password=: (untyped value) -> untyped

      def socks_version=: (untyped value) -> untyped

      def type=: (untyped type) -> untyped

      def as_json: (*untyped) -> untyped

      def to_json: (*untyped) -> untyped
    end
  end
end
