module Selenium
  module WebDriver
    module SearchContext
      include _Driver

      FINDERS: untyped

      def find_element: (*untyped args) -> untyped

      def find_elements: (*untyped args) -> untyped

      private

      def extract_args: (untyped args) -> untyped
    end
  end
end
