module Selenium
  module WebDriver
    class SeleniumManager
      include _Platform
      include Open3

      self.@bin_path: untyped

      self.@binary: untyped

      attr_writer self.bin_path: untyped

      def self.bin_path: () -> untyped

      def self.driver_path: (untyped options) -> untyped

      private

      def self.generate_command: (untyped binary, untyped options) -> untyped

      def self.binary: () -> untyped

      def self.validate_location: (untyped location) -> untyped

      def self.run: (*untyped command) -> untyped
    end
  end
end
