# Licensed to the Software Freedom Conservancy (SFC) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The SFC licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.


module Selenium
  module WebDriver
    module FedCM
      class Account
        @account_id: String
        @email: String
        @name: String
        @given_name: String
        @picture_url: String
        @idp_config_url: String
        @login_state: String
        @terms_of_service_url: String
        @privacy_policy_url: String

        LOGIN_STATE_SIGNIN: String
        LOGIN_STATE_SIGNUP: String

        attr_reader account_id: String
        attr_reader email: String
        attr_reader name: String
        attr_reader given_name: String
        attr_reader picture_url: String
        attr_reader idp_config_url: String
        attr_reader login_state: String
        attr_reader terms_of_service_url: String
        attr_reader privacy_policy_url: String

        def initialize: (**String args) -> void
      end
    end
  end
end
