module FedCM
  # Represents an account displayed in a FedCm account list.
  # See: https://fedidcg.github.io/FedCM/#dictdef-identityprovideraccount
  #      https://fedidcg.github.io/FedCM/#webdriver-accountlist
  class Account
    @account_id: untyped

    @email: untyped

    @name: untyped

    @given_name: untyped

    @picture_url: untyped

    @idp_config_url: untyped

    @login_state: untyped

    @terms_of_service_url: untyped

    @privacy_policy_url: untyped

    LOGIN_STATE_SIGNIN: "SignIn"

    LOGIN_STATE_SIGNUP: "SignUp"

    attr_reader account_id: untyped

    attr_reader email: untyped

    attr_reader name: untyped

    attr_reader given_name: untyped

    attr_reader picture_url: untyped

    attr_reader idp_config_url: untyped

    attr_reader login_state: untyped

    attr_reader terms_of_service_url: untyped

    attr_reader privacy_policy_url: untyped

    # Initializes a new account with the provided attributes.
    #
    # @param [Hash]
    def initialize: (**untyped args) -> void
  end
end
