java_library(
    name = "simple",
    srcs = glob(["*.java"]),
    deps = [
        "//third_party/java/opentracing:opentracing-util",
        "//third_party/java/guava:guava",
    ],
    visibility = [
        "//java/client/test/org/openqa/...",
        "//java/server/test/org/openqa/...",
    ],
)
