load("//rb/spec:tests.bzl", "rb_integration_test")

_BROWSERS = [
    "chrome",
    "chrome-beta",
]

filegroup(
    name = "all_srcs",
    testonly = True,
    srcs = glob(["**/*.rb"]),
    visibility = ["//rb/spec:__pkg__"],
)

[
    rb_integration_test(
        name = file[:-8],
        srcs = [file],
        browsers = _BROWSERS,
        data = ["//common/extensions"],
    )
    for file in glob(
        ["*_spec.rb"],
        exclude = [
            "driver_spec.rb",
            "service_spec.rb",
        ],
    )
]

rb_integration_test(
    name = "driver",
    srcs = ["driver_spec.rb"],
    bidi = True,
    browsers = _BROWSERS,
    data = ["//common/extensions"],
)

rb_integration_test(
    name = "service",
    srcs = ["service_spec.rb"],
    browsers = _BROWSERS,
    grid = False,
)
