include_defs('//SELENIUM_VERSION')

java_library(name = 'support',
  srcs = [
    'Color.java',
    'Colors.java',
    'ThreadGuard.java',
  ],
  maven_coords = 'org.seleniumhq.selenium:selenium-support:' + SE_VERSION,
  maven_pom_template = '//java/client/src/org/openqa/selenium:template-pom',
  deps = [
    ':page-factory',
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/src/org/openqa/selenium/lift:lift',
    '//java/client/src/org/openqa/selenium/support/events:events',
    '//java/client/src/org/openqa/selenium/support/ui:clock',
    '//java/client/src/org/openqa/selenium/support/ui:components',
    '//java/client/src/org/openqa/selenium/support/ui:elements',
    '//java/client/src/org/openqa/selenium/support/ui:wait',
  ],
  visibility = ['PUBLIC'],
)

java_library(name = 'page-factory',
  srcs = [
    'ByIdOrName.java',
    'CacheLookup.java',
    'FindAll.java',
    'FindBy.java',
    'FindBys.java',
    'How.java',
    'PageFactory.java',
  ] + glob(['pagefactory/*.java', 'pagefactory/internal/*.java',]),
  deps = [
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/src/org/openqa/selenium/support/ui:clock',
    '//java/client/src/org/openqa/selenium/support/ui:components',
    '//third_party/java/guava:guava',
  ],
  visibility = ['PUBLIC'],
)
