java_test(
    name = "node",
    srcs = glob(["*.java"]),
    labels = [
        "small",
    ],
    deps = [
        "//java/client/src/org/openqa/selenium:core",
        "//java/client/src/org/openqa/selenium/chrome:chrome",
        "//java/client/src/org/openqa/selenium/firefox:firefox",
        "//java/server/src/org/openqa/grid:grid",
        "//java/server/src/org/openqa/grid/selenium/node:node",
        "//third_party/java/junit:junit",
        "//third_party/java/guava:guava",
    ],
)
