java_test(name = 'htmlunit',
  srcs = [
    'JavascriptEnabledHtmlUnitDriverTests.java',
  ],
  vm_args = [
    '-Dselenium.browser=htmlunit_js',
  ],
  deps = [
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//java/client/test/org/openqa/selenium:large-tests',
    '//java/client/test/org/openqa/selenium:tests',
    '//third_party/java/htmlunit:htmlunit',
    '//third_party/java/htmlunit:htmlunit-driver',
    '//third_party/java/junit:junit',
  ],
)

java_test(name = 'htmlunit-no-js',
  srcs = [
    'HtmlUnitDriverTests.java',
  ],
  vm_args = [
    '-Dselenium.browser=htmlunit',
  ],
  deps = [
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//java/client/test/org/openqa/selenium:large-tests',
    '//java/client/test/org/openqa/selenium:tests',
    '//third_party/java/htmlunit:htmlunit-driver',
    '//third_party/java/junit:junit',
  ],
)
