java_library(
    name = "injector",
    srcs = glob(["*.java"]),
    deps = [
        "//third_party/java/guava:guava",
    ],
    visibility = [
        "//java/server/src/org/openqa/selenium/...",
        "//java/server/test/org/openqa/selenium/injector:",
    ],
)
