# BUILD FILE SYNTAX: SKYLARK

java_library(
    name = "injector",
    srcs = glob(["*.java"]),
    deps = [
        "//third_party/java/guava:guava",
    ],
    visibility = [
        "//java/server/test/org/openqa/selenium/injector:"
    ],
)