include_defs('//SELENIUM_VERSION')

java_library(
  name = 'leg-rc',
  maven_coords = 'org.seleniumhq.selenium:leg-rc:' + SE_VERSION,
  deps = [
    '//java/client/src/com/thoughtworks/selenium:selenium',
    '//java/server/src/org/openqa/selenium/server/htmlrunner:htmlrunner',
    '//java/server/src/com/thoughtworks/selenium/webdriven:rc-emulation-servlet',
  ],
)

