/* AUTO GENERATED - Do not edit by hand. */
/* See rake-tasts/crazy_fun/mappings/javascript.rb for generator. */

#ifndef WD_GET_ATTRIBUTE_H
#define WD_GET_ATTRIBUTE_H

const wchar_t* WD_GET_ATTRIBUTE[] = {
L"var wdGetAttribute=function(){var f=this;function g(a){return typeof a==\"string\"}function aa(a,b){var c=b||f;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(c,e)}}else return function(){return a.apply(c,arguments)}}function h(a){var b=Array.prototype.slice.call(arguments,1);return function(){var c=Array.prototype.slice.call(arguments);c.unshift.apply(c,b);return a.apply(this,c)}}",
L"var ba=Date.now||function(){return+new Date};function i(a,b){function c(){}c.prototype=b.prototype;a.G=b.prototype;a.prototype=new c};function j(a){this.stack=Error().stack||\"\";if(a)this.message=String(a)}i(j,Error);j.prototype.name=\"CustomError\";function ca(a){for(var b=1;b<arguments.length;b++){var c=String(arguments[b]).replace(/\\$/g,\"$$$$\");a=a.replace(/\\%s/,c)}return a}function k(a,b){return a.replace(/(\\r\\n|\\r|\\n)/g,b?\"<br />\":\"<br>\")}",
L"function l(a,b){if(b)return a.replace(m,\"&amp;\").replace(n,\"&lt;\").replace(o,\"&gt;\").replace(p,\"&quot;\");else{if(!da.test(a))return a;if(a.indexOf(\"&\")!=-1)a=a.replace(m,\"&amp;\");if(a.indexOf(\"<\")!=-1)a=a.replace(n,\"&lt;\");if(a.indexOf(\">\")!=-1)a=a.replace(o,\"&gt;\");if(a.indexOf('\"')!=-1)a=a.replace(p,\"&quot;\");return a}}var m=/&/g,n=/</g,o=/>/g,p=/\\\"/g,da=/[&<>\\\"]/;function q(a,b){return k(a.replace(/  /g,\" &#160;\"),b)};function r(a,b){b.unshift(a);j.call(this,ca.apply(null,b));b.shift();this.D=a}i(r,j);r.prototype.name=\"AssertionError\";function s(a,b,c,d){var e=\"Assertion failed\";if(c){e+=\": \"+c;var O=d}else if(a){e+=\": \"+a;O=b}throw new r(\"\"+e,O||[]);}function ea(a,b){!a&&s(\"\",null,b,Array.prototype.slice.call(arguments,2))}function fa(a,b){typeof a!=\"number\"&&s(\"Expected number but got %s.\",[a],b,Array.prototype.slice.call(arguments,2));return a};var t=Array.prototype,u=t.indexOf?function(a,b,c){ea(a||g(a));fa(a.length);return t.indexOf.call(a,b,c)}:function(a,b,c){c=c==null?0:c<0?Math.max(0,a.length+c):c;if(g(a)){if(!g(b)||b.length!=1)return-1;return a.indexOf(b,c)}for(c=c;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};var v,w,x,y;function z(){return f.navigator?f.navigator.userAgent:null}y=x=w=v=false;var A;if(A=z()){var ga=f.navigator;v=A.indexOf(\"Opera\")==0;w=!v&&A.indexOf(\"MSIE\")!=-1;x=!v&&A.indexOf(\"WebKit\")!=-1;y=!v&&!x&&ga.product==\"Gecko\"}var B=w,ha=y,ia=x,C=\"\",D;if(v&&f.opera){var E=f.opera.version;C=typeof E==\"function\"?E():E}else{if(ha)D=/rv\\:([^\\);]+)(\\)|;)/;else if(B)D=/MSIE\\s+([^\\);]+)(\\)|;)/;else if(ia)D=/WebKit\\/(\\S+)/;if(D){var F=D.exec(z());C=F?F[1]:\"\"}};function G(a,b,c,d){if(typeof d==\"number\")d=(b?Math.round(d):d)+\"px\";c.style[a]=d}h(G,\"height\",true);h(G,\"width\",true);var H={\"class\":\"className\",readonly:\"readOnly\"},ja=[\"checked\",\"disabled\",\"readonly\",\"selected\"];function I(a,b){if(8==a.nodeType)return null;b=b.toLowerCase();if(b==\"style\"){var c=a.style.cssText.replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").toLowerCase();return c.charAt(c.length-1)==\";\"?c:c+\";\"}c=a.getAttributeNode(b);if(!c)return null;if(u(ja,b)>=0)return B&&c.value==\"false\"?null:true;return c.specified?c.value:null};function J(a){this.F=a}J.prototype.v=null;J.prototype.c=null;J.prototype.a=null;J.prototype.b=null;function K(a,b){this.name=a;this.value=b}K.prototype.toString=function(){return this.name};var ka=new K(\"SHOUT\",1200),la=new K(\"SEVERE\",1E3),ma=new K(\"WARNING\",900),na=new K(\"INFO\",800),oa=new K(\"CONFIG\",700),pa=new K(\"FINE\",500),L={},M=null;function N(){if(!M){M=new J(\"\");L[\"\"]=M;M.c=oa}}",
L"function P(a){N();var b;if(!(b=L[a])){b=new J(a);var c=a.lastIndexOf(\".\"),d=a.substr(0,c);c=a.substr(c+1);d=P(d);if(!d.a)d.a={};d.a[c]=b;b.v=d;b=L[a]=b}return b};var qa=new (function(){this.i=ba()});function Q(a){this.h=a||\"\";this.m=qa}Q.prototype.j=true;Q.prototype.l=true;Q.prototype.k=true;Q.prototype.d=false;Q.prototype.z=false;function R(a){a=new Date(a.t());return S(a.getFullYear()-2E3)+S(a.getMonth()+1)+S(a.getDate())+\" \"+S(a.getHours())+\":\"+S(a.getMinutes())+\":\"+S(a.getSeconds())+\".\"+S(Math.floor(a.getMilliseconds()/10))}function S(a){if(a<10)return\"0\"+a;return String(a)}",
L"function T(a,b){var c=(a.t()-b)/1E3,d=c.toFixed(3),e=0;if(c<1)e=2;else for(;c<100;){e++;c*=10}for(;e-- >0;)d=\" \"+d;return d}function U(a){Q.call(this,a)}i(U,Q);U.prototype.d=true;",
L"U.prototype.f=function(a){var b;switch(a.c.value){case ka.value:b=\"dbg-sh\";break;case la.value:b=\"dbg-sev\";break;case ma.value:b=\"dbg-w\";break;case na.value:b=\"dbg-i\";break;case pa.value:default:b=\"dbg-f\";break}var c=[];c.push(this.h,\" \");this.j&&c.push(\"[\",R(a),\"] \");this.l&&c.push(\"[\",q(T(a,this.m.i)),\"s] \");this.k&&c.push(\"[\",l(a.r()),\"] \");c.push('<span class=\"',b,'\">',k(q(l(a.s()))));if(this.d&&a.p())c.push(\"<br>\",k(q(a.q()||\"\")));c.push(\"</span><br>\");return c.join(\"\")};",
L"function V(a){Q.call(this,a)}i(V,Q);V.prototype.f=function(a){var b=[];b.push(this.h,\" \");this.j&&b.push(\"[\",R(a),\"] \");this.l&&b.push(\"[\",T(a,this.m.i),\"s] \");this.k&&b.push(\"[\",a.r(),\"] \");this.z&&b.push(\"[\",a.c.name,\"] \");b.push(a.s(),\"\\n\");this.d&&a.p()&&b.push(a.q(),\"\\n\");return b.join(\"\")};",
L"function ra(){this.e=Components.A[\"@mozilla.org/consoleservice;1\"].B(Components.C.nsIConsoleService);this.w=aa(this.n,this);this.o=new V;this.g=false}ra.prototype.n=function(a){a=this.o.f(a);if(this.e.u){var b=Components.stack;for(var c=0;c<6&&b;c++)b=b.caller;this.e.u((b?b.filename.replace(/.*\\//,\"\"):\"unknown\")+\":\"+(b?b.lineNumber:\"xx\")+\" - \"+a)}};if(!sa)var sa=new ra;var W=sa;if(true!=W.g){N();var X=M,ta=W.w;if(!X.b)X.b=[];X.b.push(ta);W.g=true};",
L"P(\"web_element\");var ua=[\"checkbox\",\"radio\"];function va(a){var b=a.tagName.toUpperCase();if(b==\"OPTION\")return true;if(b==\"INPUT\")if(u(ua,a.type)>=0)return true;return false};function wa(a,b){var c=null,d=b.toLowerCase();if(\"style\"==b.toLowerCase()){if((c=a.style)&&!g(c))c=c.cssText;return c}if(\"selected\"==d||\"checked\"==d&&va(a)){if(va(a)){c=\"selected\";d=a.type&&a.type.toLowerCase();if(\"checkbox\"==d||\"radio\"==d)c=\"checked\";c=!!a[c]}else c=false;return c?\"true\":null}var e=a.tagName&&\"A\"==a.tagName.toUpperCase();if(d==\"href\"&&e)c=I(a,b);else a[H[b]||b]===null||(c=a[H[b]||b]);if(d=c===undefined)d=I(a,b)!==null;if(d)c=I(a,b);return c||c===\"\"?c.toString():null}",
L"var Y=\"_\".split(\".\"),Z=f;!(Y[0]in Z)&&Z.execScript&&Z.execScript(\"var \"+Y[0]);for(var $;Y.length&&($=Y.shift());)if(!Y.length&&wa!==undefined)Z[$]=wa;else Z=Z[$]?Z[$]:Z[$]={};; return _.apply(null,arguments);};",
NULL
};

#endif

