/* AUTO GENERATED - Do not edit by hand. */
/* See rake-tasts/crazy_fun/mappings/javascript.rb for generator. */

#ifndef WD_GET_ATTRIBUTE_H
#define WD_GET_ATTRIBUTE_H

const wchar_t* WD_GET_ATTRIBUTE[] = {
L"var wdGetAttribute=function(){var e=this;function f(a){return typeof a==\"string\"}function g(a){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}}function i(a,c){function b(){}b.prototype=c.prototype;a.b=c.prototype;a.prototype=new b};function j(a){this.stack=Error().stack||\"\";if(a)this.message=String(a)}i(j,Error);function k(a){for(var c=1;c<arguments.length;c++){var b=String(arguments[c]).replace(/\\$/g,\"$$$$\");a=a.replace(/\\%s/,b)}return a};function l(a,c){c.unshift(a);j.call(this,k.apply(null,c));c.shift();this.a=a}i(l,j);function m(a,c,b,d){var h=\"Assertion failed\";if(b){h+=\": \"+b;var x=d}else if(a){h+=\": \"+a;x=c}throw new l(\"\"+h,x||[]);}function n(a,c){!a&&m(\"\",null,c,Array.prototype.slice.call(arguments,2))}function o(a,c){typeof a!=\"number\"&&m(\"Expected number but got %s.\",[a],c,Array.prototype.slice.call(arguments,2));return a};var p=Array.prototype,q=p.indexOf?function(a,c,b){n(a||f(a));o(a.length);return p.indexOf.call(a,c,b)}:function(a,c,b){b=b==null?0:b<0?Math.max(0,a.length+b):b;if(f(a)){if(!f(c)||c.length!=1)return-1;return a.indexOf(c,b)}for(b=b;b<a.length;b++)if(b in a&&a[b]===c)return b;return-1};var r,s,t,u;function v(){return e.navigator?e.navigator.userAgent:null}u=t=s=r=false;var w;if(w=v()){var y=e.navigator;r=w.indexOf(\"Opera\")==0;s=!r&&w.indexOf(\"MSIE\")!=-1;t=!r&&w.indexOf(\"WebKit\")!=-1;u=!r&&!t&&y.product==\"Gecko\"}var z=s,A=u,B=t,C=\"\",D;if(r&&e.opera){var E=e.opera.version;C=typeof E==\"function\"?E():E}else{if(A)D=/rv\\:([^\\);]+)(\\)|;)/;else if(z)D=/MSIE\\s+([^\\);]+)(\\)|;)/;else if(B)D=/WebKit\\/(\\S+)/;if(D){var F=D.exec(v());C=F?F[1]:\"\"}};function G(a,c,b,d){if(typeof d==\"number\")d=(c?Math.round(d):d)+\"px\";b.style[a]=d}g(G,\"height\",true);g(G,\"width\",true);var H={\"class\":\"className\",readonly:\"readOnly\"},I=[\"checked\",\"disabled\",\"readonly\",\"selected\"];function J(a,c){if(8==a.nodeType)return null;c=c.toLowerCase();if(c==\"style\"){var b=a.style.cssText.replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").toLowerCase();return b.charAt(b.length-1)==\";\"?b:b+\";\"}b=a.getAttributeNode(c);if(!b)return null;if(q(I,c)>=0)return z&&b.value==\"false\"?null:true;return b.specified?b.value:null};",
L"var K=[\"checkbox\",\"radio\"];function L(a){var c=a.tagName.toUpperCase();if(c==\"OPTION\")return true;if(c==\"INPUT\")if(q(K,a.type)>=0)return true;return false};function M(a,c){var b=null,d=c.toLowerCase();if(\"style\"==c.toLowerCase()){if((b=a.style)&&!f(b))b=b.cssText;return b}if(\"selected\"==d||\"checked\"==d&&L(a)){if(L(a)){b=\"selected\";d=a.type&&a.type.toLowerCase();if(\"checkbox\"==d||\"radio\"==d)b=\"checked\";b=!!a[b]}else b=false;return b?\"true\":null}var h=a.tagName&&\"A\"==a.tagName.toUpperCase();if(d==\"href\"&&h)b=J(a,c);else a[H[c]||c]===null||(b=a[H[c]||c]);if(d=b===undefined)d=J(a,c)!==null;if(d)b=J(a,c);return b||b===\"\"?b.toString():null}",
L"var N=\"_\".split(\".\"),O=e;!(N[0]in O)&&O.execScript&&O.execScript(\"var \"+N[0]);for(var P;N.length&&(P=N.shift());)if(!N.length&&M!==undefined)O[P]=M;else O=O[P]?O[P]:O[P]={};; return _.apply(null,arguments);};",
NULL
};

#endif

