/* AUTO GENERATED - Do not edit by hand. */
/* See rake-tasts/crazy_fun/mappings/javascript.rb for generator. */

#ifndef WD_GET_ATTRIBUTE_H
#define WD_GET_ATTRIBUTE_H

const wchar_t* WD_GET_ATTRIBUTE[] = {
L"var wdGetAttribute=function(){var e=this;function f(b){return typeof b==\"string\"}function h(b){var c=Array.prototype.slice.call(arguments,1);return function(){var a=Array.prototype.slice.call(arguments);a.unshift.apply(a,c);return b.apply(this,a)}}function i(b,c){function a(){}a.prototype=c.prototype;b.g=c.prototype;b.prototype=new a};function j(b){this.stack=Error().stack||\"\";if(b)this.message=String(b)}i(j,Error);function k(b){for(var c=1;c<arguments.length;c++){var a=String(arguments[c]).replace(/\\$/g,\"$$$$\");b=b.replace(/\\%s/,a)}return b};function l(b,c){c.unshift(b);j.call(this,k.apply(null,c));c.shift();this.f=b}i(l,j);function m(b,c,a,d){var g=\"Assertion failed\";if(a){g+=\": \"+a;var x=d}else if(b){g+=\": \"+b;x=c}throw new l(\"\"+g,x||[]);}function n(b,c){!b&&m(\"\",null,c,Array.prototype.slice.call(arguments,2))}function o(b,c){typeof b!=\"number\"&&m(\"Expected number but got %s.\",[b],c,Array.prototype.slice.call(arguments,2));return b};var p=Array.prototype,q=p.indexOf?function(b,c,a){n(b||f(b));o(b.length);return p.indexOf.call(b,c,a)}:function(b,c,a){a=a==null?0:a<0?Math.max(0,b.length+a):a;if(f(b)){if(!f(c)||c.length!=1)return-1;return b.indexOf(c,a)}for(a=a;a<b.length;a++)if(a in b&&b[a]===c)return a;return-1};var r,s,t,u;function v(){return e.navigator?e.navigator.userAgent:null}u=t=s=r=false;var w;if(w=v()){var y=e.navigator;r=w.indexOf(\"Opera\")==0;s=!r&&w.indexOf(\"MSIE\")!=-1;t=!r&&w.indexOf(\"WebKit\")!=-1;u=!r&&!t&&y.product==\"Gecko\"}var z=s,A=u,B=t,C=\"\",D;if(r&&e.opera){var E=e.opera.version;C=typeof E==\"function\"?E():E}else{if(A)D=/rv\\:([^\\);]+)(\\)|;)/;else if(z)D=/MSIE\\s+([^\\);]+)(\\)|;)/;else if(B)D=/WebKit\\/(\\S+)/;if(D){var F=D.exec(v());C=F?F[1]:\"\"}};function G(b,c,a,d,g){this.c=!!c;if(b){if(this.b=b)this.d=typeof d==\"number\"?d:this.b.nodeType!=1?0:this.c?-1:1;if(typeof void 0==\"number\")this.a=void 0}this.a=g!=undefined?g:this.d||0;if(this.c)this.a*=-1;this.e=!a}i(G,function(){});G.prototype.b=null;G.prototype.d=null;i(function(b,c,a,d){G.call(this,b,c,a,null,d)},G);function H(b,c,a,d){if(typeof d==\"number\")d=(c?Math.round(d):d)+\"px\";a.style[b]=d}h(H,\"height\",true);h(H,\"width\",true);var I={\"class\":\"className\",readonly:\"readOnly\"},J=[\"checked\",\"compact\",\"declare\",\"defer\",\"disabled\",\"ismap\",\"multiple\",\"nohref\",\"noresize\",\"noshade\",\"nowrap\",\"readonly\",\"selected\"];function K(b,c){if(8==b.nodeType)return null;c=c.toLowerCase();if(c==\"style\"){var a=b.style.cssText.replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").toLowerCase();return a.charAt(a.length-1)==\";\"?a:a+\";\"}a=b.getAttributeNode(c);if(!a)return null;if(q(J,c)>=0)return z&&a.value==\"false\"?null:\"true\";return a.specified?a.value:null};",
L"var L=[\"checkbox\",\"radio\"];function M(b){var c=b.tagName.toUpperCase();if(c==\"OPTION\")return true;if(c==\"INPUT\")if(q(L,b.type)>=0)return true;return false};function N(b,c){var a=null;a=c.toLowerCase();if(\"style\"==c.toLowerCase()){if((a=b.style)&&!f(a))a=a.cssText;return a}if(\"selected\"==a||\"checked\"==a&&M(b)){if(M(b)){a=\"selected\";var d=b.type&&b.type.toLowerCase();if(\"checkbox\"==d||\"radio\"==d)a=\"checked\";a=!!b[a]}else a=false;return a?\"true\":null}d=b.tagName&&\"A\"==b.tagName.toUpperCase();a=a==\"href\"&&d?K(b,c):b[I[c]||c];a!==undefined||(a=K(b,c));return a||a===\"\"?a.toString():null}var O=\"_\".split(\".\"),P=e;",
L"!(O[0]in P)&&P.execScript&&P.execScript(\"var \"+O[0]);for(var Q;O.length&&(Q=O.shift());)if(!O.length&&N!==undefined)P[Q]=N;else P=P[Q]?P[Q]:P[Q]={};; return _.apply(null,arguments);};",
NULL
};

#endif

