/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thoughtworks_webdriver_ie_InternetExplorerDriver_InternetExplorerTargetLocator */

#ifndef _Included_com_thoughtworks_webdriver_ie_InternetExplorerDriver_InternetExplorerTargetLocator
#define _Included_com_thoughtworks_webdriver_ie_InternetExplorerDriver_InternetExplorerTargetLocator
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
