/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thoughtworks_webdriver_ie_InternetExplorerDriver */

#ifndef _Included_com_thoughtworks_webdriver_ie_InternetExplorerDriver
#define _Included_com_thoughtworks_webdriver_ie_InternetExplorerDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thoughtworks_webdriver_ie_InternetExplorerDriver
 * Method:    close
 * Signature: ()Lcom/thoughtworks/webdriver/WebDriver;
 */
JNIEXPORT jobject JNICALL Java_com_thoughtworks_webdriver_ie_InternetExplorerDriver_close
  (JNIEnv *, jobject);

/*
 * Class:     com_thoughtworks_webdriver_ie_InternetExplorerDriver
 * Method:    get
 * Signature: (Ljava/lang/String;)Lcom/thoughtworks/webdriver/WebDriver;
 */
JNIEXPORT jobject JNICALL Java_com_thoughtworks_webdriver_ie_InternetExplorerDriver_get
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_thoughtworks_webdriver_ie_InternetExplorerDriver
 * Method:    getCurrentUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_thoughtworks_webdriver_ie_InternetExplorerDriver_getCurrentUrl
  (JNIEnv *, jobject);

/*
 * Class:     com_thoughtworks_webdriver_ie_InternetExplorerDriver
 * Method:    getTitle
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_thoughtworks_webdriver_ie_InternetExplorerDriver_getTitle
  (JNIEnv *, jobject);

/*
 * Class:     com_thoughtworks_webdriver_ie_InternetExplorerDriver
 * Method:    getVisible
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_thoughtworks_webdriver_ie_InternetExplorerDriver_getVisible
  (JNIEnv *, jobject);

/*
 * Class:     com_thoughtworks_webdriver_ie_InternetExplorerDriver
 * Method:    setVisible
 * Signature: (Z)Lcom/thoughtworks/webdriver/WebDriver;
 */
JNIEXPORT jobject JNICALL Java_com_thoughtworks_webdriver_ie_InternetExplorerDriver_setVisible
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_thoughtworks_webdriver_ie_InternetExplorerDriver
 * Method:    waitForLoadToComplete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_thoughtworks_webdriver_ie_InternetExplorerDriver_waitForLoadToComplete
  (JNIEnv *, jobject);

/*
 * Class:     com_thoughtworks_webdriver_ie_InternetExplorerDriver
 * Method:    startComNatively
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_thoughtworks_webdriver_ie_InternetExplorerDriver_startComNatively
  (JNIEnv *, jobject);

/*
 * Class:     com_thoughtworks_webdriver_ie_InternetExplorerDriver
 * Method:    openIe
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_thoughtworks_webdriver_ie_InternetExplorerDriver_openIe
  (JNIEnv *, jobject);

/*
 * Class:     com_thoughtworks_webdriver_ie_InternetExplorerDriver
 * Method:    selectElementById
 * Signature: (Ljava/lang/String;)Lcom/thoughtworks/webdriver/WebElement;
 */
JNIEXPORT jobject JNICALL Java_com_thoughtworks_webdriver_ie_InternetExplorerDriver_selectElementById
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_thoughtworks_webdriver_ie_InternetExplorerDriver
 * Method:    selectElementByLink
 * Signature: (Ljava/lang/String;)Lcom/thoughtworks/webdriver/WebElement;
 */
JNIEXPORT jobject JNICALL Java_com_thoughtworks_webdriver_ie_InternetExplorerDriver_selectElementByLink
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_thoughtworks_webdriver_ie_InternetExplorerDriver
 * Method:    selectElementsByLink
 * Signature: (Ljava/lang/String;Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_thoughtworks_webdriver_ie_InternetExplorerDriver_selectElementsByLink
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_thoughtworks_webdriver_ie_InternetExplorerDriver
 * Method:    getDocument
 * Signature: ()Lcom/thoughtworks/webdriver/ie/DocumentNode;
 */
JNIEXPORT jobject JNICALL Java_com_thoughtworks_webdriver_ie_InternetExplorerDriver_getDocument
  (JNIEnv *, jobject);

/*
 * Class:     com_thoughtworks_webdriver_ie_InternetExplorerDriver
 * Method:    deleteStoredObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_thoughtworks_webdriver_ie_InternetExplorerDriver_deleteStoredObject
  (JNIEnv *, jobject);

/*
 * Class:     com_thoughtworks_webdriver_ie_InternetExplorerDriver
 * Method:    setFrameIndex
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_thoughtworks_webdriver_ie_InternetExplorerDriver_setFrameIndex
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
