/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thoughtworks_webdriver_ie_ElementNode */

#ifndef _Included_com_thoughtworks_webdriver_ie_ElementNode
#define _Included_com_thoughtworks_webdriver_ie_ElementNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thoughtworks_webdriver_ie_ElementNode
 * Method:    getDocument
 * Signature: ()Lcom/thoughtworks/webdriver/ie/DocumentNode;
 */
JNIEXPORT jobject JNICALL Java_com_thoughtworks_webdriver_ie_ElementNode_getDocument
  (JNIEnv *, jobject);

/*
 * Class:     com_thoughtworks_webdriver_ie_ElementNode
 * Method:    getFirstChild
 * Signature: ()Lcom/thoughtworks/webdriver/ie/HtmlNode;
 */
JNIEXPORT jobject JNICALL Java_com_thoughtworks_webdriver_ie_ElementNode_getFirstChild
  (JNIEnv *, jobject);

/*
 * Class:     com_thoughtworks_webdriver_ie_ElementNode
 * Method:    getNextSibling
 * Signature: ()Lcom/thoughtworks/webdriver/ie/HtmlNode;
 */
JNIEXPORT jobject JNICALL Java_com_thoughtworks_webdriver_ie_ElementNode_getNextSibling
  (JNIEnv *, jobject);

/*
 * Class:     com_thoughtworks_webdriver_ie_ElementNode
 * Method:    getFirstAttribute
 * Signature: ()Lcom/thoughtworks/webdriver/ie/AttributeNode;
 */
JNIEXPORT jobject JNICALL Java_com_thoughtworks_webdriver_ie_ElementNode_getFirstAttribute
  (JNIEnv *, jobject);

/*
 * Class:     com_thoughtworks_webdriver_ie_ElementNode
 * Method:    getNativeName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_thoughtworks_webdriver_ie_ElementNode_getNativeName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
