/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_googlecode_webdriver_ie_AttributeNode */

#ifndef _Included_com_googlecode_webdriver_ie_AttributeNode
#define _Included_com_googlecode_webdriver_ie_AttributeNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_googlecode_webdriver_ie_AttributeNode
 * Method:    getParent
 * Signature: ()Lcom/googlecode/webdriver/ie/HtmlNode;
 */
JNIEXPORT jobject JNICALL Java_com_googlecode_webdriver_ie_AttributeNode_getParent
  (JNIEnv *, jobject);

/*
 * Class:     com_googlecode_webdriver_ie_AttributeNode
 * Method:    getFirstAttribute
 * Signature: ()Lcom/googlecode/webdriver/ie/AttributeNode;
 */
JNIEXPORT jobject JNICALL Java_com_googlecode_webdriver_ie_AttributeNode_getFirstAttribute
  (JNIEnv *, jobject);

/*
 * Class:     com_googlecode_webdriver_ie_AttributeNode
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_googlecode_webdriver_ie_AttributeNode_getName
  (JNIEnv *, jobject);

/*
 * Class:     com_googlecode_webdriver_ie_AttributeNode
 * Method:    getNextSibling
 * Signature: ()Lcom/googlecode/webdriver/ie/HtmlNode;
 */
JNIEXPORT jobject JNICALL Java_com_googlecode_webdriver_ie_AttributeNode_getNextSibling
  (JNIEnv *, jobject);

/*
 * Class:     com_googlecode_webdriver_ie_AttributeNode
 * Method:    getText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_googlecode_webdriver_ie_AttributeNode_getText
  (JNIEnv *, jobject);

/*
 * Class:     com_googlecode_webdriver_ie_AttributeNode
 * Method:    deleteStoredObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_googlecode_webdriver_ie_AttributeNode_deleteStoredObject
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
