/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openqa_selenium_ie_Finder */

#ifndef _Included_org_openqa_selenium_ie_Finder
#define _Included_org_openqa_selenium_ie_Finder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openqa_selenium_ie_Finder
 * Method:    selectElementById
 * Signature: (JJLjava/lang/String;)Lorg/openqa/selenium/WebElement;
 */
JNIEXPORT jobject JNICALL Java_org_openqa_selenium_ie_Finder_selectElementById
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     org_openqa_selenium_ie_Finder
 * Method:    selectElementsById
 * Signature: (JLjava/lang/String;Ljava/util/List;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_openqa_selenium_ie_Finder_selectElementsById
  (JNIEnv *, jclass, jlong, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
