/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openqa_selenium_ie_InternetExplorerElement */

#ifndef _Included_org_openqa_selenium_ie_InternetExplorerElement
#define _Included_org_openqa_selenium_ie_InternetExplorerElement
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openqa_selenium_ie_InternetExplorerElement
 * Method:    createInternetExplorerElement
 * Signature: (JLorg/openqa/selenium/ie/ElementNode;)Lorg/openqa/selenium/ie/InternetExplorerElement;
 */
JNIEXPORT jobject JNICALL Java_org_openqa_selenium_ie_InternetExplorerElement_createInternetExplorerElement
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_openqa_selenium_ie_InternetExplorerElement
 * Method:    click
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_openqa_selenium_ie_InternetExplorerElement_click
  (JNIEnv *, jobject);

/*
 * Class:     org_openqa_selenium_ie_InternetExplorerElement
 * Method:    getAttribute
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openqa_selenium_ie_InternetExplorerElement_getAttribute
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_openqa_selenium_ie_InternetExplorerElement
 * Method:    getText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openqa_selenium_ie_InternetExplorerElement_getText
  (JNIEnv *, jobject);

/*
 * Class:     org_openqa_selenium_ie_InternetExplorerElement
 * Method:    getValue
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openqa_selenium_ie_InternetExplorerElement_getValue
  (JNIEnv *, jobject);

/*
 * Class:     org_openqa_selenium_ie_InternetExplorerElement
 * Method:    doSendKeys
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_openqa_selenium_ie_InternetExplorerElement_doSendKeys
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_openqa_selenium_ie_InternetExplorerElement
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_openqa_selenium_ie_InternetExplorerElement_clear
  (JNIEnv *, jobject);

/*
 * Class:     org_openqa_selenium_ie_InternetExplorerElement
 * Method:    isEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_openqa_selenium_ie_InternetExplorerElement_isEnabled
  (JNIEnv *, jobject);

/*
 * Class:     org_openqa_selenium_ie_InternetExplorerElement
 * Method:    isSelected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_openqa_selenium_ie_InternetExplorerElement_isSelected
  (JNIEnv *, jobject);

/*
 * Class:     org_openqa_selenium_ie_InternetExplorerElement
 * Method:    setSelected
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_openqa_selenium_ie_InternetExplorerElement_setSelected
  (JNIEnv *, jobject);

/*
 * Class:     org_openqa_selenium_ie_InternetExplorerElement
 * Method:    submit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_openqa_selenium_ie_InternetExplorerElement_submit
  (JNIEnv *, jobject);

/*
 * Class:     org_openqa_selenium_ie_InternetExplorerElement
 * Method:    toggle
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_openqa_selenium_ie_InternetExplorerElement_toggle
  (JNIEnv *, jobject);

/*
 * Class:     org_openqa_selenium_ie_InternetExplorerElement
 * Method:    isDisplayed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_openqa_selenium_ie_InternetExplorerElement_isDisplayed
  (JNIEnv *, jobject);

/*
 * Class:     org_openqa_selenium_ie_InternetExplorerElement
 * Method:    getLocation
 * Signature: ()Ljava/awt/Point;
 */
JNIEXPORT jobject JNICALL Java_org_openqa_selenium_ie_InternetExplorerElement_getLocation
  (JNIEnv *, jobject);

/*
 * Class:     org_openqa_selenium_ie_InternetExplorerElement
 * Method:    getSize
 * Signature: ()Ljava/awt/Dimension;
 */
JNIEXPORT jobject JNICALL Java_org_openqa_selenium_ie_InternetExplorerElement_getSize
  (JNIEnv *, jobject);

/*
 * Class:     org_openqa_selenium_ie_InternetExplorerElement
 * Method:    getElementNode
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_openqa_selenium_ie_InternetExplorerElement_getElementNode
  (JNIEnv *, jobject);

/*
 * Class:     org_openqa_selenium_ie_InternetExplorerElement
 * Method:    releaseElementNode
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openqa_selenium_ie_InternetExplorerElement_releaseElementNode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_openqa_selenium_ie_InternetExplorerElement
 * Method:    getIePointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_openqa_selenium_ie_InternetExplorerElement_getIePointer
  (JNIEnv *, jobject);

/*
 * Class:     org_openqa_selenium_ie_InternetExplorerElement
 * Method:    releaseIePointer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openqa_selenium_ie_InternetExplorerElement_releaseIePointer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_openqa_selenium_ie_InternetExplorerElement
 * Method:    deleteStoredObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_openqa_selenium_ie_InternetExplorerElement_deleteStoredObject
  (JNIEnv *, jobject);

/*
 * Class:     org_openqa_selenium_ie_InternetExplorerElement
 * Method:    getChildrenOfTypeNatively
 * Signature: (Ljava/util/List;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_openqa_selenium_ie_InternetExplorerElement_getChildrenOfTypeNatively
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     org_openqa_selenium_ie_InternetExplorerElement
 * Method:    getValueOfCssProperty
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openqa_selenium_ie_InternetExplorerElement_getValueOfCssProperty
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
