java_library(
  name = 'chrome',
  srcs = glob(['*.java']),
  deps = [
    '//java/client/src/org/openqa/selenium:webdriver-api',
    '//java/client/src/org/openqa/selenium/logging:logging',
    '//java/client/src/org/openqa/selenium/net:net',
    '//java/client/src/org/openqa/selenium/remote:api',
    '//java/client/src/org/openqa/selenium/remote:capabilities',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//java/client/src/org/openqa/selenium/remote/service:service',
    '//third_party/java/guava-libraries:guava-libraries',
    '//third_party/java/json:json',
  ],
)
