include_defs('//SELENIUM_VERSION')

java_library(
  name = 'chrome',
  maven_coords = 'org.seleniumhq.selenium:selenium-chrome-driver:' + SE_VERSION,
  srcs = glob(['*.java']),
  deps = [
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//third_party/java/gson:gson',
    '//third_party/java/guava:guava',
  ],
  visibility = [ 'PUBLIC' ],
)
