include_defs('//SELENIUM_VERSION')

java_library(name = 'firefox',
  maven_coords = 'org.seleniumhq.selenium:selenium-firefox-driver:jar:' + SE_VERSION,
  maven_pom_template = '//java/client/src/org/openqa/selenium:template-pom',
  srcs = glob(['*.java', 'internal/*.java']),
  resources = [
    ':prefs',
    ':webdriver.xpi',
  ],
  deps = [
    ':prefs',
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//third_party/java/guava:guava',
  ],
  visibility = [ 'PUBLIC' ],
)

export_file(name = 'prefs',
  src = '//javascript/firefox-driver:webdriver_prefs',
  out = 'webdriver_prefs.json',
)

export_file(name = 'webdriver.xpi',
  src = '//javascript/firefox-driver:webdriver',
)
