load("//java:version.bzl", "SE_VERSION")
load("//java:rules.bzl", "java_library")

java_library(
    name = "firefox",
    maven_coords = "org.seleniumhq.selenium:selenium-firefox-driver:jar:" + SE_VERSION,
    maven_pom_template = "//java/client/src/org/openqa/selenium:template-pom",
    module_info = "module-info.txt",
    srcs = glob(["*.java"]),
    resources = [
        ":prefs",
    ],
    exported_deps = [
        "//java/client/src/org/openqa/selenium/remote:remote",
    ],
    provided_deps = [
        "//third_party/java/service:auto-service",
    ],
    annotation_processor_deps = [
        "//third_party/java/auto:auto-common",
        "//third_party/java/service:auto-service",
        "//third_party/java/guava:guava",
    ],
    annotation_processors = [
        "com.google.auto.service.processor.AutoServiceProcessor",
    ],
    deps = [
        "//third_party/java/guava:guava",
    ],
    visibility = ["PUBLIC"],
)

export_file(
    name = "prefs",
    src = "//third_party/js/selenium:webdriver_prefs",
    out = "webdriver_prefs.json",
)
