module Selenium
  module WebDriver
    module Edge
      class Service < WebDriver::Service
        DRIVER_PATH_ENV_KEY: String

        @log: untyped

        DEFAULT_PORT: Integer

        EXECUTABLE: String

        SHUTDOWN_SUPPORTED: bool

        def log: () -> untyped
      end
    end
  end
end
