js_fragment(name = 'clear',
  function = 'bot.action.clear',
  module = 'bot.action',
  deps = [
    '//javascript/atoms:action',
  ],
)

js_fragment(name = 'execute_script',
  function = 'bot.inject.executeScript',
  module = 'bot.inject',
  deps = [
    '//javascript/atoms:inject',
  ],
  visibility = [
    '//java/client/test/org/openqa/selenium/atoms:',
  ],
)

