java_library(
    name = "config",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/server/src/org/openqa/selenium/grid/node:node",
        "//java/server/src/org/openqa/selenium/grid/node/local:local",
    ],
    deps = [
        "//java/server/src/org/openqa/selenium/grid/config:config",
        "//java/server/src/org/openqa/selenium/grid/data:data",
        "//java/server/src/org/openqa/selenium/grid/web:web",
        "//third_party/java/beust:jcommander",
    ],
    visibility = [
        "//java/server/src/org/openqa/selenium/grid/...",
    ],
)