java_library(
    name = "test-base",
    srcs = glob([
        "*.java",
    ]),
    deps = [
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/server/src/org/openqa/selenium/remote/server:server",
        "//java/server/src/org/openqa/selenium/remote/server:sessions",
        "//third_party/java/guava:guava",
        "//third_party/java/mockito:mockito-core",
        "//third_party/java/servlet:javax.servlet-api",
    ],
    visibility = [
        "//java/server/test/org/openqa/selenium/...",
    ],
)
