# BUILD FILE SYNTAX: SKYLARK

java_library(
    name = "hub",
    srcs = glob(["*.java"]),
    deps = [
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/server/src/org/openqa/selenium/remote/server:webdriver-servlet",
        "//java/server/src/org/openqa/selenium/remote/server/scheduler:scheduler",
        "//third_party/java/guava:guava",
    ],
    visibility = [
        "//java/server/src/org/openqa/selenium/grid:",
    ],
)