java_library(name = 'interactions',
  srcs = [
    'ActionChainExecutor.java',
    'Actions.java',
    'CanPerformActionChain.java',
  ] + glob(['*Action.java', 'internal/*Action.java', 'touch/*.java'], excludes = ['Action.java']),
  exported_deps = [
    ':core',
    ':exceptions',
    '//java/client/src/org/openqa/selenium:core',
  ],
  deps = [
    '//third_party/java/guava:guava',
  ],
  visibility = [
    '//java/client/src/org/openqa/selenium:selenium',
  ],
)

java_library(name = 'core',
  srcs = [
    'Action.java',
    'HasInputDevices.java',
    'HasTouchScreen.java',
    'Keyboard.java',
    'Mouse.java',
    'TouchScreen.java',
    'internal/Coordinates.java',
  ],
  deps = [
    '//java/client/src/org/openqa/selenium:primitives',
  ],
  visibility = [
    '//java/client/src/org/openqa/selenium:core',
  ],
)

java_library(name = 'exceptions',
  srcs = [
    'InvalidCoordinatesException.java',
    'MoveTargetOutOfBoundsException.java',
  ],
  deps = [
    '//java/client/src/org/openqa/selenium:exceptions',
  ],
  visibility = [
    '//java/client/src/org/openqa/selenium:core',
    '//java/client/src/org/openqa/selenium/remote:remote',
  ],
)
