genrule(
    name = "net45",
    srcs = ["WebDriver.Common.Tests.csproj"],
    bash = "echo '$(location :webdriver_deps)' && dotnet build $SRCS --configuration Release --framework net45 --output $OUT /p:IntermediateOutputPath=$OUT/../obj/ /p:BuildSystem=buck",
    cmd_exe = "echo '$(location :webdriver_deps)' && dotnet build %SRCS% --configuration Release --framework net45 --output %OUT% /p:IntermediateOutputPath=%OUT%\..\obj\ /p:BuildSystem=buck",
    out = "bin",
    visibility = [
        "//dotnet/test/...",
    ],
)

genrule(
    name = "webdriver_deps",
    srcs = [
        "//java/client/test/org/openqa/selenium/environment:webserver",
        "//dotnet/src/webdriver:net45",
    ],
    bash = 'echo "$SRCS" > $OUT',
    cmd_exe = 'echo "%SRCS%" > %OUT%',
    out = "deps.txt",
)
