java_library(name = 'security',
  srcs = glob(['*.java']),
  deps = [
    '//java/client/src/org/openqa/selenium:beta',
  ],
  visibility = [
    '//java/client/src/org/openqa/selenium:core',
    '//java/client/src/org/openqa/selenium:selenium',
  ],
)
