module Selenium
  module WebDriver
    module Firefox
      @path: String?

      DEFAULT_PORT: Integer

      DEFAULT_SECURE_SSL: bool

      DEFAULT_ASSUME_UNTRUSTED_ISSUER: bool

      DEFAULT_LOAD_NO_FOCUS_LIB: bool

      DEVTOOLS_VERSION: Integer

      def self.path=: (String path) -> String

      def self.path: () -> String?
    end
  end
end
