load("//dotnet:selenium-dotnet-version.bzl", "ASSEMBLY_VERSION", "SE_VERSION")

genrule(
    name = "net47",
    srcs = ["WebDriver.csproj"],
    bash = "echo '$(location :webdriver_deps)' && dotnet build $SRCS --configuration Release --framework net47 --output $OUT /p:Version={} /p:AssemblyVersion={} /p:FileVersion={} /p:IntermediateOutputPath=$OUT/../obj/ /p:BuildSystem=buck".format(SE_VERSION, ASSEMBLY_VERSION, ASSEMBLY_VERSION),
    cmd_exe = "echo '$(location :webdriver_deps)' && dotnet build %SRCS% --configuration Release --framework net47 --output %OUT% /p:Version={} /p:AssemblyVersion={} /p:FileVersion={} /p:IntermediateOutputPath=%OUT%\..\obj\ /p:BuildSystem=buck".format(SE_VERSION, ASSEMBLY_VERSION, ASSEMBLY_VERSION),
    out = "bin",
    visibility = [
        "//dotnet/src/webdriverbackedselenium:net47",
        "//dotnet/src/support:net47",
    ],
)

genrule(
    name = "net46",
    srcs = ["WebDriver.csproj"],
    bash = "echo '$(location :webdriver_deps)' && dotnet build $SRCS --configuration Release --framework net46 --output $OUT /p:Version={} /p:AssemblyVersion={} /p:FileVersion={} /p:IntermediateOutputPath=$OUT/../obj/ /p:BuildSystem=buck".format(SE_VERSION, ASSEMBLY_VERSION, ASSEMBLY_VERSION),
    cmd_exe = "echo '$(location :webdriver_deps)' && dotnet build %SRCS% --configuration Release --framework net46 --output %OUT% /p:Version={} /p:AssemblyVersion={} /p:FileVersion={} /p:IntermediateOutputPath=%OUT%\..\obj\ /p:BuildSystem=buck".format(SE_VERSION, ASSEMBLY_VERSION, ASSEMBLY_VERSION),
    out = "bin",
    visibility = [
        "//dotnet/src/webdriverbackedselenium:net46",
        "//dotnet/src/support:net46",
    ],
)

genrule(
    name = "net45",
    srcs = ["WebDriver.csproj"],
    bash = "echo '$(location :webdriver_deps)' && dotnet build $SRCS --configuration Release --framework net45 --output $OUT /p:Version={} /p:AssemblyVersion={} /p:FileVersion={} /p:IntermediateOutputPath=$OUT/../obj/ /p:BuildSystem=buck".format(SE_VERSION, ASSEMBLY_VERSION, ASSEMBLY_VERSION),
    cmd_exe = "echo '$(location :webdriver_deps)' && dotnet build %SRCS% --configuration Release --framework net45 --output %OUT% /p:Version={} /p:AssemblyVersion={} /p:FileVersion={} /p:IntermediateOutputPath=%OUT%\..\obj\ /p:BuildSystem=buck".format(SE_VERSION, ASSEMBLY_VERSION, ASSEMBLY_VERSION),
    out = "bin",
    visibility = [
        "//dotnet/src/webdriverbackedselenium:net45",
        "//dotnet/src/support:net45",
        "//dotnet/test/...",
    ],
)

genrule(
    name = "netstandard2.0",
    srcs = ["WebDriver.csproj"],
    bash = "echo '$(location :webdriver_deps)' && dotnet build $SRCS --configuration Release --framework netstandard2.0 --output $OUT /p:Version={} /p:AssemblyVersion={} /p:IntermediateOutputPath=$OUT/../obj/ /p:FileVersion={} /p:BuildSystem=buck".format(SE_VERSION, ASSEMBLY_VERSION, ASSEMBLY_VERSION),
    cmd_exe = "echo '$(location :webdriver_deps)' && dotnet build %SRCS% --configuration Release --framework netstandard2.0 --output %OUT% /p:Version={} /p:AssemblyVersion={} /p:FileVersion={} /p:IntermediateOutputPath=%OUT%\..\obj\ /p:BuildSystem=buck".format(SE_VERSION, ASSEMBLY_VERSION, ASSEMBLY_VERSION),
    out = "bin",
    visibility = [
        "//dotnet/src/webdriverbackedselenium:netstandard2.0",
        "//dotnet/src/support:netstandard2.0",
    ],
)

genrule(
    name = "merge",
    srcs = [
        ":net47",
        ":net46",
        ":net45",
        ":netstandard2.0",
    ],
    cmd_exe =
        "setlocal EnableDelayedExpansion && " +
        "(if not exist %OUT% mkdir %OUT%) && " +
        "for %%G in (%SRCS%) do (" +
        "set target_dir=%%G&& " +
        "set platform_dir=%%G\..&& " +
        "for %%H in (!target_dir!) do (" +
        "for %%I in (!platform_dir!) do set platform_moniker=%%~nxI&& " +
        'if \"!platform_moniker!\"==\"netstandard2.0\" (' +
        "(if not exist %OUT%\\!platform_moniker! mkdir %OUT%\\!platform_moniker!) && " +
        "copy !target_dir!\\WebDriver.dll %OUT%\\!platform_moniker! &&" +
        "copy !target_dir!\\WebDriver.xml %OUT%\\!platform_moniker!" +
        ") else (" +
        "set merge_args=/v4 /xmldocs /internalize /lib=%%H /out=%OUT%\\!platform_moniker!\\WebDriver.dll !target_dir!\\WebDriver.dll !target_dir!\\Newtonsoft.Json.dll&& " +
        "$(exe //third_party/dotnet/ilrepack:ilrepack) !merge_args!" +
        ")" +
        ")" +
        ")",
    out = "lib",
)

genrule(
    name = "net47_strongnamed",
    srcs = ["WebDriver.csproj"],
    cmd = "echo '$(location :webdriver_deps)' && dotnet build %SRCS% --configuration Release --framework net47 --output %OUT% /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=$(location //dotnet:keyfile) /p:Version={} /p:AssemblyVersion={} /p:FileVersion={} /p:IntermediateOutputPath=%OUT%\..\obj\ /p:BuildSystem=buck".format(SE_VERSION, ASSEMBLY_VERSION, ASSEMBLY_VERSION),
    out = "bin",
    visibility = [
        "//dotnet/src/webdriverbackedselenium:net47_strongnamed",
        "//dotnet/src/support:net47_strongnamed",
    ],
)

genrule(
    name = "net46_strongnamed",
    srcs = ["WebDriver.csproj"],
    cmd = "echo '$(location :webdriver_deps)' && dotnet build %SRCS% --configuration Release --framework net46 --output %OUT% /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=$(location //dotnet:keyfile) /p:Version={} /p:AssemblyVersion={} /p:FileVersion={} /p:IntermediateOutputPath=%OUT%\..\obj\ /p:BuildSystem=buck".format(SE_VERSION, ASSEMBLY_VERSION, ASSEMBLY_VERSION),
    out = "bin",
    visibility = [
        "//dotnet/src/webdriverbackedselenium:net46_strongnamed",
        "//dotnet/src/support:net46_strongnamed",
    ],
)

genrule(
    name = "net45_strongnamed",
    srcs = ["WebDriver.csproj"],
    cmd = "echo '$(location :webdriver_deps)' && dotnet build %SRCS% --configuration Release --framework net45 --output %OUT% /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=$(location //dotnet:keyfile) /p:Version={} /p:AssemblyVersion={} /p:FileVersion={} /p:IntermediateOutputPath=%OUT%\..\obj\ /p:BuildSystem=buck".format(SE_VERSION, ASSEMBLY_VERSION, ASSEMBLY_VERSION),
    out = "bin",
    visibility = [
        "//dotnet/src/webdriverbackedselenium:net45_strongnamed",
        "//dotnet/src/support:net45_strongnamed",
    ],
)

genrule(
    name = "netstandard2.0_strongnamed",
    srcs = ["WebDriver.csproj"],
    cmd = "echo '$(location :webdriver_deps)' && dotnet build %SRCS% --configuration Release --framework netstandard2.0 --output %OUT% /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=$(location //dotnet:keyfile) /p:Version={} /p:AssemblyVersion={} /p:FileVersion={} /p:IntermediateOutputPath=%OUT%\..\obj\ /p:BuildSystem=buck".format(SE_VERSION, ASSEMBLY_VERSION, ASSEMBLY_VERSION),
    out = "bin",
    visibility = [
        "//dotnet/src/webdriverbackedselenium:netstandard2.0_strongnamed",
        "//dotnet/src/support:netstandard2.0_strongnamed",
    ],
)

genrule(
    name = "merge_strongnamed",
    srcs = [
        ":net47_strongnamed",
        ":net46_strongnamed",
        ":net45_strongnamed",
        ":netstandard2.0_strongnamed",
    ],
    cmd_exe =
        "setlocal EnableDelayedExpansion && " +
        "(if not exist %OUT% mkdir %OUT%) && " +
        "for %%G in (%SRCS%) do (" +
        "set target_dir=%%G&& " +
        "set platform_dir=%%G\..&& " +
        "for %%H in (!target_dir!) do (" +
        "for %%I in (!platform_dir!) do set full_platform_moniker=%%~nxI&& " +
        'for /f "delims=_" %%J in (\"!full_platform_moniker!\") do set platform_moniker=%%J&& ' +
        'if \"!platform_moniker!\"==\"netstandard2.0\" (' +
        "(if not exist %OUT%\\!platform_moniker! mkdir %OUT%\\!platform_moniker!) && " +
        "copy !target_dir!\\WebDriver.dll %OUT%\\!platform_moniker! &&" +
        "copy !target_dir!\\WebDriver.xml %OUT%\\!platform_moniker!" +
        ") else (" +
        "set merge_args=/v4 /xmldocs /internalize /keyfile=$(location //dotnet:keyfile) /lib=%%H /out=%OUT%\\!platform_moniker!\\WebDriver.dll !target_dir!\\WebDriver.dll !target_dir!\\Newtonsoft.Json.dll&& " +
        "$(exe //third_party/dotnet/ilrepack:ilrepack) !merge_args!" +
        ")" +
        ")" +
        ")",
    out = "lib",
)

genrule(
    name = "pack",
    srcs = ["WebDriver.nuspec"],
    cmd_exe = "$(exe //third_party/dotnet/nuget:nuget) pack %SRCS% /Properties packageid=Selenium.WebDriver /Version {} /BasePath $(location :merge) /OutputDirectory %OUT%".format(SE_VERSION),
    out = "dist",
    visibility = ["PUBLIC"],
)

genrule(
    name = "pack_strongnamed",
    srcs = ["WebDriver.StrongNamed.nuspec"],
    cmd_exe = "$(exe //third_party/dotnet/nuget:nuget) pack %SRCS% /Properties packageid=Selenium.WebDriver.StrongNamed /Version {} /BasePath $(location :merge_strongnamed) /OutputDirectory %OUT%".format(SE_VERSION),
    out = "dist",
    visibility = ["PUBLIC"],
)

genrule(
    name = "webdriver_deps",
    srcs = [
        "//third_party/js/selenium:webdriver_prefs",
        "//javascript/webdriver/atoms:get-attribute",
        "//javascript/atoms/fragments:is-displayed",
    ],
    bash = 'echo "$SRCS" > $OUT',
    cmd_exe = 'echo "%SRCS%" > %OUT%',
    out = "deps.txt",
)
