java_library(name = 'proxies',
  srcs = [
    'DoNotUseProxyPac.java',
    'Maps.java',
    'Proxies.java',
  ],
  deps = [
    '//java/client/src/org/openqa/selenium:webdriver-api',
    '//java/client/src/org/openqa/selenium/remote:capabilities',
  ],
  visibility = [
    '//java/client/src/org/openqa/selenium/firefox:firefox',
    '//java/client/src/org/openqa/selenium/htmlunit:htmlunit',
    '//java/client/src/org/openqa/selenium/remote:remote',
  ],
)
