module Selenium
  module WebDriver
    class Credential
      @id: untyped

      @resident_credential: untyped

      @rp_id: untyped

      @user_handle: untyped

      @private_key: untyped

      @sign_count: untyped

      def self.resident: (**untyped opts) -> Credential

      def self.non_resident: (**untyped opts) -> Credential

      def self.encode: (untyped byte_array) -> untyped

      def self.decode: (untyped base64) -> untyped

      def self.from_json: (untyped opts) -> Credential

      attr_reader id: untyped

      attr_reader resident_credential: untyped

      attr_reader rp_id: untyped

      attr_reader user_handle: untyped

      attr_reader private_key: untyped

      attr_reader sign_count: untyped

      alias resident_credential? resident_credential

      def initialize: (id: untyped, resident_credential: untyped, rp_id: untyped, private_key: untyped, **untyped opts) -> void

      def as_json: (*untyped) -> untyped
    end
  end
end
