java_library(
    name = "os",
    srcs = glob(["*.java"]),
    deps = [
        "//java/client/src/org/openqa/selenium:core",
        "//java/client/src/org/openqa/selenium/io:io",
        "//third_party/java/commons:commons-exec",
        "//third_party/java/guava:guava",
    ],
    visibility = [
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/test/org/openqa/selenium:tests",
        "//java/client/test/org/openqa/selenium/build:build",
        "//java/client/test/org/openqa/selenium/testing/drivers:drivers",
    ],
)
