java_library(
  name = 'os',
  srcs = glob(['*.java']),
  deps = [
    '//java/client/src/org/openqa/selenium:webdriver-api',
    '//java/client/src/org/openqa/selenium/io:io',
    '//third_party/java/commons-exec:commons-exec',
    '//third_party/java/guava:guava',
    '//third_party/java/jna:jna',
  ],
  visibility = [
    '//java/client/src/org/openqa/selenium/browserlaunchers/locators:locators',
    '//java/client/src/org/openqa/selenium/firefox:firefox',
    '//java/client/src/org/openqa/selenium/remote/service:service',
    '//java/client/src/org/openqa/selenium/safari:safari',
    '//java/client/test/org/openqa/selenium:tests',
    '//java/client/test/org/openqa/selenium/testing/drivers:drivers',
    '//java/server/src/org/openqa/selenium/server:server',
  ],
)

