java_binary(
    name = "selenium-runner",
    main_class = "org.openqa.selenium.server.htmlrunner.HTMLLauncher",
    deps = [
        ":htmlrunner",
    ],
)

java_library(
    name = "htmlrunner",
    srcs = glob(["*.java"]),
    deps = [
        "//java/client/src/com/thoughtworks/selenium:leg-rc",
        "//java/client/src/com/thoughtworks/selenium/webdriven:webdriven",
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/src/org/openqa/selenium/chrome:chrome",
        "//java/client/src/org/openqa/selenium/edge/edgehtml:edgehtml",
        "//java/client/src/org/openqa/selenium/firefox:firefox",
        "//java/client/src/org/openqa/selenium/ie:ie",
        "//java/client/src/org/openqa/selenium/opera:opera",
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/client/src/org/openqa/selenium/safari:safari",
        "//third_party/java/beust:jcommander",
        "//third_party/java/guava:guava",
        "//third_party/java/jetty:jetty",
    ],
    visibility = [
        "//java/server/src/com/thoughtworks/selenium:leg-rc",
        "//java/server/test/org/openqa/selenium/...",
    ],
)
