java_library(name = 'htmlunit',
  srcs = glob(['*.java']),
  exported_deps = [
    '//third_party/java/htmlunit:htmlunit',
    '//third_party/java/htmlunit:js-core',
  ],
  deps = [
    '//java/client/src/org/openqa/selenium:webdriver-api',
    '//java/client/src/org/openqa/selenium/interactions:interactions',
    '//java/client/src/org/openqa/selenium/logging:api',
    '//java/client/src/org/openqa/selenium/remote:capabilities',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//java/client/src/org/openqa/selenium/support:support',
    '//third_party/java/css:sac',
    '//third_party/java/guava:guava',
    '//third_party/java/xml:xml',
  ],
  visibility = ['PUBLIC'],
)
