java_test(
    name = "config",
    srcs = glob(["*.java"]),
    labels = [
        "small",
    ],
    deps = [
        "//java/server/src/org/openqa/selenium/grid:grid",
        "//third_party/java/beust:jcommander",
        "//third_party/java/guava:guava",
        "//third_party/java/junit:junit",
    ],
)
