java_test(
    name = "config",
    srcs = glob(["*.java"]),
    labels = [
        "small",
    ],
    deps = [
        "//java/server/src/org/openqa/selenium/grid/config:config",
        "//third_party/java/guava:guava",
        "//third_party/java/junit:junit",
    ],
)
