# Rakefile for Selenium Ruby Client   -*- ruby -*-

$:.unshift '../../../../lib'

require 'rubygems'
require 'rake/clean'
require 'rake/testtask'
require 'rake/packagetask'
require 'rake/gempackagetask'
require 'rake/rdoctask'

gem "rspec", ">=1.2.8"
require 'spec/rake/spectask'
CLEAN.include("target")

desc "Run all Selenium tests"
Spec::Rake::SpecTask.new("test") do |t|
    t.spec_files = FileList['*_spec.rb']
    t.spec_opts << '--color'
    t.spec_opts << "--require '../../../../lib/selenium/rspec/reporting/selenium_test_report_formatter'"
    t.spec_opts << "--format=Selenium::RSpec::SeleniumTestReportFormatter:./target/integration_tests_report.html"
    t.spec_opts << "--format=progress"                
end

task :test => :report_dir

task :report_dir do
  mkdir_p "./target"
end
