load("//java:version.bzl", "SE_VERSION")
load("//java:rules.bzl", "java_library")

java_library(
    name = "api",
    srcs = [
        "Augmentable.java",
        "Command.java",
        "CommandPayload.java",
        "CommandExecutor.java",
        "ErrorCodes.java",
        "Response.java",
        "ScreenshotException.java",
        "SessionId.java",
    ],
    deps = [
        "//java/client/src/org/openqa/selenium:core",
        "//java/client/src/org/openqa/selenium/json:json",
        "//third_party/java/guava:guava",
    ],
)

java_library(
    name = "capabilities",
    srcs = [
        "BrowserType.java",
        "CapabilityType.java",
        "DesiredCapabilities.java",
    ],
    deps = [
        "//java/client/src/org/openqa/selenium:selenium",
        "//third_party/java/guava:guava",
    ],
    visibility = [
        "//java/client/src/org/openqa/selenium/remote/session:session",
    ],
)

java_library(
    name = "http-session-id",
    srcs = ["HttpSessionId.java"],
)

java_library(
    name = "remote",
    maven_coords = "org.seleniumhq.selenium:selenium-remote-driver:" + SE_VERSION,
    maven_pom_template = "//java/client/src/org/openqa/selenium:template-pom",
    module_info = "module-info.txt",
    srcs = [
        "Augmenter.java",
        "AugmenterProvider.java",
        "AddRotatable.java",
        "BaseAugmenter.java",
        "InterfaceImplementation.java",
        "JdkAugmenter.java",
        "html5/AddApplicationCache.java",
        "html5/AddLocationContext.java",
        "html5/AddWebStorage.java",
        "mobile/AddNetworkConnection.java",
    ],
    exported_deps = [
        ":remote-lib",
        "//java/client/src/org/openqa/selenium:selenium",
    ],
    deps = [
        "//java/client/src/org/openqa/selenium/remote/tracing:tracing",
        "//third_party/java/bytebuddy:byte-buddy",
        "//third_party/java/guava:guava",
    ],
    visibility = ["PUBLIC"],
)

java_library(
    name = "remote-lib",
    srcs = [
        "AbstractDriverOptions.java",
        "AcceptedW3CCapabilityKeys.java",
        "CommandCodec.java",
        "CommandInfo.java",
        "Dialect.java",
        "DriverCommand.java",
        "ErrorHandler.java",
        "ExecuteMethod.java",
        "FileDetector.java",
        "HandshakeResponse.java",
        "HttpCommandExecutor.java",
        "InitialHandshakeResponse.java",
        "JsonToWebElementConverter.java",
        "JsonWireProtocolResponse.java",
        "LocalFileDetector.java",
        "NewSessionPayload.java",
        "ProtocolHandshake.java",
        "RemoteExecuteMethod.java",
        "RemoteKeyboard.java",
        "RemoteLogs.java",
        "RemoteMouse.java",
        "RemoteStatus.java",
        "RemoteTouchScreen.java",
        "RemoteWebDriver.java",
        "RemoteWebDriverBuilder.java",
        "RemoteWebElement.java",
        "ResponseCodec.java",
        "UnreachableBrowserException.java",
        "UselessFileDetector.java",
        "W3CHandshakeResponse.java",
        "html5/RemoteApplicationCache.java",
        "html5/RemoteLocalStorage.java",
        "html5/RemoteLocationContext.java",
        "html5/RemoteSessionStorage.java",
        "html5/RemoteWebStorage.java",
        "internal/JsonToWebElementConverter.java",
        "internal/WebElementToJsonConverter.java",
        "mobile/RemoteNetworkConnection.java",
    ] + glob([
        "codec/*.java",
        "codec/jwp/*.java",
        "codec/w3c/*.java",
        "service/*.java",
    ]),
    resources = [
        ":get-attribute",
        ":is-displayed",
    ],
    exported_deps = [
        ":api",
        ":capabilities",
        ":http-session-id",
        "//java/client/src/org/openqa/selenium/devtools:devtools",
        "//java/client/src/org/openqa/selenium/remote/http:http",
        "//java/client/src/org/openqa/selenium/json:json",
        "//java/client/src/org/openqa/selenium/remote/session:session",
        "//third_party/java/okhttp3:okhttp",
    ],
    deps = [
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/src/org/openqa/selenium/remote/http/okhttp:okhttp",
        "//third_party/java/guava:guava",
    ],
)

export_file(
    name = "get-attribute",
    src = "//javascript/webdriver/atoms:get-attribute",
    out = "getAttribute.js",
)

export_file(
    name = "is-displayed",
    src = "//javascript/atoms/fragments:is-displayed",
    out = "isDisplayed.js",
)
