java_library(
  name = 'api',
  srcs = [
    'Command.java',
    'CommandExecutor.java',
    'Response.java',
    'SessionId.java',
  ],
  visibility = ['PUBLIC'],
)

java_library(
  name = 'capabilities',
  srcs = [
    'BrowserType.java',
    'CapabilityType.java',
    'DesiredCapabilities.java',
  ],
  deps = [
    '//java/client/src/org/openqa/selenium:webdriver-api',
    '//java/client/src/org/openqa/selenium/logging:logging',
    '//third_party/java/guava-libraries:guava-libraries',
  ],
  visibility = ['PUBLIC'],
)

java_library(
  name = 'http-session-id',
  srcs = [ 'HttpSessionId.java' ],
)

java_library(name = 'remote',
  srcs = [
    'BeanToJsonConverter.java',
    'CommandInfo.java',
    'CoordinatesUtils.java',
    'DriverCommand.java',
    'ErrorCodes.java',
    'ErrorHandler.java',
    'ExecuteMethod.java',
    'FileDetector.java',
    'HttpCommandExecutor.java',
    'HttpVerb.java',
    'JsonException.java',
    'JsonToBeanConverter.java',
    'RemoteExecuteMethod.java',
    'RemoteKeyboard.java',
    'RemoteLogs.java',
    'RemoteMouse.java',
    'RemoteStatus.java',
    'RemoteTouchScreen.java',
    'RemoteWebDriver.java',
    'RemoteWebElement.java',
    'ScreenshotException.java',
    'SessionNotFoundException.java',
    'SimplePropertyDescriptor.java',
    'UnreachableBrowserException.java',
    'UselessFileDetector.java',
    'internal/CircularOutputStream.java',
    'internal/HttpClientFactory.java',
    'internal/JsonToWebElementConverter.java',
    'internal/WebElementToJsonConverter.java',
  ],
  exported_deps = [
    ':api',
    ':capabilities',
    '//java/client/src/org/openqa/selenium:webdriver-api',
    '//java/client/src/org/openqa/selenium/interactions:exceptions',
    '//java/client/src/org/openqa/selenium/logging:logging',
  ],
  deps = [
    ':http-session-id',
    '//java/client/src/org/openqa/selenium/browserlaunchers:proxies',
    '//java/client/src/org/openqa/selenium/io:io',
    '//java/client/src/org/openqa/selenium/net:net',
    '//third_party/java/apache-httpclient:apache-httpclient',
    '//third_party/java/guava-libraries:guava-libraries',
    '//third_party/java/json:json',
  ],
  visibility = ['PUBLIC'],
)
