java_library(
    name = "okhttp",
    srcs = glob(["*.java"]),
    deps = [
        "//java/client/src/org/openqa/selenium/remote/http:http",
        "//third_party/java/guava:guava",
        "//third_party/java/okhttp3:okhttp",
    ],
    visibility = [
        "//java/client/src/org/openqa/selenium/remote:",
        "//java/client/test/org/openqa/selenium/remote/http/okhttp:",
    ],
)
