module Selenium
  module WebDriver
    module DriverExtensions
      module HasDevTools
        include _Driver

        @devtools: untyped

        def devtools: () -> untyped
      end
    end
  end
end
