module Selenium
  module WebDriver
    module DriverExtensions
      module HasPinnedScripts
        include _DevTools

        @pinned_scripts: untyped

        def pinned_scripts: () -> untyped

        def pin_script: (untyped script) -> untyped

        def unpin_script: (untyped script) -> untyped
      end
    end
  end
end
