module Selenium
  module WebDriver
    module DriverExtensions
      module HasAuthentication
        include _DevTools

        @auth_handlers: untyped

        def register: (username: untyped, password: untyped, ?uri: untyped) -> untyped

        private

        def auth_handlers: () -> untyped

        def authenticate: (untyped request_id, untyped url) -> untyped
      end
    end
  end
end
