java_library(name = 'api',
  srcs = [
    'CommandProcessor.java',
    'Selenium.java',
    'SeleniumException.java',
  ],
  visibility = ['PUBLIC'],
)

java_library(name = 'selenium',
  srcs = [
    'BrowserConfigurationOptions.java',
    'DefaultRemoteCommand.java',
    'DefaultSelenium.java',
    'HttpCommandProcessor.java',
    'RemoteCommand.java',
    'ScreenshotListener.java',
    'SeleneseTestBase.java',
    'SeleneseTestCase.java',
    'SeleneseTestNgHelper.java',
    'SeleniumLogLevels.java',
  ],
  exported_deps = [
    ':api',
    ':wait',
    '//java/client/src/com/thoughtworks/selenium/condition:condition',
  ],
  deps = [
    '//java/client/src/org/openqa/selenium:webdriver-api',
    '//java/client/src/org/openqa/selenium/net:net',
    '//third_party/java/guava-libraries:guava-libraries',
    '//third_party/java/junit:junit',
    '//third_party/java/testng:testng',
  ],
  visibility = ['PUBLIC'],
)

java_library(name = 'wait',
  srcs = [
    'Wait.java',
  ],
  deps = [
    ':api',
  ])

