load("//java:version.bzl", "SE_VERSION")

java_library(
    name = "api",
    srcs = [
        "CommandProcessor.java",
        "Selenium.java",
        "SeleniumException.java",
        "Wait.java",
    ],
    visibility = [
        "//java/client/src/com/thoughtworks/selenium/condition:condition",
    ],
)

java_library(
    name = "selenium",
    srcs = [
        "BrowserConfigurationOptions.java",
        "DefaultRemoteCommand.java",
        "DefaultSelenium.java",
        "HttpCommandProcessor.java",
        "RemoteCommand.java",
        "ScreenshotListener.java",
        "SeleneseTestBase.java",
        "SeleneseTestCase.java",
        "SeleneseTestNgHelper.java",
        "SeleniumLogLevels.java",
    ],
    exported_deps = [
        ":api",
    ],
    deps = [
        "//java/client/src/org/openqa/selenium/edge/edgehtml:edgehtml",
        "//third_party/java/guava:guava",
        "//third_party/java/junit:junit",
        "//third_party/java/testng:testng",
    ],
    visibility = [
        "//java/client/src/com/thoughtworks/selenium/...",
        "//java/client/test/com/thoughtworks/selenium/...",
        "//java/server/src/com/thoughtworks/selenium:leg-rc",
    ],
)

java_library(
    name = "leg-rc",
    exported_deps = [
        ":api",
        ":selenium",
        "//java/client/src/com/thoughtworks/selenium/condition:condition",
        "//java/client/src/com/thoughtworks/selenium/webdriven:webdriven",
    ],
    visibility = [
        "PUBLIC",
    ],
)
