java_library(name = 'api',
  srcs = [
    'CommandProcessor.java',
    'Selenium.java',
    'SeleniumException.java',
    'Wait.java',
  ],
  visibility = ['PUBLIC'],
)

java_library(name = 'selenium',
  srcs = [
    'BrowserConfigurationOptions.java',
    'DefaultRemoteCommand.java',
    'DefaultSelenium.java',
    'HttpCommandProcessor.java',
    'RemoteCommand.java',
    'ScreenshotListener.java',
    'SeleneseTestBase.java',
    'SeleneseTestCase.java',
    'SeleneseTestNgHelper.java',
    'SeleniumLogLevels.java',
  ],
  exported_deps = [
    ':api',
    '//java/client/src/com/thoughtworks/selenium/condition:condition',
  ],
  deps = [
    '//java/client/src/org/openqa/selenium:selenium',
    '//third_party/java/guava:guava',
    '//third_party/java/junit:junit',
    '//third_party/java/testng:testng',
  ],
  visibility = ['PUBLIC'],
)


java_binary(name = "legacy-selenium-client",
  deps = [
    ':selenium',
    '//java/client/src/com/thoughtworks/selenium/webdriven:webdriven',
  ],
)
