module Selenium
  module WebDriver
    class BiDi
      module UrlPattern
        ALLOWED_KEYS: Array[Symbol]

        WEB: Array[Hash[Symbol, String]]

        def self?.format_pattern: (nil | Array[String] | Array[URI] | Array[Hash[Symbol, String]]) -> Array[Hash[Symbol, String]]

        def self?.to_url_pattern: (Hash[Symbol, String]) -> Hash[Symbol, String]
      end
    end
  end
end
