#!/bin/sh

# JsUnit - a JUnit port for JavaScript
# Copyright (C) 1999,2000,2001,2002,2003,2006 Joerg Schaible
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

JS="../lib/JsUtil.js"
JS="$JS ../lib/JsUnit.js"
JS="$JS ../lib/JsUnitBV.js"
JS="$JS ArrayTest.js"
JS="$JS demo/Demo.js"
JS="$JS demo/DemoTest.js"
JS="$JS money/IMoney.js"
JS="$JS money/Money.js"
JS="$JS money/MoneyBag.js"
JS="$JS money/MoneyTest.js"
JS="$JS SimpleTest.js"
CWD=$PWD

rm -rf .ctx/ > /dev/null 2>&1
mkdir .ctx
(cd .ctx; for js in $JS; do ln -s $CWD/$js `basename $js`; done)
ctxdriver -R -s .ctx:$BV1TO1/script_library -l $BV1TO1/lib/components JsUnitBVTest.jsp
rm -rf .ctx/ 

