using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;
using System.Data;
using System.IO;
using System.Text;
using System.Threading;

namespace Selenium.WebDriver.SourceGenerator;

[Generator]
public class ResourceUtilitiesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var jsFiles = context.AdditionalTextsProvider
            .Where(static (text) => text.Path.EndsWith(".js") || text.Path.EndsWith(".json"))
            .WithTrackingName("AtomFiles")
            .Select(static (data, token) =>
            {
                var name = Path.GetFileName(data.Path);
                var code = GenerateAtom(data, token, out var diagnostics);
                
                return (name, code, diagnostics);
            });

        context.RegisterSourceOutput(jsFiles, static (context, pair) =>
        {
            foreach (var diagnostic in pair.diagnostics)
            {
                context.ReportDiagnostic(diagnostic);
            }
            if (pair.code is not null)
            {
                var propertyName = GetPropertyNameFromFilePath(pair.name, out _, out var diag);
                if (diag is not null)
                {
                    context.ReportDiagnostic(diag);
                }

                context.AddSource($"ResourceUtilities.{propertyName}.g.cs", SourceText.From(pair.code, Encoding.UTF8));
            }
        });
    }

    private static string? GenerateAtom(AdditionalText additionalText, CancellationToken token, out ImmutableArray<Diagnostic> diagnostics)
    {
        diagnostics = [];
        var sourceText = additionalText.GetText(token);
        if (sourceText is null)
        {
            var d = Diagnostic.Create(new DiagnosticDescriptor("WRG1001", "Failed to read atom", "Atom '{0}' could not be read", "WebDriverResourceGenerator", DiagnosticSeverity.Error, true), Location.None, additionalText.Path);
            diagnostics = [d];
            return null;
        }

        var propertyName = GetPropertyNameFromFilePath(additionalText.Path, out var lang, out var diag);
        if (diag is not null)
        {
            diagnostics = [diag];
        }

        return $$"""""""
            // <auto-generated />

            namespace OpenQA.Selenium.Internal;

            internal static partial class ResourceUtilities
            {
                [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("{{lang}}")]
                internal const string {{propertyName}} =
            """""
            {{sourceText}}
            """"";
            }

            """"""";
    }

    private static string GetPropertyNameFromFilePath(string filePath, out string language, out Diagnostic? diagnostic)
    {
        diagnostic = null;
        if (filePath.EndsWith("webdriver.json"))
        {
            language = "json";
            return "WebDriverPrefsJson";
        }
        else if (filePath.EndsWith("is-displayed.js"))
        {
            language = "javascript";
            return "IsDisplayedAtom";
        }
        else if (filePath.EndsWith("mutation-listener.js"))
        {
            language = "javascript";
            return "MutationListenerAtom";
        }
        else if (filePath.EndsWith("get-attribute.js"))
        {
            language = "javascript";
            return "GetAttributeAtom";
        }
        else if (filePath.EndsWith("find-elements.js"))
        {
            language = "javascript";
            return "FindElementsAtom";
        }
 
        diagnostic = Diagnostic.Create(new DiagnosticDescriptor("WRG1002", "Unknown resource file", "Unknown file in the resource generator '{0}'", "WebDriverResourceGenerator", DiagnosticSeverity.Warning, true), Location.None, filePath);
        
        var suffix = filePath.EndsWith(".js") ? "Atom" : "Json";

        language = string.Empty;
        return KebabCaseToPascalCase(Path.GetFileNameWithoutExtension(filePath)) + suffix;
    }

    private static string KebabCaseToPascalCase(string v)
    {
        Span<char> newValues = new char[v.Length];
        int newValuesOffset = 0;
        for (int i = 0; i < v.Length; i++)
        {
            if (i == 0)
            {
                newValues[i - newValuesOffset] = char.ToUpperInvariant(v[i]);
            }
            else if (char.IsLetter(v[i]))
            {
                newValues[i - newValuesOffset] = v[i];
            }
            else
            {
                i++;
                newValuesOffset++;
                newValues[i - newValuesOffset] = char.ToUpperInvariant(v[i]);
            }
        }

        return newValues.Slice(0, v.Length - newValuesOffset).ToString();
    }
}
