# frozen_string_literal: true

# Licensed to the Software Freedom Conservancy (SFC) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The SFC licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# This file is automatically generated. DO NOT EDIT!
# Regenerate with: bazel run //rb/lib/selenium/webdriver:bidi-generate

module Selenium
  module WebDriver
    class BiDi
      module Protocol
        # @api private
        # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
        class Bluetooth
          EVENTS = {
            request_device_prompt_updated: 'bluetooth.requestDevicePromptUpdated',
            gatt_connection_attempted: 'bluetooth.gattConnectionAttempted'
          }.freeze

          SIMULATE_ADAPTER_PARAMETERS_STATE = {
            absent: 'absent',
            powered_off: 'powered-off',
            powered_on: 'powered-on'
          }.freeze

          SIMULATE_SERVICE_PARAMETERS_TYPE = {
            add: 'add',
            remove: 'remove'
          }.freeze

          SIMULATE_CHARACTERISTIC_PARAMETERS_TYPE = {
            add: 'add',
            remove: 'remove'
          }.freeze

          SIMULATE_CHARACTERISTIC_RESPONSE_PARAMETERS_TYPE = {
            read: 'read',
            write: 'write',
            subscribe_to_notifications: 'subscribe-to-notifications',
            unsubscribe_from_notifications: 'unsubscribe-from-notifications'
          }.freeze

          SIMULATE_DESCRIPTOR_PARAMETERS_TYPE = {
            add: 'add',
            remove: 'remove'
          }.freeze

          SIMULATE_DESCRIPTOR_RESPONSE_PARAMETERS_TYPE = {
            read: 'read',
            write: 'write'
          }.freeze

          CHARACTERISTIC_EVENT_GENERATED_PARAMETERS_TYPE = {
            read: 'read',
            write_with_response: 'write-with-response',
            write_without_response: 'write-without-response',
            subscribe_to_notifications: 'subscribe-to-notifications',
            unsubscribe_from_notifications: 'unsubscribe-from-notifications'
          }.freeze

          DESCRIPTOR_EVENT_GENERATED_PARAMETERS_TYPE = {
            read: 'read',
            write: 'write'
          }.freeze

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          BluetoothManufacturerData = Serialization::Record.define(key: 'key', data: 'data')

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          CharacteristicProperties = Serialization::Record.define(
            broadcast: 'broadcast',
            read: 'read',
            write_without_response: 'writeWithoutResponse',
            write: 'write',
            notify: 'notify',
            indicate: 'indicate',
            authenticated_signed_writes: 'authenticatedSignedWrites',
            extended_properties: 'extendedProperties'
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          RequestDeviceInfo = Serialization::Record.define(id: 'id', name: {json_key: 'name', nullable: true})

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          ScanRecord = Serialization::Record.define(
            name: 'name',
            uuids: {json_key: 'uuids', list: true},
            appearance: 'appearance',
            manufacturer_data: {json_key: 'manufacturerData', ref: 'Bluetooth::BluetoothManufacturerData', list: true}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class HandleRequestDevicePromptParameters < Serialization::Union
            discriminator 'accept'
            variants(
              true => 'Bluetooth::HandleRequestDevicePromptParameters::AcceptParameters',
              false => 'Bluetooth::HandleRequestDevicePromptParameters::CancelParameters'
            )

            # @api private
            # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
            AcceptParameters = Serialization::Record.define(
              accept: {fixed: true},
              context: 'context',
              prompt: 'prompt',
              device: 'device'
            )

            # @api private
            # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
            CancelParameters = Serialization::Record.define(
              accept: {fixed: false},
              context: 'context',
              prompt: 'prompt'
            )
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          SimulateAdapterParameters = Serialization::Record.define(
            context: 'context',
            le_supported: 'leSupported',
            state: {json_key: 'state', enum: 'Bluetooth::SIMULATE_ADAPTER_PARAMETERS_STATE'}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          DisableSimulationParameters = Serialization::Record.define(context: 'context')

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          SimulatePreconnectedPeripheralParameters = Serialization::Record.define(
            context: 'context',
            address: 'address',
            name: 'name',
            manufacturer_data: {json_key: 'manufacturerData', ref: 'Bluetooth::BluetoothManufacturerData', list: true},
            known_service_uuids: {json_key: 'knownServiceUuids', list: true}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          SimulateAdvertisementParameters = Serialization::Record.define(
            context: 'context',
            scan_entry: {json_key: 'scanEntry', ref: 'Bluetooth::SimulateAdvertisementScanEntryParameters'}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          SimulateAdvertisementScanEntryParameters = Serialization::Record.define(
            device_address: 'deviceAddress',
            rssi: 'rssi',
            scan_record: {json_key: 'scanRecord', ref: 'Bluetooth::ScanRecord'}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          SimulateGattConnectionResponseParameters = Serialization::Record.define(
            context: 'context',
            address: 'address',
            code: 'code'
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          SimulateGattDisconnectionParameters = Serialization::Record.define(context: 'context', address: 'address')

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          SimulateServiceParameters = Serialization::Record.define(
            context: 'context',
            address: 'address',
            uuid: 'uuid',
            type: {json_key: 'type', enum: 'Bluetooth::SIMULATE_SERVICE_PARAMETERS_TYPE'}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          SimulateCharacteristicParameters = Serialization::Record.define(
            context: 'context',
            address: 'address',
            service_uuid: 'serviceUuid',
            characteristic_uuid: 'characteristicUuid',
            characteristic_properties: {json_key: 'characteristicProperties', ref: 'Bluetooth::CharacteristicProperties'},
            type: {json_key: 'type', enum: 'Bluetooth::SIMULATE_CHARACTERISTIC_PARAMETERS_TYPE'}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          SimulateCharacteristicResponseParameters = Serialization::Record.define(
            context: 'context',
            address: 'address',
            service_uuid: 'serviceUuid',
            characteristic_uuid: 'characteristicUuid',
            type: {json_key: 'type', enum: 'Bluetooth::SIMULATE_CHARACTERISTIC_RESPONSE_PARAMETERS_TYPE'},
            code: 'code',
            data: {json_key: 'data', list: true}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          SimulateDescriptorParameters = Serialization::Record.define(
            context: 'context',
            address: 'address',
            service_uuid: 'serviceUuid',
            characteristic_uuid: 'characteristicUuid',
            descriptor_uuid: 'descriptorUuid',
            type: {json_key: 'type', enum: 'Bluetooth::SIMULATE_DESCRIPTOR_PARAMETERS_TYPE'}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          SimulateDescriptorResponseParameters = Serialization::Record.define(
            context: 'context',
            address: 'address',
            service_uuid: 'serviceUuid',
            characteristic_uuid: 'characteristicUuid',
            descriptor_uuid: 'descriptorUuid',
            type: {json_key: 'type', enum: 'Bluetooth::SIMULATE_DESCRIPTOR_RESPONSE_PARAMETERS_TYPE'},
            code: 'code',
            data: {json_key: 'data', list: true}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          RequestDevicePromptUpdatedParameters = Serialization::Record.define(
            context: 'context',
            prompt: 'prompt',
            devices: {json_key: 'devices', ref: 'Bluetooth::RequestDeviceInfo', list: true}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          GattConnectionAttemptedParameters = Serialization::Record.define(context: 'context', address: 'address')

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          CharacteristicEventGeneratedParameters = Serialization::Record.define(
            context: 'context',
            address: 'address',
            service_uuid: 'serviceUuid',
            characteristic_uuid: 'characteristicUuid',
            type: {json_key: 'type', enum: 'Bluetooth::CHARACTERISTIC_EVENT_GENERATED_PARAMETERS_TYPE'},
            data: {json_key: 'data', list: true}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          DescriptorEventGeneratedParameters = Serialization::Record.define(
            context: 'context',
            address: 'address',
            service_uuid: 'serviceUuid',
            characteristic_uuid: 'characteristicUuid',
            descriptor_uuid: 'descriptorUuid',
            type: {json_key: 'type', enum: 'Bluetooth::DESCRIPTOR_EVENT_GENERATED_PARAMETERS_TYPE'},
            data: {json_key: 'data', list: true}
          )

          EVENT_TYPES = {
            'bluetooth.requestDevicePromptUpdated' => Bluetooth::RequestDevicePromptUpdatedParameters,
            'bluetooth.gattConnectionAttempted' => Bluetooth::GattConnectionAttemptedParameters
          }.freeze

          def initialize(transport)
            @transport = transport
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def handle_request_device_prompt(context:, prompt:, accept:, device: Serialization::UNSET)
            params = HandleRequestDevicePromptParameters.build(
              context: context,
              prompt: prompt,
              accept: accept,
              device: device
            )
            @transport.execute(cmd: 'bluetooth.handleRequestDevicePrompt', params: params)
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def simulate_adapter(context:, state:, le_supported: Serialization::UNSET)
            Serialization.validate!('state', state, Bluetooth::SIMULATE_ADAPTER_PARAMETERS_STATE)
            params = SimulateAdapterParameters.new(context: context, le_supported: le_supported, state: state)
            @transport.execute(cmd: 'bluetooth.simulateAdapter', params: params)
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def disable_simulation(context:)
            params = DisableSimulationParameters.new(context: context)
            @transport.execute(cmd: 'bluetooth.disableSimulation', params: params)
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def simulate_preconnected_peripheral(context:, address:, name:, manufacturer_data:, known_service_uuids:)
            params = SimulatePreconnectedPeripheralParameters.new(
              context: context,
              address: address,
              name: name,
              manufacturer_data: manufacturer_data,
              known_service_uuids: known_service_uuids
            )
            @transport.execute(cmd: 'bluetooth.simulatePreconnectedPeripheral', params: params)
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def simulate_advertisement(context:, scan_entry:)
            params = SimulateAdvertisementParameters.new(context: context, scan_entry: scan_entry)
            @transport.execute(cmd: 'bluetooth.simulateAdvertisement', params: params)
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def simulate_gatt_connection_response(context:, address:, code:)
            params = SimulateGattConnectionResponseParameters.new(context: context, address: address, code: code)
            @transport.execute(cmd: 'bluetooth.simulateGattConnectionResponse', params: params)
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def simulate_gatt_disconnection(context:, address:)
            params = SimulateGattDisconnectionParameters.new(context: context, address: address)
            @transport.execute(cmd: 'bluetooth.simulateGattDisconnection', params: params)
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def simulate_service(context:, address:, uuid:, type:)
            Serialization.validate!('type', type, Bluetooth::SIMULATE_SERVICE_PARAMETERS_TYPE)
            params = SimulateServiceParameters.new(context: context, address: address, uuid: uuid, type: type)
            @transport.execute(cmd: 'bluetooth.simulateService', params: params)
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def simulate_characteristic(
            context:,
            address:,
            service_uuid:,
            characteristic_uuid:,
            type:,
            characteristic_properties: Serialization::UNSET
          )
            Serialization.validate!('type', type, Bluetooth::SIMULATE_CHARACTERISTIC_PARAMETERS_TYPE)
            params = SimulateCharacteristicParameters.new(
              context: context,
              address: address,
              service_uuid: service_uuid,
              characteristic_uuid: characteristic_uuid,
              characteristic_properties: characteristic_properties,
              type: type
            )
            @transport.execute(cmd: 'bluetooth.simulateCharacteristic', params: params)
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def simulate_characteristic_response(
            context:,
            address:,
            service_uuid:,
            characteristic_uuid:,
            type:,
            code:,
            data: Serialization::UNSET
          )
            Serialization.validate!('type', type, Bluetooth::SIMULATE_CHARACTERISTIC_RESPONSE_PARAMETERS_TYPE)
            params = SimulateCharacteristicResponseParameters.new(
              context: context,
              address: address,
              service_uuid: service_uuid,
              characteristic_uuid: characteristic_uuid,
              type: type,
              code: code,
              data: data
            )
            @transport.execute(cmd: 'bluetooth.simulateCharacteristicResponse', params: params)
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def simulate_descriptor(context:, address:, service_uuid:, characteristic_uuid:, descriptor_uuid:, type:)
            Serialization.validate!('type', type, Bluetooth::SIMULATE_DESCRIPTOR_PARAMETERS_TYPE)
            params = SimulateDescriptorParameters.new(
              context: context,
              address: address,
              service_uuid: service_uuid,
              characteristic_uuid: characteristic_uuid,
              descriptor_uuid: descriptor_uuid,
              type: type
            )
            @transport.execute(cmd: 'bluetooth.simulateDescriptor', params: params)
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def simulate_descriptor_response(
            context:,
            address:,
            service_uuid:,
            characteristic_uuid:,
            descriptor_uuid:,
            type:,
            code:,
            data: Serialization::UNSET
          )
            Serialization.validate!('type', type, Bluetooth::SIMULATE_DESCRIPTOR_RESPONSE_PARAMETERS_TYPE)
            params = SimulateDescriptorResponseParameters.new(
              context: context,
              address: address,
              service_uuid: service_uuid,
              characteristic_uuid: characteristic_uuid,
              descriptor_uuid: descriptor_uuid,
              type: type,
              code: code,
              data: data
            )
            @transport.execute(cmd: 'bluetooth.simulateDescriptorResponse', params: params)
          end
        end # Bluetooth
      end # Protocol
    end # BiDi
  end # WebDriver
end # Selenium
