# frozen_string_literal: true

# Licensed to the Software Freedom Conservancy (SFC) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The SFC licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# DO NOT EDIT! This file is generated by rb/lib/selenium/webdriver/bidi/support/bidi_generate.rb.
# Regenerate with: `bazel run //rb/lib/selenium/webdriver:bidi-generate`

module Selenium
  module WebDriver
    class BiDi
      module Protocol
        # @api private
        # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
        class DigitalCredentials < Domain
          # @see https://w3c-fedid.github.io/digital-credentials/#cddl-type-digitalcredentials-virtualwalletaction
          VIRTUAL_WALLET_ACTION = {
            decline: 'decline',
            respond: 'respond',
            wait: 'wait',
            clear: 'clear'
          }.freeze

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          # @see https://w3c-fedid.github.io/digital-credentials/#cddl-type-digitalcredentials-setvirtualwalletbehaviorparameters
          SetVirtualWalletBehaviorParameters = Serialization::Record.define(
            action: {wire_key: 'action', enum: 'DigitalCredentials::VIRTUAL_WALLET_ACTION'},
            context: {wire_key: 'context', required: false, primitive: 'string'},
            protocol: {wire_key: 'protocol', required: false, primitive: 'string'},
            response: {wire_key: 'response', required: false}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def set_virtual_wallet_behavior(
            action:,
            context: Serialization::UNSET,
            protocol: Serialization::UNSET,
            response: Serialization::UNSET
          )
            Serialization.validate!('action', action, DigitalCredentials::VIRTUAL_WALLET_ACTION)
            params = SetVirtualWalletBehaviorParameters.new(
              action: action,
              context: context,
              protocol: protocol,
              response: response
            )
            execute(cmd: 'digitalCredentials.setVirtualWalletBehavior', params: params)
          end
        end # DigitalCredentials
      end # Protocol
    end # BiDi
  end # WebDriver
end # Selenium
