# frozen_string_literal: true

# Licensed to the Software Freedom Conservancy (SFC) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The SFC licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# This file is automatically generated. DO NOT EDIT!
# Regenerate with: bazel run //rb/lib/selenium/webdriver:bidi-generate

module Selenium
  module WebDriver
    class BiDi
      module Protocol
        # @api private
        # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
        class Input < Domain
          EVENTS = {
            file_dialog_opened: 'input.fileDialogOpened'
          }.freeze

          POINTER_TYPE = {
            mouse: 'mouse',
            pen: 'pen',
            touch: 'touch'
          }.freeze

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          ElementOrigin = Serialization::Record.define(
            type: {fixed: 'element'},
            element: {json_key: 'element', ref: 'Script::SharedReference'}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          PerformActionsParameters = Serialization::Record.define(
            context: 'context',
            actions: {json_key: 'actions', ref: 'Input::SourceActions', list: true}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class SourceActions < Serialization::Union
            discriminator 'type', {none: 'none', key: 'key', pointer: 'pointer', wheel: 'wheel'}
            variants(
              none: 'Input::NoneSourceActions',
              key: 'Input::KeySourceActions',
              pointer: 'Input::PointerSourceActions',
              wheel: 'Input::WheelSourceActions'
            )
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          NoneSourceActions = Serialization::Record.define(
            type: {fixed: 'none'},
            id: 'id',
            actions: {json_key: 'actions', ref: 'Input::PauseAction', list: true}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          KeySourceActions = Serialization::Record.define(
            type: {fixed: 'key'},
            id: 'id',
            actions: {json_key: 'actions', ref: 'Input::KeySourceAction', list: true}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class KeySourceAction < Serialization::Union
            discriminator 'type', {pause: 'pause', key_down: 'keyDown', key_up: 'keyUp'}
            variants(
              pause: 'Input::PauseAction',
              key_down: 'Input::KeyDownAction',
              key_up: 'Input::KeyUpAction'
            )
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          PointerSourceActions = Serialization::Record.define(
            type: {fixed: 'pointer'},
            id: 'id',
            parameters: {json_key: 'parameters', required: false, ref: 'Input::PointerParameters'},
            actions: {json_key: 'actions', ref: 'Input::PointerSourceAction', list: true}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          PointerParameters = Serialization::Record.define(
            pointer_type: {json_key: 'pointerType', required: false, enum: 'Input::POINTER_TYPE'}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class PointerSourceAction < Serialization::Union
            discriminator 'type', {
              pause: 'pause',
              pointer_down: 'pointerDown',
              pointer_up: 'pointerUp',
              pointer_move: 'pointerMove'
            }
            variants(
              pause: 'Input::PauseAction',
              pointer_down: 'Input::PointerDownAction',
              pointer_up: 'Input::PointerUpAction',
              pointer_move: 'Input::PointerMoveAction'
            )
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          WheelSourceActions = Serialization::Record.define(
            type: {fixed: 'wheel'},
            id: 'id',
            actions: {json_key: 'actions', ref: 'Input::WheelSourceAction', list: true}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class WheelSourceAction < Serialization::Union
            discriminator 'type', {pause: 'pause', scroll: 'scroll'}
            variants(
              pause: 'Input::PauseAction',
              scroll: 'Input::WheelScrollAction'
            )
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          PauseAction = Serialization::Record.define(
            type: {fixed: 'pause'},
            duration: {json_key: 'duration', required: false}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          KeyDownAction = Serialization::Record.define(type: {fixed: 'keyDown'}, value: 'value')

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          KeyUpAction = Serialization::Record.define(type: {fixed: 'keyUp'}, value: 'value')

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          PointerUpAction = Serialization::Record.define(type: {fixed: 'pointerUp'}, button: 'button')

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          PointerDownAction = Serialization::Record.define(
            type: {fixed: 'pointerDown'},
            button: 'button',
            width: {json_key: 'width', required: false},
            height: {json_key: 'height', required: false},
            pressure: {json_key: 'pressure', required: false},
            tangential_pressure: {json_key: 'tangentialPressure', required: false},
            twist: {json_key: 'twist', required: false},
            altitude_angle: {json_key: 'altitudeAngle', required: false},
            azimuth_angle: {json_key: 'azimuthAngle', required: false}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          PointerMoveAction = Serialization::Record.define(
            type: {fixed: 'pointerMove'},
            x: 'x',
            y: 'y',
            duration: {json_key: 'duration', required: false},
            origin: {json_key: 'origin', required: false, ref: 'Input::Origin'},
            width: {json_key: 'width', required: false},
            height: {json_key: 'height', required: false},
            pressure: {json_key: 'pressure', required: false},
            tangential_pressure: {json_key: 'tangentialPressure', required: false},
            twist: {json_key: 'twist', required: false},
            altitude_angle: {json_key: 'altitudeAngle', required: false},
            azimuth_angle: {json_key: 'azimuthAngle', required: false}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          WheelScrollAction = Serialization::Record.define(
            type: {fixed: 'scroll'},
            x: 'x',
            y: 'y',
            delta_x: 'deltaX',
            delta_y: 'deltaY',
            duration: {json_key: 'duration', required: false},
            origin: {json_key: 'origin', required: false, ref: 'Input::Origin'}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          PointerCommonProperties = Serialization::Record.define(
            width: {json_key: 'width', required: false},
            height: {json_key: 'height', required: false},
            pressure: {json_key: 'pressure', required: false},
            tangential_pressure: {json_key: 'tangentialPressure', required: false},
            twist: {json_key: 'twist', required: false},
            altitude_angle: {json_key: 'altitudeAngle', required: false},
            azimuth_angle: {json_key: 'azimuthAngle', required: false}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class Origin < Serialization::Union
            discriminator 'type', {element: 'element'}
            variants(
              element: 'Input::ElementOrigin'
            )
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          ReleaseActionsParameters = Serialization::Record.define(context: 'context')

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          SetFilesParameters = Serialization::Record.define(
            context: 'context',
            element: {json_key: 'element', ref: 'Script::SharedReference'},
            files: {json_key: 'files', list: true}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          FileDialogInfo = Serialization::Record.define(
            context: 'context',
            user_context: {json_key: 'userContext', required: false},
            element: {json_key: 'element', required: false, ref: 'Script::SharedReference'},
            multiple: 'multiple'
          )

          EVENT_TYPES = {
            'input.fileDialogOpened' => Input::FileDialogInfo
          }.freeze

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def perform_actions(context:, actions:)
            params = PerformActionsParameters.new(context: context, actions: actions)
            execute(cmd: 'input.performActions', params: params)
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def release_actions(context:)
            params = ReleaseActionsParameters.new(context: context)
            execute(cmd: 'input.releaseActions', params: params)
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def set_files(context:, element:, files:)
            params = SetFilesParameters.new(context: context, element: element, files: files)
            execute(cmd: 'input.setFiles', params: params)
          end
        end # Input
      end # Protocol
    end # BiDi
  end # WebDriver
end # Selenium
