# frozen_string_literal: true

# Licensed to the Software Freedom Conservancy (SFC) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The SFC licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# This file is automatically generated. DO NOT EDIT!
# Regenerate with: bazel run //rb/lib/selenium/webdriver:bidi-generate

module Selenium
  module WebDriver
    class BiDi
      module Protocol
        # @api private
        # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
        class Session
          USER_PROMPT_HANDLER_TYPE = {
            accept: 'accept',
            dismiss: 'dismiss',
            ignore: 'ignore'
          }.freeze

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          CapabilitiesRequest = Serialization::Record.define(
            always_match: {json_key: 'alwaysMatch', ref: 'Session::CapabilityRequest'},
            first_match: {json_key: 'firstMatch', ref: 'Session::CapabilityRequest', list: true}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          CapabilityRequest = Serialization::Record.define(
            accept_insecure_certs: 'acceptInsecureCerts',
            browser_name: 'browserName',
            browser_version: 'browserVersion',
            platform_name: 'platformName',
            proxy: {json_key: 'proxy', ref: 'Session::ProxyConfiguration'},
            unhandled_prompt_behavior: {json_key: 'unhandledPromptBehavior', ref: 'Session::UserPromptHandler'},
            extensible: true
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class ProxyConfiguration < Serialization::Union
            discriminator 'proxyType'
            variants(
              'autodetect' => 'Session::AutodetectProxyConfiguration',
              'direct' => 'Session::DirectProxyConfiguration',
              'manual' => 'Session::ManualProxyConfiguration',
              'pac' => 'Session::PacProxyConfiguration',
              'system' => 'Session::SystemProxyConfiguration'
            )
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          AutodetectProxyConfiguration = Serialization::Record.define(
            proxy_type: {json_key: 'proxyType', fixed: 'autodetect'},
            extensible: true
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          DirectProxyConfiguration = Serialization::Record.define(
            proxy_type: {json_key: 'proxyType', fixed: 'direct'},
            extensible: true
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          ManualProxyConfiguration = Serialization::Record.define(
            proxy_type: {json_key: 'proxyType', fixed: 'manual'},
            http_proxy: 'httpProxy',
            ssl_proxy: 'sslProxy',
            socks_proxy: 'socksProxy',
            socks_version: 'socksVersion',
            no_proxy: {json_key: 'noProxy', list: true},
            extensible: true
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          SocksProxyConfiguration = Serialization::Record.define(
            socks_proxy: 'socksProxy',
            socks_version: 'socksVersion'
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          PacProxyConfiguration = Serialization::Record.define(
            proxy_type: {json_key: 'proxyType', fixed: 'pac'},
            proxy_autoconfig_url: 'proxyAutoconfigUrl',
            extensible: true
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          SystemProxyConfiguration = Serialization::Record.define(
            proxy_type: {json_key: 'proxyType', fixed: 'system'},
            extensible: true
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          UserPromptHandler = Serialization::Record.define(
            alert: {json_key: 'alert', enum: 'Session::USER_PROMPT_HANDLER_TYPE'},
            before_unload: {json_key: 'beforeUnload', enum: 'Session::USER_PROMPT_HANDLER_TYPE'},
            confirm: {json_key: 'confirm', enum: 'Session::USER_PROMPT_HANDLER_TYPE'},
            default: {json_key: 'default', enum: 'Session::USER_PROMPT_HANDLER_TYPE'},
            file: {json_key: 'file', enum: 'Session::USER_PROMPT_HANDLER_TYPE'},
            prompt: {json_key: 'prompt', enum: 'Session::USER_PROMPT_HANDLER_TYPE'}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          SubscribeParameters = Serialization::Record.define(
            events: {json_key: 'events', list: true},
            contexts: {json_key: 'contexts', list: true},
            user_contexts: {json_key: 'userContexts', list: true}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          UnsubscribeByIDRequest = Serialization::Record.define(subscriptions: {json_key: 'subscriptions', list: true})

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          UnsubscribeByAttributesRequest = Serialization::Record.define(events: {json_key: 'events', list: true})

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          StatusResult = Serialization::Record.define(ready: 'ready', message: 'message')

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          NewParameters = Serialization::Record.define(
            capabilities: {json_key: 'capabilities', ref: 'Session::CapabilitiesRequest'}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          NewResult = Serialization::Record.define(
            session_id: 'sessionId',
            capabilities: {json_key: 'capabilities', ref: 'Session::NewResult::Capabilities'}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          NewResult::Capabilities = Serialization::Record.define(
            accept_insecure_certs: 'acceptInsecureCerts',
            browser_name: 'browserName',
            browser_version: 'browserVersion',
            platform_name: 'platformName',
            set_window_rect: 'setWindowRect',
            user_agent: 'userAgent',
            proxy: {json_key: 'proxy', ref: 'Session::ProxyConfiguration'},
            unhandled_prompt_behavior: {json_key: 'unhandledPromptBehavior', ref: 'Session::UserPromptHandler'},
            web_socket_url: 'webSocketUrl',
            extensible: true
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          SubscribeResult = Serialization::Record.define(subscription: 'subscription')

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class UnsubscribeParameters < Serialization::Union
            presence(
              'Session::UnsubscribeByAttributesRequest' => ['events'],
              'Session::UnsubscribeByIDRequest' => ['subscriptions']
            )
          end

          def initialize(transport)
            @transport = transport
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def end_
            @transport.execute(cmd: 'session.end')
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def new(capabilities:)
            params = NewParameters.new(capabilities: capabilities)
            @transport.execute(cmd: 'session.new', params: params, result: Session::NewResult)
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def status
            @transport.execute(cmd: 'session.status', result: Session::StatusResult)
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def subscribe(events:, contexts: Serialization::UNSET, user_contexts: Serialization::UNSET)
            params = SubscribeParameters.new(events: events, contexts: contexts, user_contexts: user_contexts)
            @transport.execute(cmd: 'session.subscribe', params: params, result: Session::SubscribeResult)
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def unsubscribe(events: Serialization::UNSET, subscriptions: Serialization::UNSET)
            params = UnsubscribeParameters.build(events: events, subscriptions: subscriptions)
            @transport.execute(cmd: 'session.unsubscribe', params: params)
          end
        end # Session
      end # Protocol
    end # BiDi
  end # WebDriver
end # Selenium
