# frozen_string_literal: true

# Licensed to the Software Freedom Conservancy (SFC) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The SFC licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# This file is automatically generated. DO NOT EDIT!
# Regenerate with: bazel run //rb/lib/selenium/webdriver:bidi-generate

module Selenium
  module WebDriver
    class BiDi
      module Protocol
        # @api private
        # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
        class Storage < Domain
          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          PartitionKey = Serialization::Record.define(
            user_context: 'userContext',
            source_origin: 'sourceOrigin',
            extensible: true
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          CookieFilter = Serialization::Record.define(
            name: 'name',
            value: {json_key: 'value', ref: 'Network::BytesValue'},
            domain: 'domain',
            path: 'path',
            size: 'size',
            http_only: 'httpOnly',
            secure: 'secure',
            same_site: {json_key: 'sameSite', enum: 'Network::SAME_SITE'},
            expiry: 'expiry',
            extensible: true
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          BrowsingContextPartitionDescriptor = Serialization::Record.define(
            type: {fixed: 'context'},
            context: 'context'
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          StorageKeyPartitionDescriptor = Serialization::Record.define(
            type: {fixed: 'storageKey'},
            user_context: 'userContext',
            source_origin: 'sourceOrigin',
            extensible: true
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          class PartitionDescriptor < Serialization::Union
            discriminator 'type', {context: 'context', storage_key: 'storageKey'}
            variants(
              context: 'Storage::BrowsingContextPartitionDescriptor',
              storage_key: 'Storage::StorageKeyPartitionDescriptor'
            )
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          GetCookiesParameters = Serialization::Record.define(
            filter: {json_key: 'filter', ref: 'Storage::CookieFilter'},
            partition: {json_key: 'partition', ref: 'Storage::PartitionDescriptor'}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          GetCookiesResult = Serialization::Record.define(
            cookies: {json_key: 'cookies', ref: 'Network::Cookie', list: true},
            partition_key: {json_key: 'partitionKey', ref: 'Storage::PartitionKey'}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          PartialCookie = Serialization::Record.define(
            name: 'name',
            value: {json_key: 'value', ref: 'Network::BytesValue'},
            domain: 'domain',
            path: 'path',
            http_only: 'httpOnly',
            secure: 'secure',
            same_site: {json_key: 'sameSite', enum: 'Network::SAME_SITE'},
            expiry: 'expiry',
            extensible: true
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          SetCookieParameters = Serialization::Record.define(
            cookie: {json_key: 'cookie', ref: 'Storage::PartialCookie'},
            partition: {json_key: 'partition', ref: 'Storage::PartitionDescriptor'}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          SetCookieResult = Serialization::Record.define(
            partition_key: {json_key: 'partitionKey', ref: 'Storage::PartitionKey'}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          DeleteCookiesParameters = Serialization::Record.define(
            filter: {json_key: 'filter', ref: 'Storage::CookieFilter'},
            partition: {json_key: 'partition', ref: 'Storage::PartitionDescriptor'}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          DeleteCookiesResult = Serialization::Record.define(
            partition_key: {json_key: 'partitionKey', ref: 'Storage::PartitionKey'}
          )

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def delete_cookies(filter: Serialization::UNSET, partition: Serialization::UNSET)
            params = DeleteCookiesParameters.new(filter: filter, partition: partition)
            execute(cmd: 'storage.deleteCookies', params: params, result: Storage::DeleteCookiesResult)
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def get_cookies(filter: Serialization::UNSET, partition: Serialization::UNSET)
            params = GetCookiesParameters.new(filter: filter, partition: partition)
            execute(cmd: 'storage.getCookies', params: params, result: Storage::GetCookiesResult)
          end

          # @api private
          # @see https://www.selenium.dev/documentation/warnings/bidi-implementation/
          def set_cookie(cookie:, partition: Serialization::UNSET)
            params = SetCookieParameters.new(cookie: cookie, partition: partition)
            execute(cmd: 'storage.setCookie', params: params, result: Storage::SetCookieResult)
          end
        end # Storage
      end # Protocol
    end # BiDi
  end # WebDriver
end # Selenium
