java_library(
    name = "sessions",
    srcs = [
        "DriverSessions.java",
        "KnownElements.java",
        "Session.java",
    ],
    deps = [
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//third_party/java/guava:guava",
    ],
    visibility = [
        "//java/server/src/com/thoughtworks/selenium/webdriven:rc-emulation-servlet",
        "//java/server/test/...",
    ],
)

java_library(
    name = "server",
    srcs = [
        "CapabilitiesComparator.java",
        "DefaultDriverFactory.java",
        "DefaultDriverProvider.java",
        "DefaultSession.java",
        "DriverFactory.java",
        "DriverProvider.java",
        "InputStreamWrappingServletInputStream.java",
        "JsonHttpCommandHandler.java",
        "RequiresAllSessions.java",
        "RequiresSession.java",
        "SnapshotScreenListener.java",
        "StaticResourceHandler.java",
    ] + glob([
        "handler/**/*.java",
        "rest/*.java",
        "xdrpc/*.java",
    ]),
    resources = [
        ":client",
        ":hub",
        ":style",
    ],
    provided_deps = [
        "//third_party/java/servlet:javax.servlet-api",
    ],
    deps = [
        ":sessions",
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/src/org/openqa/selenium/json:json",
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/client/src/org/openqa/selenium/support/events:events",
        "//java/server/src/org/openqa/selenium/remote/server/log:log",
        "//third_party/java/guava:guava",
    ],
    visibility = [
        "//java/server/src/com/thoughtworks/selenium/webdriven:rc-emulation-servlet",
        "//java/server/test/...",
    ],
)

java_library(
    name = "webdriver-servlet",
    srcs = [
        "ActiveSessionFactory.java",
        "ActiveSessionListener.java",
        "ActiveSessions.java",
        "AllHandlers.java",
        "DefaultPipeline.java",
        "InMemorySession.java",
        "NewSessionPipeline.java",
        "WebDriverServlet.java",
    ] + glob(["commandhandler/*.java"]),
    provided_deps = [
        "//third_party/java/servlet:javax.servlet-api",
    ],
    deps = [
        ":server",
        ":sessions",
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/server/src/org/openqa/selenium/grid/server:server",
        "//java/server/src/org/openqa/selenium/grid/session:session",
        "//java/server/src/org/openqa/selenium/grid/session/remote:remote",
        "//java/server/src/org/openqa/selenium/grid/web:web",
        "//java/server/src/org/openqa/selenium/remote/server/log:log",
        "//third_party/java/guava:guava",
    ],
    visibility = [
        "//java/server/src/com/thoughtworks/selenium/webdriven:rc-emulation-servlet",
        "//java/server/test/com/thoughtworks/selenium/webdriven:webdriven",
        "//java/server/test/org/openqa/selenium:lib",
        "//java/server/test/org/openqa/selenium/remote/server:tests",
        "//java/server/test/org/openqa/selenium/remote/server/auth:lib",
    ],
)

export_file(
    name = "client",
    src = "//javascript/remote:client",
    out = "client.js",
)

export_file(
    name = "hub",
    src = "//javascript/remote:hub",
    out = "hub.html",
)

export_file(
    name = "style",
    src = "//javascript/remote:style",
    out = "style.css",
)

java_library(
    name = "standalone-server-lib",
    srcs = [
        "SeleniumServer.java",
    ],
    deps = [
        ":server",
        ":sessions",
        ":webdriver-servlet",
        "//java/client/src/org/openqa/selenium/chrome:chrome",
        "//java/client/src/org/openqa/selenium/edge/edgehtml:edgehtml",
        "//java/client/src/org/openqa/selenium/firefox:firefox",
        "//java/client/src/org/openqa/selenium/ie:ie",
        "//java/client/src/org/openqa/selenium/opera:opera",
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/client/src/org/openqa/selenium/safari:safari",
        "//java/server/src/org/openqa/selenium/grid:grid",
        "//third_party/java/beust:jcommander",
        "//third_party/java/jetty:jetty",
        "//third_party/java/servlet:javax.servlet-api",
    ],
)

java_binary(
    name = "standalone-server",
    main_class = "org.openqa.selenium.remote.server.SeleniumServer",
    deps = [
        ":standalone-server-lib",
    ],
)