load("@rules_jvm_external//:defs.bzl", "maven_install")

def selenium_java_deps():
    maven_install(
        artifacts = [
            "com.beust:jcommander:1.82",
            "com.github.javaparser:javaparser-core:3.25.7",
            "com.github.spotbugs:spotbugs:4.8.3",
            "com.github.stephenc.jcip:jcip-annotations:1.0-1",
            "com.google.code.gson:gson:2.10.1",
            "com.google.guava:guava:33.0.0-jre",
            "com.google.auto:auto-common:1.2.2",
            "com.google.auto.service:auto-service:1.1.1",
            "com.google.auto.service:auto-service-annotations:1.1.1",
            "com.google.googlejavaformat:google-java-format:jar:1.19.1",
            "com.graphql-java:graphql-java:20.2",
            "com.graphql-java:java-dataloader:3.2.0",
            "dev.failsafe:failsafe:3.3.2",
            "io.grpc:grpc-context:1.60.1",
            "io.lettuce:lettuce-core:6.3.0.RELEASE",
            "io.netty:netty-buffer:4.1.104.Final",
            "io.netty:netty-codec-http:4.1.104.Final",
            "io.netty:netty-codec-http2:4.1.104.Final",
            "io.netty:netty-common:4.1.104.Final",
            "io.netty:netty-handler:4.1.104.Final",
            "io.netty:netty-handler-proxy:4.1.104.Final",
            "io.netty:netty-transport:4.1.104.Final",
            "io.opentelemetry:opentelemetry-api:1.33.0",
            "io.opentelemetry:opentelemetry-context:1.33.0",
            "io.opentelemetry:opentelemetry-exporter-logging:1.33.0",
            "io.opentelemetry:opentelemetry-sdk:1.33.0",
            "io.opentelemetry:opentelemetry-sdk-common:1.33.0",
            "io.opentelemetry:opentelemetry-sdk-extension-autoconfigure:1.33.0",
            "io.opentelemetry:opentelemetry-sdk-extension-autoconfigure-spi:1.33.0",
            "io.opentelemetry:opentelemetry-sdk-testing:1.33.0",
            "io.opentelemetry:opentelemetry-sdk-trace:1.33.0",
            "io.opentelemetry.semconv:opentelemetry-semconv:1.23.1-alpha",
            "io.ous:jtoml:2.0.0",
            "it.ozimov:embedded-redis:0.7.3",
            "net.bytebuddy:byte-buddy:1.14.11",
            "org.htmlunit:htmlunit-core-js:3.9.0",
            "org.apache.commons:commons-exec:1.3",
            "org.apache.logging.log4j:log4j-core:2.22.0",
            "org.assertj:assertj-core:3.24.2",
            "org.bouncycastle:bcpkix-jdk18on:1.77",
            "org.eclipse.mylyn.github:org.eclipse.egit.github.core:2.1.5",
            "org.hsqldb:hsqldb:2.7.2",
            "org.junit.jupiter:junit-jupiter-api:5.10.1",
            "org.junit.jupiter:junit-jupiter-engine:5.10.1",
            "org.junit.jupiter:junit-jupiter-params:5.10.1",
            "org.junit.platform:junit-platform-launcher:1.10.1",
            "org.junit.platform:junit-platform-reporting:1.10.1",
            "org.junit.platform:junit-platform-commons:1.10.1",
            "org.junit.platform:junit-platform-engine:1.10.1",
            "org.mockito:mockito-core:5.8.0",
            "org.mockito:mockito-inline:5.2.0",
            "org.redisson:redisson:3.25.2",
            "org.slf4j:slf4j-api:2.0.9",
            "org.slf4j:slf4j-jdk14:2.0.9",
            "org.zeromq:jeromq:0.5.4",
        ],
        excluded_artifacts = [
            "org.hamcrest:hamcrest-all",  # Replaced by hamcrest 2
            "org.hamcrest:hamcrest-core",
            "io.netty:netty-all",  # Depend on the actual things you need
        ],
        fail_on_missing_checksum = True,
        fail_if_repin_required = True,
        fetch_sources = True,
        strict_visibility = True,
        repositories = [
            "https://repo1.maven.org/maven2",
            "https://maven.google.com",
        ],
        maven_install_json = "@selenium//java:maven_install.json",
        version_conflict_policy = "pinned",
    )
