java_test(name = 'common-tests',
  srcs = [
    'BeanToJsonConverterTest.java',
    'DesiredCapabilitiesTest.java',
    'HttpRequest.java',
    'JsonToBeanConverterTest.java',
    'RemoteCommonTests.java',
    'http/JsonHttpCommandCodecTest.java',
    'http/JsonHttpResponseCodecTest.java',
    'http/W3CHttpResponseCodecTest.java',
  ],
  deps = [
   '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//third_party/java/gson:gson',
    '//third_party/java/guava:guava',
    '//third_party/java/hamcrest:hamcrest-library',
    '//third_party/java/httpcomponents:httpclient',
    '//third_party/java/junit:junit',
  ])

java_test(name = 'client-tests',
  srcs = [
    'AugmenterTest.java',
    'BaseAugmenterTest.java',
    'ErrorHandlerTest.java',
    'Gecko013ProtocolResponseTest.java',
    'JdkAugmenterTest.java',
    'JsonWireProtocolResponseTest.java',
    'ProtocolHandshakeTest.java',
    'RemoteClientTests.java',
    'RemoteLogsTest.java',
    'RemoteWebDriverInitializationTest.java',
    'W3CHandshakeResponseTest.java',
    'internal/ApacheHttpClientTest.java',
    'internal/CircularOutputStreamTest.java',
    'internal/WebElementToJsonConverterTest.java',
  ],
  deps = [
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//java/client/test/org/openqa/selenium:helpers',
    '//third_party/java/gson:gson',
    '//third_party/java/guava:guava',
    '//third_party/java/hamcrest:hamcrest-library',
    '//third_party/java/jetty:jetty',
    '//third_party/java/junit:junit',
    '//third_party/java/mockito:mockito',
  ])

java_test(name = 'remote-driver-tests',
  srcs = [
    'RemoteWebDriverTests.java',
  ],
  vm_args = [
    '-Dselenium.browser=ff',
    '-Dselenium.browser.remote=true',
  ],
  deps = [
    ':remote-driver-test-lib',
    '//java/client/test/org/openqa/selenium:large-tests',
    '//third_party/java/junit:junit',
  ],
)

java_test(name = 'remote-driver-grid-tests',
  srcs = [
    'RemoteWebDriverTests.java',
  ],
  vm_args = [
    '-Dselenium.browser=ff',
    '-Dselenium.browser.grid=true',
  ],
  deps = [
    ':remote-driver-test-lib',
    '//java/client/test/org/openqa/selenium:large-tests',
    '//third_party/java/junit:junit',
  ],
)


java_library(name = 'remote-driver-test-lib',
  srcs = [
    'RemoteSpecificTests.java',
    'RemoteWebDriverScreenshotTest.java',
    'StartingFirefoxRemotelyTest.java',
  ],
  deps = [
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/src/org/openqa/selenium/firefox:firefox',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//java/client/test/org/openqa/selenium/testing:test-base',
    '//java/client/test/org/openqa/selenium/testing/drivers:drivers',
    '//third_party/java/guava:guava',
    '//third_party/java/junit:junit',
  ],
)
