java_test(
    name = "small-tests",
    srcs = [
        "AugmenterTest.java",
        "BaseAugmenterTest.java",
        "DesiredCapabilitiesTest.java",
        "ErrorHandlerTest.java",
        "JdkAugmenterTest.java",
        "ProtocolHandshakeTest.java",
        "RemoteLogsTest.java",
        "RemoteWebDriverInitializationTest.java",
        "RemoteWebDriverUnitTest.java",
        "W3CHandshakeResponseTest.java",
        "W3CRemoteDriverTest.java",
        "internal/HttpClientTestBase.java",
        "internal/WebElementToJsonConverterTest.java",
    ],
    labels = [
        "small",
    ],
    provided_deps = [
        "//third_party/java/servlet:javax.servlet-api",
    ],
    deps = [
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//third_party/java/guava:guava",
        "//third_party/java/assertj:assertj",
        "//third_party/java/junit:junit",
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/src/org/openqa/selenium/chrome:chrome",
        "//java/client/src/org/openqa/selenium/edge:edge",
        "//java/client/src/org/openqa/selenium/firefox:firefox",
        "//java/client/src/org/openqa/selenium/firefox/xpi:firefox-xpi",
        "//java/client/src/org/openqa/selenium/ie:ie",
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/client/test/org/openqa/selenium:helpers",
        "//java/client/test/org/openqa/selenium/testing:test-base",
        "//third_party/java/guava:guava",
        "//third_party/java/assertj:assertj",
        "//third_party/java/jetty:jetty",
        "//third_party/java/junit:junit",
        "//third_party/java/mockito:mockito-core",
    ],
)

java_test(
    name = "remote-driver-tests",
    srcs = [
        "RemoteWebDriverTests.java",
    ],
    vm_args = [
        "-Dselenium.browser=ff",
        "-Dselenium.browser.remote=true",
    ],
    deps = [
        ":remote-driver-test-lib",
        "//java/client/test/org/openqa/selenium:large-tests",
        "//third_party/java/junit:junit",
    ],
)

java_test(
    name = "remote-driver-grid-tests",
    srcs = [
        "RemoteWebDriverTests.java",
    ],
    vm_args = [
        "-Dselenium.browser=ff",
        "-Dselenium.browser.grid=true",
    ],
    deps = [
        ":remote-driver-test-lib",
        "//java/client/test/org/openqa/selenium:large-tests",
        "//third_party/java/junit:junit",
    ],
)

java_library(
    name = "remote-driver-test-lib",
    srcs = [
        "RemoteSpecificTests.java",
        "RemoteWebDriverScreenshotTest.java",
    ],
    deps = [
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/src/org/openqa/selenium/firefox:firefox",
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/client/test/org/openqa/selenium/testing:test-base",
        "//java/client/test/org/openqa/selenium/testing/drivers:drivers",
        "//third_party/java/assertj:assertj",
        "//third_party/java/guava:guava",
        "//third_party/java/junit:junit",
    ],
)
