# Licensed to the Software Freedom Conservancy (SFC) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The SFC licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.


module Selenium
  module WebDriver
    module Remote
      class BiDiBridge < Bridge
        READINESS_STATE: Hash[String, Symbol]

        @browsing_context: BiDi::Protocol::BrowsingContext

        @connection: untyped

        @web_extension: BiDi::Protocol::WebExtension

        attr_reader bidi: BiDi

        attr_reader connection: untyped

        def create_session: (untyped capabilities) -> void

        def install_web_extension: (String path) -> WebExtension

        def uninstall_web_extension: (String id) -> void

        def get: (String url) -> void

        def go_back: () -> void

        def go_forward: () -> void

        def refresh: () -> void

        def quit: () -> void

        def close: () -> void

        private

        def validated_socket_url: () -> String

        def browsing_context: () -> BiDi::Protocol::BrowsingContext

        def web_extension: () -> BiDi::Protocol::WebExtension

        def web_extension_data: (String path) -> untyped

        def readiness_state: () -> Symbol
      end
    end
  end
end
