# Licensed to the Software Freedom Conservancy (SFC) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The SFC licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.


module Selenium
  module WebDriver
    module Remote
      class Driver < WebDriver::Driver
        include DriverExtensions::UploadsFiles

        include DriverExtensions::HasSessionId

        include DriverExtensions::HasFileDownloads

        def initialize: (?capabilities: untyped?, ?options: untyped?, ?service: untyped?, ?url: untyped?, ?http_client: untyped?, ?client_config: ClientConfig?, **untyped opts) -> void

        private

        def assert_arguments: (untyped service, untyped url, untyped http_client, ClientConfig? client_config) -> void

        def devtools_url: () -> untyped

        def devtools_version: () -> untyped

        def process_options: (untyped options, untyped capabilities) -> untyped

        def generate_capabilities: (untyped capabilities) -> untyped
      end
    end
  end
end
