java_library(
  name = 'net',
  srcs = glob(['*.java']),
  deps = [
    '//java/client/src/org/openqa/selenium:webdriver-api',
    '//third_party/java/guava-libraries:guava-libraries',
  ],
  visibility = ['PUBLIC'],
)
