# BUILD FILE SYNTAX: STARLARK

SE_VERSION = "4.26.0-nightly202409202352"
ASSEMBLY_VERSION = "4.0.0.0"
SUPPORTED_NET_STANDARD_VERSIONS = ["netstandard2.0"]

SUPPORTED_DEVTOOLS_VERSIONS = [
    "v85",
    "v128",
    "v129",
    "v127",
]

ASSEMBLY_COMPANY = "Selenium Committers"
ASSEMBLY_COPYRIGHT = "Copyright © Software Freedom Conservancy 2023"
ASSEMBLY_INFORMATIONAL_VERSION = SE_VERSION
ASSEMBLY_PRODUCT = "Selenium"
