# BUILD FILE SYNTAX: STARLARK

SE_VERSION = "4.47.0-nightly202607110055"

SUPPORTED_DEVTOOLS_VERSIONS = [
    "v149",
    "v150",
    "v148",
]

ASSEMBLY_COMPANY = "Selenium Committers"
ASSEMBLY_COPYRIGHT = "Copyright © Software Freedom Conservancy 2023"
ASSEMBLY_INFORMATIONAL_VERSION = SE_VERSION
ASSEMBLY_PRODUCT = "Selenium"
ASSEMBLY_VERSION = "4.0.0.0"
