module Selenium
  module WebDriver
    module WheelActions
      class ScrollOrigin
        @origin: untyped

        @x_offset: Integer

        @y_offset: Integer

        def self.element: (Element element, ?::Integer x_offset, ?::Integer y_offset) -> untyped

        def self.viewport: (?::Integer x_offset, ?::Integer y_offset) -> ScrollOrigin

        attr_reader origin: untyped

        attr_reader x_offset: Integer

        attr_reader y_offset: Integer

        def initialize: (untyped origin, Integer x_offset, Integer y_offset) -> void
      end
    end
  end
end
