js_library(
  name = 'message',
  srcs = [
      'alert.js',
      'connect.js',
      'command.js',
      'load.js',
      'loadmodule.js',
      'logmessage.js',
      'message.js',
      'messagetarget.js',
  ],
  deps = [
    '//javascript/safari-driver:command',
    '//javascript/webdriver:base',
    '//javascript/webdriver:logging',
    '//third_party/closure:closure',
  ],
  visibility = [
    '//javascript/safari-driver/...',
  ],
)
