include_defs('//SELENIUM_VERSION')

build_stamp(name = 'build-stamp',
  kind = 'manifest',
  source_control_system = 'git',
)

java_library(name = 'selenium',
  exported_deps = [
    ':beta',
    ':core',
    ':exceptions',
    ':platform',
    ':primitives',
    '//java/client/src/org/openqa/selenium/interactions:interactions',
    '//java/client/src/org/openqa/selenium/io:io',
    '//java/client/src/org/openqa/selenium/logging:api',
    '//java/client/src/org/openqa/selenium/logging:logging',
    '//java/client/src/org/openqa/selenium/net:net',
    '//java/client/src/org/openqa/selenium/os:os',
    '//java/client/src/org/openqa/selenium/security:security',
  ],
  visibility = ['PUBLIC'],
)

java_library(name = 'core',
  maven_coords = 'org.seleniumhq.selenium:selenium-api:' + SE_VERSION,
  maven_pom_template = ':template-pom',
  srcs = [
    'Alert.java',
    'By.java',
    'Capabilities.java',
    'Cookie.java',
    'ContextAware.java',
    'HasCapabilities.java',
    'JavascriptExecutor.java',
    'DeviceRotation.java',
    'Keys.java',
    'ImmutableCapabilities.java',
    'MutableCapabilities.java',
    'OutputType.java',
    'PageLoadStrategy.java',
    'Proxy.java',
    'Rotatable.java',
    'ScreenOrientation.java',
    'SearchContext.java',
    'TakesScreenshot.java',
    'UnexpectedAlertBehaviour.java',
    'WebDriver.java',
    'WebElement.java',
    'internal/ElementScrollBehavior.java',
    'internal/HasIdentity.java',
    'internal/Locatable.java',
    'internal/Lock.java',
    'internal/SocketLock.java',
    'internal/WrapsDriver.java',
    'internal/WrapsElement.java',
  ] + glob([
     'html5/*.java',
     'internal/FindsBy*.java',
     'mobile/*.java',
  ]),
  manifest_file = ':manifest',
  deps = [
    # This list of dependencies MUST NOT include anything other than code
    # from the selenium project. That means no guava and no gson.
    ':beta',
    ':exceptions',
    ':platform',
    ':primitives',
    '//java/client/src/org/openqa/selenium/interactions:core',
    '//java/client/src/org/openqa/selenium/interactions:exceptions',
    '//java/client/src/org/openqa/selenium/logging:api',
    '//java/client/src/org/openqa/selenium/security:security',
  ],
  visibility = [
    '//java/client/src/org/openqa/selenium/interactions:interactions',
  ],
)

genrule(name = 'manifest',
  out = 'manifest.mf',
  bash = "cp $(location :build-stamp) $OUT && printf 'Selenium-Version: {}\n\n' >> $OUT".format(SE_VERSION),
  cmd_exe = "copy $(location :build-stamp) %OUT% && (echo Selenium-Version: {}\n\n) >> %OUT%".format(SE_VERSION),
)

java_library(name = 'beta',
  srcs = [ 'Beta.java' ],
  visibility = [
    '//java/client/src/org/openqa/selenium/interactions:interactions',
    '//java/client/src/org/openqa/selenium/logging:api',
    '//java/client/src/org/openqa/selenium/logging:logging',
    '//java/client/src/org/openqa/selenium/os:os',
    '//java/client/src/org/openqa/selenium/security:security',
  ],
)

java_library(name = 'exceptions',
  srcs = [
    'ElementClickInterceptedException.java',
    'ElementNotInteractableException.java',
    'ElementNotSelectableException.java',
    'ElementNotVisibleException.java',
    'ImeActivationFailedException.java',
    'ImeNotAvailableException.java',
    'InvalidArgumentException.java',
    'InvalidCookieDomainException.java',
    'InvalidElementStateException.java',
    'InvalidSelectorException.java',
    'JavascriptException.java',
    'NoAlertPresentException.java',
    'NoSuchCookieException.java',
    'NoSuchElementException.java',
    'NoSuchFrameException.java',
    'NoSuchSessionException.java',
    'NoSuchWindowException.java',
    'NotFoundException.java',
    'SessionNotCreatedException.java',
    'ScriptTimeoutException.java',
    'StaleElementReferenceException.java',
    'TimeoutException.java',
    'UnableToSetCookieException.java',
    'UnhandledAlertException.java',
    'UnsupportedCommandException.java',
    'WebDriverException.java',
    'internal/BuildInfo.java',
  ],
  deps = [
    ':beta',
  ],
  visibility = [
    '//java/client/src/org/openqa/selenium/interactions:exceptions',
    '//java/client/src/org/openqa/selenium/interactions:interactions',
    '//java/client/src/org/openqa/selenium/io:io',
    '//java/client/src/org/openqa/selenium/net:net',
    '//java/client/src/org/openqa/selenium/os:os',
    '//java/client/test/org/openqa/selenium/testing:helpers',
  ],
)

java_library(
  name = 'platform',
  srcs = [
    'Architecture.java',
    'Platform.java',
  ],
  deps = [
    ':exceptions',
  ],
  visibility = [
    '//java/client/src/org/openqa/selenium/io:io',
    '//java/client/src/org/openqa/selenium/net:net',
    '//java/client/src/org/openqa/selenium/os:os',
  ],
)

java_library(name = 'primitives',
  srcs = [
    'Dimension.java',
    'Point.java',
    'Rectangle.java',
  ],
  visibility = [
    '//java/client/src/org/openqa/selenium/interactions:core',
  ],
)

java_library(
  name = 'client-combined',
  maven_coords = 'org.seleniumhq.selenium:selenium-java:' + SE_VERSION,
  maven_pom_template = ':template-pom',
  exported_deps = [
    ':selenium',
    '//java/client/src/org/openqa/selenium/chrome:chrome',
    '//java/client/src/org/openqa/selenium/firefox:firefox',
    '//java/client/src/org/openqa/selenium/edge:edge',
    '//java/client/src/org/openqa/selenium/ie:ie',
    '//java/client/src/org/openqa/selenium/opera:opera',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//java/client/src/org/openqa/selenium/safari:safari',
    '//java/client/src/org/openqa/selenium/support:support'
  ],
  visibility = [
    '//java/server/src/org/openqa/grid/selenium:classes',
    '//java/server/test/org/openqa/selenium:lib',
  ],
)

java_binary(
  name = 'client-combined-' + SE_VERSION,
  blacklist = [
    '^(?!com.thoughtworks.selenium.*|org.openqa.selenium.*|org.openqa.grid.*)',
  ],
  deps = [
    ':client-combined',
  ],
)

# Output of this rule is named a source jar so we can do merging later
genrule(
  name = 'client-libs',
  out = 'libs-sources.jar',
  cmd = 'mkdir libs && echo $(classpath :client-combined) | tr : "\\n" | grep third_party/java | grep .jar | xargs -J % cp % libs && jar cMf $OUT libs/*',
)

zip_file(
  name = 'client-combined-zip',
  out = 'selenium-java-' + SE_VERSION + '.zip',
  srcs = [
    ':client-combined-' + SE_VERSION,
    ':client-libs',
    '//java:changelog',
    '//:notice',
    '//:license',
  ],
)


export_file(
  name = 'template-pom',
  src = 'pom.xml',
  out = 'pom.xml',
  visibility = ['PUBLIC'],
)
