include_defs('//SELENIUM_VERSION')

java_library(name = 'selenium',
  exported_deps = [
    ':beta',
    ':core',
    ':exceptions',
    ':platform',
    ':primitives',
    '//java/client/src/org/openqa/selenium/interactions:interactions',
    '//java/client/src/org/openqa/selenium/io:io',
    '//java/client/src/org/openqa/selenium/logging:api',
    '//java/client/src/org/openqa/selenium/logging:logging',
    '//java/client/src/org/openqa/selenium/net:net',
    '//java/client/src/org/openqa/selenium/os:os',
    '//java/client/src/org/openqa/selenium/security:security',
  ],
  visibility = ['PUBLIC'],
)

java_library(name = 'core',
  maven_coords = 'org.seleniumhq.selenium:selenium-api:' + SE_VERSION,
  maven_pom_template = ':template-pom',
  srcs = [
    'Alert.java',
    'By.java',
    'Capabilities.java',
    'Cookie.java',
    'ContextAware.java',
    'HasCapabilities.java',
    'JavascriptExecutor.java',
    'DeviceRotation.java',
    'Keys.java',
    'OutputType.java',
    'Proxy.java',
    'Rotatable.java',
    'ScreenOrientation.java',
    'SearchContext.java',
    'TakesScreenshot.java',
    'UnexpectedAlertBehaviour.java',
    'WebDriver.java',
    'WebElement.java',
    'internal/ElementScrollBehavior.java',
    'internal/HasIdentity.java',
    'internal/Killable.java',
    'internal/Locatable.java',
    'internal/Lock.java',
    'internal/SocketLock.java',
    'internal/WrapsDriver.java',
    'internal/WrapsElement.java',
  ] + glob([
     'html5/*.java',
     'internal/FindsBy*.java',
     'mobile/*.java',
  ]),
  manifest_file = ':manifest',
  deps = [
    ':beta',
    ':exceptions',
    ':platform',
    ':primitives',
    '//java/client/src/org/openqa/selenium/interactions:core',
    '//java/client/src/org/openqa/selenium/interactions:exceptions',
    '//java/client/src/org/openqa/selenium/logging:api',
    '//java/client/src/org/openqa/selenium/security:security',
  ],
  visibility = [
    '//java/client/src/org/openqa/selenium/interactions:interactions',
  ],
)

genrule(name = 'manifest',
  out = 'manifest.mf',
  bash = 'printf "\nName: Build-Info\nSelenium-Version: {}\n" > $OUT'.format(SE_VERSION),
  cmd_exe = "(echo.\necho Name: Build-Info\necho Selenium-Version: {}\n) > %OUT%".format(SE_VERSION),
)

java_library(name = 'beta',
  srcs = [ 'Beta.java' ],
  visibility = [
    '//java/client/src/org/openqa/selenium/logging:api',
    '//java/client/src/org/openqa/selenium/logging:logging',
    '//java/client/src/org/openqa/selenium/os:os',
    '//java/client/src/org/openqa/selenium/security:security',
  ],
)

java_library(name = 'exceptions',
  srcs = [
    'ElementNotInteractableException.java',
    'ElementNotSelectableException.java',
    'ElementNotVisibleException.java',
    'ImeActivationFailedException.java',
    'ImeNotAvailableException.java',
    'InvalidArgumentException.java',
    'InvalidCookieDomainException.java',
    'InvalidElementStateException.java',
    'InvalidSelectorException.java',
    'JavascriptException.java',
    'NoAlertPresentException.java',
    'NoSuchCookieException.java',
    'NoSuchElementException.java',
    'NoSuchFrameException.java',
    'NoSuchSessionException.java',
    'NoSuchWindowException.java',
    'NotFoundException.java',
    'SessionNotCreatedException.java',
    'ScriptTimeoutException.java',
    'StaleElementReferenceException.java',
    'TimeoutException.java',
    'UnableToSetCookieException.java',
    'UnhandledAlertException.java',
    'UnsupportedCommandException.java',
    'WebDriverException.java',
    'internal/BuildInfo.java',
  ],
  deps = [
    ':beta',
  ],
  visibility = [
    '//java/client/src/org/openqa/selenium/interactions:exceptions',
    '//java/client/src/org/openqa/selenium/io:io',
    '//java/client/src/org/openqa/selenium/net:net',
    '//java/client/src/org/openqa/selenium/os:os',
    '//java/client/test/org/openqa/selenium/testing:helpers',
  ],
)

java_library(
  name = 'platform',
  srcs = [
    'Architecture.java',
    'Platform.java',
  ],
  deps = [
    ':exceptions',
  ],
  visibility = [
    '//java/client/src/org/openqa/selenium/io:io',
    '//java/client/src/org/openqa/selenium/net:net',
    '//java/client/src/org/openqa/selenium/os:os',
  ],
)

java_library(name = 'primitives',
  srcs = [
    'Dimension.java',
    'Point.java',
    'Rectangle.java',
  ],
  visibility = [
    '//java/client/src/org/openqa/selenium/interactions:core',
  ],
)

java_library(
  name = 'client-combined',
  maven_coords = 'org.seleniumhq.selenium:selenium-java:' + SE_VERSION,
  maven_pom_template = ':template-pom',
  exported_deps = [
    ":selenium",
    "//java/client/src/org/openqa/selenium/chrome:chrome",
    "//java/client/src/org/openqa/selenium/firefox:firefox",
    "//java/client/src/org/openqa/selenium/edge:edge",
    "//java/client/src/org/openqa/selenium/ie:ie",
    "//java/client/src/org/openqa/selenium/opera:opera",
    "//java/client/src/org/openqa/selenium/remote:remote",
    "//java/client/src/org/openqa/selenium/safari:safari",
    "//java/client/src/org/openqa/selenium/support:support",
    "//third_party/java/htmlunit:htmlunit",
    "//third_party/java/phantomjs-driver:phantomjs-driver",
  ],
  visibility = [
    '//java/server/src/org/openqa/grid/selenium:classes',
    '//java/server/test/org/openqa/selenium:lib',
  ],
)

export_file(
  name = 'template-pom',
  src = 'pom.xml',
  out = 'pom.xml',
  visibility = ['PUBLIC'],
)
