java_library(
    name = "selenium",
    srcs = glob([
        "*.java",
        "html5/*.java",
        "internal/*.java",
        "interactions/**/*.java",
        "logging/**/*.java",
        "mobile/*.java",
    ]),
    deps = [
        # Deliberately left empty of third party deps
    ],
    visibility = [
        "//visibility:public",
    ],
)
