# BUILD FILE SYNTAX: SKYLARK
API_SRCS = [
  'Logs.java',
  'LogEntries.java',
  'LogEntry.java',
  'LogLevelMapping.java',
  'LoggingPreferences.java',
]

java_library(name = 'api',
  srcs = API_SRCS,
  deps = [
    '//java/client/src/org/openqa/selenium:beta',
  ],
  visibility = [
    '//java/client/src/org/openqa/selenium:core',
    '//java/client/src/org/openqa/selenium:selenium',
  ],
)

java_library(name = 'logging',
  srcs = glob(['*.java', 'profiler/*.java'], excludes = API_SRCS),
  deps = [
    ':api',
    '//java/client/src/org/openqa/selenium:beta',
    '//java/client/src/org/openqa/selenium:exceptions',
    '//java/client/src/org/openqa/selenium/json:json',
    '//third_party/java/guava:guava',
  ],
  visibility = [
    '//java/client/src/org/openqa/selenium:selenium'
  ],
)
