load("//dotnet:selenium-dotnet-version.bzl", "ASSEMBLY_VERSION", "SE_VERSION")

genrule(
    name = "net47",
    srcs = ["Selenium.WebDriverBackedSelenium.csproj"],
    bash = "echo '$(location :webdriverbackedselenium_deps)' && echo '$(location //dotnet/src/webdriver:net47)' && dotnet build $SRCS --configuration Release --framework net47 --output $OUT /p:Version={} /p:AssemblyVersion={} /p:FileVersion={} /p:IntermediateOutputPath=$OUT/../obj/ /p:BuildSystem=buck".format(SE_VERSION, ASSEMBLY_VERSION, ASSEMBLY_VERSION),
    cmd_exe = "echo '$(location :webdriverbackedselenium_deps)' && echo '$(location //dotnet/src/webdriver:net47)' && dotnet build %SRCS% --configuration Release --framework net47 --output %OUT% /p:Version={} /p:AssemblyVersion={} /p:FileVersion={} /p:IntermediateOutputPath=%OUT%\..\obj\ /p:BuildSystem=buck".format(SE_VERSION, ASSEMBLY_VERSION, ASSEMBLY_VERSION),
    out = "bin",
)

genrule(
    name = "net46",
    srcs = ["Selenium.WebDriverBackedSelenium.csproj"],
    bash = "echo '$(location :webdriverbackedselenium_deps)' && echo '$(location //dotnet/src/webdriver:net46)' && dotnet build $SRCS --configuration Release --framework net46 --output $OUT /p:Version={} /p:AssemblyVersion={} /p:FileVersion={} /p:IntermediateOutputPath=$OUT/../obj/ /p:BuildSystem=buck".format(SE_VERSION, ASSEMBLY_VERSION, ASSEMBLY_VERSION),
    cmd_exe = "echo '$(location :webdriverbackedselenium_deps)' && echo '$(location //dotnet/src/webdriver:net46)' && dotnet build %SRCS% --configuration Release --framework net46 --output %OUT% /p:Version={} /p:AssemblyVersion={} /p:FileVersion={} /p:IntermediateOutputPath=%OUT%\..\obj\ /p:BuildSystem=buck".format(SE_VERSION, ASSEMBLY_VERSION, ASSEMBLY_VERSION),
    out = "bin",
)

genrule(
    name = "net45",
    srcs = ["Selenium.WebDriverBackedSelenium.csproj"],
    bash = "echo '$(location :webdriverbackedselenium_deps)' && echo '$(location //dotnet/src/webdriver:net45)' && dotnet build $SRCS --configuration Release --framework net45 --output $OUT /p:Version={} /p:AssemblyVersion={} /p:FileVersion={} /p:IntermediateOutputPath=$OUT/../obj/ /p:BuildSystem=buck".format(SE_VERSION, ASSEMBLY_VERSION, ASSEMBLY_VERSION),
    cmd_exe = "echo '$(location :webdriverbackedselenium_deps)' && echo '$(location //dotnet/src/webdriver:net45)' && dotnet build %SRCS% --configuration Release --framework net45 --output %OUT% /p:Version={} /p:AssemblyVersion={} /p:FileVersion={} /p:IntermediateOutputPath=%OUT%\..\obj\ /p:BuildSystem=buck".format(SE_VERSION, ASSEMBLY_VERSION, ASSEMBLY_VERSION),
    out = "bin",
)

genrule(
    name = "netstandard2.0",
    srcs = ["Selenium.WebDriverBackedSelenium.csproj"],
    bash = "echo '$(location :webdriverbackedselenium_deps)' && echo '$(location //dotnet/src/webdriver:netstandard2.0)' && dotnet build $SRCS --configuration Release --framework netstandard2.0 --output $OUT /p:Version={} /p:AssemblyVersion={} /p:FileVersion={} /p:IntermediateOutputPath=$OUT/../obj/ /p:BuildSystem=buck".format(SE_VERSION, ASSEMBLY_VERSION, ASSEMBLY_VERSION),
    cmd_exe = "echo '$(location :webdriverbackedselenium_deps)' && echo '$(location //dotnet/src/webdriver:netstandard2.0)' && dotnet build %SRCS% --configuration Release --framework netstandard2.0 --output %OUT% /p:Version={} /p:AssemblyVersion={} /p:FileVersion={} /p:IntermediateOutputPath=%OUT%\..\obj\ /p:BuildSystem=buck".format(SE_VERSION, ASSEMBLY_VERSION, ASSEMBLY_VERSION),
    out = "bin",
)

genrule(
    name = "merge",
    srcs = [
        ":net47",
        ":net46",
        ":net45",
        ":netstandard2.0",
    ],
    cmd_exe =
        "setlocal EnableDelayedExpansion && " +
        "(if not exist %OUT% mkdir %OUT%) && " +
        "for %%G in (%SRCS%) do (" +
        "set target_dir=%%G&& " +
        "set platform_dir=%%G\..&& " +
        "for %%H in (!target_dir!) do (" +
        "for %%I in (!platform_dir!) do set platform_moniker=%%~nxI&& " +
        "(if not exist %OUT%\!platform_moniker! mkdir %OUT%\!platform_moniker!) && " +
        "copy !target_dir!\Selenium.WebDriverBackedSelenium.dll %OUT%\!platform_moniker! &&" +
        "copy !target_dir!\Selenium.WebDriverBackedSelenium.xml %OUT%\!platform_moniker!" +
        ")" +
        ")",
    out = "lib",
)

genrule(
    name = "pack",
    srcs = ["Selenium.WebDriverBackedSelenium.nuspec"],
    cmd_exe = "$(exe //third_party/dotnet/nuget:nuget) pack %SRCS% /Properties packageid=Selenium.WebDriverBackedSelenium;version={} /Version {} /BasePath $(location :merge) /OutputDirectory %OUT%".format(SE_VERSION, SE_VERSION),
    out = "dist",
    visibility = ["PUBLIC"],
)

genrule(
    name = "net47_strongnamed",
    srcs = ["Selenium.WebDriverBackedSelenium.csproj"],
    cmd = "echo '$(location :webdriverbackedselenium_deps)' && echo '$(location //dotnet/src/webdriver:net47_strongnamed)' && dotnet build %SRCS% --configuration Release --framework net47 --output %OUT% /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=$(location //dotnet:keyfile) /p:Version={} /p:AssemblyVersion={} /p:FileVersion={} /p:IntermediateOutputPath=%OUT%\..\obj\ /p:BuildSystem=buck".format(SE_VERSION, ASSEMBLY_VERSION, ASSEMBLY_VERSION),
    out = "bin",
)

genrule(
    name = "net46_strongnamed",
    srcs = ["Selenium.WebDriverBackedSelenium.csproj"],
    cmd = "echo '$(location :webdriverbackedselenium_deps)' && echo '$(location //dotnet/src/webdriver:net46_strongnamed)' && dotnet build %SRCS% --configuration Release --framework net46 --output %OUT% /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=$(location //dotnet:keyfile) /p:Version={} /p:AssemblyVersion={} /p:FileVersion={} /p:IntermediateOutputPath=%OUT%\..\obj\ /p:BuildSystem=buck".format(SE_VERSION, ASSEMBLY_VERSION, ASSEMBLY_VERSION),
    out = "bin",
)

genrule(
    name = "net45_strongnamed",
    srcs = ["Selenium.WebDriverBackedSelenium.csproj"],
    cmd = "echo '$(location :webdriverbackedselenium_deps)' && echo '$(location //dotnet/src/webdriver:net45_strongnamed)' && dotnet build %SRCS% --configuration Release --framework net45 --output %OUT% /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=$(location //dotnet:keyfile) /p:Version={} /p:AssemblyVersion={} /p:FileVersion={} /p:IntermediateOutputPath=%OUT%\..\obj\ /p:BuildSystem=buck".format(SE_VERSION, ASSEMBLY_VERSION, ASSEMBLY_VERSION),
    out = "bin",
)

genrule(
    name = "netstandard2.0_strongnamed",
    srcs = ["Selenium.WebDriverBackedSelenium.csproj"],
    cmd = "echo '$(location :webdriverbackedselenium_deps)' && echo '$(location //dotnet/src/webdriver:netstandard2.0_strongnamed)' && dotnet build %SRCS% --configuration Release --framework netstandard2.0 --output %OUT% /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=$(location //dotnet:keyfile) /p:Version={} /p:AssemblyVersion={} /p:IntermediateOutputPath=%OUT%\..\obj\ /p:FileVersion={} /p:BuildSystem=buck".format(SE_VERSION, ASSEMBLY_VERSION, ASSEMBLY_VERSION),
    out = "bin",
)

genrule(
    name = "merge_strongnamed",
    srcs = [
        ":net47_strongnamed",
        ":net46_strongnamed",
        ":net45_strongnamed",
        ":netstandard2.0_strongnamed",
    ],
    cmd_exe =
        "setlocal EnableDelayedExpansion && " +
        "(if not exist %OUT% mkdir %OUT%) && " +
        "for %%G in (%SRCS%) do (" +
        "set target_dir=%%G&& " +
        "set platform_dir=%%G\..&& " +
        "for %%H in (!target_dir!) do (" +
        "for %%I in (!platform_dir!) do set full_platform_moniker=%%~nxI&& " +
        'for /f \"delims=_\" %%J in (\"!full_platform_moniker!\") do set platform_moniker=%%J&& ' +
        "(if not exist %OUT%\!platform_moniker! mkdir %OUT%\!platform_moniker!) && " +
        "copy !target_dir!\Selenium.WebDriverBackedSelenium.dll %OUT%\!platform_moniker! &&" +
        "copy !target_dir!\Selenium.WebDriverBackedSelenium.xml %OUT%\!platform_moniker!" +
        ")" +
        ")",
    out = "lib",
)

genrule(
    name = "pack_strongnamed",
    srcs = ["Selenium.WebDriverBackedSelenium.StrongNamed.nuspec"],
    cmd_exe = "$(exe //third_party/dotnet/nuget:nuget) pack %SRCS% /Properties packageid=Selenium.WebDriverBackedSelenium.StrongNamed;version={} /Version {} /BasePath $(location :merge_strongnamed) /OutputDirectory %OUT%".format(SE_VERSION, SE_VERSION),
    out = "dist",
    visibility = ["PUBLIC"],
)

genrule(
    name = "webdriverbackedselenium_deps",
    srcs = [
        "//java/client/src/com/thoughtworks/selenium/webdriven:injectableSelenium.js",
        "//java/client/src/com/thoughtworks/selenium/webdriven:htmlutils.js",
        "//javascript/selenium-atoms:findElement",
        "//javascript/selenium-atoms:findOption",
        "//javascript/selenium-atoms:fireEvent",
        "//javascript/selenium-atoms:fireEventAt",
        "//javascript/selenium-atoms:getText",
        "//javascript/selenium-atoms:linkLocator",
        "//javascript/selenium-atoms:isElementPresent",
        "//javascript/selenium-atoms:isSomethingSelected",
        "//javascript/selenium-atoms:isTextPresent",
        "//javascript/selenium-atoms:isVisible",
        "//javascript/selenium-atoms:type",
    ],
    bash = 'echo "$SRCS" > $OUT',
    cmd = 'echo "%SRCS%" > %OUT%',
    out = "deps.txt",
)
