include_defs('//dotnet/SELENIUM_DOTNET_VERSION')

genrule(
  name = 'net35',
  srcs = [ 'WebDriverBackedSelenium.NetCore.csproj' ],
  cmd = 'echo "$(location :webdriverbackedselenium_deps)" && dotnet build %SRCS% --configuration Release --framework net35 --output %OUT% /p:BuildSystem=buck',
  out = 'net35'
)

genrule(
  name = 'net40',
  srcs = [ 'WebDriverBackedSelenium.NetCore.csproj' ],
  cmd = 'echo "$(location :webdriverbackedselenium_deps)" && dotnet build %SRCS% --configuration Release --framework net40 --output %OUT% /p:BuildSystem=buck',
  out = 'net40'
)

genrule(
  name = 'net45',
  srcs = [ 'WebDriverBackedSelenium.NetCore.csproj' ],
  cmd = 'echo "$(location :webdriverbackedselenium_deps)" && dotnet build %SRCS% --configuration Release --framework net45 --output %OUT% /p:BuildSystem=buck',
  out = 'net45'
)

genrule(
  name = 'netstandard2.0',
  srcs = [ 'WebDriverBackedSelenium.NetCore.csproj' ],
  cmd = 'echo "$(location :webdriverbackedselenium_deps)" && dotnet build %SRCS% --configuration Release --framework netstandard2.0 --output %OUT% /p:BuildSystem=buck',
  out = 'netstandard2.0'
)

genrule(
  name = 'merge',
  srcs = [
    ':net35',
    ':net40',
    ':net45',
    ':netstandard2.0'
  ],
  cmd_exe = 
    'setlocal EnableDelayedExpansion && '\
    '(if not exist %OUT% mkdir %OUT%) && '\
    'for %%G in (%SRCS%) do ('\
      'set target_dir=%%G&& '\
      'for %%H in (!target_dir!) do ('\
        'set platform_moniker=%%~nxH&& '\
        '(if not exist %OUT%\\!platform_moniker! mkdir %OUT%\\!platform_moniker!) && '\
        'copy !target_dir!\\Selenium.WebDriverBackedSelenium.dll %OUT%\\!platform_moniker! &&'\
        'copy !target_dir!\\Selenium.WebDriverBackedSelenium.xml %OUT%\\!platform_moniker!'\
      ')'\
    ')',
  out = 'lib'
)

genrule(
  name = 'pack',
  srcs = ['Selenium.WebDriverBackedSelenium.nuspec'],
  cmd_exe = "$(exe //third_party/dotnet/nuget:nuget) pack %SRCS% /Properties packageid=Selenium.WebDriverBackedSelenium;version={} /Version {} /BasePath $(location :merge) /OutputDirectory %OUT%".format(SE_VERSION, SE_VERSION),
  out = 'dist'
)

genrule(
  name = 'net35_strongnamed',
  srcs = [ 'WebDriverBackedSelenium.NetCore.csproj' ],
  cmd = 'echo "$(location :webdriverbackedselenium_deps)" && dotnet build %SRCS% --configuration Release --framework net35 --output %OUT% /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=$(location //dotnet:keyfile) /p:BuildSystem=buck',
  out = 'net35'
)

genrule(
  name = 'net40_strongnamed',
  srcs = [ 'WebDriverBackedSelenium.NetCore.csproj' ],
  cmd = 'echo "$(location :webdriverbackedselenium_deps)" && dotnet build %SRCS% --configuration Release --framework net40 --output %OUT% /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=$(location //dotnet:keyfile) /p:BuildSystem=buck',
  out = 'net40'
)

genrule(
  name = 'net45_strongnamed',
  srcs = [ 'WebDriverBackedSelenium.NetCore.csproj' ],
  cmd = 'echo "$(location :webdriverbackedselenium_deps)" && dotnet build %SRCS% --configuration Release --framework net45 --output %OUT% /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=$(location //dotnet:keyfile) /p:BuildSystem=buck',
  out = 'net45'
)

genrule(
  name = 'netstandard2.0_strongnamed',
  srcs = [ 'WebDriverBackedSelenium.NetCore.csproj' ],
  cmd = 'echo "$(location :webdriverbackedselenium_deps)" && dotnet build %SRCS% --configuration Release --framework netstandard2.0 --output %OUT% /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=$(location //dotnet:keyfile) /p:BuildSystem=buck',
  out = 'netstandard2.0'
)

genrule(
  name = 'merge_strongnamed',
  srcs = [
    ':net35_strongnamed',
    ':net40_strongnamed',
    ':net45_strongnamed',
    ':netstandard2.0_strongnamed'
  ],
  cmd_exe = 
    'setlocal EnableDelayedExpansion && '\
    '(if not exist %OUT% mkdir %OUT%) && '\
    'for %%G in (%SRCS%) do ('\
      'set target_dir=%%G&& '\
      'for %%H in (!target_dir!) do ('\
        'set platform_moniker=%%~nxH&& '\
        '(if not exist %OUT%\\!platform_moniker! mkdir %OUT%\\!platform_moniker!) && '\
        'copy !target_dir!\\Selenium.WebDriverBackedSelenium.dll %OUT%\\!platform_moniker! &&'\
        'copy !target_dir!\\Selenium.WebDriverBackedSelenium.xml %OUT%\\!platform_moniker!'\
      ')'\
    ')',
  out = 'lib'
)

genrule(
  name = 'pack_strongnamed',
  srcs = ['Selenium.WebDriverBackedSelenium.nuspec'],
  cmd_exe = "$(exe //third_party/dotnet/nuget:nuget) pack %SRCS% /Properties packageid=Selenium.WebDriverBackedSelenium.StrongNamed;version={} /Version {} /BasePath $(location :merge_strongnamed) /OutputDirectory %OUT%".format(SE_VERSION, SE_VERSION),
  out = 'dist'
)

genrule(
  name = 'webdriverbackedselenium_deps',
  srcs = [
    '//java/client/src/com/thoughtworks/selenium/webdriven:injectableSelenium.js',
    '//java/client/src/com/thoughtworks/selenium/webdriven:htmlutils.js',
    '//javascript/selenium-atoms:findElement',
    '//javascript/selenium-atoms:findOption',
    '//javascript/selenium-atoms:fireEvent',
    '//javascript/selenium-atoms:fireEventAt',
    '//javascript/selenium-atoms:getText',
    '//javascript/selenium-atoms:linkLocator',
    '//javascript/selenium-atoms:isElementPresent',
    '//javascript/selenium-atoms:isSomethingSelected',
    '//javascript/selenium-atoms:isTextPresent',
    '//javascript/selenium-atoms:isVisible',
    '//javascript/selenium-atoms:type'
  ],
  cmd = 'echo "%SRCS%" > %OUT%',
  out = 'deps.txt'
)
