java_test(
    name = "data",
    labels = [
        "small",
    ],
    srcs = glob(["*.java"]),
    deps = [
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/server/src/org/openqa/selenium/grid/data:data",
        "//third_party/java/assertj:assertj",
        "//third_party/java/guava:guava",
        "//third_party/java/junit:junit",
    ],
)
