java_library(
    name = "http",
    srcs = glob(["*.java"]),
    deps = [
        "//java/client/src/org/openqa/selenium:selenium",
        "//third_party/java/guava:guava",
    ],
    visibility = [
        "//java/client/src/org/openqa/selenium/devtools:",
        "//java/client/src/org/openqa/selenium/remote/...",
    ],
)