#include "nsISupportsArray.idl"
#include "nsIAutoCompleteSearch.idl"

interface nsISupportsString;
interface nsISupportsArray;

[scriptable, uuid(47AFA811-9BAC-4211-AE30-EAEACE2138AE)]
interface nsISeleniumIDEGenericAutoCompleteSearch : nsIAutoCompleteSearch
{
  void setCandidates(in nsISupportsString searchKey, in nsISupportsArray values);
  void setCandidatesWithComments(in nsISupportsString searchKey, in nsISupportsArray values, in nsISupportsArray comments);
  void clearCandidates(in nsISupportsString searchKey);
};
