module Selenium
  module WebDriver
    module DriverExtensions
      module HasFedCmDialog
        @fedcm_dialog: untyped

        def fedcm_dialog: -> untyped

        def reset_cooldown: -> untyped

        def wait_for_fedcm_dialog: -> untyped
      end
    end
  end
end
