java_library(name = 'log',
  srcs = glob(['*.java']),
  deps = [
    '//java/client/src/org/openqa/selenium:webdriver-api',
    '//java/client/src/org/openqa/selenium/logging:logging',
    '//java/client/src/org/openqa/selenium/remote:api',
    '//third_party/java/guava:guava',
  ],
  visibility = [
    '//java/server/src/...',
  ],
)
