java_library(name = 'log',
  srcs = glob(['*.java']),
  deps = [
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//third_party/java/guava:guava',
  ],
  visibility = [
    '//java/server/src/...',
    '//java/server/test/...',
  ],
)
