java_library(
    name = "log",
    srcs = glob(["*.java"]),
    deps = [
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/server/src/org/openqa/selenium/grid:grid",
        "//third_party/java/guava:guava",
    ],
    visibility = [
        "//java/server/src/...",
        "//java/server/test/...",
    ],
)
