# DO NOT EDIT! This file is generated by scripts/selenium_manager.py.
# Regenerate with: `bazel run //scripts:selenium_manager`

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

def selenium_manager():
    http_file(
        name = "download_sm_linux_x86_64",
        executable = True,
        sha256 = "ec5822f3c6e910fdd51500508eb5f5b07b5ce0a2035008bbecc675d261bab6fd",
        url = "https://github.com/SeleniumHQ/selenium_manager_artifacts/releases/download/selenium-manager-60bc75f/selenium-manager-linux-x86_64",
    )

    http_file(
        name = "download_sm_linux_arm64",
        executable = True,
        sha256 = "0eef6f4c21fff93f33cfe7d175800c1be1043f9170eeeb803d7e72e1742c6847",
        url = "https://github.com/SeleniumHQ/selenium_manager_artifacts/releases/download/selenium-manager-60bc75f/selenium-manager-linux-arm64",
    )

    http_file(
        name = "download_sm_macos",
        executable = True,
        sha256 = "7dc667c416b33688a91bcef4cc981fafbdc0c56a2758ff32d070e28e6804dcb9",
        url = "https://github.com/SeleniumHQ/selenium_manager_artifacts/releases/download/selenium-manager-60bc75f/selenium-manager-macos",
    )

    http_file(
        name = "download_sm_windows",
        executable = True,
        sha256 = "2453c3cbb0b6647f6fc26d2720ed6b19b6b5dac550dc73491d4bd71e612f58da",
        url = "https://github.com/SeleniumHQ/selenium_manager_artifacts/releases/download/selenium-manager-60bc75f/selenium-manager-windows.exe",
    )

    http_file(
        name = "download_sm_sbom",
        sha256 = "4c452e7547de9b0925309e7e720723bbea1deaf3fe6ab3ff53db21fd92de73d4",
        url = "https://github.com/SeleniumHQ/selenium_manager_artifacts/releases/download/selenium-manager-60bc75f/selenium-manager.cdx.json",
    )

    http_file(
        name = "download_sm_notice",
        sha256 = "41ab35781239cc9a1faf47d77873b45e47f51ba1cacbdd16bbfbd53480d8660d",
        url = "https://github.com/SeleniumHQ/selenium_manager_artifacts/releases/download/selenium-manager-60bc75f/selenium-manager-THIRD-PARTY-NOTICES.txt",
    )

def _selenium_manager_artifacts_impl(_ctx):
    selenium_manager()

selenium_manager_artifacts = module_extension(
    implementation = _selenium_manager_artifacts_impl,
)
