# DO NOT EDIT! This file is generated by scripts/selenium_manager.py.
# Regenerate with: `bazel run //scripts:selenium_manager`

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

def selenium_manager():
    http_file(
        name = "download_sm_linux_x86_64",
        executable = True,
        sha256 = "d76852d481cd736426a0e3b3b7ec3c246b5abe6907b44341249bf51f00781901",
        url = "https://github.com/SeleniumHQ/selenium_manager_artifacts/releases/download/selenium-manager-d62f09d/selenium-manager-linux",
    )

    http_file(
        name = "download_sm_linux_arm64",
        executable = True,
        sha256 = "774d08f8188b991e657ee503aa28cee2dea6c97c8f804a73d7646db5fa7d995b",
        url = "https://github.com/SeleniumHQ/selenium_manager_artifacts/releases/download/selenium-manager-d62f09d/selenium-manager-linux-aarch64",
    )

    http_file(
        name = "download_sm_macos",
        executable = True,
        sha256 = "8b228c9ff5d212a93e5895f3387efc4f22e548de75c48976c36efab23fbf3377",
        url = "https://github.com/SeleniumHQ/selenium_manager_artifacts/releases/download/selenium-manager-d62f09d/selenium-manager-macos",
    )

    http_file(
        name = "download_sm_windows",
        executable = True,
        sha256 = "cb7460d2330b3d9037a6ab78c8e626cfecec97a30059fc51c46764e07e8c43ef",
        url = "https://github.com/SeleniumHQ/selenium_manager_artifacts/releases/download/selenium-manager-d62f09d/selenium-manager-windows.exe",
    )

    http_file(
        name = "download_sm_sbom",
        sha256 = "2e5e138a6a52e6536e8689dbfdff1c19ace8ae0be64a00bb9dfd65ea83854e93",
        url = "https://github.com/SeleniumHQ/selenium_manager_artifacts/releases/download/selenium-manager-d62f09d/selenium-manager.cdx.json",
    )

    http_file(
        name = "download_sm_notice",
        sha256 = "562302c53a61f88b900c09b1ec5cc4574fd9e5bf8eae3b3a8e49d30026c95ce3",
        url = "https://github.com/SeleniumHQ/selenium_manager_artifacts/releases/download/selenium-manager-d62f09d/selenium-manager-THIRD-PARTY-NOTICES.txt",
    )

def _selenium_manager_artifacts_impl(_ctx):
    selenium_manager()

selenium_manager_artifacts = module_extension(
    implementation = _selenium_manager_artifacts_impl,
)
