# DO NOT EDIT! This file is generated by scripts/selenium_manager.py.
# Regenerate with: `bazel run //scripts:selenium_manager`

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

def selenium_manager():
    http_file(
        name = "download_sm_linux_x86_64",
        executable = True,
        sha256 = "3bad0443dbf99e7268ee9c10cce57c12afd6dd8433f57bf103aec196afbb65b3",
        url = "https://github.com/SeleniumHQ/selenium_manager_artifacts/releases/download/selenium-manager-231a1fa/selenium-manager-linux-x86_64",
    )

    http_file(
        name = "download_sm_linux_arm64",
        executable = True,
        sha256 = "6218628f021bb52b93bf23a3c6f165a51674f61faa6377a5951dff177ca6cf4b",
        url = "https://github.com/SeleniumHQ/selenium_manager_artifacts/releases/download/selenium-manager-231a1fa/selenium-manager-linux-arm64",
    )

    http_file(
        name = "download_sm_macos",
        executable = True,
        sha256 = "77f80894c26591ee0ff08e26c34a558b40eab96686e9ef5b70645560569532f1",
        url = "https://github.com/SeleniumHQ/selenium_manager_artifacts/releases/download/selenium-manager-231a1fa/selenium-manager-macos",
    )

    http_file(
        name = "download_sm_windows",
        executable = True,
        sha256 = "b64edc4dfcd91372fa05cc4640b0fac9824fd385b4769bdbadf33a84d1a92bad",
        url = "https://github.com/SeleniumHQ/selenium_manager_artifacts/releases/download/selenium-manager-231a1fa/selenium-manager-windows.exe",
    )

    http_file(
        name = "download_sm_sbom",
        sha256 = "8ac5ea4dd0087f3688899138da43634392484d451d802f6b0b256e4097505049",
        url = "https://github.com/SeleniumHQ/selenium_manager_artifacts/releases/download/selenium-manager-231a1fa/selenium-manager.cdx.json",
    )

    http_file(
        name = "download_sm_notice",
        sha256 = "1282ec9b00345e42ca99f0709f65f2c81378ddb960cfc06f51b7b9cae9deb210",
        url = "https://github.com/SeleniumHQ/selenium_manager_artifacts/releases/download/selenium-manager-231a1fa/selenium-manager-THIRD-PARTY-NOTICES.txt",
    )

def _selenium_manager_artifacts_impl(_ctx):
    selenium_manager()

selenium_manager_artifacts = module_extension(
    implementation = _selenium_manager_artifacts_impl,
)
