closure_library(
    name = "lib",
    srcs = glob(["*.js"]),
    deps = [
        "//javascript/atoms:dom",
        "//javascript/atoms:locators",
        "//third_party/closure:closure",
    ],
)

closure_fragment(
    name = "get_location_in_view",
    module = "webdriver.chrome",
    function = "webdriver.chrome.getLocationInView",
    deps = [":lib"],
)

closure_fragment(
    name = "get_first_client_rect",
    module = "webdriver.chrome",
    function = "webdriver.chrome.getFirstClientRect",
    deps = [":lib"],
)

closure_fragment(
    name = "is_element_clickable",
    module = "webdriver.chrome",
    function = "webdriver.chrome.isElementClickable",
    deps = [":lib"],
)

closure_fragment(
    name = "get_page_zoom",
    module = "webdriver.chrome",
    function = "webdriver.chrome.getPageZoom",
    deps = [":lib"],
)

closure_fragment(
    name = "is_element_displayed",
    module = "webdriver.chrome",
    function = "webdriver.chrome.isElementDisplayed",
    deps = [
        ":lib",
        "//javascript/atoms/fragments:is-displayed",
    ],
)

closure_fragment(
    name = "find_element",
    module = "webdriver.chrome",
    function = "webdriver.chrome.findElement",
    deps = [":lib"],
)

java_test(
    name = "atoms-chrome",
    vm_args = [
        "-Dselenium.browser=chrome",
        "-Djs.test.timeout=20",
        "-Djs.test.dir=%s" % package_name(),
    ],
    test_classes = [
        "org.openqa.selenium.javascript.ClosureTestSuite",
    ],
    deps = [
        "//java/client/test/org/openqa/selenium/javascript:javascript",
        "//java/client/src/org/openqa/selenium/chrome:chrome",
    ],
)
