java_library(
    name = "webdriven",
    srcs = [
        "CompoundMutator.java",
        "ExplodingSupplier.java",
        "FunctionDeclaration.java",
        "SeleniumMutator.java",
        "VariableDeclaration.java",
        "WebDriverBackedSelenium.java",
        "WebDriverCommandProcessor.java",
    ],
    resources = [
        "htmlutils.js",
        "injectableSelenium.js",
        ":findElement",
        ":findOption",
        ":fireEvent",
        ":fireEventAt",
        ":getAttribute",
        ":getText",
        ":linkLocator",
        ":isElementPresent",
        ":isSomethingSelected",
        ":isTextPresent",
        ":isVisible",
        ":setCursorPosition",
        ":type",
        # TODO(simons): remove sizzle. There are no longer any browsers that need it.
        ":sizzle",
    ],
    exported_deps = [
        ":emulation-api",
        "//java/client/src/com/thoughtworks/selenium/webdriven/commands:commands",
    ],
    deps = [
        "//java/client/src/com/thoughtworks/selenium:selenium",
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//third_party/java/guava:guava",
    ],
    visibility = [
        "//java/client/src/com/thoughtworks/selenium/...",
        "//java/client/test/com/thoughtworks/selenium/...",
        "//java/server/src/com/thoughtworks/selenium/webdriven:rc-emulation-servlet",
        "//java/server/src/org/openqa/selenium/server/htmlrunner:htmlrunner",
    ],
)

java_library(
    name = "emulation-api",
    srcs = [
        "ElementFinder.java",
        "JavascriptLibrary.java",
        "ScriptMutator.java",
        "SeleneseCommand.java",
        "Timer.java",
        "Windows.java",
    ],
    deps = [
        "//java/client/src/com/thoughtworks/selenium:selenium",
        "//java/client/src/org/openqa/selenium:selenium",
        "//third_party/java/guava:guava",
    ],
    visibility = [
        "//java/client/src/com/thoughtworks/selenium/...",
        "//java/client/test/com/thoughtworks/selenium/...",
    ],
)

[export_file(
    name = name,
    out = "%s.js" % name,
    src = "//javascript/selenium-atoms:%s" % name,
) for name in [
    "findElement",
    "findOption",
    "fireEvent",
    "fireEventAt",
    "getAttribute",
    "getText",
    "linkLocator",
    "isElementPresent",
    "isSomethingSelected",
    "isTextPresent",
    "isVisible",
    "setCursorPosition",
    "type",
]]

export_file(
    name = "sizzle",
    out = "sizzle.js",
    src = "//third_party/js/sizzle:sizzle",
)

export_file(
    name = "injectableSelenium.js",
    src = "injectableSelenium.js",
    out = "injectableSelenium.js",
    visibility = [
        "//dotnet/src/webdriverbackedselenium:webdriverbackedselenium_deps",
    ],
)

export_file(
    name = "htmlutils.js",
    src = "htmlutils.js",
    out = "htmlutils.js",
    visibility = [
        "//dotnet/src/webdriverbackedselenium:webdriverbackedselenium_deps",
    ],
)
