
java_library(name = 'webdriven',
  srcs = [
    'CompoundMutator.java',
    'ExplodingSupplier.java',
    'FunctionDeclaration.java',
    'SeleniumMutator.java',
    'VariableDeclaration.java',
    'WebDriverBackedSelenium.java',
    'WebDriverCommandProcessor.java',
  ],
  resources = [
    'htmlutils.js',
    'injectableSelenium.js',
    ':findElement',
    ':findOption',
    ':fireEvent',
    ':fireEventAt',
    ':getAttribute',
    ':getText',
    ':linkLocator',
    ':isElementPresent',
    ':isSomethingSelected',
    ':isTextPresent',
    ':isVisible',
    ':type',
    # TODO(simons): remove sizzle. There are no longer any browsers that need it.
    ':sizzle',
  ],
  exported_deps = [
    ':emulation-api',
  ],
  deps = [
    '//java/client/src/com/thoughtworks/selenium:selenium',
    '//java/client/src/com/thoughtworks/selenium/webdriven/commands:commands',
    '//java/client/src/org/openqa/selenium:webdriver-api',
    '//third_party/java/guava-libraries:guava-libraries',
  ],
  visibility = [
    '//java/client/src/com/thoughtworks/selenium/...',
    '//java/client/test/com/thoughtworks/selenium/...',
    '//java/client/test/org/openqa/selenium/v1:tests',
    '//java/client/test/org/openqa/selenium/v1/internal/seleniumemulation:LargeTests',
    '//java/client/test/org/openqa/selenium/v1/internal/seleniumemulation:tests',
    '//java/server/src/com/thoughtworks/selenium/webdriven:rc-emulation-servlet',
    '//java/server/src/org/openqa/grid/selenium:classes',
    '//java/server/src/org/openqa/selenium/server:server',
  ],
)

java_library(name = 'emulation-api',
  srcs = [
    'ElementFinder.java',
    'JavascriptLibrary.java',
    'ScriptMutator.java',
    'SeleneseCommand.java',
    'Timer.java',
    'Windows.java',
  ],
  deps = [
    '//java/client/src/com/thoughtworks/selenium:api',
    '//java/client/src/org/openqa/selenium:webdriver-api',
    '//third_party/java/guava-libraries:guava-libraries',
  ],
  visibility = [
    '//java/client/src/com/thoughtworks/selenium/...',
    '//java/client/test/com/thoughtworks/selenium/...',
    '//java/client/test/org/openqa/selenium/v1/internal/seleniumemulation:tests',
  ],
)

for name in ['findElement', 'findOption', 'fireEvent', 'fireEventAt', 'getAttribute', 'getText',
             'linkLocator', 'isElementPresent', 'isSomethingSelected', 'isTextPresent',
             'isVisible', 'type',]:
  export_file(name = name,
    out = '%s.js' % name,
    src = '//javascript/selenium-atoms:%s' % name,
  )

export_file(name = 'sizzle',
  out = 'sizzle.js',
  src = '//third_party/js/sizzle:sizzle',
)
