load("@aspect_rules_js//npm:defs.bzl", "npm_package")
load("//common:defs.bzl", "copy_file")
load("//javascript/selenium-manager:version.bzl", "SM_VERSION")

copy_file(
    name = "manager-binary",
    src = "//common/manager:selenium-manager-linux-arm64",
    out = "bin/selenium-manager",
)

genrule(
    name = "license",
    srcs = ["//:license"],
    outs = [
        "LICENSE",
        "NOTICE",
    ],
    cmd = "cp $(locations //:license) $(@D)",
)

npm_package(
    name = "selenium-manager-linux-arm64",
    srcs = [
        "package.json",
        ":license",
        ":manager-binary",
    ],
    package = "@selenium/manager-linux-arm64",
    publishable = True,
    tags = ["release-artifact"],
    version = SM_VERSION,
    visibility = ["//visibility:public"],
)
