# DO NOT EDIT THIS FILE!
#
# This file is generated from the WebDriver BiDi specification. If you need to make
# changes, edit the generator and regenerate all of the modules.
#
# WebDriver BiDi module: log
from __future__ import annotations

from typing import Any, Dict, List, Optional, Union
from .common import command_builder
from dataclasses import field
from typing import Generator
from dataclasses import dataclass


class Level:
    """Level."""

    DEBUG = "debug"
    INFO = "info"
    WARN = "warn"
    ERROR = "error"


LogLevel = Level

@dataclass
class BaseLogEntry:
    """BaseLogEntry."""

    level: Any | None = None
    source: Any | None = None
    text: Any | None = None
    timestamp: Any | None = None
    stack_trace: Any | None = None


@dataclass
class GenericLogEntry:
    """GenericLogEntry."""

    type: str | None = None


@dataclass
class ConsoleLogEntry:
    """ConsoleLogEntry - a console log entry from the browser."""

    type_: str | None = None
    method: str | None = None
    args: list | None = None
    level: Any | None = None
    text: Any | None = None
    source: Any | None = None
    timestamp: Any | None = None
    stack_trace: Any | None = None

    @classmethod
    def from_json(cls, params: dict) -> "ConsoleLogEntry":
        """Deserialize from BiDi params dict."""
        return cls(
            type_=params.get("type"),
            method=params.get("method"),
            args=params.get("args"),
            level=params.get("level"),
            text=params.get("text"),
            source=params.get("source"),
            timestamp=params.get("timestamp"),
            stack_trace=params.get("stackTrace"),
        )

@dataclass
class JavascriptLogEntry:
    """JavascriptLogEntry - a JavaScript error log entry from the browser."""

    type_: str | None = None
    level: Any | None = None
    text: Any | None = None
    source: Any | None = None
    timestamp: Any | None = None
    stacktrace: Any | None = None

    @classmethod
    def from_json(cls, params: dict) -> "JavascriptLogEntry":
        """Deserialize from BiDi params dict."""
        return cls(
            type_=params.get("type"),
            level=params.get("level"),
            text=params.get("text"),
            source=params.get("source"),
            timestamp=params.get("timestamp"),
            stacktrace=params.get("stackTrace"),
        )

class Log:
    """WebDriver BiDi log module."""

    def __init__(self, conn) -> None:
        self._conn = conn

    def entry_added(self):
        """Execute log.entryAdded."""
        params = {
        }
        params = {k: v for k, v in params.items() if v is not None}
        cmd = command_builder("log.entryAdded", params)
        result = self._conn.execute(cmd)
        return result

