java_test(name = 'lift',
  srcs = glob([
    '*.java',
    'find/*.java',
    'match/*.java',
  ]),
  deps = [
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/src/org/openqa/selenium/lift:lift',
    '//java/client/src/org/openqa/selenium/support/ui:clock',
    '//java/client/test/org/openqa/selenium/support:tests',
    '//third_party/java/hamcrest:hamcrest',
    '//third_party/java/junit:junit',
    '//third_party/java/mockito:mockito',
  ])
