/* AUTO GENERATED - Do not edit by hand. */
/* See rake-tasks/crazy_fun/mappings/javascript.rb for generator. */

#ifndef GET_ATTRIBUTE_H
#define GET_ATTRIBUTE_H

const wchar_t* GET_ATTRIBUTE[] = {
L"function(){var e=this;",
L"function f(a){var c=typeof a;if(c==\"object\")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)==\"[object Array]\"||typeof a.length==\"number\"&&typeof a.splice!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"&&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(!(a instanceof Object)&&(Object.prototype.toString.call(a)==\"[object Function]\"||typeof a.call!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"&&!a.propertyIsEnumerable(\"call\")))return\"function\"}else return\"null\";else if(c==",
L"\"function\"&&typeof a.call==\"undefined\")return\"object\";return c}function h(a,c){function b(){}b.prototype=c.prototype;a.g=c.prototype;a.prototype=new b};function i(a){this.stack=Error().stack||\"\";if(a)this.message=String(a)}h(i,Error);function j(a){for(var c=1;c<arguments.length;c++){var b=String(arguments[c]).replace(/\\$/g,\"$$$$\");a=a.replace(/\\%s/,b)}return a}function k(a){return a.replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\")}function o(a,c){if(a<c)return-1;else if(a>c)return 1;return 0};function p(a,c){c.unshift(a);i.call(this,j.apply(null,c));c.shift();this.h=a}h(p,i);function q(a,c){if(!a){var b=Array.prototype.slice.call(arguments,2),d=\"Assertion failed\";if(c){d+=\": \"+c;var g=b}throw new p(\"\"+d,g||[]);}return a};var r=Array.prototype,s=r.indexOf?function(a,c,b){q(a.length!=null);return r.indexOf.call(a,c,b)}:function(a,c,b){b=b==null?0:b<0?Math.max(0,a.length+b):b;if(typeof a==\"string\"){if(typeof c!=\"string\"||c.length!=1)return-1;return a.indexOf(c,b)}for(b=b;b<a.length;b++)if(b in a&&a[b]===c)return b;return-1};var t,u,v,w;function x(){return e.navigator?e.navigator.userAgent:null}w=v=u=t=false;var y;if(y=x()){var z=e.navigator;t=y.indexOf(\"Opera\")==0;u=!t&&y.indexOf(\"MSIE\")!=-1;v=!t&&y.indexOf(\"WebKit\")!=-1;w=!t&&!v&&z.product==\"Gecko\"}var A=u,B=w,C=v,D;",
L"a:{var E=\"\",F;if(t&&e.opera){var G=e.opera.version;E=typeof G==\"function\"?G():G}else{if(B)F=/rv\\:([^\\);]+)(\\)|;)/;else if(A)F=/MSIE\\s+([^\\);]+)(\\)|;)/;else if(C)F=/WebKit\\/(\\S+)/;if(F){var H=F.exec(x());E=H?H[1]:\"\"}}if(A){var I,J=e.document;I=J?J.documentMode:undefined;if(I>parseFloat(E)){D=String(I);break a}}D=E}var K={};",
L"function L(a){var c;if(!(c=K[a])){c=0;var b=k(String(D)).split(\".\"),d=k(String(a)).split(\".\"),g=Math.max(b.length,d.length);for(var l=0;c==0&&l<g;l++){var X=b[l]||\"\",Y=d[l]||\"\",Z=RegExp(\"(\\\\d*)(\\\\D*)\",\"g\"),$=RegExp(\"(\\\\d*)(\\\\D*)\",\"g\");do{var m=Z.exec(X)||[\"\",\"\",\"\"],n=$.exec(Y)||[\"\",\"\",\"\"];if(m[0].length==0&&n[0].length==0)break;c=o(m[1].length==0?0:parseInt(m[1],10),n[1].length==0?0:parseInt(n[1],10))||o(m[2].length==0,n[2].length==0)||o(m[2],n[2])}while(c==0)}c=K[a]=c>=0}return c};!A||L(\"9\");A&&L(\"9\");var M=\"StopIteration\"in e?e.StopIteration:Error(\"StopIteration\");function N(){}N.prototype.next=function(){throw M;};function O(a,c,b,d,g){this.a=!!c;a&&P(this,a,d);this.d=g!=undefined?g:this.c||0;if(this.a)this.d*=-1;this.f=!b}h(O,N);O.prototype.b=null;O.prototype.c=0;O.prototype.e=false;function P(a,c,b,d){if(a.b=c)a.c=typeof b==\"number\"?b:a.b.nodeType!=1?0:a.a?-1:1;if(typeof d==\"number\")a.d=d}",
L"O.prototype.next=function(){var a;if(this.e){if(!this.b||this.f&&this.d==0)throw M;a=this.b;var c=this.a?-1:1;if(this.c==c){var b=this.a?a.lastChild:a.firstChild;b?P(this,b):P(this,a,c*-1)}else(b=this.a?a.previousSibling:a.nextSibling)?P(this,b):P(this,a.parentNode,c*-1);this.d+=this.c*(this.a?-1:1)}else this.e=true;a=this.b;if(!this.b)throw M;return a};",
L"O.prototype.splice=function(){var a=this.b,c=this.a?1:-1;if(this.c==c){this.c=c*-1;this.d+=this.c*(this.a?-1:1)}this.a=!this.a;O.prototype.next.call(this);this.a=!this.a;c=arguments[0];var b=f(c);c=b==\"array\"||b==\"object\"&&typeof c.length==\"number\"?arguments[0]:arguments;for(b=c.length-1;b>=0;b--)a.parentNode&&a.parentNode.insertBefore(c[b],a.nextSibling);a&&a.parentNode&&a.parentNode.removeChild(a)};function Q(a,c,b,d){O.call(this,a,c,b,null,d)}h(Q,O);Q.prototype.next=function(){do Q.g.next.call(this);while(this.c==-1);return this.b};var aa={\"class\":\"className\",readonly:\"readOnly\"},R=[\"async\",\"autofocus\",\"autoplay\",\"checked\",\"compact\",\"complete\",\"controls\",\"declare\",\"defaultchecked\",\"defaultselected\",\"defer\",\"disabled\",\"draggable\",\"ended\",\"formnovalidate\",\"hidden\",\"indeterminate\",\"iscontenteditable\",\"ismap\",\"itemscope\",\"loop\",\"multiple\",\"muted\",\"nohref\",\"noresize\",\"noshade\",\"novalidate\",\"nowrap\",\"open\",\"paused\",\"pubdate\",\"readonly\",\"required\",\"reversed\",\"scoped\",\"seamless\",\"seeking\",\"selected\",\"spellcheck\",\"truespeed\",\"willvalidate\"];",
L"function ba(a,c){if(8==a.nodeType)return null;c=c.toLowerCase();if(c==\"style\"){var b=k(a.style.cssText).toLowerCase();return b.charAt(b.length-1)==\";\"?b:b+\";\"}b=a.getAttributeNode(c);if(A)if(!b&&L(8)&&s(R,c)>=0)b=a[c];if(!b)return null;if(s(R,c)>=0)return A&&b.value==\"false\"?null:\"true\";return b.specified?b.value:null};",
L"var ca=[\"checkbox\",\"radio\"];function S(a){var c=a.tagName.toUpperCase();if(c==\"OPTION\")return true;if(c==\"INPUT\")if(s(ca,a.type)>=0)return true;return false};function T(a,c){var b=null;b=c.toLowerCase();if(\"style\"==c.toLowerCase()){if((b=a.style)&&typeof b!=\"string\")b=b.cssText;return b}if(\"selected\"==b||\"checked\"==b&&S(a)){var d;if(S(a)){d=\"selected\";b=a.type&&a.type.toLowerCase();if(\"checkbox\"==b||\"radio\"==b)d=\"checked\";d=!!a[d]}else d=false;return d?\"true\":null}var g=a.tagName&&\"A\"==a.tagName.toUpperCase();try{d=a[aa[c]||c]}catch(l){}if(!(b=b==\"href\"&&g)){if(!(b=d==null)){b=f(d);b=b==\"object\"||b==\"array\"||b==\"function\"}b=b}b=b?ba(a,c):d;return b!=null?",
L"b.toString():null}var U=\"_\".split(\".\"),V=e;!(U[0]in V)&&V.execScript&&V.execScript(\"var \"+U[0]);for(var W;U.length&&(W=U.shift());)if(!U.length&&T!==undefined)V[W]=T;else V=V[W]?V[W]:V[W]={};; return _.apply(null,arguments);}",
NULL
};

#endif

