java_library(
    name = "config",
    srcs = glob(["*.java"]),
    deps = [
        "//third_party/java/guava:guava",
    ],
    visibility = [
        "//java/server/src/org/openqa/selenium/events/...",
        "//java/server/src/org/openqa/selenium/grid/...",
    ],
)
