java_library(name = 'environment',
  srcs = glob(['*.java', 'webserver/*.java'], excludes = ['**/*Test.java']),
  deps = [
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/test/org/openqa/selenium/testing:helpers',
    '//third_party/java/commons-fileupload:commons-fileupload',
    '//third_party/java/guava:guava',
    '//third_party/java/httpcomponents:httpclient',
    '//third_party/java/jetty:jetty',
    '//third_party/java/servlet:servlet-api',
  ],
  visibility = [
    '//java/client/test/...',
    '//java/server/test/...',
  ],
)

java_binary(name = 'webserver',
  main_class = 'org.openqa.selenium.environment.webserver.JettyAppServer',
  deps = [
    ':environment'
  ]
)

java_test(name = "webserver-test",
  srcs = [
    "webserver/AppServerTest.java",
  ],
  vm_args = [
    '-Dselenium.browser=ff',
  ],
  deps = [
    ":environment",
    "//java/client/src/org/openqa/selenium/remote:remote",
    "//java/client/src/org/openqa/selenium/chrome:chrome",
    '//java/client/test/org/openqa/selenium/testing/drivers:drivers',
    "//third_party/java/guava:guava",
    "//third_party/java/httpcomponents:httpclient",
    "//third_party/java/junit:junit",
  ],
)

