java_library(name = 'environment',
  srcs = glob(['*.java', 'webserver/*.java'], excludes = ['**/*Test.java']),
  deps = [
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/test/org/openqa/selenium/testing:helpers',
    '//third_party/java/commons-fileupload:commons-fileupload',
    '//third_party/java/guava:guava',
    '//third_party/java/httpcomponents:httpclient',
    '//third_party/java/jetty:jetty',
    '//third_party/java/servlet:servlet-api',
  ],
  visibility = [
    '//java/client/test/...',
    '//java/server/test/...',
  ],
)
