module Selenium
  module WebDriver
    module Safari
      module Features
        # https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/WebDriverEndpointDoc/Commands/Commands.html
        SAFARI_COMMANDS: Hash[Symbol, Array[Symbol | String]]

        def commands: (untyped command) -> untyped

        def permissions: () -> untyped

        def permissions=: (untyped permissions) -> untyped

        def attach_debugger: () -> untyped
      end
    end
  end
end
