module Selenium
  module WebDriver
    module Safari
      class Options < WebDriver::Options
        attr_accessor options: untyped

        # @see https://developer.apple.com/documentation/webkit/about_webdriver_for_safari
        CAPABILITIES: { automatic_inspection: "safari:automaticInspection", automatic_profiling: "safari:automaticProfiling" }

        BROWSER: untyped

        def add_option: (untyped name, ?untyped? value) -> untyped

        def as_json: (*untyped) -> untyped
      end
    end
  end
end
