module Selenium
  module WebDriver
    module Safari
      class Options < WebDriver::Options
        attr_accessor options: untyped

        CAPABILITIES: Hash[Symbol, String]

        BROWSER: String

        TECHNOLOGY_PREVIEW: String

        def add_option: (untyped name, ?untyped? value) -> untyped

        def browser_name: () -> String

        def browser_name=: (String value) -> String
      end
    end
  end
end
