#!/bin/bash

gh run download --pattern 'selenium-manager*'

extract_move_delete() {
    local SOURCE="$1"
    local TARGET="$2"
    local PARENT_DIR="$(dirname "$SOURCE")"

    if [[ "$SOURCE" == *.tar ]]; then
        tar -xf "$SOURCE" -C "$TARGET"
    else
        mv "$SOURCE" "$TARGET"
    fi

    rm -rf "$PARENT_DIR"
}

extract_move_delete "selenium-manager_linux-x64/selenium-manager.tar" "common/manager/linux"
extract_move_delete "selenium-manager_macos-universal/selenium-manager.tar" "common/manager/macos"
extract_move_delete "selenium-manager_windows-x32/selenium-manager.exe" "common/manager/windows"
