java_library(name = 'common',
  srcs = glob(['**/*.java']),
  resources = glob(['defaults/*.json']),
  deps = [
    '//java/client/src/org/openqa/selenium:platform',
    '//java/client/src/org/openqa/selenium/net:net',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//java/server/src/org/openqa/grid/shared:cli',
    '//third_party/java/gson:gson',
    '//third_party/java/guava-libraries:guava-libraries',
  ],
  visibility = [
    '//java/server/src/org/openqa/grid:grid',
    '//java/server/src/org/openqa/grid/selenium:classes',
    '//java/server/test/org/openqa/grid/...',
  ],
)
