// This file was autogenerated by calcdeps.py
goog.addDependency('../../../js/src/abstractcommandprocessor.js', ['webdriver.AbstractCommandProcessor'], ['goog.Disposable', 'goog.array', 'goog.object', 'webdriver.CommandName', 'webdriver.Context', 'webdriver.Future', 'webdriver.Response', 'webdriver.timing']);
goog.addDependency('../../../js/src/asserts.js', ['webdriver.asserts'], ['goog.math.Coordinate', 'goog.string', 'webdriver.Future']);
goog.addDependency('../../../js/src/by.js', ['webdriver.By', 'webdriver.By.Locator', 'webdriver.By.Strategy'], ['goog.object', 'goog.string']);
goog.addDependency('../../../js/src/command.js', ['webdriver.Command', 'webdriver.CommandName', 'webdriver.Response'], ['goog.Disposable', 'goog.array', 'goog.testing.stacktrace']);
goog.addDependency('../../../js/src/context.js', ['webdriver.Context'], []);
goog.addDependency('../../../js/src/factory.js', ['webdriver.factory'], ['goog.userAgent', 'webdriver.LocalCommandProcessor', 'webdriver.WebDriver']);
goog.addDependency('../../../js/src/future.js', ['webdriver.Future'], ['goog.events.EventType', 'goog.events.EventTarget']);
goog.addDependency('../../../js/src/key.js', ['webdriver.Key'], ['goog.array']);
goog.addDependency('../../../js/src/localcommandprocessor.js', ['webdriver.LocalCommandProcessor'], ['goog.array', 'goog.dom', 'goog.events', 'goog.json', 'goog.object', 'webdriver.AbstractCommandProcessor', 'webdriver.CommandName', 'webdriver.Context', 'webdriver.Response']);
goog.addDependency('../../../js/src/logging.js', ['webdriver.logging', 'webdriver.logging.Level'], ['goog.dom', 'goog.string']);
goog.addDependency('../../../js/src/testrunner.js', ['webdriver.TestCase', 'webdriver.TestResult', 'webdriver.TestRunner'], ['goog.Uri', 'goog.dom', 'goog.style', 'webdriver.WebDriver.EventType', 'webdriver.factory', 'webdriver.logging', 'webdriver.timing']);
goog.addDependency('../../../js/src/timing.js', ['webdriver.timing'], ['goog.userAgent']);
goog.addDependency('../../../js/src/wait.js', ['webdriver.Wait'], ['goog.events', 'webdriver.Future', 'webdriver.timing']);
goog.addDependency('../../../js/src/webdriver.js', ['webdriver.WebDriver', 'webdriver.WebDriver.EventType'], ['goog.events', 'goog.events.EventTarget', 'webdriver.Command', 'webdriver.CommandName', 'webdriver.Context', 'webdriver.Future', 'webdriver.Response', 'webdriver.Wait', 'webdriver.WebElement', 'webdriver.logging', 'webdriver.timing']);
goog.addDependency('../../../js/src/webelement.js', ['webdriver.WebElement'], ['goog.array', 'webdriver.By.Locator', 'webdriver.By.Strategy', 'webdriver.Command', 'webdriver.CommandName', 'webdriver.Future']);
goog.addDependency('../../../js/src/extension/dommessenger.js', [], []);
