// This file was autogenerated by calcdeps.py
goog.addDependency('../../../js/src/abstractcommandprocessor.js', ['webdriver.AbstractCommandProcessor'], ['goog.Disposable', 'goog.array', 'goog.object', 'webdriver.CommandName', 'webdriver.Future', 'webdriver.Response', 'webdriver.WebElement', 'webdriver.timing']);
goog.addDependency('../../../js/src/asserts.js', ['webdriver.asserts'], ['goog.math.Coordinate', 'goog.string', 'webdriver.Future']);
goog.addDependency('../../../js/src/by.js', ['webdriver.By', 'webdriver.By.Locator', 'webdriver.By.Strategy'], ['goog.object', 'goog.string']);
goog.addDependency('../../../js/src/command.js', ['webdriver.Command', 'webdriver.CommandName', 'webdriver.Response'], ['goog.array', 'goog.events.EventTarget', 'goog.testing.stacktrace', 'webdriver.Future']);
goog.addDependency('../../../js/src/factory.js', ['webdriver.factory'], ['goog.userAgent', 'webdriver.LocalCommandProcessor', 'webdriver.WebDriver']);
goog.addDependency('../../../js/src/future.js', ['webdriver.Future'], ['goog.Disposable', 'goog.array']);
goog.addDependency('../../../js/src/jsunit.js', ['webdriver.jsunit'], ['goog.testing.jsunit', 'webdriver.TestCase', 'webdriver.asserts', 'webdriver.factory']);
goog.addDependency('../../../js/src/key.js', ['webdriver.Key'], ['goog.array']);
goog.addDependency('../../../js/src/localcommandprocessor.js', ['webdriver.LocalCommandProcessor'], ['goog.array', 'goog.debug.Logger', 'goog.dom', 'goog.events', 'goog.json', 'goog.object', 'webdriver.AbstractCommandProcessor', 'webdriver.CommandName', 'webdriver.Response']);
goog.addDependency('../../../js/src/testcase.js', ['webdriver.TestCase', 'webdriver.TestCase.Test'], ['goog.events', 'goog.testing.TestCase', 'goog.testing.TestCase.Test', 'goog.testing.asserts', 'webdriver.Command']);
goog.addDependency('../../../js/src/timing.js', ['webdriver.timing'], ['goog.userAgent']);
goog.addDependency('../../../js/src/webdriver.js', ['webdriver.WebDriver', 'webdriver.WebDriver.EventType', 'webdriver.WebDriver.Speed'], ['goog.debug.Logger', 'goog.events', 'goog.events.EventTarget', 'webdriver.By.Locator', 'webdriver.Command', 'webdriver.CommandName', 'webdriver.Response', 'webdriver.WebElement', 'webdriver.timing']);
goog.addDependency('../../../js/src/webelement.js', ['webdriver.WebElement'], ['goog.array', 'webdriver.By.Locator', 'webdriver.By.Strategy', 'webdriver.CommandName', 'webdriver.Future']);
goog.addDependency('../../../js/src/extension/dommessenger.js', [], []);
goog.addDependency('../../../js/test/deps.js', [], []);
goog.addDependency('../../../js/test/fakecommandprocessor.js', ['webdriver.FakeCommandProcessor'], ['goog.structs.Map', 'goog.testing.asserts', 'webdriver.AbstractCommandProcessor']);
goog.addDependency('../../../js/test/testbase.js', [], ['goog.Uri', 'goog.dom', 'goog.events', 'goog.math.Coordinate', 'goog.math.Size', 'goog.string', 'goog.userAgent', 'webdriver.Key', 'webdriver.WebElement', 'webdriver.asserts', 'webdriver.factory', 'webdriver.jsunit']);
goog.addDependency('../../../js/test/webdriver-bootstrap.js', [], []);
