java_library(
    name = "server",
    srcs = glob(["*.java"]),
    provided_deps = [
        "//third_party/java/servlet:javax.servlet-api",
    ],
    exported_deps = [
        "//java/server/src/org/openqa/selenium/events:events",
        "//java/server/src/org/openqa/selenium/grid/component:component",
        "//java/server/src/org/openqa/selenium/grid/log:log",
        "//java/server/src/org/openqa/selenium/grid/web:web",
    ],
    deps = [
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/client/src/org/openqa/selenium/remote/tracing:tracing",
        "//java/server/src/org/openqa/selenium/events/zeromq:zeromq",
        "//java/server/src/org/openqa/selenium/grid/config:config",
        "//third_party/java/beust:jcommander",
        "//third_party/java/guava:guava",
        "//third_party/java/jetty:jetty",
    ],
    visibility = [
        "//java/server/src/org/openqa/selenium/grid/...",
        "//java/server/src/org/openqa/selenium/remote/server/...",
        "//java/server/test/org/openqa/...",
    ],
)
