# BUILD FILE SYNTAX: SKYLARK

java_library(
    name = "server",
    srcs = glob(["*.java"]),
    provided_deps = [
        "//third_party/java/servlet:javax.servlet-api",
    ],
    deps = [
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/server/src/org/openqa/selenium/injector:injector",
        "//java/server/src/org/openqa/selenium/grid/web:web",
        "//third_party/java/guava:guava",
        "//third_party/java/jetty:jetty",
    ],
    visibility = [
        "//java/server/test/org/openqa/selenium/grid/...",
    ],
)