
js_library(name = 'atoms-lib',
  srcs = glob(['*.js', 'storage/*.js']),
  deps = [
    '//javascript/atoms:action',
    '//javascript/atoms:devices',
    '//javascript/atoms:dom',
    '//javascript/atoms:html5',
    '//javascript/webdriver:key',
    '//third_party/closure:closure',
  ],
  visibility = [
    '//javascript/...',
  ],
)

