java_test(
    name = "small-tests",
    srcs = glob(["*.java"]),
    labels = [
        "small",
    ],
    deps = [
        "//java/client/src/org/openqa/selenium:core",
        "//java/client/src/org/openqa/selenium/json:json",
        "//java/server/src/org/openqa/selenium/injector:injector",
        '//third_party/java/assertj:assertj',
        "//third_party/java/junit:junit",
    ],
)
