module Selenium
  module WebDriver
    module Chrome
      class Driver < Chromium::Driver
        include LocalDriver

        def initialize: (?options: untyped?, ?service: untyped?, ?url: untyped?, **untyped opts) -> void

        def browser: () -> Symbol

        private

        def devtools_address: () -> String
      end
    end
  end
end
