module Selenium
  module WebDriver
    module Chrome
      class Options < Chromium::Options
        KEY: "goog:chromeOptions"

        BROWSER: "chrome"

        private

        def enable_logging: (untyped browser_options) -> untyped

        def binary_path: () -> untyped
      end
    end
  end
end
