module Selenium
  module WebDriver
    module Chrome
      class Options < Chromium::Options
        KEY: String

        BROWSER: String

        private

        def enable_logging: (untyped browser_options) -> untyped

        def binary_path: () -> untyped
      end
    end
  end
end
