load("@rules_jvm_external//:defs.bzl", "artifact")
load("//java:defs.bzl", "java_library")

java_library(
    name = "k8s",
    srcs = glob(["*.java"]),
    visibility = [
        "//deploys/docker:__pkg__",
        "//java/src/org/openqa/selenium/grid/commands:__pkg__",
        "//java/src/org/openqa/selenium/grid/node/httpd:__pkg__",
        "//java/src/org/openqa/selenium/grid/node/local:__pkg__",
        "//java/test/org/openqa/selenium/grid/node/k8s:__pkg__",
    ],
    deps = [
        "//java:auto-service",
        "//java/src/org/openqa/selenium/events",
        "//java/src/org/openqa/selenium/grid/config",
        "//java/src/org/openqa/selenium/grid/data",
        "//java/src/org/openqa/selenium/grid/jmx",
        "//java/src/org/openqa/selenium/grid/log",
        "//java/src/org/openqa/selenium/grid/node",
        "//java/src/org/openqa/selenium/grid/node/config",
        "//java/src/org/openqa/selenium/grid/security",
        "//java/src/org/openqa/selenium/grid/server",
        "//java/src/org/openqa/selenium/json",
        "//java/src/org/openqa/selenium/remote",
        "//java/src/org/openqa/selenium/support",
        "@maven//:io_kubernetes_client_java_api",
        artifact("com.beust:jcommander"),
        artifact("com.google.guava:guava"),
        artifact("io.kubernetes:client-java"),
    ],
)
