// Hand-ported equivalent of the source files normally generated by
// Microsoft.Testing.Platform.MSBuild (TestingPlatformEntryPoint.cs and
// SelfRegisteredExtensions.cs).
//
// Bazel's `csharp_test` invokes csc directly and never runs MSBuild, so the
// MTP entry point + extension self-registration glue must be checked in.
// Only the NUnit hook is registered: the MSBuild and Telemetry hooks add
// nothing useful in a Bazel-driven test invocation.

internal static class MicrosoftTestingPlatformEntryPoint
{
    public static async global::System.Threading.Tasks.Task<int> Main(string[] args)
    {
        global::Microsoft.Testing.Platform.Builder.ITestApplicationBuilder builder =
            await global::Microsoft.Testing.Platform.Builder.TestApplication.CreateBuilderAsync(args);

        global::NUnit.VisualStudio.TestAdapter.TestingPlatformAdapter.TestingPlatformBuilderHook.AddExtensions(builder, args);

        using global::Microsoft.Testing.Platform.Builder.ITestApplication app = await builder.BuildAsync();
        return await app.RunAsync();
    }
}
