java_test(
    name = "web",
    labels = ["small"],
    srcs = glob(["*Test.java"]),
    deps = [
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/server/src/org/openqa/selenium/grid/server:server",
        "//java/server/src/org/openqa/selenium/grid/web:web",
        "//java/server/test/org/openqa/selenium/grid/testing:testing",
        "//third_party/java/assertj:assertj",
        "//third_party/java/guava:guava",
        "//third_party/java/junit:junit",
    ],
)
