java_test(
    name = "web",
    labels = [ "small" ],
    srcs = glob(["*.java"]),
    deps = [
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/server/src/org/openqa/selenium/grid/web:web",
        "//third_party/java/guava:guava",
        "//third_party/java/junit:junit",
    ],
)
