java_library(name = 'grid',
  srcs = glob([
    'internal/**/*.java',
    'web/**/*.java',
  ]),
  deps = [
    ':images',
    '//java/client/src/org/openqa/selenium:platform',
    '//java/client/src/org/openqa/selenium/io:io',
    '//java/client/src/org/openqa/selenium/net:net',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//java/server/src/org/openqa/grid/common:common',
    '//java/server/src/org/openqa/selenium/remote/server/log:log',
    '//java/server/src/org/openqa/selenium/server:server',
    '//third_party/java/apache-httpclient:apache-httpclient',
    '//third_party/java/gson:gson',
    '//third_party/java/guava-libraries:guava-libraries',
    '//third_party/java/jcip_annotations:jcip_annotations',
    '//third_party/java/jetty:jetty',
    '//third_party/java/jetty:jetty-for-rc',
    '//third_party/java/servlet-api:servlet-api',
    '//third_party/java/yaml:yaml',
  ],
  visibility = [
    '//java/server/src/org/openqa/grid/selenium:classes',
  ],
)

prebuilt_jar(name = 'images',
  binary_jar = ':images-zip',
)

zip(name = 'images-zip',
  srcs = glob(['images/*']),
  out = 'images.jar',
)