java_library(
    name = "docker",
    srcs = glob(["*.java"]),
    deps = [
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//third_party/java/guava:guava",
    ],
    visibility = [
    ],
)
