java_library(
    name = "json",
    srcs = glob(["*.java"]),
    deps = [
        "//java/client/src/org/openqa/selenium:core",
        "//java/client/src/org/openqa/selenium/remote:api",
        "//third_party/java/guava:guava",
    ],
    visibility = [
        "//java/client/src/org/openqa/...",
        "//java/client/test/org/openqa/...",
        "//java/server/src/org/openqa/...",
        "//java/server/test/org/openqa/...",
    ],
)
