java_library(
  name = 'opera',
  srcs = glob(['*.java']),
  deps = [
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//third_party/java/gson:gson',
    '//third_party/java/guava:guava',
  ],
  visibility = [ 'PUBLIC' ],
)
