java_library(name = 'cli',
  srcs = glob(['CliUtils.java']),
  visibility = [
    '//java/server/src/org/openqa/grid:grid',
    '//java/server/src/org/openqa/grid/common:common',
    '//java/server/src/org/openqa/grid/selenium:classes',
    '//java/server/src/org/openqa/selenium/server:server',
  ],
)

java_library(name = 'interfaces',
  srcs = glob(['GridNodeServer.java']),
  visibility = [
    '//java/server/src/org/openqa/grid:grid',
    '//java/server/src/org/openqa/grid/common:common',
    '//java/server/src/org/openqa/grid/selenium:classes',
    '//java/server/src/org/openqa/selenium/server:server',
    '//java/server/src/org/openqa/selenium/remote/server:standalone-server-lib',
  ],
)
