java_test(name = 'LargeTests',
  srcs = [
    'ScriptMutatorTest.java',
  ],
  deps = [
    '//java/client/src/com/thoughtworks/selenium/webdriven:webdriven',
    '//java/client/src/com/thoughtworks/selenium:selenium',
    '//java/client/src/org/openqa/selenium:webdriver-api',
    '//java/client/test/org/openqa/selenium/testing:test-base',
    '//third_party/java/guava-libraries:guava-libraries',
    '//third_party/java/junit:junit',
  ],
)

java_test(name = 'small-tests',
  srcs = [
    'SmallTests.java',
  ],
  deps = [
    ':tests',
    '//third_party/java/junit:junit',
  ],
  visibility = [
    '//java/client/test/org/openqa/selenium/v1:small-tests',
  ],
)

java_library(name = 'tests',
  srcs = glob(['*Test.java'], excludes = ['ScriptMutatorTest.java',]),
  deps = [
    '//java/client/src/com/thoughtworks/selenium/webdriven:emulation-api',
    '//java/client/src/com/thoughtworks/selenium/webdriven:webdriven',
    '//java/client/src/com/thoughtworks/selenium:api',
    '//java/client/src/org/openqa/selenium:webdriver-api',
    '//third_party/java/junit:junit',
  ],
)
