java_test(name = 'LargeTests',
  srcs = [
    'LargeTests.java',
    'ScriptMutatorTest.java',
    'WebDriverBackedSeleniumLargeTest.java',
  ],
  deps = [
    '//java/client/src/com/thoughtworks/selenium:leg-rc',
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/test/org/openqa/selenium/testing:test-base',
    '//third_party/java/guava:guava',
    '//third_party/java/junit:junit',
  ],
)

java_test(name = 'small-tests',
  srcs = [
    'SmallTests.java',
  ],
  deps = [
    ':tests',
    '//third_party/java/junit:junit',
  ],
  visibility = [
    '//java/client/test/org/openqa/selenium:small-tests',
  ],
)

java_test(name = 'exception-tests',
  srcs = [
    'WebDriverExceptionTest.java',
  ],
  deps = [
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//java/client/src/com/thoughtworks/selenium/webdriven:webdriven',
    '//java/client/src/com/thoughtworks/selenium/webdriven/commands:commands',
    '//third_party/java/junit:junit',
    '//third_party/java/mockito:mockito',
    '//third_party/java/guava:guava',
  ],
)

java_library(name = 'tests',
  srcs = glob(['*Test.java'], excludes = [
    'ScriptMutatorTest.java','WebDriverBackedSeleniumLargeTest.java', 'WebDriverExceptionTest.java'
  ]),
  deps = [
    '//java/client/src/com/thoughtworks/selenium:leg-rc',
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/test/org/openqa/selenium:helpers',
    '//third_party/java/guava:guava',
    '//third_party/java/junit:junit',
    '//third_party/java/mockito:mockito',
  ],
)
