module Selenium
  module WebDriver
    module Firefox
      class Service < WebDriver::Service
        DEFAULT_PORT: 4444

        DRIVER_PATH_ENV_KEY: String
        EXECUTABLE: "geckodriver"

        SHUTDOWN_SUPPORTED: false
      end
    end
  end
end
