# frozen_string_literal: true

require 'rspec/core/rake_task'
require 'steep/rake_task'

desc 'Setup everything to run tests in RubyMine'
task :update do
  cmd = [
    'bazel build @bundle//:bundle',
    '//rb:selenium-devtools',
    '//rb:selenium-webdriver',
    '//java/src/org/openqa/selenium/grid:executable-grid'
  ].join(' ')

  system cmd
end

desc 'Run unit tests'
task :unit do
  system 'bazel test --test_size_filters small //rb/...'
end

desc 'Run all integration tests in chrome'
task :spec do
  system 'bazel test --test_size_filters large //rb/...'
end

Steep::RakeTask.new do |t|
  t.check.severity_level = :error # Only output errors, hide warnings
end
