# frozen_string_literal: true

require 'rspec/core/rake_task'

desc 'Setup everything to run tests in RubyMine'
task :update do
  system 'bazel build @bundle//:bundle //rb:selenium-devtools //rb:selenium-webdriver'
end

desc 'Run unit tests'
task :unit do
  system 'bazel test --test_size_filters small //rb/...'
end

desc 'Run all integration tests in chrome'
task :spec do
  system 'bazel test --test_size_filters large //rb/...'
end
