load("//rb/spec:tests.bzl", "rb_integration_test")

filegroup(
    name = "all_srcs",
    testonly = True,
    srcs = glob(["**/*.rb"]),
    visibility = ["//rb/spec:__pkg__"],
)

[
    rb_integration_test(
        name = file[:-8],
        srcs = [file],
        browsers = [
            "safari",
            "safari-preview",
        ],
    )
    for file in glob(["*_spec.rb"])
]
