
java_library(
    name = "tracing",
    srcs = glob(["*.java"]),
    exported_deps = [
        # Required for the "register" API
        "//third_party/java/opencensus:opencensus",
        "//third_party/java/opentracing:opentracing-api",
    ],
    deps = [
        "//java/client/src/org/openqa/selenium/remote:remote",
        '//third_party/java/contrib:opentracing-tracerresolver',
        "//third_party/java/guava:guava",
        "//third_party/java/opentracing:opentracing-noop",
        "//third_party/java/opentracing:opentracing-util",
    ],
    visibility = [
        "//java/client/test/org/openqa/selenium/remote/tracing:",
        "//java/server/src/org/openqa/selenium/grid/...",
        "//java/server/test/org/openqa/selenium/grid/...",
    ],
)
