/*
 Copyright 2011 WebDriver committers
 Copyright 2011 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

#include "nsISupports.idl"
#include "wdICoordinate.idl"
#include "wdIModifierKeys.idl"
#include "wdIStatus.idl"

/**
 * Models a mouse device.
 *
 * TODO(simon): Consider replacing "coordinates" with "target" and removing the
 * coordinates interface.
 */
[scriptable, uuid(6291C63C-30B2-4C69-9212-7DEB1ED40DC4)]
interface wdIMouse : nsISupports
{
  void initialize(in wdIModifierKeys modifierKeys, [retval] out wdIStatus result);
  /**
   * Move the mouse cursor to a specified location. If x and y are specified
   * they are offsets from the "where" parameter
   */
  void move(in nsISupports target, in PRInt32 xOffset, in PRInt32 yOffset, [retval] out wdIStatus result);

  void down(in wdICoordinate where, [retval] out wdIStatus result);
  void up(in wdICoordinate where, [retval] out wdIStatus result);

  void click(in nsISupports target, [retval] out wdIStatus result);
  void doubleClick(in nsISupports where, [retval] out wdIStatus result);
  void contextClick(in wdICoordinate where, [retval] out wdIStatus result);
};
