#include "nsISupports.idl"

/**
 * Modifier keys structure for use in synthetic mouse calls
 */
[scriptable, uuid(2E4B69B9-21FE-48ad-A2F6-AB355D6D2FCE)]
interface wdIModifierKeys : nsISupports
{
  void isShiftPressed([retval] out boolean isPressed);
  void isControlPressed([retval] out boolean isPressed);
  void isAltPressed([retval] out boolean isPressed);
  void isMetaPressed([retval] out boolean isPressed);

  void setShiftPressed(in boolean isPressed);
  void setControlPressed(in boolean isPressed);
  void setAltPressed(in boolean isPressed);
  void setMetaPressed(in boolean isPressed);
};
