
java_binary(name = 'rc',
  main_class = "org.openqa.selenium.server.SeleniumServer",
  deps = [
    ':server',
  ],
)

java_library(name = 'server',
  srcs = glob(['**/*.java'], excludes = ['security/*.java']),
  deps = [
    ':resources',
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/src/org/openqa/selenium/browserlaunchers/locators:locators',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//java/client/src/com/thoughtworks/selenium:api',
    '//java/client/src/com/thoughtworks/selenium/webdriven:webdriven',
    '//java/server/src/cybervillains:cybervillains',
    '//java/server/src/org/openqa/selenium/remote/server:server',
    '//java/server/src/org/openqa/selenium/remote/server:sessions',
    '//java/server/src/org/openqa/selenium/remote/server/log:log',
    '//java/server/src/org/openqa/grid:grid',
    ':selenium-core',
    '//third_party/java/commons-logging:commons-logging',
    '//third_party/java/guava:guava',
    '//third_party/java/gson:gson',
    '//third_party/java/jetty:jetty-for-rc',
    '//third_party/java/servlet:servlet-api',
  ],
  visibility = [
    '//java/server/src/org/openqa/grid:grid',
    '//java/server/src/org/openqa/grid/selenium:classes',
    '//java/server/test/org/openqa/grid/...',
  ],
)

prebuilt_jar(name = 'selenium-core',
  binary_jar = '//javascript/selenium-core:selenium-core',
)

prebuilt_jar(name = 'resources',
  binary_jar = ':resources-zip',
)

zip_file(name = 'resources-zip',
  out = 'resources-sources.jar',
  srcs = [
    'VERSION.txt',
  ] + glob([
    'customProfileDirCUSTFF/**/*',
    'customProfileDirCUSTFFCHROME/**/*',
    'hudsuckr/*',
    'konqueror/*',
    'opera/*',
    'sslSupport/*',
  ]),
)
