
java_binary(name = 'rc',
  main_class = "org.openqa.selenium.server.SeleniumServer",
  deps = [
    ':server',
  ],
)

java_library(name = 'server',
  srcs = glob(['**/*.java'], excludes = ['security/*.java']),
  deps = [
    ':resources',
    '//java/client/src/org/openqa/selenium:codecs',
    '//java/client/src/org/openqa/selenium:webdriver-api',
    '//java/client/src/org/openqa/selenium/browserlaunchers/locators:locators',
    '//java/client/src/org/openqa/selenium/io:io',
    '//java/client/src/org/openqa/selenium/net:net',
    '//java/client/src/org/openqa/selenium/os:os',
    '//java/client/src/org/openqa/selenium/remote:api',
    '//java/client/src/org/openqa/selenium/remote:capabilities',
    '//java/client/src/com/thoughtworks/selenium:api',
    '//java/client/src/com/thoughtworks/selenium/webdriven:webdriven',
    '//java/server/src/cybervillains:cybervillains',
    '//java/server/src/org/openqa/selenium/remote/server:server',
    '//java/server/src/org/openqa/selenium/remote/server:sessions',
    '//java/server/src/org/openqa/selenium/remote/server/log:log',
    '//third_party/java/commons-logging:commons-logging',
    '//third_party/java/guava-libraries:guava-libraries',
    '//third_party/java/gson:gson',
    '//third_party/java/jetty:jetty-for-rc',
  ],
  visibility = [
    '//java/server/src/org/openqa/grid:grid',
    '//java/server/src/org/openqa/grid/common:common',
    '//java/server/src/org/openqa/grid/selenium:classes',
  ],
)

prebuilt_jar(name = 'resources',
  binary_jar = ':resources-zip',
)

zip(name = 'resources-zip',
  out = 'resources.jar',
  srcs = [
    'VERSION.txt',
  ] + glob([
    'customProfileDirCUSTFF/**/*',
    'customProfileDirCUSTFFCHROME/**/*',
    'hudsuckr/*',
    'konqueror/*',
    'opera/*',
    'sslSupport/*',
  ]),
)
