java_library(name = 'locators',
  srcs = glob(['*.java']),
  deps = [
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//third_party/java/guava:guava',
  ],
  visibility = [
    '//java/client/src/org/openqa/selenium/safari:safari',
    '//java/client/test/org/openqa/selenium:helpers',
    '//java/server/src/org/openqa/selenium/server:server',
  ],
)
