java_library(name = 'locators',
  srcs = glob(['*.java']),
  deps = [
    '//java/client/src/org/openqa/selenium/io:io',
    '//java/client/src/org/openqa/selenium/os:os',
    '//java/client/src/org/openqa/selenium/remote:capabilities',
    '//java/client/src/org/openqa/selenium:platform',
    '//third_party/java/guava:guava',
  ],
  visibility = [
    '//java/client/src/org/openqa/selenium/safari:safari',
    '//java/client/test/org/openqa/selenium:helpers',
    '//java/server/src/org/openqa/selenium/server:server',
  ],
)
