<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <AssemblyName>WebDriver.Remote.Tests</AssemblyName>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
    <EnableMicrosoftTestingPlatform>true</EnableMicrosoftTestingPlatform>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <EnableNUnitRunner>true</EnableNUnitRunner>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\webdriver\Selenium.WebDriver.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="WebDriver.Remote.Tests.nunit">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Import Project="..\..\.paket\Paket.Restore.targets" />

</Project>
