java_library(
    name = "web",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//java/client/src/org/openqa/selenium/remote:remote",
    ],
    deps = [
        "//third_party/java/guava:guava",
    ],
    visibility = [
        "//java/server/src/org/openqa/selenium/grid/...",
        "//java/server/src/org/openqa/selenium/remote/server/...",
        "//java/server/test/org/openqa/...",
    ],
)
