# BUILD FILE SYNTAX: SKYLARK

java_library(
    name = "web",
    srcs = glob(["*.java"]),
    deps = [
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//third_party/java/guava:guava",
    ],
    provided_deps = [
        "//third_party/java/servlet:javax.servlet-api",
    ],
    visibility = [
        "//java/server/...",
    ]
)