/* AUTO GENERATED - DO NOT EDIT BY HAND */
#ifndef ATOMS_H__
#define ATOMS_H__

#include <stddef.h>  // For wchar_t.

namespace webdriver {

const wchar_t* const CLEAR[] = {
    L"function(){var g=this;\nfunction i(a){var b=typeof a;if(b==\"object\")i",
    L"f(a){if(a instanceof Array)return\"array\";else if(a instanceof Object)",
    L"return b;var c=Object.prototype.toString.call(a);if(c==\"[object Window",
    L"]\")return\"object\";if(c==\"[object Array]\"||typeof a.length==\"numbe",
    L"r\"&&typeof a.splice!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"u",
    L"ndefined\"&&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(c==",
    L"\"[object Function]\"||typeof a.call!=\"undefined\"&&typeof a.propertyI",
    L"sEnumerable!=\"undefined\"&&!a.propertyIsEnumerable(\"call\"))return\"f",
    L"unction\"}else return\"null\";else if(b==\n\"function\"&&typeof a.call=",
    L"=\"undefined\")return\"object\";return b}function k(a){return i(a)==\"f",
    L"unction\"}function l(a){a=i(a);return a==\"object\"||a==\"array\"||a==",
    L"\"function\"}Math.floor(Math.random()*2147483648).toString(36);function",
    L" m(a,b){function c(){}c.prototype=b.prototype;a.g=b.prototype;a.prototy",
    L"pe=new c};function p(a){this.stack=Error().stack||\"\";if(a)this.messag",
    L"e=String(a)}m(p,Error);p.prototype.name=\"CustomError\";function q(a,b)",
    L"{p.call(this,b);this.code=a;this.name=s[a]||s[13]}m(q,p);var s,ba={NoSu",
    L"chElementError:7,NoSuchFrameError:8,UnknownCommandError:9,StaleElementR",
    L"eferenceError:10,ElementNotVisibleError:11,InvalidElementStateError:12,",
    L"UnknownError:13,ElementNotSelectableError:15,XPathLookupError:19,NoSuch",
    L"WindowError:23,InvalidCookieDomainError:24,UnableToSetCookieError:25,Mo",
    L"dalDialogOpenedError:26,ModalDialogOpenError:27,ScriptTimeoutError:28},",
    L"ca={};for(var da in ba)ca[ba[da]]=da;s=ca;\nq.prototype.toString=functi",
    L"on(){return\"[\"+this.name+\"] \"+this.message};function ea(a){for(var ",
    L"b=1;b<arguments.length;b++){var c=String(arguments[b]).replace(/\\$/g,",
    L"\"$$$$\");a=a.replace(/\\%s/,c)}return a}function t(a){return a.replace",
    L"(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\")}function u(a,b){if(a<b)return-1;els",
    L"e if(a>b)return 1;return 0}var fa={};function ga(a){return fa[a]||(fa[a",
    L"]=String(a).replace(/\\-([a-z])/g,function(b,c){return c.toUpperCase()}",
    L"))};function v(a,b){b.unshift(a);p.call(this,ea.apply(null,b));b.shift(",
    L");this.j=a}m(v,p);v.prototype.name=\"AssertionError\";function ha(a,b){",
    L"if(!a){var c=Array.prototype.slice.call(arguments,2),d=\"Assertion fail",
    L"ed\";if(b){d+=\": \"+b;var e=c}throw new v(\"\"+d,e||[]);}return a};var",
    L" w=Array.prototype,x=w.indexOf?function(a,b,c){ha(a.length!=null);retur",
    L"n w.indexOf.call(a,b,c)}:function(a,b,c){c=c==null?0:c<0?Math.max(0,a.l",
    L"ength+c):c;if(typeof a==\"string\"){if(typeof b!=\"string\"||b.length!=",
    L"1)return-1;return a.indexOf(b,c)}for(c=c;c<a.length;c++)if(c in a&&a[c]",
    L"===b)return c;return-1},ia=w.some?function(a,b,c){ha(a.length!=null);re",
    L"turn w.some.call(a,b,c)}:function(a,b,c){var d=a.length,e=typeof a==\"s",
    L"tring\"?a.split(\"\"):a;for(var f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,",
    L"a))return true;\nreturn false};var y,A,B,C;function ja(){return g.navig",
    L"ator?g.navigator.userAgent:null}C=B=A=y=false;var D;if(D=ja()){var ka=g",
    L".navigator;y=D.indexOf(\"Opera\")==0;A=!y&&D.indexOf(\"MSIE\")!=-1;B=!y",
    L"&&D.indexOf(\"WebKit\")!=-1;C=!y&&!B&&ka.product==\"Gecko\"}var la=y,E=",
    L"A,ma=C,na=B,F;\na:{var G=\"\",H;if(la&&g.opera){var I=g.opera.version;G",
    L"=typeof I==\"function\"?I():I}else{if(ma)H=/rv\\:([^\\);]+)(\\)|;)/;els",
    L"e if(E)H=/MSIE\\s+([^\\);]+)(\\)|;)/;else if(na)H=/WebKit\\/(\\S+)/;if(",
    L"H){var oa=H.exec(ja());G=oa?oa[1]:\"\"}}if(E){var J,pa=g.document;J=pa?",
    L"pa.documentMode:undefined;if(J>parseFloat(G)){F=String(J);break a}}F=G}",
    L"var qa={};\nfunction K(a){var b;if(!(b=qa[a])){b=0;var c=t(String(F)).s",
    L"plit(\".\"),d=t(String(a)).split(\".\"),e=Math.max(c.length,d.length);f",
    L"or(var f=0;b==0&&f<e;f++){var h=c[f]||\"\",j=d[f]||\"\",r=RegExp(\"(",
    L"\\\\d*)(\\\\D*)\",\"g\"),z=RegExp(\"(\\\\d*)(\\\\D*)\",\"g\");do{var n=",
    L"r.exec(h)||[\"\",\"\",\"\"],o=z.exec(j)||[\"\",\"\",\"\"];if(n[0].lengt",
    L"h==0&&o[0].length==0)break;b=u(n[1].length==0?0:parseInt(n[1],10),o[1].",
    L"length==0?0:parseInt(o[1],10))||u(n[2].length==0,o[2].length==0)||u(n[2",
    L"],o[2])}while(b==0)}b=qa[a]=b>=0}return b};!E||K(\"9\");E&&K(\"9\");fun",
    L"ction L(a,b){this.width=a;this.height=b}L.prototype.toString=function()",
    L"{return\"(\"+this.width+\" x \"+this.height+\")\"};L.prototype.floor=fu",
    L"nction(){this.width=Math.floor(this.width);this.height=Math.floor(this.",
    L"height);return this};function M(a){return a?a.parentWindow||a.defaultVi",
    L"ew:window}function N(a){return a.nodeType==9?a:a.ownerDocument||a.docum",
    L"ent}function ra(a,b){var c=[];return sa(a,b,c,true)?c[0]:undefined}func",
    L"tion sa(a,b,c,d){if(a!=null){var e=0;for(var f;f=a.childNodes[e];e++){i",
    L"f(b(f)){c.push(f);if(d)return true}if(sa(f,b,c,d))return true}}return f",
    L"alse}function ta(a,b,c,d){if(!c)a=a.parentNode;c=d==null;for(var e=0;a&",
    L"&(c||e<=d);){if(b(a))return a;a=a.parentNode;e++}return null};function ",
    L"ua(a,b){try{var c;if(typeof b.selectSingleNode!=\"undefined\"){var d=N(",
    L"b);typeof d.setProperty!=\"undefined\"&&d.setProperty(\"SelectionLangua",
    L"ge\",\"XPath\");c=b.selectSingleNode(a)}else if(document.implementation",
    L".hasFeature(\"XPath\",\"3.0\")){d=N(b);var e=d.createNSResolver(d.docum",
    L"entElement);c=d.evaluate(a,b,e,XPathResult.FIRST_ORDERED_NODE_TYPE,null",
    L").singleNodeValue}else c=null}catch(f){return null}if(!c)return null;if",
    L"(c.nodeType!=1)throw Error(\"Returned node is not an element: \"+a);ret",
    L"urn c};var O=\"StopIteration\"in g?g.StopIteration:Error(\"StopIteratio",
    L"n\");function va(){}va.prototype.next=function(){throw O;};function P(a",
    L",b,c,d,e){this.a=!!b;a&&Q(this,a,d);this.d=e!=undefined?e:this.c||0;if(",
    L"this.a)this.d*=-1;this.f=!c}m(P,va);P.prototype.b=null;P.prototype.c=0;",
    L"P.prototype.e=false;function Q(a,b,c,d){if(a.b=b)a.c=typeof c==\"number",
    L"\"?c:a.b.nodeType!=1?0:a.a?-1:1;if(typeof d==\"number\")a.d=d}\nP.proto",
    L"type.next=function(){var a;if(this.e){if(!this.b||this.f&&this.d==0)thr",
    L"ow O;a=this.b;var b=this.a?-1:1;if(this.c==b){var c=this.a?a.lastChild:",
    L"a.firstChild;c?Q(this,c):Q(this,a,b*-1)}else(c=this.a?a.previousSibling",
    L":a.nextSibling)?Q(this,c):Q(this,a.parentNode,b*-1);this.d+=this.c*(thi",
    L"s.a?-1:1)}else this.e=true;a=this.b;if(!this.b)throw O;return a};\nP.pr",
    L"ototype.splice=function(){var a=this.b,b=this.a?1:-1;if(this.c==b){this",
    L".c=b*-1;this.d+=this.c*(this.a?-1:1)}this.a=!this.a;P.prototype.next.ca",
    L"ll(this);this.a=!this.a;b=arguments[0];var c=i(b);b=c==\"array\"||c==\"",
    L"object\"&&typeof b.length==\"number\"?arguments[0]:arguments;for(c=b.le",
    L"ngth-1;c>=0;c--)a.parentNode&&a.parentNode.insertBefore(b[c],a.nextSibl",
    L"ing);a&&a.parentNode&&a.parentNode.removeChild(a)};function R(a,b,c,d){",
    L"P.call(this,a,b,c,null,d)}m(R,P);R.prototype.next=function(){do R.g.nex",
    L"t.call(this);while(this.c==-1);return this.b};function wa(a,b){var c=N(",
    L"a);if(c.defaultView&&c.defaultView.getComputedStyle)if(c=c.defaultView.",
    L"getComputedStyle(a,null))return c[b]||c.getPropertyValue(b);return\"\"}",
    L";function S(a,b){return!!a&&a.nodeType==1&&(!b||a.tagName.toUpperCase()",
    L"==b)}\nvar xa={\"class\":\"className\",readonly:\"readOnly\"},ya=[\"asy",
    L"nc\",\"autofocus\",\"autoplay\",\"checked\",\"compact\",\"complete\",\"",
    L"controls\",\"declare\",\"defaultchecked\",\"defaultselected\",\"defer\"",
    L",\"disabled\",\"draggable\",\"ended\",\"formnovalidate\",\"hidden\",\"i",
    L"ndeterminate\",\"iscontenteditable\",\"ismap\",\"itemscope\",\"loop\",",
    L"\"multiple\",\"muted\",\"nohref\",\"noresize\",\"noshade\",\"novalidate",
    L"\",\"nowrap\",\"open\",\"paused\",\"pubdate\",\"readonly\",\"required\"",
    L",\"reversed\",\"scoped\",\"seamless\",\"seeking\",\"selected\",\"spellc",
    L"heck\",\"truespeed\",\"willvalidate\"];\nfunction za(a,b){if(8==a.nodeT",
    L"ype)return null;b=b.toLowerCase();if(b==\"style\"){var c=t(a.style.cssT",
    L"ext).toLowerCase();return c.charAt(c.length-1)==\";\"?c:c+\";\"}c=a.get",
    L"AttributeNode(b);if(E)if(!c&&K(8)&&x(ya,b)>=0)c=a[b];if(!c)return null;",
    L"if(x(ya,b)>=0)return E&&c.value==\"false\"?null:\"true\";return c.speci",
    L"fied?c.value:null}var Aa=[\"BUTTON\",\"INPUT\",\"OPTGROUP\",\"OPTION\",",
    L"\"SELECT\",\"TEXTAREA\"];\nfunction Ba(a){var b=a.tagName.toUpperCase()",
    L";if(!(x(Aa,b)>=0))return true;if(za(a,\"disabled\"))return false;if(a.p",
    L"arentNode&&a.parentNode.nodeType==1&&\"OPTGROUP\"==b||\"OPTION\"==b)ret",
    L"urn Ba(a.parentNode);return true}function T(a){for(a=a.parentNode;a&&a.",
    L"nodeType!=1&&a.nodeType!=9&&a.nodeType!=11;)a=a.parentNode;return S(a)?",
    L"a:null}function U(a,b){b=ga(String(b));return wa(a,b)||Ca(a,b)}\nfuncti",
    L"on Ca(a,b){var c=(a.currentStyle||a.style)[b];if(c!=\"inherit\")return ",
    L"c!==undefined?c:null;return(c=T(a))?Ca(c,b):null}\nfunction Da(a){if(k(",
    L"a.getBBox))return a.getBBox();var b;var c=la&&!K(\"10\");if((wa(a,\"dis",
    L"play\")||(a.currentStyle?a.currentStyle.display:null)||a.style.display)",
    L"!=\"none\")b=c?new L(a.offsetWidth||a.clientWidth,a.offsetHeight||a.cli",
    L"entHeight):new L(a.offsetWidth,a.offsetHeight);else{b=a.style;var d=b.d",
    L"isplay,e=b.visibility,f=b.position;b.visibility=\"hidden\";b.position=",
    L"\"absolute\";b.display=\"inline\";if(c){c=a.offsetWidth||a.clientWidth;",
    L"a=a.offsetHeight||a.clientHeight}else{c=a.offsetWidth;a=a.offsetHeight}",
    L"b.display=\nd;b.position=f;b.visibility=e;b=new L(c,a)}return b}\nfunct",
    L"ion V(a){function b(e){if(U(e,\"display\")==\"none\")return false;e=T(e",
    L");return!e||b(e)}function c(e){var f=Da(e);if(f.height>0&&f.width>0)ret",
    L"urn true;if(e.innerText||e.textContent)return true;return na&&ia(e.chil",
    L"dNodes,function(h){return S(h)&&c(h)})}if(!S(a))throw Error(\"Argument ",
    L"to isShown must be of type Element\");if(S(a,\"TITLE\"))return M(N(a))=",
    L"=g;if(S(a,\"OPTION\")||S(a,\"OPTGROUP\")){var d=ta(a,function(e){return",
    L" S(e,\"SELECT\")});return!!d&&V(d)}if(S(a,\"MAP\")){if(!a.name)return f",
    L"alse;d=N(a);d=d.evaluate?\nua('/descendant::*[@usemap = \"#'+a.name+'\"",
    L"]',d):ra(d,function(e){return S(e)&&za(e,\"usemap\")==\"#\"+a.name});re",
    L"turn!!d&&V(d)}if(S(a,\"AREA\")){d=ta(a,function(e){return S(e,\"MAP\")}",
    L");return!!d&&V(d)}if(S(a,\"INPUT\")&&a.type.toLowerCase()==\"hidden\")r",
    L"eturn false;if(U(a,\"visibility\")==\"hidden\")return false;if(!b(a))re",
    L"turn false;if(Ea(a)==0)return false;if(!c(a))return false;return true}S",
    L"tring.fromCharCode(160);\nfunction Ea(a){if(E){if(U(a,\"position\")==\"",
    L"relative\")return 1;a=U(a,\"filter\");return(a=a.match(/^alpha\\(opacit",
    L"y=(\\d*)\\)/)||a.match(/^progid:DXImageTransform.Microsoft.Alpha\\(Opac",
    L"ity=(\\d*)\\)/))?Number(a[1])/100:1}else return Fa(a)}function Fa(a){va",
    L"r b=1,c=U(a,\"opacity\");if(c)b=Number(c);if(a=T(a))b*=Fa(a);return b};",
    L"var Ga=E?1:0,Ha=[\"dragstart\",\"dragexit\",\"mouseover\",\"mouseout\"]",
    L";\nfunction W(a,b,c){var d=N(a),e=M(d),f=c||{};c=f.x||0;var h=f.y||0,j=",
    L"f.button||Ga,r=f.bubble||true,z=null;if(x(Ha,b)>=0)z=f.related||null;va",
    L"r n=!!f.alt,o=!!f.control,aa=!!f.shift;f=!!f.meta;if(a.fireEvent&&d&&d.",
    L"createEventObject){a=d.createEventObject();a.altKey=n;a.h=o;a.metaKey=f",
    L";a.shiftKey=aa;a.clientX=c;a.clientY=h;a.button=j;a.relatedTarget=z}els",
    L"e{a=d.createEvent(\"MouseEvents\");if(a.initMouseEvent)a.initMouseEvent",
    L"(b,r,true,e,1,0,0,c,h,o,n,aa,f,j,z);else{a.initEvent(b,r,true);a.shiftK",
    L"ey=aa;a.metaKey=\nf;a.altKey=n;a.ctrlKey=o;a.button=j}}return a}functio",
    L"n Ia(a,b,c){var d=N(a);a=M(d);var e=c||{};c=e.keyCode||0;var f=e.charCo",
    L"de||0,h=!!e.alt,j=!!e.ctrl,r=!!e.shift;e=!!e.meta;if(ma){d=d.createEven",
    L"t(\"KeyboardEvent\");d.initKeyEvent(b,true,true,a,j,h,r,e,c,f)}else{if(",
    L"E)d=d.createEventObject();else{d=d.createEvent(\"Events\");d.initEvent(",
    L"b,true,true);d.charCode=f}d.keyCode=c;d.altKey=h;d.ctrlKey=j;d.metaKey=",
    L"e;d.shiftKey=r}return d}\nfunction Ja(a,b,c){var d=N(a),e=c||{};c=e.bub",
    L"ble!==false;var f=!!e.alt,h=!!e.control,j=!!e.shift;e=!!e.meta;if(a.fir",
    L"eEvent&&d&&d.createEventObject){a=d.createEventObject();a.altKey=f;a.i=",
    L"h;a.metaKey=e;a.shiftKey=j}else{a=d.createEvent(\"HTMLEvents\");a.initE",
    L"vent(b,c,true);a.shiftKey=j;a.metaKey=e;a.altKey=f;a.ctrlKey=h}return a",
    L"}var X={};X.click=W;X.keydown=Ia;X.keypress=Ia;X.keyup=Ia;X.mousedown=W",
    L";X.mousemove=W;X.mouseout=W;X.mouseover=W;X.mouseup=W;function Ka(a){if",
    L"(!V(a))throw new q(11,\"Element is not currently visible and may not be",
    L" manipulated\");};function La(a){var b;if(S(a,\"TEXTAREA\"))b=true;else",
    L" if(S(a,\"INPUT\")){b=a.type.toLowerCase();b=b==\"text\"||b==\"password",
    L"\"||b==\"email\"||b==\"search\"}else b=false;if(b){if(a[xa.readOnly||\"",
    L"readOnly\"])throw new q(12,\"Element is readonly and may not be cleared",
    L".\");if(a.value!=\"\"){Ka(a);if(!Ba(a))throw new q(12,\"Element is not ",
    L"currently enabled and may not be manipulated\");b=N(a).activeElement;Ka",
    L"(a);if(a!=b){if(b){if(k(b.blur)||E&&l(b.blur))b.blur();E&&!K(8)&&M(N(a)",
    L").focus()}if(k(a.focus)||E&&l(a.focus))a.focus()}a.value=\n\"\";b=(X.ch",
    L"ange||Ja)(a,\"change\",void 0);if(k(a.fireEvent)||l(a.fireEvent)){try{M",
    L"(N(a)).event=b}catch(c){}a.fireEvent(\"onchange\",b)}else a.dispatchEve",
    L"nt(b)}}}var Y=\"_\".split(\".\"),Z=g;!(Y[0]in Z)&&Z.execScript&&Z.execS",
    L"cript(\"var \"+Y[0]);for(var $;Y.length&&($=Y.shift());)if(!Y.length&&L",
    L"a!==undefined)Z[$]=La;else Z=Z[$]?Z[$]:Z[$]={};; return _.apply(null,ar",
    L"guments);}",
    NULL
};

const wchar_t* const FIND_ELEMENT[] = {
    L"function(){var h=this;\nfunction i(a){var b=typeof a;if(b==\"object\")i",
    L"f(a){if(a instanceof Array)return\"array\";else if(a instanceof Object)",
    L"return b;var c=Object.prototype.toString.call(a);if(c==\"[object Window",
    L"]\")return\"object\";if(c==\"[object Array]\"||typeof a.length==\"numbe",
    L"r\"&&typeof a.splice!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"u",
    L"ndefined\"&&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(c==",
    L"\"[object Function]\"||typeof a.call!=\"undefined\"&&typeof a.propertyI",
    L"sEnumerable!=\"undefined\"&&!a.propertyIsEnumerable(\"call\"))return\"f",
    L"unction\"}else return\"null\";else if(b==\n\"function\"&&typeof a.call=",
    L"=\"undefined\")return\"object\";return b}function j(a){return typeof a=",
    L"=\"string\"}function k(a){return i(a)==\"function\"}function aa(a){a=i(",
    L"a);return a==\"object\"||a==\"array\"||a==\"function\"}function l(a,b){",
    L"function c(){}c.prototype=b.prototype;a.l=b.prototype;a.prototype=new c",
    L"};function m(a){this.stack=Error().stack||\"\";if(a)this.message=String",
    L"(a)}l(m,Error);m.prototype.name=\"CustomError\";function ba(a){for(var ",
    L"b=1;b<arguments.length;b++){var c=String(arguments[b]).replace(/\\$/g,",
    L"\"$$$$\");a=a.replace(/\\%s/,c)}return a}function n(a){return a.replace",
    L"(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\")}function o(a,b){if(a<b)return-1;els",
    L"e if(a>b)return 1;return 0}var ca={};function da(a){return ca[a]||(ca[a",
    L"]=String(a).replace(/\\-([a-z])/g,function(b,c){return c.toUpperCase()}",
    L"))};function p(a,b){b.unshift(a);m.call(this,ba.apply(null,b));b.shift(",
    L");this.m=a}l(p,m);p.prototype.name=\"AssertionError\";function q(a,b){i",
    L"f(!a){var c=Array.prototype.slice.call(arguments,2),d=\"Assertion faile",
    L"d\";if(b){d+=\": \"+b;var e=c}throw new p(\"\"+d,e||[]);}return a};var ",
    L"r=Array.prototype,s=r.indexOf?function(a,b,c){q(a.length!=null);return ",
    L"r.indexOf.call(a,b,c)}:function(a,b,c){c=c==null?0:c<0?Math.max(0,a.len",
    L"gth+c):c;if(j(a)){if(!j(b)||b.length!=1)return-1;return a.indexOf(b,c)}",
    L"for(c=c;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ea=r.forE",
    L"ach?function(a,b,c){q(a.length!=null);r.forEach.call(a,b,c)}:function(a",
    L",b,c){var d=a.length,e=j(a)?a.split(\"\"):a;for(var f=0;f<d;f++)f in e&",
    L"&b.call(c,e[f],f,a)},u=r.filter?function(a,b,c){q(a.length!=null);retur",
    L"n r.filter.call(a,\nb,c)}:function(a,b,c){var d=a.length,e=[],f=0,g=j(a",
    L")?a.split(\"\"):a;for(var t=0;t<d;t++)if(t in g){var I=g[t];if(b.call(c",
    L",I,t,a))e[f++]=I}return e},fa=r.map?function(a,b,c){q(a.length!=null);r",
    L"eturn r.map.call(a,b,c)}:function(a,b,c){var d=a.length,e=Array(d),f=j(",
    L"a)?a.split(\"\"):a;for(var g=0;g<d;g++)if(g in f)e[g]=b.call(c,f[g],g,a",
    L");return e},ga=r.some?function(a,b,c){q(a.length!=null);return r.some.c",
    L"all(a,b,c)}:function(a,b,c){var d=a.length,e=j(a)?a.split(\"\"):a;for(v",
    L"ar f=0;f<d;f++)if(f in e&&b.call(c,\ne[f],f,a))return true;return false",
    L"};function v(a,b,c){a:{var d=a.length,e=j(a)?a.split(\"\"):a;for(var f=",
    L"0;f<d;f++)if(f in e&&b.call(c,e[f],f,a)){b=f;break a}b=-1}return b<0?nu",
    L"ll:j(a)?a.charAt(b):a[b]};var w,x,y,z;function ha(){return h.navigator?",
    L"h.navigator.userAgent:null}z=y=x=w=false;var C;if(C=ha()){var ia=h.navi",
    L"gator;w=C.indexOf(\"Opera\")==0;x=!w&&C.indexOf(\"MSIE\")!=-1;y=!w&&C.i",
    L"ndexOf(\"WebKit\")!=-1;z=!w&&!y&&ia.product==\"Gecko\"}var ja=w,D=x,ka=",
    L"z,E=y,F;\na:{var G=\"\",H;if(ja&&h.opera){var J=h.opera.version;G=typeo",
    L"f J==\"function\"?J():J}else{if(ka)H=/rv\\:([^\\);]+)(\\)|;)/;else if(D",
    L")H=/MSIE\\s+([^\\);]+)(\\)|;)/;else if(E)H=/WebKit\\/(\\S+)/;if(H){var ",
    L"la=H.exec(ha());G=la?la[1]:\"\"}}if(D){var ma,na=h.document;ma=na?na.do",
    L"cumentMode:undefined;if(ma>parseFloat(G)){F=String(ma);break a}}F=G}var",
    L" oa={};\nfunction K(a){var b;if(!(b=oa[a])){b=0;var c=n(String(F)).spli",
    L"t(\".\"),d=n(String(a)).split(\".\"),e=Math.max(c.length,d.length);for(",
    L"var f=0;b==0&&f<e;f++){var g=c[f]||\"\",t=d[f]||\"\",I=RegExp(\"(\\\\d*",
    L")(\\\\D*)\",\"g\"),Ka=RegExp(\"(\\\\d*)(\\\\D*)\",\"g\");do{var A=I.exe",
    L"c(g)||[\"\",\"\",\"\"],B=Ka.exec(t)||[\"\",\"\",\"\"];if(A[0].length==0",
    L"&&B[0].length==0)break;b=o(A[1].length==0?0:parseInt(A[1],10),B[1].leng",
    L"th==0?0:parseInt(B[1],10))||o(A[2].length==0,B[2].length==0)||o(A[2],B[",
    L"2])}while(b==0)}b=oa[a]=b>=0}return b};var pa;!D||K(\"9\");D&&K(\"9\");",
    L"function L(a,b){this.width=a;this.height=b}L.prototype.toString=functio",
    L"n(){return\"(\"+this.width+\" x \"+this.height+\")\"};function M(a){ret",
    L"urn a?new qa(N(a)):pa||(pa=new qa)}function ra(a,b){if(a.contains&&b.no",
    L"deType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPositio",
    L"n!=\"undefined\")return a==b||Boolean(a.compareDocumentPosition(b)&16);",
    L"for(;b&&a!=b;)b=b.parentNode;return b==a}function N(a){return a.nodeTyp",
    L"e==9?a:a.ownerDocument||a.document}function sa(a,b){var c=[];return ta(",
    L"a,b,c,true)?c[0]:undefined}\nfunction ta(a,b,c,d){if(a!=null){var e=0;f",
    L"or(var f;f=a.childNodes[e];e++){if(b(f)){c.push(f);if(d)return true}if(",
    L"ta(f,b,c,d))return true}}return false}function ua(a,b,c,d){if(!c)a=a.pa",
    L"rentNode;c=d==null;for(var e=0;a&&(c||e<=d);){if(b(a))return a;a=a.pare",
    L"ntNode;e++}return null}function qa(a){this.g=a||h.document||document}\n",
    L"function O(a,b,c,d){a=d||a.g;b=b&&b!=\"*\"?b.toUpperCase():\"\";if(a.qu",
    L"erySelectorAll&&a.querySelector&&(!E||document.compatMode==\"CSS1Compat",
    L"\"||K(\"528\"))&&(b||c))c=a.querySelectorAll(b+(c?\".\"+c:\"\"));else i",
    L"f(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={}",
    L";var e=0,f=0;for(var g;g=a[f];f++)if(b==g.nodeName)d[e++]=g;d.length=e;",
    L"c=d}else c=a}else{a=a.getElementsByTagName(b||\"*\");if(c){d={};e=0;for",
    L"(f=0;g=a[f];f++){b=g.className;if(typeof b.split==\"function\"&&s(b.spl",
    L"it(/\\s+/),c)>=0)d[e++]=\ng}d.length=e;c=d}else c=a}return c}qa.prototy",
    L"pe.contains=ra;var va={};va.b=function(a,b){if(!a)throw Error(\"No clas",
    L"s name specified\");a=n(a);if(a.split(/\\s+/).length>1)throw Error(\"Co",
    L"mpound class names not permitted\");var c=O(M(b),\"*\",a,b);return c.le",
    L"ngth?c[0]:null};va.e=function(a,b){if(!a)throw Error(\"No class name sp",
    L"ecified\");a=n(a);if(a.split(/\\s+/).length>1)throw Error(\"Compound cl",
    L"ass names not permitted\");return O(M(b),\"*\",a,b)};var wa={};wa.b=fun",
    L"ction(a,b){if(!k(b.querySelector)&&D&&K(8)&&!aa(b.querySelector))throw ",
    L"Error(\"CSS selection is not supported\");if(!a)throw Error(\"No select",
    L"or specified\");if(a.split(/,/).length>1)throw Error(\"Compound selecto",
    L"rs not permitted\");a=n(a);var c=b.querySelector(a);return c&&c.nodeTyp",
    L"e==1?c:null};\nwa.e=function(a,b){if(!k(b.querySelectorAll)&&D&&K(8)&&!",
    L"aa(b.querySelector))throw Error(\"CSS selection is not supported\");if(",
    L"!a)throw Error(\"No selector specified\");if(a.split(/,/).length>1)thro",
    L"w Error(\"Compound selectors not permitted\");a=n(a);return b.querySele",
    L"ctorAll(a)};function xa(a,b){if(typeof a.selectNodes!=\"undefined\"){va",
    L"r c=N(a);typeof c.setProperty!=\"undefined\"&&c.setProperty(\"Selection",
    L"Language\",\"XPath\");return a.selectNodes(b)}else if(document.implemen",
    L"tation.hasFeature(\"XPath\",\"3.0\")){c=N(a);var d=c.createNSResolver(c",
    L".documentElement);c=c.evaluate(b,a,d,XPathResult.ORDERED_NODE_SNAPSHOT_",
    L"TYPE,null);d=[];var e=c.snapshotLength;for(var f=0;f<e;f++)d.push(c.sna",
    L"pshotItem(f));return d}else return[]};var P={};P.b=function(a,b){try{va",
    L"r c;if(typeof b.selectSingleNode!=\"undefined\"){var d=N(b);typeof d.se",
    L"tProperty!=\"undefined\"&&d.setProperty(\"SelectionLanguage\",\"XPath\"",
    L");c=b.selectSingleNode(a)}else if(document.implementation.hasFeature(\"",
    L"XPath\",\"3.0\")){d=N(b);var e=d.createNSResolver(d.documentElement);c=",
    L"d.evaluate(a,b,e,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeVa",
    L"lue}else c=null}catch(f){return null}if(!c)return null;if(c.nodeType!=1",
    L")throw Error(\"Returned node is not an element: \"+a);return c};\nP.e=f",
    L"unction(a,b){var c=xa(b,a);ea(c,function(d){if(d.nodeType!=1)throw Erro",
    L"r(\"Returned nodes must be elements: \"+a);});return c};var ya=\"StopIt",
    L"eration\"in h?h.StopIteration:Error(\"StopIteration\");function za(){}z",
    L"a.prototype.next=function(){throw ya;};function Q(a,b,c,d,e){this.a=!!b",
    L";a&&R(this,a,d);this.f=e!=undefined?e:this.d||0;if(this.a)this.f*=-1;th",
    L"is.k=!c}l(Q,za);Q.prototype.c=null;Q.prototype.d=0;Q.prototype.j=false;",
    L"function R(a,b,c,d){if(a.c=b)a.d=typeof c==\"number\"?c:a.c.nodeType!=1",
    L"?0:a.a?-1:1;if(typeof d==\"number\")a.f=d}\nQ.prototype.next=function()",
    L"{var a;if(this.j){if(!this.c||this.k&&this.f==0)throw ya;a=this.c;var b",
    L"=this.a?-1:1;if(this.d==b){var c=this.a?a.lastChild:a.firstChild;c?R(th",
    L"is,c):R(this,a,b*-1)}else(c=this.a?a.previousSibling:a.nextSibling)?R(t",
    L"his,c):R(this,a.parentNode,b*-1);this.f+=this.d*(this.a?-1:1)}else this",
    L".j=true;a=this.c;if(!this.c)throw ya;return a};\nQ.prototype.splice=fun",
    L"ction(){var a=this.c,b=this.a?1:-1;if(this.d==b){this.d=b*-1;this.f+=th",
    L"is.d*(this.a?-1:1)}this.a=!this.a;Q.prototype.next.call(this);this.a=!t",
    L"his.a;b=arguments[0];var c=i(b);b=c==\"array\"||c==\"object\"&&typeof b",
    L".length==\"number\"?arguments[0]:arguments;for(c=b.length-1;c>=0;c--)a.",
    L"parentNode&&a.parentNode.insertBefore(b[c],a.nextSibling);a&&a.parentNo",
    L"de&&a.parentNode.removeChild(a)};function Aa(a,b,c,d){Q.call(this,a,b,c",
    L",null,d)}l(Aa,Q);Aa.prototype.next=function(){do Aa.l.next.call(this);w",
    L"hile(this.d==-1);return this.c};function Ba(a,b){var c=N(a);if(c.defaul",
    L"tView&&c.defaultView.getComputedStyle)if(c=c.defaultView.getComputedSty",
    L"le(a,null))return c[b]||c.getPropertyValue(b);return\"\"};function S(a,",
    L"b){return!!a&&a.nodeType==1&&(!b||a.tagName.toUpperCase()==b)}\nvar Ca=",
    L"[\"async\",\"autofocus\",\"autoplay\",\"checked\",\"compact\",\"complet",
    L"e\",\"controls\",\"declare\",\"defaultchecked\",\"defaultselected\",\"d",
    L"efer\",\"disabled\",\"draggable\",\"ended\",\"formnovalidate\",\"hidden",
    L"\",\"indeterminate\",\"iscontenteditable\",\"ismap\",\"itemscope\",\"lo",
    L"op\",\"multiple\",\"muted\",\"nohref\",\"noresize\",\"noshade\",\"noval",
    L"idate\",\"nowrap\",\"open\",\"paused\",\"pubdate\",\"readonly\",\"requi",
    L"red\",\"reversed\",\"scoped\",\"seamless\",\"seeking\",\"selected\",\"s",
    L"pellcheck\",\"truespeed\",\"willvalidate\"];\nfunction T(a,b){if(8==a.n",
    L"odeType)return null;b=b.toLowerCase();if(b==\"style\"){var c=n(a.style.",
    L"cssText).toLowerCase();return c.charAt(c.length-1)==\";\"?c:c+\";\"}c=a",
    L".getAttributeNode(b);if(D)if(!c&&K(8)&&s(Ca,b)>=0)c=a[b];if(!c)return n",
    L"ull;if(s(Ca,b)>=0)return D&&c.value==\"false\"?null:\"true\";return c.s",
    L"pecified?c.value:null}function U(a){for(a=a.parentNode;a&&a.nodeType!=1",
    L"&&a.nodeType!=9&&a.nodeType!=11;)a=a.parentNode;return S(a)?a:null}func",
    L"tion V(a,b){b=da(String(b));return Ba(a,b)||Da(a,b)}\nfunction Da(a,b){",
    L"var c=(a.currentStyle||a.style)[b];if(c!=\"inherit\")return c!==undefin",
    L"ed?c:null;return(c=U(a))?Da(c,b):null}\nfunction Ea(a){if(k(a.getBBox))",
    L"return a.getBBox();var b;var c=ja&&!K(\"10\");if((Ba(a,\"display\")||(a",
    L".currentStyle?a.currentStyle.display:null)||a.style.display)!=\"none\")",
    L"b=c?new L(a.offsetWidth||a.clientWidth,a.offsetHeight||a.clientHeight):",
    L"new L(a.offsetWidth,a.offsetHeight);else{b=a.style;var d=b.display,e=b.",
    L"visibility,f=b.position;b.visibility=\"hidden\";b.position=\"absolute\"",
    L";b.display=\"inline\";if(c){c=a.offsetWidth||a.clientWidth;a=a.offsetHe",
    L"ight||a.clientHeight}else{c=a.offsetWidth;a=a.offsetHeight}b.display=\n",
    L"d;b.position=f;b.visibility=e;b=new L(c,a)}return b}\nfunction W(a){fun",
    L"ction b(e){if(V(e,\"display\")==\"none\")return false;e=U(e);return!e||",
    L"b(e)}function c(e){var f=Ea(e);if(f.height>0&&f.width>0)return true;if(",
    L"e.innerText||e.textContent)return true;return E&&ga(e.childNodes,functi",
    L"on(g){return S(g)&&c(g)})}if(!S(a))throw Error(\"Argument to isShown mu",
    L"st be of type Element\");if(S(a,\"TITLE\"))return(N(a)?N(a).parentWindo",
    L"w||N(a).defaultView:window)==h;if(S(a,\"OPTION\")||S(a,\"OPTGROUP\")){v",
    L"ar d=ua(a,function(e){return S(e,\"SELECT\")});return!!d&&W(d)}if(S(a,",
    L"\"MAP\")){if(!a.name)return false;\nd=N(a);d=d.evaluate?P.b('/descendan",
    L"t::*[@usemap = \"#'+a.name+'\"]',d):sa(d,function(e){return S(e)&&T(e,",
    L"\"usemap\")==\"#\"+a.name});return!!d&&W(d)}if(S(a,\"AREA\")){d=ua(a,fu",
    L"nction(e){return S(e,\"MAP\")});return!!d&&W(d)}if(S(a,\"INPUT\")&&a.ty",
    L"pe.toLowerCase()==\"hidden\")return false;if(V(a,\"visibility\")==\"hid",
    L"den\")return false;if(!b(a))return false;if(Fa(a)==0)return false;if(!c",
    L"(a))return false;return true}function Ga(a){var b=[\"\"];Ha(a,b);b=fa(b",
    L",n);return n(b.join(\"\\n\"))}\nfunction Ha(a,b){if(S(a,\"BR\"))b.push(",
    L"\"\");else{var c=Ia(a);c&&b[b.length-1]&&b.push(\"\");ea(a.childNodes,f",
    L"unction(d){if(d.nodeType==3){var e=U(d);if(e&&W(e)){d=d.nodeValue.repla",
    L"ce(Ja,\" \");e=b.pop();var f=e.length-1;if(f>=0&&e.indexOf(\" \",f)==f&",
    L"&d.lastIndexOf(\" \",0)==0)d=d.substr(1);b.push(e+d)}}else S(d)&&Ha(d,b",
    L")});c&&b[b.length-1]&&b.push(\"\")}}function Ia(a){a=V(a,\"display\");r",
    L"eturn a==\"block\"||a==\"inline-block\"}var Ja=RegExp(\"[\\\\s\\\\xa0\"",
    L"+String.fromCharCode(160)+\"]+\",\"g\");\nfunction Fa(a){if(D){if(V(a,",
    L"\"position\")==\"relative\")return 1;a=V(a,\"filter\");return(a=a.match",
    L"(/^alpha\\(opacity=(\\d*)\\)/)||a.match(/^progid:DXImageTransform.Micro",
    L"soft.Alpha\\(Opacity=(\\d*)\\)/))?Number(a[1])/100:1}else return La(a)}",
    L"function La(a){var b=1,c=V(a,\"opacity\");if(c)b=Number(c);if(a=U(a))b*",
    L"=La(a);return b};var Ma={};Ma.b=function(a,b){var c=M(b),d=j(a)?c.g.get",
    L"ElementById(a):a;if(!d)return null;if(T(d,\"id\")==a&&ra(b,d))return d;",
    L"c=O(c,\"*\");return v(c,function(e){return T(e,\"id\")==a&&ra(b,e)})};M",
    L"a.e=function(a,b){var c=O(M(b),\"*\",null,b);return u(c,function(d){ret",
    L"urn T(d,\"id\")==a})};var X={},Na={};X.i=function(a,b,c){b=O(M(b),\"A\"",
    L",null,b);return v(b,function(d){d=Ga(d);return c&&d.indexOf(a)!=-1||d==",
    L"a})};X.h=function(a,b,c){b=O(M(b),\"A\",null,b);return u(b,function(d){",
    L"d=Ga(d);return c&&d.indexOf(a)!=-1||d==a})};X.b=function(a,b){return X.",
    L"i(a,b,false)};X.e=function(a,b){return X.h(a,b,false)};Na.b=function(a,",
    L"b){return X.i(a,b,true)};Na.e=function(a,b){return X.h(a,b,true)};var O",
    L"a={};Oa.b=function(a,b){var c=O(M(b),\"*\",null,b);return v(c,function(",
    L"d){return T(d,\"name\")==a})};Oa.e=function(a,b){var c=O(M(b),\"*\",nul",
    L"l,b);return u(c,function(d){return T(d,\"name\")==a})};var Pa={};Pa.b=f",
    L"unction(a,b){return O(M(b),a,null,b)[0]||null};Pa.e=function(a,b){retur",
    L"n O(M(b),a,null,b)};var Qa={className:va,css:wa,id:Ma,linkText:X,name:O",
    L"a,partialLinkText:Na,tagName:Pa,xpath:P};function Ra(a,b){var c;a:{for(",
    L"c in a){c=c;break a}c=void 0}if(c){var d=Qa[c];if(d&&k(d.b))return d.b(",
    L"a[c],b||N(h))}throw Error(\"Unsupported locator strategy: \"+c);}var Y=",
    L"\"_\".split(\".\"),Z=h;!(Y[0]in Z)&&Z.execScript&&Z.execScript(\"var \"",
    L"+Y[0]);for(var $;Y.length&&($=Y.shift());)if(!Y.length&&Ra!==undefined)",
    L"Z[$]=Ra;else Z=Z[$]?Z[$]:Z[$]={};; return _.apply(null,arguments);}",
    NULL
};

const wchar_t* const FIND_ELEMENTS[] = {
    L"function(){var h=this;\nfunction i(a){var b=typeof a;if(b==\"object\")i",
    L"f(a){if(a instanceof Array)return\"array\";else if(a instanceof Object)",
    L"return b;var c=Object.prototype.toString.call(a);if(c==\"[object Window",
    L"]\")return\"object\";if(c==\"[object Array]\"||typeof a.length==\"numbe",
    L"r\"&&typeof a.splice!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"u",
    L"ndefined\"&&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(c==",
    L"\"[object Function]\"||typeof a.call!=\"undefined\"&&typeof a.propertyI",
    L"sEnumerable!=\"undefined\"&&!a.propertyIsEnumerable(\"call\"))return\"f",
    L"unction\"}else return\"null\";else if(b==\n\"function\"&&typeof a.call=",
    L"=\"undefined\")return\"object\";return b}function j(a){return typeof a=",
    L"=\"string\"}function k(a){return i(a)==\"function\"}function aa(a){a=i(",
    L"a);return a==\"object\"||a==\"array\"||a==\"function\"}function l(a,b){",
    L"function c(){}c.prototype=b.prototype;a.l=b.prototype;a.prototype=new c",
    L"};function m(a){this.stack=Error().stack||\"\";if(a)this.message=String",
    L"(a)}l(m,Error);m.prototype.name=\"CustomError\";function ba(a){for(var ",
    L"b=1;b<arguments.length;b++){var c=String(arguments[b]).replace(/\\$/g,",
    L"\"$$$$\");a=a.replace(/\\%s/,c)}return a}function n(a){return a.replace",
    L"(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\")}function o(a,b){if(a<b)return-1;els",
    L"e if(a>b)return 1;return 0}var ca={};function da(a){return ca[a]||(ca[a",
    L"]=String(a).replace(/\\-([a-z])/g,function(b,c){return c.toUpperCase()}",
    L"))};function p(a,b){b.unshift(a);m.call(this,ba.apply(null,b));b.shift(",
    L");this.m=a}l(p,m);p.prototype.name=\"AssertionError\";function q(a,b){i",
    L"f(!a){var c=Array.prototype.slice.call(arguments,2),d=\"Assertion faile",
    L"d\";if(b){d+=\": \"+b;var e=c}throw new p(\"\"+d,e||[]);}return a};var ",
    L"r=Array.prototype,s=r.indexOf?function(a,b,c){q(a.length!=null);return ",
    L"r.indexOf.call(a,b,c)}:function(a,b,c){c=c==null?0:c<0?Math.max(0,a.len",
    L"gth+c):c;if(j(a)){if(!j(b)||b.length!=1)return-1;return a.indexOf(b,c)}",
    L"for(c=c;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ea=r.forE",
    L"ach?function(a,b,c){q(a.length!=null);r.forEach.call(a,b,c)}:function(a",
    L",b,c){var d=a.length,e=j(a)?a.split(\"\"):a;for(var f=0;f<d;f++)f in e&",
    L"&b.call(c,e[f],f,a)},u=r.filter?function(a,b,c){q(a.length!=null);retur",
    L"n r.filter.call(a,\nb,c)}:function(a,b,c){var d=a.length,e=[],f=0,g=j(a",
    L")?a.split(\"\"):a;for(var t=0;t<d;t++)if(t in g){var I=g[t];if(b.call(c",
    L",I,t,a))e[f++]=I}return e},fa=r.map?function(a,b,c){q(a.length!=null);r",
    L"eturn r.map.call(a,b,c)}:function(a,b,c){var d=a.length,e=Array(d),f=j(",
    L"a)?a.split(\"\"):a;for(var g=0;g<d;g++)if(g in f)e[g]=b.call(c,f[g],g,a",
    L");return e},ga=r.some?function(a,b,c){q(a.length!=null);return r.some.c",
    L"all(a,b,c)}:function(a,b,c){var d=a.length,e=j(a)?a.split(\"\"):a;for(v",
    L"ar f=0;f<d;f++)if(f in e&&b.call(c,\ne[f],f,a))return true;return false",
    L"};function v(a,b,c){a:{var d=a.length,e=j(a)?a.split(\"\"):a;for(var f=",
    L"0;f<d;f++)if(f in e&&b.call(c,e[f],f,a)){b=f;break a}b=-1}return b<0?nu",
    L"ll:j(a)?a.charAt(b):a[b]};var w,x,y,z;function ha(){return h.navigator?",
    L"h.navigator.userAgent:null}z=y=x=w=false;var C;if(C=ha()){var ia=h.navi",
    L"gator;w=C.indexOf(\"Opera\")==0;x=!w&&C.indexOf(\"MSIE\")!=-1;y=!w&&C.i",
    L"ndexOf(\"WebKit\")!=-1;z=!w&&!y&&ia.product==\"Gecko\"}var ja=w,D=x,ka=",
    L"z,E=y,F;\na:{var G=\"\",H;if(ja&&h.opera){var J=h.opera.version;G=typeo",
    L"f J==\"function\"?J():J}else{if(ka)H=/rv\\:([^\\);]+)(\\)|;)/;else if(D",
    L")H=/MSIE\\s+([^\\);]+)(\\)|;)/;else if(E)H=/WebKit\\/(\\S+)/;if(H){var ",
    L"la=H.exec(ha());G=la?la[1]:\"\"}}if(D){var ma,na=h.document;ma=na?na.do",
    L"cumentMode:undefined;if(ma>parseFloat(G)){F=String(ma);break a}}F=G}var",
    L" oa={};\nfunction K(a){var b;if(!(b=oa[a])){b=0;var c=n(String(F)).spli",
    L"t(\".\"),d=n(String(a)).split(\".\"),e=Math.max(c.length,d.length);for(",
    L"var f=0;b==0&&f<e;f++){var g=c[f]||\"\",t=d[f]||\"\",I=RegExp(\"(\\\\d*",
    L")(\\\\D*)\",\"g\"),Ka=RegExp(\"(\\\\d*)(\\\\D*)\",\"g\");do{var A=I.exe",
    L"c(g)||[\"\",\"\",\"\"],B=Ka.exec(t)||[\"\",\"\",\"\"];if(A[0].length==0",
    L"&&B[0].length==0)break;b=o(A[1].length==0?0:parseInt(A[1],10),B[1].leng",
    L"th==0?0:parseInt(B[1],10))||o(A[2].length==0,B[2].length==0)||o(A[2],B[",
    L"2])}while(b==0)}b=oa[a]=b>=0}return b};var pa;!D||K(\"9\");D&&K(\"9\");",
    L"function L(a,b){this.width=a;this.height=b}L.prototype.toString=functio",
    L"n(){return\"(\"+this.width+\" x \"+this.height+\")\"};function M(a){ret",
    L"urn a?new qa(N(a)):pa||(pa=new qa)}function ra(a,b){if(a.contains&&b.no",
    L"deType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPositio",
    L"n!=\"undefined\")return a==b||Boolean(a.compareDocumentPosition(b)&16);",
    L"for(;b&&a!=b;)b=b.parentNode;return b==a}function N(a){return a.nodeTyp",
    L"e==9?a:a.ownerDocument||a.document}function sa(a,b){var c=[];return ta(",
    L"a,b,c,true)?c[0]:undefined}\nfunction ta(a,b,c,d){if(a!=null){var e=0;f",
    L"or(var f;f=a.childNodes[e];e++){if(b(f)){c.push(f);if(d)return true}if(",
    L"ta(f,b,c,d))return true}}return false}function ua(a,b,c,d){if(!c)a=a.pa",
    L"rentNode;c=d==null;for(var e=0;a&&(c||e<=d);){if(b(a))return a;a=a.pare",
    L"ntNode;e++}return null}function qa(a){this.g=a||h.document||document}\n",
    L"function O(a,b,c,d){a=d||a.g;b=b&&b!=\"*\"?b.toUpperCase():\"\";if(a.qu",
    L"erySelectorAll&&a.querySelector&&(!E||document.compatMode==\"CSS1Compat",
    L"\"||K(\"528\"))&&(b||c))c=a.querySelectorAll(b+(c?\".\"+c:\"\"));else i",
    L"f(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={}",
    L";var e=0,f=0;for(var g;g=a[f];f++)if(b==g.nodeName)d[e++]=g;d.length=e;",
    L"c=d}else c=a}else{a=a.getElementsByTagName(b||\"*\");if(c){d={};e=0;for",
    L"(f=0;g=a[f];f++){b=g.className;if(typeof b.split==\"function\"&&s(b.spl",
    L"it(/\\s+/),c)>=0)d[e++]=\ng}d.length=e;c=d}else c=a}return c}qa.prototy",
    L"pe.contains=ra;var va={};va.d=function(a,b){if(!a)throw Error(\"No clas",
    L"s name specified\");a=n(a);if(a.split(/\\s+/).length>1)throw Error(\"Co",
    L"mpound class names not permitted\");var c=O(M(b),\"*\",a,b);return c.le",
    L"ngth?c[0]:null};va.b=function(a,b){if(!a)throw Error(\"No class name sp",
    L"ecified\");a=n(a);if(a.split(/\\s+/).length>1)throw Error(\"Compound cl",
    L"ass names not permitted\");return O(M(b),\"*\",a,b)};var wa={};wa.d=fun",
    L"ction(a,b){if(!k(b.querySelector)&&D&&K(8)&&!aa(b.querySelector))throw ",
    L"Error(\"CSS selection is not supported\");if(!a)throw Error(\"No select",
    L"or specified\");if(a.split(/,/).length>1)throw Error(\"Compound selecto",
    L"rs not permitted\");a=n(a);var c=b.querySelector(a);return c&&c.nodeTyp",
    L"e==1?c:null};\nwa.b=function(a,b){if(!k(b.querySelectorAll)&&D&&K(8)&&!",
    L"aa(b.querySelector))throw Error(\"CSS selection is not supported\");if(",
    L"!a)throw Error(\"No selector specified\");if(a.split(/,/).length>1)thro",
    L"w Error(\"Compound selectors not permitted\");a=n(a);return b.querySele",
    L"ctorAll(a)};function xa(a,b){if(typeof a.selectNodes!=\"undefined\"){va",
    L"r c=N(a);typeof c.setProperty!=\"undefined\"&&c.setProperty(\"Selection",
    L"Language\",\"XPath\");return a.selectNodes(b)}else if(document.implemen",
    L"tation.hasFeature(\"XPath\",\"3.0\")){c=N(a);var d=c.createNSResolver(c",
    L".documentElement);c=c.evaluate(b,a,d,XPathResult.ORDERED_NODE_SNAPSHOT_",
    L"TYPE,null);d=[];var e=c.snapshotLength;for(var f=0;f<e;f++)d.push(c.sna",
    L"pshotItem(f));return d}else return[]};var P={};P.d=function(a,b){try{va",
    L"r c;if(typeof b.selectSingleNode!=\"undefined\"){var d=N(b);typeof d.se",
    L"tProperty!=\"undefined\"&&d.setProperty(\"SelectionLanguage\",\"XPath\"",
    L");c=b.selectSingleNode(a)}else if(document.implementation.hasFeature(\"",
    L"XPath\",\"3.0\")){d=N(b);var e=d.createNSResolver(d.documentElement);c=",
    L"d.evaluate(a,b,e,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeVa",
    L"lue}else c=null}catch(f){return null}if(!c)return null;if(c.nodeType!=1",
    L")throw Error(\"Returned node is not an element: \"+a);return c};\nP.b=f",
    L"unction(a,b){var c=xa(b,a);ea(c,function(d){if(d.nodeType!=1)throw Erro",
    L"r(\"Returned nodes must be elements: \"+a);});return c};var ya=\"StopIt",
    L"eration\"in h?h.StopIteration:Error(\"StopIteration\");function za(){}z",
    L"a.prototype.next=function(){throw ya;};function Q(a,b,c,d,e){this.a=!!b",
    L";a&&R(this,a,d);this.f=e!=undefined?e:this.e||0;if(this.a)this.f*=-1;th",
    L"is.k=!c}l(Q,za);Q.prototype.c=null;Q.prototype.e=0;Q.prototype.j=false;",
    L"function R(a,b,c,d){if(a.c=b)a.e=typeof c==\"number\"?c:a.c.nodeType!=1",
    L"?0:a.a?-1:1;if(typeof d==\"number\")a.f=d}\nQ.prototype.next=function()",
    L"{var a;if(this.j){if(!this.c||this.k&&this.f==0)throw ya;a=this.c;var b",
    L"=this.a?-1:1;if(this.e==b){var c=this.a?a.lastChild:a.firstChild;c?R(th",
    L"is,c):R(this,a,b*-1)}else(c=this.a?a.previousSibling:a.nextSibling)?R(t",
    L"his,c):R(this,a.parentNode,b*-1);this.f+=this.e*(this.a?-1:1)}else this",
    L".j=true;a=this.c;if(!this.c)throw ya;return a};\nQ.prototype.splice=fun",
    L"ction(){var a=this.c,b=this.a?1:-1;if(this.e==b){this.e=b*-1;this.f+=th",
    L"is.e*(this.a?-1:1)}this.a=!this.a;Q.prototype.next.call(this);this.a=!t",
    L"his.a;b=arguments[0];var c=i(b);b=c==\"array\"||c==\"object\"&&typeof b",
    L".length==\"number\"?arguments[0]:arguments;for(c=b.length-1;c>=0;c--)a.",
    L"parentNode&&a.parentNode.insertBefore(b[c],a.nextSibling);a&&a.parentNo",
    L"de&&a.parentNode.removeChild(a)};function Aa(a,b,c,d){Q.call(this,a,b,c",
    L",null,d)}l(Aa,Q);Aa.prototype.next=function(){do Aa.l.next.call(this);w",
    L"hile(this.e==-1);return this.c};function Ba(a,b){var c=N(a);if(c.defaul",
    L"tView&&c.defaultView.getComputedStyle)if(c=c.defaultView.getComputedSty",
    L"le(a,null))return c[b]||c.getPropertyValue(b);return\"\"};function S(a,",
    L"b){return!!a&&a.nodeType==1&&(!b||a.tagName.toUpperCase()==b)}\nvar Ca=",
    L"[\"async\",\"autofocus\",\"autoplay\",\"checked\",\"compact\",\"complet",
    L"e\",\"controls\",\"declare\",\"defaultchecked\",\"defaultselected\",\"d",
    L"efer\",\"disabled\",\"draggable\",\"ended\",\"formnovalidate\",\"hidden",
    L"\",\"indeterminate\",\"iscontenteditable\",\"ismap\",\"itemscope\",\"lo",
    L"op\",\"multiple\",\"muted\",\"nohref\",\"noresize\",\"noshade\",\"noval",
    L"idate\",\"nowrap\",\"open\",\"paused\",\"pubdate\",\"readonly\",\"requi",
    L"red\",\"reversed\",\"scoped\",\"seamless\",\"seeking\",\"selected\",\"s",
    L"pellcheck\",\"truespeed\",\"willvalidate\"];\nfunction T(a,b){if(8==a.n",
    L"odeType)return null;b=b.toLowerCase();if(b==\"style\"){var c=n(a.style.",
    L"cssText).toLowerCase();return c.charAt(c.length-1)==\";\"?c:c+\";\"}c=a",
    L".getAttributeNode(b);if(D)if(!c&&K(8)&&s(Ca,b)>=0)c=a[b];if(!c)return n",
    L"ull;if(s(Ca,b)>=0)return D&&c.value==\"false\"?null:\"true\";return c.s",
    L"pecified?c.value:null}function U(a){for(a=a.parentNode;a&&a.nodeType!=1",
    L"&&a.nodeType!=9&&a.nodeType!=11;)a=a.parentNode;return S(a)?a:null}func",
    L"tion V(a,b){b=da(String(b));return Ba(a,b)||Da(a,b)}\nfunction Da(a,b){",
    L"var c=(a.currentStyle||a.style)[b];if(c!=\"inherit\")return c!==undefin",
    L"ed?c:null;return(c=U(a))?Da(c,b):null}\nfunction Ea(a){if(k(a.getBBox))",
    L"return a.getBBox();var b;var c=ja&&!K(\"10\");if((Ba(a,\"display\")||(a",
    L".currentStyle?a.currentStyle.display:null)||a.style.display)!=\"none\")",
    L"b=c?new L(a.offsetWidth||a.clientWidth,a.offsetHeight||a.clientHeight):",
    L"new L(a.offsetWidth,a.offsetHeight);else{b=a.style;var d=b.display,e=b.",
    L"visibility,f=b.position;b.visibility=\"hidden\";b.position=\"absolute\"",
    L";b.display=\"inline\";if(c){c=a.offsetWidth||a.clientWidth;a=a.offsetHe",
    L"ight||a.clientHeight}else{c=a.offsetWidth;a=a.offsetHeight}b.display=\n",
    L"d;b.position=f;b.visibility=e;b=new L(c,a)}return b}\nfunction W(a){fun",
    L"ction b(e){if(V(e,\"display\")==\"none\")return false;e=U(e);return!e||",
    L"b(e)}function c(e){var f=Ea(e);if(f.height>0&&f.width>0)return true;if(",
    L"e.innerText||e.textContent)return true;return E&&ga(e.childNodes,functi",
    L"on(g){return S(g)&&c(g)})}if(!S(a))throw Error(\"Argument to isShown mu",
    L"st be of type Element\");if(S(a,\"TITLE\"))return(N(a)?N(a).parentWindo",
    L"w||N(a).defaultView:window)==h;if(S(a,\"OPTION\")||S(a,\"OPTGROUP\")){v",
    L"ar d=ua(a,function(e){return S(e,\"SELECT\")});return!!d&&W(d)}if(S(a,",
    L"\"MAP\")){if(!a.name)return false;\nd=N(a);d=d.evaluate?P.d('/descendan",
    L"t::*[@usemap = \"#'+a.name+'\"]',d):sa(d,function(e){return S(e)&&T(e,",
    L"\"usemap\")==\"#\"+a.name});return!!d&&W(d)}if(S(a,\"AREA\")){d=ua(a,fu",
    L"nction(e){return S(e,\"MAP\")});return!!d&&W(d)}if(S(a,\"INPUT\")&&a.ty",
    L"pe.toLowerCase()==\"hidden\")return false;if(V(a,\"visibility\")==\"hid",
    L"den\")return false;if(!b(a))return false;if(Fa(a)==0)return false;if(!c",
    L"(a))return false;return true}function Ga(a){var b=[\"\"];Ha(a,b);b=fa(b",
    L",n);return n(b.join(\"\\n\"))}\nfunction Ha(a,b){if(S(a,\"BR\"))b.push(",
    L"\"\");else{var c=Ia(a);c&&b[b.length-1]&&b.push(\"\");ea(a.childNodes,f",
    L"unction(d){if(d.nodeType==3){var e=U(d);if(e&&W(e)){d=d.nodeValue.repla",
    L"ce(Ja,\" \");e=b.pop();var f=e.length-1;if(f>=0&&e.indexOf(\" \",f)==f&",
    L"&d.lastIndexOf(\" \",0)==0)d=d.substr(1);b.push(e+d)}}else S(d)&&Ha(d,b",
    L")});c&&b[b.length-1]&&b.push(\"\")}}function Ia(a){a=V(a,\"display\");r",
    L"eturn a==\"block\"||a==\"inline-block\"}var Ja=RegExp(\"[\\\\s\\\\xa0\"",
    L"+String.fromCharCode(160)+\"]+\",\"g\");\nfunction Fa(a){if(D){if(V(a,",
    L"\"position\")==\"relative\")return 1;a=V(a,\"filter\");return(a=a.match",
    L"(/^alpha\\(opacity=(\\d*)\\)/)||a.match(/^progid:DXImageTransform.Micro",
    L"soft.Alpha\\(Opacity=(\\d*)\\)/))?Number(a[1])/100:1}else return La(a)}",
    L"function La(a){var b=1,c=V(a,\"opacity\");if(c)b=Number(c);if(a=U(a))b*",
    L"=La(a);return b};var Ma={};Ma.d=function(a,b){var c=M(b),d=j(a)?c.g.get",
    L"ElementById(a):a;if(!d)return null;if(T(d,\"id\")==a&&ra(b,d))return d;",
    L"c=O(c,\"*\");return v(c,function(e){return T(e,\"id\")==a&&ra(b,e)})};M",
    L"a.b=function(a,b){var c=O(M(b),\"*\",null,b);return u(c,function(d){ret",
    L"urn T(d,\"id\")==a})};var X={},Na={};X.i=function(a,b,c){b=O(M(b),\"A\"",
    L",null,b);return v(b,function(d){d=Ga(d);return c&&d.indexOf(a)!=-1||d==",
    L"a})};X.h=function(a,b,c){b=O(M(b),\"A\",null,b);return u(b,function(d){",
    L"d=Ga(d);return c&&d.indexOf(a)!=-1||d==a})};X.d=function(a,b){return X.",
    L"i(a,b,false)};X.b=function(a,b){return X.h(a,b,false)};Na.d=function(a,",
    L"b){return X.i(a,b,true)};Na.b=function(a,b){return X.h(a,b,true)};var O",
    L"a={};Oa.d=function(a,b){var c=O(M(b),\"*\",null,b);return v(c,function(",
    L"d){return T(d,\"name\")==a})};Oa.b=function(a,b){var c=O(M(b),\"*\",nul",
    L"l,b);return u(c,function(d){return T(d,\"name\")==a})};var Pa={};Pa.d=f",
    L"unction(a,b){return O(M(b),a,null,b)[0]||null};Pa.b=function(a,b){retur",
    L"n O(M(b),a,null,b)};var Qa={className:va,css:wa,id:Ma,linkText:X,name:O",
    L"a,partialLinkText:Na,tagName:Pa,xpath:P};function Ra(a,b){var c;a:{for(",
    L"c in a){c=c;break a}c=void 0}if(c){var d=Qa[c];if(d&&k(d.b))return d.b(",
    L"a[c],b||N(h))}throw Error(\"Unsupported locator strategy: \"+c);}var Y=",
    L"\"_\".split(\".\"),Z=h;!(Y[0]in Z)&&Z.execScript&&Z.execScript(\"var \"",
    L"+Y[0]);for(var $;Y.length&&($=Y.shift());)if(!Y.length&&Ra!==undefined)",
    L"Z[$]=Ra;else Z=Z[$]?Z[$]:Z[$]={};; return _.apply(null,arguments);}",
    NULL
};

const wchar_t* const GET_ATTRIBUTE[] = {
    L"function(){var f=this;\nfunction g(a){var c=typeof a;if(c==\"object\")i",
    L"f(a){if(a instanceof Array)return\"array\";else if(a instanceof Object)",
    L"return c;var b=Object.prototype.toString.call(a);if(b==\"[object Window",
    L"]\")return\"object\";if(b==\"[object Array]\"||typeof a.length==\"numbe",
    L"r\"&&typeof a.splice!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"u",
    L"ndefined\"&&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(b==",
    L"\"[object Function]\"||typeof a.call!=\"undefined\"&&typeof a.propertyI",
    L"sEnumerable!=\"undefined\"&&!a.propertyIsEnumerable(\"call\"))return\"f",
    L"unction\"}else return\"null\";else if(c==\n\"function\"&&typeof a.call=",
    L"=\"undefined\")return\"object\";return c}function h(a,c){function b(){}",
    L"b.prototype=c.prototype;a.g=c.prototype;a.prototype=new b};function i(a",
    L"){this.stack=Error().stack||\"\";if(a)this.message=String(a)}h(i,Error)",
    L";function j(a){for(var c=1;c<arguments.length;c++){var b=String(argumen",
    L"ts[c]).replace(/\\$/g,\"$$$$\");a=a.replace(/\\%s/,b)}return a}function",
    L" l(a){return a.replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\")}function o(a,",
    L"c){if(a<c)return-1;else if(a>c)return 1;return 0};function p(a,c){c.uns",
    L"hift(a);i.call(this,j.apply(null,c));c.shift();this.h=a}h(p,i);function",
    L" q(a,c){if(!a){var b=Array.prototype.slice.call(arguments,2),d=\"Assert",
    L"ion failed\";if(c){d+=\": \"+c;var e=b}throw new p(\"\"+d,e||[]);}retur",
    L"n a};var r=Array.prototype,s=r.indexOf?function(a,c,b){q(a.length!=null",
    L");return r.indexOf.call(a,c,b)}:function(a,c,b){b=b==null?0:b<0?Math.ma",
    L"x(0,a.length+b):b;if(typeof a==\"string\"){if(typeof c!=\"string\"||c.l",
    L"ength!=1)return-1;return a.indexOf(c,b)}for(b=b;b<a.length;b++)if(b in ",
    L"a&&a[b]===c)return b;return-1};var t,u,v,w;function x(){return f.naviga",
    L"tor?f.navigator.userAgent:null}w=v=u=t=false;var y;if(y=x()){var z=f.na",
    L"vigator;t=y.indexOf(\"Opera\")==0;u=!t&&y.indexOf(\"MSIE\")!=-1;v=!t&&y",
    L".indexOf(\"WebKit\")!=-1;w=!t&&!v&&z.product==\"Gecko\"}var A=u,B=w,C=v",
    L",D;\na:{var E=\"\",F;if(t&&f.opera){var G=f.opera.version;E=typeof G==",
    L"\"function\"?G():G}else{if(B)F=/rv\\:([^\\);]+)(\\)|;)/;else if(A)F=/MS",
    L"IE\\s+([^\\);]+)(\\)|;)/;else if(C)F=/WebKit\\/(\\S+)/;if(F){var H=F.ex",
    L"ec(x());E=H?H[1]:\"\"}}if(A){var I,J=f.document;I=J?J.documentMode:unde",
    L"fined;if(I>parseFloat(E)){D=String(I);break a}}D=E}var K={};\nfunction ",
    L"L(a){var c;if(!(c=K[a])){c=0;var b=l(String(D)).split(\".\"),d=l(String",
    L"(a)).split(\".\"),e=Math.max(b.length,d.length);for(var k=0;c==0&&k<e;k",
    L"++){var O=b[k]||\"\",Y=d[k]||\"\",Z=RegExp(\"(\\\\d*)(\\\\D*)\",\"g\"),",
    L"$=RegExp(\"(\\\\d*)(\\\\D*)\",\"g\");do{var m=Z.exec(O)||[\"\",\"\",\"",
    L"\"],n=$.exec(Y)||[\"\",\"\",\"\"];if(m[0].length==0&&n[0].length==0)bre",
    L"ak;c=o(m[1].length==0?0:parseInt(m[1],10),n[1].length==0?0:parseInt(n[1",
    L"],10))||o(m[2].length==0,n[2].length==0)||o(m[2],n[2])}while(c==0)}c=K[",
    L"a]=c>=0}return c};!A||L(\"9\");A&&L(\"9\");var M=\"StopIteration\"in f?",
    L"f.StopIteration:Error(\"StopIteration\");function N(){}N.prototype.next",
    L"=function(){throw M;};function P(a,c,b,d,e){this.a=!!c;a&&Q(this,a,d);t",
    L"his.d=e!=undefined?e:this.c||0;if(this.a)this.d*=-1;this.f=!b}h(P,N);P.",
    L"prototype.b=null;P.prototype.c=0;P.prototype.e=false;function Q(a,c,b,d",
    L"){if(a.b=c)a.c=typeof b==\"number\"?b:a.b.nodeType!=1?0:a.a?-1:1;if(typ",
    L"eof d==\"number\")a.d=d}\nP.prototype.next=function(){var a;if(this.e){",
    L"if(!this.b||this.f&&this.d==0)throw M;a=this.b;var c=this.a?-1:1;if(thi",
    L"s.c==c){var b=this.a?a.lastChild:a.firstChild;b?Q(this,b):Q(this,a,c*-1",
    L")}else(b=this.a?a.previousSibling:a.nextSibling)?Q(this,b):Q(this,a.par",
    L"entNode,c*-1);this.d+=this.c*(this.a?-1:1)}else this.e=true;a=this.b;if",
    L"(!this.b)throw M;return a};\nP.prototype.splice=function(){var a=this.b",
    L",c=this.a?1:-1;if(this.c==c){this.c=c*-1;this.d+=this.c*(this.a?-1:1)}t",
    L"his.a=!this.a;P.prototype.next.call(this);this.a=!this.a;c=arguments[0]",
    L";var b=g(c);c=b==\"array\"||b==\"object\"&&typeof c.length==\"number\"?",
    L"arguments[0]:arguments;for(b=c.length-1;b>=0;b--)a.parentNode&&a.parent",
    L"Node.insertBefore(c[b],a.nextSibling);a&&a.parentNode&&a.parentNode.rem",
    L"oveChild(a)};function R(a,c,b,d){P.call(this,a,c,b,null,d)}h(R,P);R.pro",
    L"totype.next=function(){do R.g.next.call(this);while(this.c==-1);return ",
    L"this.b};var aa={\"class\":\"className\",readonly:\"readOnly\"},S=[\"asy",
    L"nc\",\"autofocus\",\"autoplay\",\"checked\",\"compact\",\"complete\",\"",
    L"controls\",\"declare\",\"defaultchecked\",\"defaultselected\",\"defer\"",
    L",\"disabled\",\"draggable\",\"ended\",\"formnovalidate\",\"hidden\",\"i",
    L"ndeterminate\",\"iscontenteditable\",\"ismap\",\"itemscope\",\"loop\",",
    L"\"multiple\",\"muted\",\"nohref\",\"noresize\",\"noshade\",\"novalidate",
    L"\",\"nowrap\",\"open\",\"paused\",\"pubdate\",\"readonly\",\"required\"",
    L",\"reversed\",\"scoped\",\"seamless\",\"seeking\",\"selected\",\"spellc",
    L"heck\",\"truespeed\",\"willvalidate\"];\nfunction ba(a,c){if(8==a.nodeT",
    L"ype)return null;c=c.toLowerCase();if(c==\"style\"){var b=l(a.style.cssT",
    L"ext).toLowerCase();return b.charAt(b.length-1)==\";\"?b:b+\";\"}b=a.get",
    L"AttributeNode(c);if(A)if(!b&&L(8)&&s(S,c)>=0)b=a[c];if(!b)return null;i",
    L"f(s(S,c)>=0)return A&&b.value==\"false\"?null:\"true\";return b.specifi",
    L"ed?b.value:null}String.fromCharCode(160);\nvar ca=[\"checkbox\",\"radio",
    L"\"];function T(a){var c=a.tagName.toUpperCase();if(c==\"OPTION\")return",
    L" true;if(c==\"INPUT\")if(s(ca,a.type)>=0)return true;return false};func",
    L"tion U(a,c){var b=null;b=c.toLowerCase();if(\"style\"==c.toLowerCase())",
    L"{if((b=a.style)&&typeof b!=\"string\")b=b.cssText;return b}if(\"selecte",
    L"d\"==b||\"checked\"==b&&T(a)){var d;if(T(a)){d=\"selected\";b=a.type&&a",
    L".type.toLowerCase();if(\"checkbox\"==b||\"radio\"==b)d=\"checked\";d=!!",
    L"a[d]}else d=false;return d?\"true\":null}var e=a.tagName&&\"A\"==a.tagN",
    L"ame.toUpperCase(),k=a.tagName&&\"IMG\"==a.tagName.toUpperCase();try{d=a",
    L"[aa[c]||c]}catch(O){}if(!(e=b==\"href\"&&e)){if(!(b=b==\"src\"&&k)){if(",
    L"!(b=d==null)){b=g(d);b=b==\n\"object\"||b==\"array\"||b==\"function\"}b",
    L"=b}e=b}b=e?ba(a,c):d;return b!=null?b.toString():null}var V=\"_\".split",
    L"(\".\"),W=f;!(V[0]in W)&&W.execScript&&W.execScript(\"var \"+V[0]);for(",
    L"var X;V.length&&(X=V.shift());)if(!V.length&&U!==undefined)W[X]=U;else ",
    L"W=W[X]?W[X]:W[X]={};; return _.apply(null,arguments);}",
    NULL
};

const wchar_t* const GET_LOCATION[] = {
    L"function(){var g=this;function h(a,b){function c(){}c.prototype=b.proto",
    L"type;a.c=b.prototype;a.prototype=new c};function i(a){this.stack=Error(",
    L").stack||\"\";if(a)this.message=String(a)}h(i,Error);function j(a){for(",
    L"var b=1;b<arguments.length;b++){var c=String(arguments[b]).replace(/\\$",
    L"/g,\"$$$$\");a=a.replace(/\\%s/,c)}return a}\nfunction k(a,b){var c=0,f",
    L"=String(a).replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").split(\".\"),q=St",
    L"ring(b).replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").split(\".\"),d=Math.",
    L"max(f.length,q.length);for(var e=0;c==0&&e<d;e++){var Q=f[e]||\"\",R=q[",
    L"e]||\"\",S=RegExp(\"(\\\\d*)(\\\\D*)\",\"g\"),T=RegExp(\"(\\\\d*)(\\\\D",
    L"*)\",\"g\");do{var l=S.exec(Q)||[\"\",\"\",\"\"],m=T.exec(R)||[\"\",\"",
    L"\",\"\"];if(l[0].length==0&&m[0].length==0)break;c=n(l[1].length==0?0:p",
    L"arseInt(l[1],10),m[1].length==0?0:parseInt(m[1],10))||n(l[2].length==0,",
    L"m[2].length==0)||n(l[2],m[2])}while(c==\n0)}return c}function n(a,b){if",
    L"(a<b)return-1;else if(a>b)return 1;return 0};h(function(a,b){b.unshift(",
    L"a);i.call(this,j.apply(null,b));b.shift();this.b=a},i);var o,p,r,s;func",
    L"tion t(){return g.navigator?g.navigator.userAgent:null}s=r=p=o=false;va",
    L"r u;if(u=t()){var v=g.navigator;o=u.indexOf(\"Opera\")==0;p=!o&&u.index",
    L"Of(\"MSIE\")!=-1;r=!o&&u.indexOf(\"WebKit\")!=-1;s=!o&&!r&&v.product==",
    L"\"Gecko\"}var w=o,x=p,y=s,z=r,A;\na:{var B=\"\",C;if(w&&g.opera){var D=",
    L"g.opera.version;B=typeof D==\"function\"?D():D}else{if(y)C=/rv\\:([^\\)",
    L";]+)(\\)|;)/;else if(x)C=/MSIE\\s+([^\\);]+)(\\)|;)/;else if(z)C=/WebKi",
    L"t\\/(\\S+)/;if(C){var E=C.exec(t());B=E?E[1]:\"\"}}if(x){var F,G=g.docu",
    L"ment;F=G?G.documentMode:undefined;if(F>parseFloat(B)){A=String(F);break",
    L" a}}A=B}var H={};var I;!x||H[\"9\"]||(H[\"9\"]=k(A,\"9\")>=0);x&&(H[\"9",
    L"\"]||(H[\"9\"]=k(A,\"9\")>=0));function J(a,b){this.x=a!==undefined?a:0",
    L";this.y=b!==undefined?b:0}J.prototype.toString=function(){return\"(\"+t",
    L"his.x+\", \"+this.y+\")\"};function K(a){return a.nodeType==9?a:a.owner",
    L"Document||a.document}function L(a){this.a=a||g.document||document};func",
    L"tion M(a,b){var c;a:{c=K(a);if(c.defaultView&&c.defaultView.getComputed",
    L"Style)if(c=c.defaultView.getComputedStyle(a,null)){c=c[b]||c.getPropert",
    L"yValue(b);break a}c=\"\"}return c||(a.currentStyle?a.currentStyle[b]:nu",
    L"ll)||a.style[b]}\nfunction N(a){if(x)return a.offsetParent;var b=K(a),c",
    L"=M(a,\"position\"),f=c==\"fixed\"||c==\"absolute\";for(a=a.parentNode;a",
    L"&&a!=b;a=a.parentNode){c=M(a,\"position\");f=f&&c==\"static\"&&a!=b.doc",
    L"umentElement&&a!=b.body;if(!f&&(a.scrollWidth>a.clientWidth||a.scrollHe",
    L"ight>a.clientHeight||c==\"fixed\"||c==\"absolute\"))return a}return nul",
    L"l};function O(a){var b,c=K(a),f=M(a,\"position\"),q=y&&c.getBoxObjectFo",
    L"r&&!a.getBoundingClientRect&&f==\"absolute\"&&(b=c.getBoxObjectFor(a))&",
    L"&(b.screenX<0||b.screenY<0),d=new J(0,0),e;b=c?c.nodeType==9?c:K(c):doc",
    L"ument;if(e=x)e=(b?new L(K(b)):I||(I=new L)).a.compatMode!=\"CSS1Compat",
    L"\";e=e?b.body:b.documentElement;if(a==e)return d;if(a.getBoundingClient",
    L"Rect){b=a.getBoundingClientRect();if(x){a=a.ownerDocument;b.left-=a.doc",
    L"umentElement.clientLeft+a.body.clientLeft;b.top-=a.documentElement.clie",
    L"ntTop+a.body.clientTop}b=\nb;c=(c?new L(K(c)):I||(I=new L)).a;c=!z&&c.c",
    L"ompatMode==\"CSS1Compat\"?c.documentElement:c.body;c=new J(c.scrollLeft",
    L",c.scrollTop);d.x=b.left+c.x;d.y=b.top+c.y}else if(c.getBoxObjectFor&&!",
    L"q){b=c.getBoxObjectFor(a);c=c.getBoxObjectFor(e);d.x=b.screenX-c.screen",
    L"X;d.y=b.screenY-c.screenY}else{b=a;do{d.x+=b.offsetLeft;d.y+=b.offsetTo",
    L"p;if(b!=a){d.x+=b.clientLeft||0;d.y+=b.clientTop||0}if(z&&M(b,\"positio",
    L"n\")==\"fixed\"){d.x+=c.body.scrollLeft;d.y+=c.body.scrollTop;break}b=b",
    L".offsetParent}while(b&&b!=a);if(w||z&&\nf==\"absolute\")d.y-=c.body.off",
    L"setTop;for(b=a;(b=N(b))&&b!=c.body&&b!=e;){d.x-=b.scrollLeft;if(!w||b.t",
    L"agName!=\"TR\")d.y-=b.scrollTop}}return d}var P=\"_\".split(\".\"),U=g;",
    L"!(P[0]in U)&&U.execScript&&U.execScript(\"var \"+P[0]);for(var V;P.leng",
    L"th&&(V=P.shift());)if(!P.length&&O!==undefined)U[V]=O;else U=U[V]?U[V]:",
    L"U[V]={};; return _.apply(null,arguments);}",
    NULL
};

const wchar_t* const GET_SIZE[] = {
    L"function(){var d=this;function e(a,b){function c(){}c.prototype=b.proto",
    L"type;a.b=b.prototype;a.prototype=new c};function f(a){this.stack=Error(",
    L").stack||\"\";if(a)this.message=String(a)}e(f,Error);function h(a){for(",
    L"var b=1;b<arguments.length;b++){var c=String(arguments[b]).replace(/\\$",
    L"/g,\"$$$$\");a=a.replace(/\\%s/,c)}return a}function k(a,b){if(a<b)retu",
    L"rn-1;else if(a>b)return 1;return 0};e(function(a,b){b.unshift(a);f.call",
    L"(this,h.apply(null,b));b.shift();this.a=a},f);var l,m,n,o;function p(){",
    L"return d.navigator?d.navigator.userAgent:null}o=n=m=l=false;var r;if(r=",
    L"p()){var s=d.navigator;l=r.indexOf(\"Opera\")==0;m=!l&&r.indexOf(\"MSIE",
    L"\")!=-1;n=!l&&r.indexOf(\"WebKit\")!=-1;o=!l&&!n&&s.product==\"Gecko\"}",
    L"var t=l,u=m,v=o,w=n,x;\na:{var y=\"\",z;if(t&&d.opera){var B=d.opera.ve",
    L"rsion;y=typeof B==\"function\"?B():B}else{if(v)z=/rv\\:([^\\);]+)(\\)|;",
    L")/;else if(u)z=/MSIE\\s+([^\\);]+)(\\)|;)/;else if(w)z=/WebKit\\/(\\S+)",
    L"/;if(z){var C=z.exec(p());y=C?C[1]:\"\"}}if(u){var D,E=d.document;D=E?E",
    L".documentMode:undefined;if(D>parseFloat(y)){x=String(D);break a}}x=y}va",
    L"r F={};\nfunction G(a){var b;if(!(b=F[a])){b=0;var c=String(x).replace(",
    L"/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").split(\".\"),q=String(a).replace(/^[",
    L"\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").split(\".\"),A=Math.max(c.length,q.leng",
    L"th);for(var g=0;b==0&&g<A;g++){var M=c[g]||\"\",N=q[g]||\"\",O=RegExp(",
    L"\"(\\\\d*)(\\\\D*)\",\"g\"),P=RegExp(\"(\\\\d*)(\\\\D*)\",\"g\");do{var",
    L" i=O.exec(M)||[\"\",\"\",\"\"],j=P.exec(N)||[\"\",\"\",\"\"];if(i[0].le",
    L"ngth==0&&j[0].length==0)break;b=k(i[1].length==0?0:parseInt(i[1],10),j[",
    L"1].length==0?0:parseInt(j[1],10))||k(i[2].length==0,j[2].length==\n0)||",
    L"k(i[2],j[2])}while(b==0)}b=F[a]=b>=0}return b};!u||G(\"9\");u&&G(\"9\")",
    L";function H(a,b){this.width=a;this.height=b}H.prototype.toString=functi",
    L"on(){return\"(\"+this.width+\" x \"+this.height+\")\"};function I(a){va",
    L"r b=t&&!G(\"10\"),c;a:{c=a.nodeType==9?a:a.ownerDocument||a.document;if",
    L"(c.defaultView&&c.defaultView.getComputedStyle)if(c=c.defaultView.getCo",
    L"mputedStyle(a,null)){c=c.display||c.getPropertyValue(\"display\");break",
    L" a}c=\"\"}if((c||(a.currentStyle?a.currentStyle.display:null)||a.style.",
    L"display)!=\"none\")return b?new H(a.offsetWidth||a.clientWidth,a.offset",
    L"Height||a.clientHeight):new H(a.offsetWidth,a.offsetHeight);c=a.style;v",
    L"ar q=c.display,A=c.visibility,g=c.position;c.visibility=\"hidden\";c.po",
    L"sition=\n\"absolute\";c.display=\"inline\";if(b){b=a.offsetWidth||a.cli",
    L"entWidth;a=a.offsetHeight||a.clientHeight}else{b=a.offsetWidth;a=a.offs",
    L"etHeight}c.display=q;c.position=g;c.visibility=A;return new H(b,a)}var ",
    L"J=\"_\".split(\".\"),K=d;!(J[0]in K)&&K.execScript&&K.execScript(\"var ",
    L"\"+J[0]);for(var L;J.length&&(L=J.shift());)if(!J.length&&I!==undefined",
    L")K[L]=I;else K=K[L]?K[L]:K[L]={};; return _.apply(null,arguments);}",
    NULL
};

const wchar_t* const GET_TEXT[] = {
    L"function(){var g=this;\nfunction h(a){var b=typeof a;if(b==\"object\")i",
    L"f(a){if(a instanceof Array)return\"array\";else if(a instanceof Object)",
    L"return b;var c=Object.prototype.toString.call(a);if(c==\"[object Window",
    L"]\")return\"object\";if(c==\"[object Array]\"||typeof a.length==\"numbe",
    L"r\"&&typeof a.splice!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"u",
    L"ndefined\"&&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(c==",
    L"\"[object Function]\"||typeof a.call!=\"undefined\"&&typeof a.propertyI",
    L"sEnumerable!=\"undefined\"&&!a.propertyIsEnumerable(\"call\"))return\"f",
    L"unction\"}else return\"null\";else if(b==\n\"function\"&&typeof a.call=",
    L"=\"undefined\")return\"object\";return b}function j(a){return typeof a=",
    L"=\"string\"}function k(a,b){function c(){}c.prototype=b.prototype;a.g=b",
    L".prototype;a.prototype=new c};function l(a){this.stack=Error().stack||",
    L"\"\";if(a)this.message=String(a)}k(l,Error);l.prototype.name=\"CustomEr",
    L"ror\";function aa(a){for(var b=1;b<arguments.length;b++){var c=String(a",
    L"rguments[b]).replace(/\\$/g,\"$$$$\");a=a.replace(/\\%s/,c)}return a}fu",
    L"nction m(a){return a.replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\")}functio",
    L"n n(a,b){if(a<b)return-1;else if(a>b)return 1;return 0}var o={};functio",
    L"n ba(a){return o[a]||(o[a]=String(a).replace(/\\-([a-z])/g,function(b,c",
    L"){return c.toUpperCase()}))};function p(a,b){b.unshift(a);l.call(this,a",
    L"a.apply(null,b));b.shift();this.h=a}k(p,l);p.prototype.name=\"Assertion",
    L"Error\";function q(a,b){if(!a){var c=Array.prototype.slice.call(argumen",
    L"ts,2),d=\"Assertion failed\";if(b){d+=\": \"+b;var e=c}throw new p(\"\"",
    L"+d,e||[]);}return a};var r=Array.prototype,s=r.indexOf?function(a,b,c){",
    L"q(a.length!=null);return r.indexOf.call(a,b,c)}:function(a,b,c){c=c==nu",
    L"ll?0:c<0?Math.max(0,a.length+c):c;if(j(a)){if(!j(b)||b.length!=1)return",
    L"-1;return a.indexOf(b,c)}for(c=c;c<a.length;c++)if(c in a&&a[c]===b)ret",
    L"urn c;return-1},ca=r.forEach?function(a,b,c){q(a.length!=null);r.forEac",
    L"h.call(a,b,c)}:function(a,b,c){var d=a.length,e=j(a)?a.split(\"\"):a;fo",
    L"r(var f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},da=r.map?function(a,b,c){",
    L"q(a.length!=null);return r.map.call(a,\nb,c)}:function(a,b,c){var d=a.l",
    L"ength,e=Array(d),f=j(a)?a.split(\"\"):a;for(var i=0;i<d;i++)if(i in f)e",
    L"[i]=b.call(c,f[i],i,a);return e},ea=r.some?function(a,b,c){q(a.length!=",
    L"null);return r.some.call(a,b,c)}:function(a,b,c){var d=a.length,e=j(a)?",
    L"a.split(\"\"):a;for(var f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))retur",
    L"n true;return false};var v,w,x,y;function z(){return g.navigator?g.navi",
    L"gator.userAgent:null}y=x=w=v=false;var A;if(A=z()){var fa=g.navigator;v",
    L"=A.indexOf(\"Opera\")==0;w=!v&&A.indexOf(\"MSIE\")!=-1;x=!v&&A.indexOf(",
    L"\"WebKit\")!=-1;y=!v&&!x&&fa.product==\"Gecko\"}var B=v,C=w,ga=y,D=x,E;",
    L"\na:{var F=\"\",G;if(B&&g.opera){var H=g.opera.version;F=typeof H==\"fu",
    L"nction\"?H():H}else{if(ga)G=/rv\\:([^\\);]+)(\\)|;)/;else if(C)G=/MSIE",
    L"\\s+([^\\);]+)(\\)|;)/;else if(D)G=/WebKit\\/(\\S+)/;if(G){var I=G.exec",
    L"(z());F=I?I[1]:\"\"}}if(C){var J,K=g.document;J=K?K.documentMode:undefi",
    L"ned;if(J>parseFloat(F)){E=String(J);break a}}E=F}var L={};\nfunction M(",
    L"a){var b;if(!(b=L[a])){b=0;var c=m(String(E)).split(\".\"),d=m(String(a",
    L")).split(\".\"),e=Math.max(c.length,d.length);for(var f=0;b==0&&f<e;f++",
    L"){var i=c[f]||\"\",pa=d[f]||\"\",qa=RegExp(\"(\\\\d*)(\\\\D*)\",\"g\"),",
    L"ra=RegExp(\"(\\\\d*)(\\\\D*)\",\"g\");do{var t=qa.exec(i)||[\"\",\"\",",
    L"\"\"],u=ra.exec(pa)||[\"\",\"\",\"\"];if(t[0].length==0&&u[0].length==0",
    L")break;b=n(t[1].length==0?0:parseInt(t[1],10),u[1].length==0?0:parseInt",
    L"(u[1],10))||n(t[2].length==0,u[2].length==0)||n(t[2],u[2])}while(b==0)}",
    L"b=L[a]=b>=0}return b};!C||M(\"9\");C&&M(\"9\");function N(a,b){this.wid",
    L"th=a;this.height=b}N.prototype.toString=function(){return\"(\"+this.wid",
    L"th+\" x \"+this.height+\")\"};function O(a){return a.nodeType==9?a:a.ow",
    L"nerDocument||a.document}function ha(a,b){var c=[];return P(a,b,c,true)?",
    L"c[0]:undefined}function P(a,b,c,d){if(a!=null){var e=0;for(var f;f=a.ch",
    L"ildNodes[e];e++){if(b(f)){c.push(f);if(d)return true}if(P(f,b,c,d))retu",
    L"rn true}}return false}function ia(a,b,c,d){if(!c)a=a.parentNode;c=d==nu",
    L"ll;for(var e=0;a&&(c||e<=d);){if(b(a))return a;a=a.parentNode;e++}retur",
    L"n null};function ja(a,b){try{var c;if(typeof b.selectSingleNode!=\"unde",
    L"fined\"){var d=O(b);typeof d.setProperty!=\"undefined\"&&d.setProperty(",
    L"\"SelectionLanguage\",\"XPath\");c=b.selectSingleNode(a)}else if(docume",
    L"nt.implementation.hasFeature(\"XPath\",\"3.0\")){d=O(b);var e=d.createN",
    L"SResolver(d.documentElement);c=d.evaluate(a,b,e,XPathResult.FIRST_ORDER",
    L"ED_NODE_TYPE,null).singleNodeValue}else c=null}catch(f){return null}if(",
    L"!c)return null;if(c.nodeType!=1)throw Error(\"Returned node is not an e",
    L"lement: \"+a);return c};var Q=\"StopIteration\"in g?g.StopIteration:Err",
    L"or(\"StopIteration\");function ka(){}ka.prototype.next=function(){throw",
    L" Q;};function R(a,b,c,d,e){this.a=!!b;a&&S(this,a,d);this.d=e!=undefine",
    L"d?e:this.c||0;if(this.a)this.d*=-1;this.f=!c}k(R,ka);R.prototype.b=null",
    L";R.prototype.c=0;R.prototype.e=false;function S(a,b,c,d){if(a.b=b)a.c=t",
    L"ypeof c==\"number\"?c:a.b.nodeType!=1?0:a.a?-1:1;if(typeof d==\"number",
    L"\")a.d=d}\nR.prototype.next=function(){var a;if(this.e){if(!this.b||thi",
    L"s.f&&this.d==0)throw Q;a=this.b;var b=this.a?-1:1;if(this.c==b){var c=t",
    L"his.a?a.lastChild:a.firstChild;c?S(this,c):S(this,a,b*-1)}else(c=this.a",
    L"?a.previousSibling:a.nextSibling)?S(this,c):S(this,a.parentNode,b*-1);t",
    L"his.d+=this.c*(this.a?-1:1)}else this.e=true;a=this.b;if(!this.b)throw ",
    L"Q;return a};\nR.prototype.splice=function(){var a=this.b,b=this.a?1:-1;",
    L"if(this.c==b){this.c=b*-1;this.d+=this.c*(this.a?-1:1)}this.a=!this.a;R",
    L".prototype.next.call(this);this.a=!this.a;b=arguments[0];var c=h(b);b=c",
    L"==\"array\"||c==\"object\"&&typeof b.length==\"number\"?arguments[0]:ar",
    L"guments;for(c=b.length-1;c>=0;c--)a.parentNode&&a.parentNode.insertBefo",
    L"re(b[c],a.nextSibling);a&&a.parentNode&&a.parentNode.removeChild(a)};fu",
    L"nction T(a,b,c,d){R.call(this,a,b,c,null,d)}k(T,R);T.prototype.next=fun",
    L"ction(){do T.g.next.call(this);while(this.c==-1);return this.b};functio",
    L"n la(a,b){var c=O(a);if(c.defaultView&&c.defaultView.getComputedStyle)i",
    L"f(c=c.defaultView.getComputedStyle(a,null))return c[b]||c.getPropertyVa",
    L"lue(b);return\"\"};function U(a,b){return!!a&&a.nodeType==1&&(!b||a.tag",
    L"Name.toUpperCase()==b)}\nvar ma=[\"async\",\"autofocus\",\"autoplay\",",
    L"\"checked\",\"compact\",\"complete\",\"controls\",\"declare\",\"default",
    L"checked\",\"defaultselected\",\"defer\",\"disabled\",\"draggable\",\"en",
    L"ded\",\"formnovalidate\",\"hidden\",\"indeterminate\",\"iscontenteditab",
    L"le\",\"ismap\",\"itemscope\",\"loop\",\"multiple\",\"muted\",\"nohref\"",
    L",\"noresize\",\"noshade\",\"novalidate\",\"nowrap\",\"open\",\"paused\"",
    L",\"pubdate\",\"readonly\",\"required\",\"reversed\",\"scoped\",\"seamle",
    L"ss\",\"seeking\",\"selected\",\"spellcheck\",\"truespeed\",\"willvalida",
    L"te\"];\nfunction na(a,b){if(8==a.nodeType)return null;b=b.toLowerCase()",
    L";if(b==\"style\"){var c=m(a.style.cssText).toLowerCase();return c.charA",
    L"t(c.length-1)==\";\"?c:c+\";\"}c=a.getAttributeNode(b);if(C)if(!c&&M(8)",
    L"&&s(ma,b)>=0)c=a[b];if(!c)return null;if(s(ma,b)>=0)return C&&c.value==",
    L"\"false\"?null:\"true\";return c.specified?c.value:null}function V(a){f",
    L"or(a=a.parentNode;a&&a.nodeType!=1&&a.nodeType!=9&&a.nodeType!=11;)a=a.",
    L"parentNode;return U(a)?a:null}function W(a,b){b=ba(String(b));return la",
    L"(a,b)||oa(a,b)}\nfunction oa(a,b){var c=(a.currentStyle||a.style)[b];if",
    L"(c!=\"inherit\")return c!==undefined?c:null;return(c=V(a))?oa(c,b):null",
    L"}\nfunction sa(a){if(h(a.getBBox)==\"function\")return a.getBBox();var ",
    L"b;var c=B&&!M(\"10\");if((la(a,\"display\")||(a.currentStyle?a.currentS",
    L"tyle.display:null)||a.style.display)!=\"none\")b=c?new N(a.offsetWidth|",
    L"|a.clientWidth,a.offsetHeight||a.clientHeight):new N(a.offsetWidth,a.of",
    L"fsetHeight);else{b=a.style;var d=b.display,e=b.visibility,f=b.position;",
    L"b.visibility=\"hidden\";b.position=\"absolute\";b.display=\"inline\";if",
    L"(c){c=a.offsetWidth||a.clientWidth;a=a.offsetHeight||a.clientHeight}els",
    L"e{c=a.offsetWidth;a=a.offsetHeight}b.display=\nd;b.position=f;b.visibil",
    L"ity=e;b=new N(c,a)}return b}\nfunction X(a){function b(e){if(W(e,\"disp",
    L"lay\")==\"none\")return false;e=V(e);return!e||b(e)}function c(e){var f",
    L"=sa(e);if(f.height>0&&f.width>0)return true;if(e.innerText||e.textConte",
    L"nt)return true;return D&&ea(e.childNodes,function(i){return U(i)&&c(i)}",
    L")}if(!U(a))throw Error(\"Argument to isShown must be of type Element\")",
    L";if(U(a,\"TITLE\"))return(O(a)?O(a).parentWindow||O(a).defaultView:wind",
    L"ow)==g;if(U(a,\"OPTION\")||U(a,\"OPTGROUP\")){var d=ia(a,function(e){re",
    L"turn U(e,\"SELECT\")});return!!d&&X(d)}if(U(a,\"MAP\")){if(!a.name)retu",
    L"rn false;\nd=O(a);d=d.evaluate?ja('/descendant::*[@usemap = \"#'+a.name",
    L"+'\"]',d):ha(d,function(e){return U(e)&&na(e,\"usemap\")==\"#\"+a.name}",
    L");return!!d&&X(d)}if(U(a,\"AREA\")){d=ia(a,function(e){return U(e,\"MAP",
    L"\")});return!!d&&X(d)}if(U(a,\"INPUT\")&&a.type.toLowerCase()==\"hidden",
    L"\")return false;if(W(a,\"visibility\")==\"hidden\")return false;if(!b(a",
    L"))return false;if(ta(a)==0)return false;if(!c(a))return false;return tr",
    L"ue}\nfunction ua(a,b){if(U(a,\"BR\"))b.push(\"\");else{var c=va(a);c&&b",
    L"[b.length-1]&&b.push(\"\");ca(a.childNodes,function(d){if(d.nodeType==3",
    L"){var e=V(d);if(e&&X(e)){d=d.nodeValue.replace(wa,\" \");e=b.pop();var ",
    L"f=e.length-1;if(f>=0&&e.indexOf(\" \",f)==f&&d.lastIndexOf(\" \",0)==0)",
    L"d=d.substr(1);b.push(e+d)}}else U(d)&&ua(d,b)});c&&b[b.length-1]&&b.pus",
    L"h(\"\")}}function va(a){a=W(a,\"display\");return a==\"block\"||a==\"in",
    L"line-block\"}var wa=RegExp(\"[\\\\s\\\\xa0\"+String.fromCharCode(160)+",
    L"\"]+\",\"g\");\nfunction ta(a){if(C){if(W(a,\"position\")==\"relative\"",
    L")return 1;a=W(a,\"filter\");return(a=a.match(/^alpha\\(opacity=(\\d*)",
    L"\\)/)||a.match(/^progid:DXImageTransform.Microsoft.Alpha\\(Opacity=(\\d",
    L"*)\\)/))?Number(a[1])/100:1}else return xa(a)}function xa(a){var b=1,c=",
    L"W(a,\"opacity\");if(c)b=Number(c);if(a=V(a))b*=xa(a);return b};\nfuncti",
    L"on ya(a){for(;a;){if(a.tagName&&a.tagName.toLowerCase()==\"head\")retur",
    L"n true;try{a=a.parentNode}catch(b){return false}}return false};function",
    L" za(a){if(ya(a)){var b=O(a);if(a.tagName.toUpperCase()==\"TITLE\"&&(b?b",
    L".parentWindow||b.defaultView:window)==g.top)return m(b.title);return\"",
    L"\"}b=[\"\"];ua(a,b);b=da(b,m);return m(b.join(\"\\n\"))}var Y=\"_\".spl",
    L"it(\".\"),Z=g;!(Y[0]in Z)&&Z.execScript&&Z.execScript(\"var \"+Y[0]);fo",
    L"r(var $;Y.length&&($=Y.shift());)if(!Y.length&&za!==undefined)Z[$]=za;e",
    L"lse Z=Z[$]?Z[$]:Z[$]={};; return _.apply(null,arguments);}",
    NULL
};

const wchar_t* const IS_DISPLAYED[] = {
    L"function(){var g=this;\nfunction h(a){var b=typeof a;if(b==\"object\")i",
    L"f(a){if(a instanceof Array)return\"array\";else if(a instanceof Object)",
    L"return b;var c=Object.prototype.toString.call(a);if(c==\"[object Window",
    L"]\")return\"object\";if(c==\"[object Array]\"||typeof a.length==\"numbe",
    L"r\"&&typeof a.splice!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"u",
    L"ndefined\"&&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(c==",
    L"\"[object Function]\"||typeof a.call!=\"undefined\"&&typeof a.propertyI",
    L"sEnumerable!=\"undefined\"&&!a.propertyIsEnumerable(\"call\"))return\"f",
    L"unction\"}else return\"null\";else if(b==\n\"function\"&&typeof a.call=",
    L"=\"undefined\")return\"object\";return b}function i(a,b){function c(){}",
    L"c.prototype=b.prototype;a.g=b.prototype;a.prototype=new c};function j(a",
    L"){this.stack=Error().stack||\"\";if(a)this.message=String(a)}i(j,Error)",
    L";j.prototype.name=\"CustomError\";function aa(a){for(var b=1;b<argument",
    L"s.length;b++){var c=String(arguments[b]).replace(/\\$/g,\"$$$$\");a=a.r",
    L"eplace(/\\%s/,c)}return a}function k(a){return a.replace(/^[\\s\\xa0]+|",
    L"[\\s\\xa0]+$/g,\"\")}function l(a,b){if(a<b)return-1;else if(a>b)return",
    L" 1;return 0}var m={};function ba(a){return m[a]||(m[a]=String(a).replac",
    L"e(/\\-([a-z])/g,function(b,c){return c.toUpperCase()}))};function n(a,b",
    L"){b.unshift(a);j.call(this,aa.apply(null,b));b.shift();this.h=a}i(n,j);",
    L"n.prototype.name=\"AssertionError\";function q(a,b){if(!a){var c=Array.",
    L"prototype.slice.call(arguments,2),d=\"Assertion failed\";if(b){d+=\": ",
    L"\"+b;var e=c}throw new n(\"\"+d,e||[]);}return a};var r=Array.prototype",
    L",s=r.indexOf?function(a,b,c){q(a.length!=null);return r.indexOf.call(a,",
    L"b,c)}:function(a,b,c){c=c==null?0:c<0?Math.max(0,a.length+c):c;if(typeo",
    L"f a==\"string\"){if(typeof b!=\"string\"||b.length!=1)return-1;return a",
    L".indexOf(b,c)}for(c=c;c<a.length;c++)if(c in a&&a[c]===b)return c;retur",
    L"n-1},ca=r.some?function(a,b,c){q(a.length!=null);return r.some.call(a,b",
    L",c)}:function(a,b,c){var d=a.length,e=typeof a==\"string\"?a.split(\"\"",
    L"):a;for(var f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return true;\nret",
    L"urn false};var t,u,v,w;function x(){return g.navigator?g.navigator.user",
    L"Agent:null}w=v=u=t=false;var y;if(y=x()){var da=g.navigator;t=y.indexOf",
    L"(\"Opera\")==0;u=!t&&y.indexOf(\"MSIE\")!=-1;v=!t&&y.indexOf(\"WebKit\"",
    L")!=-1;w=!t&&!v&&da.product==\"Gecko\"}var z=t,A=u,ea=w,C=v,D;\na:{var E",
    L"=\"\",F;if(z&&g.opera){var G=g.opera.version;E=typeof G==\"function\"?G",
    L"():G}else{if(ea)F=/rv\\:([^\\);]+)(\\)|;)/;else if(A)F=/MSIE\\s+([^\\);",
    L"]+)(\\)|;)/;else if(C)F=/WebKit\\/(\\S+)/;if(F){var H=F.exec(x());E=H?H",
    L"[1]:\"\"}}if(A){var I,J=g.document;I=J?J.documentMode:undefined;if(I>pa",
    L"rseFloat(E)){D=String(I);break a}}D=E}var K={};\nfunction L(a){var b;if",
    L"(!(b=K[a])){b=0;var c=k(String(D)).split(\".\"),d=k(String(a)).split(\"",
    L".\"),e=Math.max(c.length,d.length);for(var f=0;b==0&&f<e;f++){var B=c[f",
    L"]||\"\",la=d[f]||\"\",ma=RegExp(\"(\\\\d*)(\\\\D*)\",\"g\"),na=RegExp(",
    L"\"(\\\\d*)(\\\\D*)\",\"g\");do{var o=ma.exec(B)||[\"\",\"\",\"\"],p=na.",
    L"exec(la)||[\"\",\"\",\"\"];if(o[0].length==0&&p[0].length==0)break;b=l(",
    L"o[1].length==0?0:parseInt(o[1],10),p[1].length==0?0:parseInt(p[1],10))|",
    L"|l(o[2].length==0,p[2].length==0)||l(o[2],p[2])}while(b==0)}b=K[a]=b>=0",
    L"}return b};!A||L(\"9\");A&&L(\"9\");function M(a,b){this.width=a;this.h",
    L"eight=b}M.prototype.toString=function(){return\"(\"+this.width+\" x \"+",
    L"this.height+\")\"};function N(a){return a.nodeType==9?a:a.ownerDocument",
    L"||a.document}function fa(a,b){var c=[];return O(a,b,c,true)?c[0]:undefi",
    L"ned}function O(a,b,c,d){if(a!=null){var e=0;for(var f;f=a.childNodes[e]",
    L";e++){if(b(f)){c.push(f);if(d)return true}if(O(f,b,c,d))return true}}re",
    L"turn false}function P(a,b,c,d){if(!c)a=a.parentNode;c=d==null;for(var e",
    L"=0;a&&(c||e<=d);){if(b(a))return a;a=a.parentNode;e++}return null};func",
    L"tion ga(a,b){try{var c;if(typeof b.selectSingleNode!=\"undefined\"){var",
    L" d=N(b);typeof d.setProperty!=\"undefined\"&&d.setProperty(\"SelectionL",
    L"anguage\",\"XPath\");c=b.selectSingleNode(a)}else if(document.implement",
    L"ation.hasFeature(\"XPath\",\"3.0\")){d=N(b);var e=d.createNSResolver(d.",
    L"documentElement);c=d.evaluate(a,b,e,XPathResult.FIRST_ORDERED_NODE_TYPE",
    L",null).singleNodeValue}else c=null}catch(f){return null}if(!c)return nu",
    L"ll;if(c.nodeType!=1)throw Error(\"Returned node is not an element: \"+a",
    L");return c};var Q=\"StopIteration\"in g?g.StopIteration:Error(\"StopIte",
    L"ration\");function ha(){}ha.prototype.next=function(){throw Q;};functio",
    L"n R(a,b,c,d,e){this.a=!!b;a&&S(this,a,d);this.d=e!=undefined?e:this.c||",
    L"0;if(this.a)this.d*=-1;this.f=!c}i(R,ha);R.prototype.b=null;R.prototype",
    L".c=0;R.prototype.e=false;function S(a,b,c,d){if(a.b=b)a.c=typeof c==\"n",
    L"umber\"?c:a.b.nodeType!=1?0:a.a?-1:1;if(typeof d==\"number\")a.d=d}\nR.",
    L"prototype.next=function(){var a;if(this.e){if(!this.b||this.f&&this.d==",
    L"0)throw Q;a=this.b;var b=this.a?-1:1;if(this.c==b){var c=this.a?a.lastC",
    L"hild:a.firstChild;c?S(this,c):S(this,a,b*-1)}else(c=this.a?a.previousSi",
    L"bling:a.nextSibling)?S(this,c):S(this,a.parentNode,b*-1);this.d+=this.c",
    L"*(this.a?-1:1)}else this.e=true;a=this.b;if(!this.b)throw Q;return a};",
    L"\nR.prototype.splice=function(){var a=this.b,b=this.a?1:-1;if(this.c==b",
    L"){this.c=b*-1;this.d+=this.c*(this.a?-1:1)}this.a=!this.a;R.prototype.n",
    L"ext.call(this);this.a=!this.a;b=arguments[0];var c=h(b);b=c==\"array\"|",
    L"|c==\"object\"&&typeof b.length==\"number\"?arguments[0]:arguments;for(",
    L"c=b.length-1;c>=0;c--)a.parentNode&&a.parentNode.insertBefore(b[c],a.ne",
    L"xtSibling);a&&a.parentNode&&a.parentNode.removeChild(a)};function T(a,b",
    L",c,d){R.call(this,a,b,c,null,d)}i(T,R);T.prototype.next=function(){do T",
    L".g.next.call(this);while(this.c==-1);return this.b};function ia(a,b){va",
    L"r c=N(a);if(c.defaultView&&c.defaultView.getComputedStyle)if(c=c.defaul",
    L"tView.getComputedStyle(a,null))return c[b]||c.getPropertyValue(b);retur",
    L"n\"\"};function U(a,b){return!!a&&a.nodeType==1&&(!b||a.tagName.toUpper",
    L"Case()==b)}\nvar ja=[\"async\",\"autofocus\",\"autoplay\",\"checked\",",
    L"\"compact\",\"complete\",\"controls\",\"declare\",\"defaultchecked\",\"",
    L"defaultselected\",\"defer\",\"disabled\",\"draggable\",\"ended\",\"form",
    L"novalidate\",\"hidden\",\"indeterminate\",\"iscontenteditable\",\"ismap",
    L"\",\"itemscope\",\"loop\",\"multiple\",\"muted\",\"nohref\",\"noresize",
    L"\",\"noshade\",\"novalidate\",\"nowrap\",\"open\",\"paused\",\"pubdate",
    L"\",\"readonly\",\"required\",\"reversed\",\"scoped\",\"seamless\",\"see",
    L"king\",\"selected\",\"spellcheck\",\"truespeed\",\"willvalidate\"];\nfu",
    L"nction ka(a,b){if(8==a.nodeType)return null;b=b.toLowerCase();if(b==\"s",
    L"tyle\"){var c=k(a.style.cssText).toLowerCase();return c.charAt(c.length",
    L"-1)==\";\"?c:c+\";\"}c=a.getAttributeNode(b);if(A)if(!c&&L(8)&&s(ja,b)>",
    L"=0)c=a[b];if(!c)return null;if(s(ja,b)>=0)return A&&c.value==\"false\"?",
    L"null:\"true\";return c.specified?c.value:null}function V(a){for(a=a.par",
    L"entNode;a&&a.nodeType!=1&&a.nodeType!=9&&a.nodeType!=11;)a=a.parentNode",
    L";return U(a)?a:null}function W(a,b){b=ba(String(b));return ia(a,b)||oa(",
    L"a,b)}\nfunction oa(a,b){var c=(a.currentStyle||a.style)[b];if(c!=\"inhe",
    L"rit\")return c!==undefined?c:null;return(c=V(a))?oa(c,b):null}\nfunctio",
    L"n pa(a){if(h(a.getBBox)==\"function\")return a.getBBox();var b;var c=z&",
    L"&!L(\"10\");if((ia(a,\"display\")||(a.currentStyle?a.currentStyle.displ",
    L"ay:null)||a.style.display)!=\"none\")b=c?new M(a.offsetWidth||a.clientW",
    L"idth,a.offsetHeight||a.clientHeight):new M(a.offsetWidth,a.offsetHeight",
    L");else{b=a.style;var d=b.display,e=b.visibility,f=b.position;b.visibili",
    L"ty=\"hidden\";b.position=\"absolute\";b.display=\"inline\";if(c){c=a.of",
    L"fsetWidth||a.clientWidth;a=a.offsetHeight||a.clientHeight}else{c=a.offs",
    L"etWidth;a=a.offsetHeight}b.display=\nd;b.position=f;b.visibility=e;b=ne",
    L"w M(c,a)}return b}\nfunction X(a){function b(e){if(W(e,\"display\")==\"",
    L"none\")return false;e=V(e);return!e||b(e)}function c(e){var f=pa(e);if(",
    L"f.height>0&&f.width>0)return true;if(e.innerText||e.textContent)return ",
    L"true;return C&&ca(e.childNodes,function(B){return U(B)&&c(B)})}if(!U(a)",
    L")throw Error(\"Argument to isShown must be of type Element\");if(U(a,\"",
    L"TITLE\"))return(N(a)?N(a).parentWindow||N(a).defaultView:window)==g;if(",
    L"U(a,\"OPTION\")||U(a,\"OPTGROUP\")){var d=P(a,function(e){return U(e,\"",
    L"SELECT\")});return!!d&&X(d)}if(U(a,\"MAP\")){if(!a.name)return false;\n",
    L"d=N(a);d=d.evaluate?ga('/descendant::*[@usemap = \"#'+a.name+'\"]',d):f",
    L"a(d,function(e){return U(e)&&ka(e,\"usemap\")==\"#\"+a.name});return!!d",
    L"&&X(d)}if(U(a,\"AREA\")){d=P(a,function(e){return U(e,\"MAP\")});return",
    L"!!d&&X(d)}if(U(a,\"INPUT\")&&a.type.toLowerCase()==\"hidden\")return fa",
    L"lse;if(W(a,\"visibility\")==\"hidden\")return false;if(!b(a))return fal",
    L"se;if(qa(a)==0)return false;if(!c(a))return false;return true}String.fr",
    L"omCharCode(160);\nfunction qa(a){if(A){if(W(a,\"position\")==\"relative",
    L"\")return 1;a=W(a,\"filter\");return(a=a.match(/^alpha\\(opacity=(\\d*)",
    L"\\)/)||a.match(/^progid:DXImageTransform.Microsoft.Alpha\\(Opacity=(\\d",
    L"*)\\)/))?Number(a[1])/100:1}else return ra(a)}function ra(a){var b=1,c=",
    L"W(a,\"opacity\");if(c)b=Number(c);if(a=V(a))b*=ra(a);return b};var sa=X",
    L",Y=\"_\".split(\".\"),Z=g;!(Y[0]in Z)&&Z.execScript&&Z.execScript(\"var",
    L" \"+Y[0]);for(var $;Y.length&&($=Y.shift());)if(!Y.length&&sa!==undefin",
    L"ed)Z[$]=sa;else Z=Z[$]?Z[$]:Z[$]={};; return _.apply(null,arguments);}",
    NULL
};

const wchar_t* const IS_ENABLED[] = {
    L"function(){var e=this;function f(a,b){function c(){}c.prototype=b.proto",
    L"type;a.g=b.prototype;a.prototype=new c};function h(a){this.stack=Error(",
    L").stack||\"\";if(a)this.message=String(a)}f(h,Error);function i(a){for(",
    L"var b=1;b<arguments.length;b++){var c=String(arguments[b]).replace(/\\$",
    L"/g,\"$$$$\");a=a.replace(/\\%s/,c)}return a}function j(a){return a.repl",
    L"ace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\")}function m(a,b){if(a<b)return-1;",
    L"else if(a>b)return 1;return 0};function n(a,b){b.unshift(a);h.call(this",
    L",i.apply(null,b));b.shift();this.f=a}f(n,h);function o(a,b){if(!a){var ",
    L"c=Array.prototype.slice.call(arguments,2),d=\"Assertion failed\";if(b){",
    L"d+=\": \"+b;var g=c}throw new n(\"\"+d,g||[]);}return a};var p=Array.pr",
    L"ototype,q=p.indexOf?function(a,b,c){o(a.length!=null);return p.indexOf.",
    L"call(a,b,c)}:function(a,b,c){c=c==null?0:c<0?Math.max(0,a.length+c):c;i",
    L"f(typeof a==\"string\"){if(typeof b!=\"string\"||b.length!=1)return-1;r",
    L"eturn a.indexOf(b,c)}for(c=c;c<a.length;c++)if(c in a&&a[c]===b)return ",
    L"c;return-1};var r,s,u,v;function w(){return e.navigator?e.navigator.use",
    L"rAgent:null}v=u=s=r=false;var x;if(x=w()){var y=e.navigator;r=x.indexOf",
    L"(\"Opera\")==0;s=!r&&x.indexOf(\"MSIE\")!=-1;u=!r&&x.indexOf(\"WebKit\"",
    L")!=-1;v=!r&&!u&&y.product==\"Gecko\"}var z=s,A=v,B=u,C;\na:{var D=\"\",",
    L"E;if(r&&e.opera){var F=e.opera.version;D=typeof F==\"function\"?F():F}e",
    L"lse{if(A)E=/rv\\:([^\\);]+)(\\)|;)/;else if(z)E=/MSIE\\s+([^\\);]+)(\\)",
    L"|;)/;else if(B)E=/WebKit\\/(\\S+)/;if(E){var G=E.exec(w());D=G?G[1]:\"",
    L"\"}}if(z){var H,I=e.document;H=I?I.documentMode:undefined;if(H>parseFlo",
    L"at(D)){C=String(H);break a}}C=D}var J={};\nfunction K(a){var b;if(!(b=J",
    L"[a])){b=0;var c=j(String(C)).split(\".\"),d=j(String(a)).split(\".\"),g",
    L"=Math.max(c.length,d.length);for(var t=0;b==0&&t<g;t++){var S=c[t]||\"",
    L"\",T=d[t]||\"\",U=RegExp(\"(\\\\d*)(\\\\D*)\",\"g\"),V=RegExp(\"(\\\\d*",
    L")(\\\\D*)\",\"g\");do{var k=U.exec(S)||[\"\",\"\",\"\"],l=V.exec(T)||[",
    L"\"\",\"\",\"\"];if(k[0].length==0&&l[0].length==0)break;b=m(k[1].length",
    L"==0?0:parseInt(k[1],10),l[1].length==0?0:parseInt(l[1],10))||m(k[2].len",
    L"gth==0,l[2].length==0)||m(k[2],l[2])}while(b==0)}b=J[a]=b>=0}return b};",
    L"!z||K(\"9\");z&&K(\"9\");function L(a,b,c,d,g){this.c=!!b;if(a){if(this",
    L".b=a)this.d=typeof d==\"number\"?d:this.b.nodeType!=1?0:this.c?-1:1;if(",
    L"typeof void 0==\"number\")this.a=void 0}this.a=g!=undefined?g:this.d||0",
    L";if(this.c)this.a*=-1;this.e=!c}f(L,function(){});L.prototype.b=null;L.",
    L"prototype.d=0;f(function(a,b,c,d){L.call(this,a,b,c,null,d)},L);var M=[",
    L"\"async\",\"autofocus\",\"autoplay\",\"checked\",\"compact\",\"complete",
    L"\",\"controls\",\"declare\",\"defaultchecked\",\"defaultselected\",\"de",
    L"fer\",\"disabled\",\"draggable\",\"ended\",\"formnovalidate\",\"hidden",
    L"\",\"indeterminate\",\"iscontenteditable\",\"ismap\",\"itemscope\",\"lo",
    L"op\",\"multiple\",\"muted\",\"nohref\",\"noresize\",\"noshade\",\"noval",
    L"idate\",\"nowrap\",\"open\",\"paused\",\"pubdate\",\"readonly\",\"requi",
    L"red\",\"reversed\",\"scoped\",\"seamless\",\"seeking\",\"selected\",\"s",
    L"pellcheck\",\"truespeed\",\"willvalidate\"];\nfunction N(a,b){if(8==a.n",
    L"odeType)return null;b=b.toLowerCase();if(b==\"style\"){var c=j(a.style.",
    L"cssText).toLowerCase();return c.charAt(c.length-1)==\";\"?c:c+\";\"}c=a",
    L".getAttributeNode(b);if(z)if(!c&&K(8)&&q(M,b)>=0)c=a[b];if(!c)return nu",
    L"ll;if(q(M,b)>=0)return z&&c.value==\"false\"?null:\"true\";return c.spe",
    L"cified?c.value:null}var O=[\"BUTTON\",\"INPUT\",\"OPTGROUP\",\"OPTION\"",
    L",\"SELECT\",\"TEXTAREA\"];\nfunction P(a){var b=a.tagName.toUpperCase()",
    L";if(!(q(O,b)>=0))return true;if(N(a,\"disabled\"))return false;if(a.par",
    L"entNode&&a.parentNode.nodeType==1&&\"OPTGROUP\"==b||\"OPTION\"==b)retur",
    L"n P(a.parentNode);return true}String.fromCharCode(160);var Q=P,R=\"_\".",
    L"split(\".\"),W=e;!(R[0]in W)&&W.execScript&&W.execScript(\"var \"+R[0])",
    L";for(var X;R.length&&(X=R.shift());)if(!R.length&&Q!==undefined)W[X]=Q;",
    L"else W=W[X]?W[X]:W[X]={};; return _.apply(null,arguments);}",
    NULL
};

const wchar_t* const IS_SELECTED[] = {
    L"function(){var e=this;function f(a,b){function c(){}c.prototype=b.proto",
    L"type;a.g=b.prototype;a.prototype=new c};function h(a){this.stack=Error(",
    L").stack||\"\";if(a)this.message=String(a)}f(h,Error);function k(a){for(",
    L"var b=1;b<arguments.length;b++){var c=String(arguments[b]).replace(/\\$",
    L"/g,\"$$$$\");a=a.replace(/\\%s/,c)}return a}\nfunction l(a,b){var c=0,d",
    L"=String(a).replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").split(\".\"),g=St",
    L"ring(b).replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").split(\".\"),K=Math.",
    L"max(d.length,g.length);for(var p=0;c==0&&p<K;p++){var L=d[p]||\"\",M=g[",
    L"p]||\"\",N=RegExp(\"(\\\\d*)(\\\\D*)\",\"g\"),O=RegExp(\"(\\\\d*)(\\\\D",
    L"*)\",\"g\");do{var i=N.exec(L)||[\"\",\"\",\"\"],j=O.exec(M)||[\"\",\"",
    L"\",\"\"];if(i[0].length==0&&j[0].length==0)break;c=m(i[1].length==0?0:p",
    L"arseInt(i[1],10),j[1].length==0?0:parseInt(j[1],10))||m(i[2].length==0,",
    L"j[2].length==0)||m(i[2],j[2])}while(c==\n0)}return c}function m(a,b){if",
    L"(a<b)return-1;else if(a>b)return 1;return 0};function n(a,b){b.unshift(",
    L"a);h.call(this,k.apply(null,b));b.shift();this.f=a}f(n,h);function o(a,",
    L"b){if(!a){var c=Array.prototype.slice.call(arguments,2),d=\"Assertion f",
    L"ailed\";if(b){d+=\": \"+b;var g=c}throw new n(\"\"+d,g||[]);}return a};",
    L"var q=Array.prototype,r=q.indexOf?function(a,b,c){o(a.length!=null);ret",
    L"urn q.indexOf.call(a,b,c)}:function(a,b,c){c=c==null?0:c<0?Math.max(0,a",
    L".length+c):c;if(typeof a==\"string\"){if(typeof b!=\"string\"||b.length",
    L"!=1)return-1;return a.indexOf(b,c)}for(c=c;c<a.length;c++)if(c in a&&a[",
    L"c]===b)return c;return-1};var s,t,u,v;function w(){return e.navigator?e",
    L".navigator.userAgent:null}v=u=t=s=false;var x;if(x=w()){var y=e.navigat",
    L"or;s=x.indexOf(\"Opera\")==0;t=!s&&x.indexOf(\"MSIE\")!=-1;u=!s&&x.inde",
    L"xOf(\"WebKit\")!=-1;v=!s&&!u&&y.product==\"Gecko\"}var z=t,A=v,B=u,C;\n",
    L"a:{var D=\"\",E;if(s&&e.opera){var F=e.opera.version;D=typeof F==\"func",
    L"tion\"?F():F}else{if(A)E=/rv\\:([^\\);]+)(\\)|;)/;else if(z)E=/MSIE\\s+",
    L"([^\\);]+)(\\)|;)/;else if(B)E=/WebKit\\/(\\S+)/;if(E){var G=E.exec(w()",
    L");D=G?G[1]:\"\"}}if(z){var H,I=e.document;H=I?I.documentMode:undefined;",
    L"if(H>parseFloat(D)){C=String(H);break a}}C=D}var J={};!z||J[\"9\"]||(J[",
    L"\"9\"]=l(C,\"9\")>=0);z&&(J[\"9\"]||(J[\"9\"]=l(C,\"9\")>=0));function ",
    L"P(a,b,c,d,g){this.c=!!b;if(a){if(this.b=a)this.d=typeof d==\"number\"?d",
    L":this.b.nodeType!=1?0:this.c?-1:1;if(typeof void 0==\"number\")this.a=v",
    L"oid 0}this.a=g!=undefined?g:this.d||0;if(this.c)this.a*=-1;this.e=!c}f(",
    L"P,function(){});P.prototype.b=null;P.prototype.d=0;f(function(a,b,c,d){",
    L"P.call(this,a,b,c,null,d)},P);String.fromCharCode(160);\nvar Q=[\"check",
    L"box\",\"radio\"];function R(a){var b;a:{b=a.tagName.toUpperCase();if(b=",
    L"=\"OPTION\")b=true;else{if(b==\"INPUT\")if(r(Q,a.type)>=0){b=true;break",
    L" a}b=false}}if(!b)return false;b=\"selected\";var c=a.type&&a.type.toLo",
    L"werCase();if(\"checkbox\"==c||\"radio\"==c)b=\"checked\";return!!a[b]}v",
    L"ar S=\"_\".split(\".\"),T=e;!(S[0]in T)&&T.execScript&&T.execScript(\"v",
    L"ar \"+S[0]);for(var U;S.length&&(U=S.shift());)if(!S.length&&R!==undefi",
    L"ned)T[U]=R;else T=T[U]?T[U]:T[U]={};; return _.apply(null,arguments);}",
    NULL
};

const wchar_t* const SUBMIT[] = {
    L"function(){var i=this;\nfunction j(a){var b=typeof a;if(b==\"object\")i",
    L"f(a){if(a instanceof Array)return\"array\";else if(a instanceof Object)",
    L"return b;var c=Object.prototype.toString.call(a);if(c==\"[object Window",
    L"]\")return\"object\";if(c==\"[object Array]\"||typeof a.length==\"numbe",
    L"r\"&&typeof a.splice!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"u",
    L"ndefined\"&&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(c==",
    L"\"[object Function]\"||typeof a.call!=\"undefined\"&&typeof a.propertyI",
    L"sEnumerable!=\"undefined\"&&!a.propertyIsEnumerable(\"call\"))return\"f",
    L"unction\"}else return\"null\";else if(b==\n\"function\"&&typeof a.call=",
    L"=\"undefined\")return\"object\";return b}Math.floor(Math.random()*21474",
    L"83648).toString(36);function m(a,b){function c(){}c.prototype=b.prototy",
    L"pe;a.g=b.prototype;a.prototype=new c};function n(a){this.stack=Error().",
    L"stack||\"\";if(a)this.message=String(a)}m(n,Error);n.prototype.name=\"C",
    L"ustomError\";function p(a,b){n.call(this,b);this.code=a;this.name=q[a]|",
    L"|q[13]}m(p,n);var q,r={NoSuchElementError:7,NoSuchFrameError:8,UnknownC",
    L"ommandError:9,StaleElementReferenceError:10,ElementNotVisibleError:11,I",
    L"nvalidElementStateError:12,UnknownError:13,ElementNotSelectableError:15",
    L",XPathLookupError:19,NoSuchWindowError:23,InvalidCookieDomainError:24,U",
    L"nableToSetCookieError:25,ModalDialogOpenedError:26,ModalDialogOpenError",
    L":27,ScriptTimeoutError:28},s={};for(var t in r)s[r[t]]=t;q=s;\np.protot",
    L"ype.toString=function(){return\"[\"+this.name+\"] \"+this.message};func",
    L"tion aa(a){for(var b=1;b<arguments.length;b++){var c=String(arguments[b",
    L"]).replace(/\\$/g,\"$$$$\");a=a.replace(/\\%s/,c)}return a}\nfunction u",
    L"(a,b){var c=0,d=String(a).replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").sp",
    L"lit(\".\"),e=String(b).replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").split",
    L"(\".\"),f=Math.max(d.length,e.length);for(var g=0;c==0&&g<f;g++){var h=",
    L"d[g]||\"\",o=e[g]||\"\",v=RegExp(\"(\\\\d*)(\\\\D*)\",\"g\"),w=RegExp(",
    L"\"(\\\\d*)(\\\\D*)\",\"g\");do{var k=v.exec(h)||[\"\",\"\",\"\"],l=w.ex",
    L"ec(o)||[\"\",\"\",\"\"];if(k[0].length==0&&l[0].length==0)break;c=x(k[1",
    L"].length==0?0:parseInt(k[1],10),l[1].length==0?0:parseInt(l[1],10))||x(",
    L"k[2].length==0,l[2].length==0)||x(k[2],l[2])}while(c==\n0)}return c}fun",
    L"ction x(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};function y(",
    L"a,b){b.unshift(a);n.call(this,aa.apply(null,b));b.shift();this.j=a}m(y,",
    L"n);y.prototype.name=\"AssertionError\";function ba(a,b){if(!a){var c=Ar",
    L"ray.prototype.slice.call(arguments,2),d=\"Assertion failed\";if(b){d+=",
    L"\": \"+b;var e=c}throw new y(\"\"+d,e||[]);}return a};var z=Array.proto",
    L"type,ca=z.indexOf?function(a,b,c){ba(a.length!=null);return z.indexOf.c",
    L"all(a,b,c)}:function(a,b,c){c=c==null?0:c<0?Math.max(0,a.length+c):c;if",
    L"(typeof a==\"string\"){if(typeof b!=\"string\"||b.length!=1)return-1;re",
    L"turn a.indexOf(b,c)}for(c=c;c<a.length;c++)if(c in a&&a[c]===b)return c",
    L";return-1};var A,B,C,D;function E(){return i.navigator?i.navigator.user",
    L"Agent:null}D=C=B=A=false;var F;if(F=E()){var da=i.navigator;A=F.indexOf",
    L"(\"Opera\")==0;B=!A&&F.indexOf(\"MSIE\")!=-1;C=!A&&F.indexOf(\"WebKit\"",
    L")!=-1;D=!A&&!C&&da.product==\"Gecko\"}var G=B,H=D,ea=C,I;\na:{var J=\"",
    L"\",K;if(A&&i.opera){var L=i.opera.version;J=typeof L==\"function\"?L():",
    L"L}else{if(H)K=/rv\\:([^\\);]+)(\\)|;)/;else if(G)K=/MSIE\\s+([^\\);]+)(",
    L"\\)|;)/;else if(ea)K=/WebKit\\/(\\S+)/;if(K){var M=K.exec(E());J=M?M[1]",
    L":\"\"}}if(G){var N,O=i.document;N=O?O.documentMode:undefined;if(N>parse",
    L"Float(J)){I=String(N);break a}}I=J}var P={};!G||P[\"9\"]||(P[\"9\"]=u(I",
    L",\"9\")>=0);G&&(P[\"9\"]||(P[\"9\"]=u(I,\"9\")>=0));function Q(a){retur",
    L"n a.nodeType==9?a:a.ownerDocument||a.document};var R=\"StopIteration\"i",
    L"n i?i.StopIteration:Error(\"StopIteration\");function fa(){}fa.prototyp",
    L"e.next=function(){throw R;};function S(a,b,c,d,e){this.a=!!b;a&&T(this,",
    L"a,d);this.d=e!=undefined?e:this.c||0;if(this.a)this.d*=-1;this.f=!c}m(S",
    L",fa);S.prototype.b=null;S.prototype.c=0;S.prototype.e=false;function T(",
    L"a,b,c,d){if(a.b=b)a.c=typeof c==\"number\"?c:a.b.nodeType!=1?0:a.a?-1:1",
    L";if(typeof d==\"number\")a.d=d}\nS.prototype.next=function(){var a;if(t",
    L"his.e){if(!this.b||this.f&&this.d==0)throw R;a=this.b;var b=this.a?-1:1",
    L";if(this.c==b){var c=this.a?a.lastChild:a.firstChild;c?T(this,c):T(this",
    L",a,b*-1)}else(c=this.a?a.previousSibling:a.nextSibling)?T(this,c):T(thi",
    L"s,a.parentNode,b*-1);this.d+=this.c*(this.a?-1:1)}else this.e=true;a=th",
    L"is.b;if(!this.b)throw R;return a};\nS.prototype.splice=function(){var a",
    L"=this.b,b=this.a?1:-1;if(this.c==b){this.c=b*-1;this.d+=this.c*(this.a?",
    L"-1:1)}this.a=!this.a;S.prototype.next.call(this);this.a=!this.a;b=argum",
    L"ents[0];var c=j(b);b=c==\"array\"||c==\"object\"&&typeof b.length==\"nu",
    L"mber\"?arguments[0]:arguments;for(c=b.length-1;c>=0;c--)a.parentNode&&a",
    L".parentNode.insertBefore(b[c],a.nextSibling);a&&a.parentNode&&a.parentN",
    L"ode.removeChild(a)};function U(a,b,c,d){S.call(this,a,b,c,null,d)}m(U,S",
    L");U.prototype.next=function(){do U.g.next.call(this);while(this.c==-1);",
    L"return this.b};String.fromCharCode(160);var ga=G?1:0,ha=[\"dragstart\",",
    L"\"dragexit\",\"mouseover\",\"mouseout\"];\nfunction V(a,b,c){var d=Q(a)",
    L",e=d?d.parentWindow||d.defaultView:window,f=c||{};c=f.x||0;var g=f.y||0",
    L",h=f.button||ga,o=f.bubble||true,v=null;if(ca(ha,b)>=0)v=f.related||nul",
    L"l;var w=!!f.alt,k=!!f.control,l=!!f.shift;f=!!f.meta;if(a.fireEvent&&d&",
    L"&d.createEventObject){a=d.createEventObject();a.altKey=w;a.h=k;a.metaKe",
    L"y=f;a.shiftKey=l;a.clientX=c;a.clientY=g;a.button=h;a.relatedTarget=v}e",
    L"lse{a=d.createEvent(\"MouseEvents\");if(a.initMouseEvent)a.initMouseEve",
    L"nt(b,o,true,e,1,0,0,c,g,k,w,l,f,h,v);else{a.initEvent(b,\no,true);a.shi",
    L"ftKey=l;a.metaKey=f;a.altKey=w;a.ctrlKey=k;a.button=h}}return a}functio",
    L"n W(a,b,c){var d=Q(a);a=d?d.parentWindow||d.defaultView:window;var e=c|",
    L"|{};c=e.keyCode||0;var f=e.charCode||0,g=!!e.alt,h=!!e.ctrl,o=!!e.shift",
    L";e=!!e.meta;if(H){d=d.createEvent(\"KeyboardEvent\");d.initKeyEvent(b,t",
    L"rue,true,a,h,g,o,e,c,f)}else{if(G)d=d.createEventObject();else{d=d.crea",
    L"teEvent(\"Events\");d.initEvent(b,true,true);d.charCode=f}d.keyCode=c;d",
    L".altKey=g;d.ctrlKey=h;d.metaKey=e;d.shiftKey=o}return d}\nfunction ia(a",
    L",b,c){var d=Q(a),e=c||{};c=e.bubble!==false;var f=!!e.alt,g=!!e.control",
    L",h=!!e.shift;e=!!e.meta;if(a.fireEvent&&d&&d.createEventObject){a=d.cre",
    L"ateEventObject();a.altKey=f;a.i=g;a.metaKey=e;a.shiftKey=h}else{a=d.cre",
    L"ateEvent(\"HTMLEvents\");a.initEvent(b,c,true);a.shiftKey=h;a.metaKey=e",
    L";a.altKey=f;a.ctrlKey=g}return a}var X={};X.click=V;X.keydown=W;X.keypr",
    L"ess=W;X.keyup=W;X.mousedown=V;X.mousemove=V;X.mouseout=V;X.mouseover=V;",
    L"X.mouseup=V;function ja(a){a:{a=a;for(var b=0;a;){if(a&&a.nodeType==1&&",
    L"a.tagName.toUpperCase()==\"FORM\"){a=a;break a}a=a.parentNode;b++}a=nul",
    L"l}if(!a)throw new p(12,\"Element was not in a form, so could not submit",
    L".\");b=a;var c=(X.submit||ia)(b,\"submit\",void 0),d;if(!(d=j(b.fireEve",
    L"nt)==\"function\")){d=j(b.fireEvent);d=d==\"object\"||d==\"array\"||d==",
    L"\"function\"}if(d){try{(Q(b)?Q(b).parentWindow||Q(b).defaultView:window",
    L").event=c}catch(e){}b=b.fireEvent(\"onsubmit\",c)}else b=b.dispatchEven",
    L"t(c);b&&a.submit()}\nvar Y=\"_\".split(\".\"),Z=i;!(Y[0]in Z)&&Z.execSc",
    L"ript&&Z.execScript(\"var \"+Y[0]);for(var $;Y.length&&($=Y.shift());)if",
    L"(!Y.length&&ja!==undefined)Z[$]=ja;else Z=Z[$]?Z[$]:Z[$]={};; return _.",
    L"apply(null,arguments);}",
    NULL
};
}
#endif  // ATOMS_H__
