/* AUTO GENERATED - DO NOT EDIT BY HAND */
#ifndef ATOMS_H__
#define ATOMS_H__

#include <stddef.h>  // For wchar_t.

namespace webdriver {

const wchar_t* const GET_ATTRIBUTE[] = {
    L"function(){var e=this;\nfunction f(a){var c=typeof a;if(c==\"object\")i",
    L"f(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.to",
    L"String.call(a)==\"[object Array]\"||typeof a.length==\"number\"&&typeof",
    L" a.splice!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"&",
    L"&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(!(a instanceof ",
    L"Object)&&(Object.prototype.toString.call(a)==\"[object Function]\"||typ",
    L"eof a.call!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"",
    L"&&!a.propertyIsEnumerable(\"call\")))return\"function\"}else return\"nu",
    L"ll\";else if(c==\n\"function\"&&typeof a.call==\"undefined\")return\"ob",
    L"ject\";return c}function h(a,c){function b(){}b.prototype=c.prototype;a",
    L".g=c.prototype;a.prototype=new b};function i(a){this.stack=Error().stac",
    L"k||\"\";if(a)this.message=String(a)}h(i,Error);function j(a){for(var c=",
    L"1;c<arguments.length;c++){var b=String(arguments[c]).replace(/\\$/g,\"$",
    L"$$$\");a=a.replace(/\\%s/,b)}return a}function k(a){return a.replace(/^",
    L"[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\")}function o(a,c){if(a<c)return-1;else i",
    L"f(a>c)return 1;return 0};function p(a,c){c.unshift(a);i.call(this,j.app",
    L"ly(null,c));c.shift();this.h=a}h(p,i);function q(a,c){if(!a){var b=Arra",
    L"y.prototype.slice.call(arguments,2),d=\"Assertion failed\";if(c){d+=\":",
    L" \"+c;var g=b}throw new p(\"\"+d,g||[]);}return a};var r=Array.prototyp",
    L"e,s=r.indexOf?function(a,c,b){q(a.length!=null);return r.indexOf.call(a",
    L",c,b)}:function(a,c,b){b=b==null?0:b<0?Math.max(0,a.length+b):b;if(type",
    L"of a==\"string\"){if(typeof c!=\"string\"||c.length!=1)return-1;return ",
    L"a.indexOf(c,b)}for(b=b;b<a.length;b++)if(b in a&&a[b]===c)return b;retu",
    L"rn-1};var t,u,v,w;function x(){return e.navigator?e.navigator.userAgent",
    L":null}w=v=u=t=false;var y;if(y=x()){var z=e.navigator;t=y.indexOf(\"Ope",
    L"ra\")==0;u=!t&&y.indexOf(\"MSIE\")!=-1;v=!t&&y.indexOf(\"WebKit\")!=-1;",
    L"w=!t&&!v&&z.product==\"Gecko\"}var A=u,B=w,C=v,D;\na:{var E=\"\",F;if(t",
    L"&&e.opera){var G=e.opera.version;E=typeof G==\"function\"?G():G}else{if",
    L"(B)F=/rv\\:([^\\);]+)(\\)|;)/;else if(A)F=/MSIE\\s+([^\\);]+)(\\)|;)/;e",
    L"lse if(C)F=/WebKit\\/(\\S+)/;if(F){var H=F.exec(x());E=H?H[1]:\"\"}}if(",
    L"A){var I,J=e.document;I=J?J.documentMode:undefined;if(I>parseFloat(E)){",
    L"D=String(I);break a}}D=E}var K={};\nfunction L(a){var c;if(!(c=K[a])){c",
    L"=0;var b=k(String(D)).split(\".\"),d=k(String(a)).split(\".\"),g=Math.m",
    L"ax(b.length,d.length);for(var l=0;c==0&&l<g;l++){var X=b[l]||\"\",Y=d[l",
    L"]||\"\",Z=RegExp(\"(\\\\d*)(\\\\D*)\",\"g\"),$=RegExp(\"(\\\\d*)(\\\\D*",
    L")\",\"g\");do{var m=Z.exec(X)||[\"\",\"\",\"\"],n=$.exec(Y)||[\"\",\"\"",
    L",\"\"];if(m[0].length==0&&n[0].length==0)break;c=o(m[1].length==0?0:par",
    L"seInt(m[1],10),n[1].length==0?0:parseInt(n[1],10))||o(m[2].length==0,n[",
    L"2].length==0)||o(m[2],n[2])}while(c==0)}c=K[a]=c>=0}return c};!A||L(\"9",
    L"\");A&&L(\"9\");var M=\"StopIteration\"in e?e.StopIteration:Error(\"Sto",
    L"pIteration\");function N(){}N.prototype.next=function(){throw M;};funct",
    L"ion O(a,c,b,d,g){this.a=!!c;a&&P(this,a,d);this.d=g!=undefined?g:this.c",
    L"||0;if(this.a)this.d*=-1;this.f=!b}h(O,N);O.prototype.b=null;O.prototyp",
    L"e.c=0;O.prototype.e=false;function P(a,c,b,d){if(a.b=c)a.c=typeof b==\"",
    L"number\"?b:a.b.nodeType!=1?0:a.a?-1:1;if(typeof d==\"number\")a.d=d}\nO",
    L".prototype.next=function(){var a;if(this.e){if(!this.b||this.f&&this.d=",
    L"=0)throw M;a=this.b;var c=this.a?-1:1;if(this.c==c){var b=this.a?a.last",
    L"Child:a.firstChild;b?P(this,b):P(this,a,c*-1)}else(b=this.a?a.previousS",
    L"ibling:a.nextSibling)?P(this,b):P(this,a.parentNode,c*-1);this.d+=this.",
    L"c*(this.a?-1:1)}else this.e=true;a=this.b;if(!this.b)throw M;return a};",
    L"\nO.prototype.splice=function(){var a=this.b,c=this.a?1:-1;if(this.c==c",
    L"){this.c=c*-1;this.d+=this.c*(this.a?-1:1)}this.a=!this.a;O.prototype.n",
    L"ext.call(this);this.a=!this.a;c=arguments[0];var b=f(c);c=b==\"array\"|",
    L"|b==\"object\"&&typeof c.length==\"number\"?arguments[0]:arguments;for(",
    L"b=c.length-1;b>=0;b--)a.parentNode&&a.parentNode.insertBefore(c[b],a.ne",
    L"xtSibling);a&&a.parentNode&&a.parentNode.removeChild(a)};function Q(a,c",
    L",b,d){O.call(this,a,c,b,null,d)}h(Q,O);Q.prototype.next=function(){do Q",
    L".g.next.call(this);while(this.c==-1);return this.b};var aa={\"class\":",
    L"\"className\",readonly:\"readOnly\"},R=[\"async\",\"autofocus\",\"autop",
    L"lay\",\"checked\",\"compact\",\"complete\",\"controls\",\"declare\",\"d",
    L"efaultchecked\",\"defaultselected\",\"defer\",\"disabled\",\"draggable",
    L"\",\"ended\",\"formnovalidate\",\"hidden\",\"indeterminate\",\"isconten",
    L"teditable\",\"ismap\",\"itemscope\",\"loop\",\"multiple\",\"muted\",\"n",
    L"ohref\",\"noresize\",\"noshade\",\"novalidate\",\"nowrap\",\"open\",\"p",
    L"aused\",\"pubdate\",\"readonly\",\"required\",\"reversed\",\"scoped\",",
    L"\"seamless\",\"seeking\",\"selected\",\"spellcheck\",\"truespeed\",\"wi",
    L"llvalidate\"];\nfunction ba(a,c){if(8==a.nodeType)return null;c=c.toLow",
    L"erCase();if(c==\"style\"){var b=k(a.style.cssText).toLowerCase();return",
    L" b.charAt(b.length-1)==\";\"?b:b+\";\"}b=a.getAttributeNode(c);if(A)if(",
    L"!b&&L(8)&&s(R,c)>=0)b=a[c];if(!b)return null;if(s(R,c)>=0)return A&&b.v",
    L"alue==\"false\"?null:\"true\";return b.specified?b.value:null};\nvar ca",
    L"=[\"checkbox\",\"radio\"];function S(a){var c=a.tagName.toUpperCase();i",
    L"f(c==\"OPTION\")return true;if(c==\"INPUT\")if(s(ca,a.type)>=0)return t",
    L"rue;return false};function T(a,c){var b=null;b=c.toLowerCase();if(\"sty",
    L"le\"==c.toLowerCase()){if((b=a.style)&&typeof b!=\"string\")b=b.cssText",
    L";return b}if(\"selected\"==b||\"checked\"==b&&S(a)){var d;if(S(a)){d=\"",
    L"selected\";b=a.type&&a.type.toLowerCase();if(\"checkbox\"==b||\"radio\"",
    L"==b)d=\"checked\";d=!!a[d]}else d=false;return d?\"true\":null}var g=a.",
    L"tagName&&\"A\"==a.tagName.toUpperCase();try{d=a[aa[c]||c]}catch(l){}if(",
    L"!(b=b==\"href\"&&g)){if(!(b=d==null)){b=f(d);b=b==\"object\"||b==\"arra",
    L"y\"||b==\"function\"}b=b}b=b?ba(a,c):d;return b!=null?\nb.toString():nu",
    L"ll}var U=\"_\".split(\".\"),V=e;!(U[0]in V)&&V.execScript&&V.execScript",
    L"(\"var \"+U[0]);for(var W;U.length&&(W=U.shift());)if(!U.length&&T!==un",
    L"defined)V[W]=T;else V=V[W]?V[W]:V[W]={};; return _.apply(null,arguments",
    L");}",
    NULL
};

const wchar_t* const GET_TEXT[] = {
    L"function(){var j=this;\nfunction k(a){var b=typeof a;if(b==\"object\")i",
    L"f(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.to",
    L"String.call(a)==\"[object Array]\"||typeof a.length==\"number\"&&typeof",
    L" a.splice!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"&",
    L"&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(!(a instanceof ",
    L"Object)&&(Object.prototype.toString.call(a)==\"[object Function]\"||typ",
    L"eof a.call!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"",
    L"&&!a.propertyIsEnumerable(\"call\")))return\"function\"}else return\"nu",
    L"ll\";else if(b==\n\"function\"&&typeof a.call==\"undefined\")return\"ob",
    L"ject\";return b}function m(a){var b=k(a);return b==\"array\"||b==\"obje",
    L"ct\"&&typeof a.length==\"number\"}function n(a){return typeof a==\"stri",
    L"ng\"}function o(a,b){function c(){}c.prototype=b.prototype;a.h=b.protot",
    L"ype;a.prototype=new c};function p(a){this.stack=Error().stack||\"\";if(",
    L"a)this.message=String(a)}o(p,Error);p.prototype.name=\"CustomError\";fu",
    L"nction aa(a){for(var b=1;b<arguments.length;b++){var c=String(arguments",
    L"[b]).replace(/\\$/g,\"$$$$\");a=a.replace(/\\%s/,c)}return a}function q",
    L"(a){return a.replace(/[\\s\\xa0]+/g,\" \").replace(/^\\s+|\\s+$/g,\"\")",
    L"}function r(a){return a.replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\")}func",
    L"tion s(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};function t(a",
    L",b){b.unshift(a);p.call(this,aa.apply(null,b));b.shift();this.i=a}o(t,p",
    L");t.prototype.name=\"AssertionError\";function u(a,b){if(!a){var c=Arra",
    L"y.prototype.slice.call(arguments,2),d=\"Assertion failed\";if(b){d+=\":",
    L" \"+b;var e=c}throw new t(\"\"+d,e||[]);}return a};var w=Array.prototyp",
    L"e,x=w.indexOf?function(a,b,c){u(a.length!=null);return w.indexOf.call(a",
    L",b,c)}:function(a,b,c){c=c==null?0:c<0?Math.max(0,a.length+c):c;if(n(a)",
    L"){if(!n(b)||b.length!=1)return-1;return a.indexOf(b,c)}for(c=c;c<a.leng",
    L"th;c++)if(c in a&&a[c]===b)return c;return-1},y=w.forEach?function(a,b,",
    L"c){u(a.length!=null);w.forEach.call(a,b,c)}:function(a,b,c){var d=a.len",
    L"gth,e=n(a)?a.split(\"\"):a;for(var f=0;f<d;f++)f in e&&b.call(c,e[f],f,",
    L"a)},ba=w.some?function(a,b,c){u(a.length!=null);return w.some.call(a,\n",
    L"b,c)}:function(a,b,c){var d=a.length,e=n(a)?a.split(\"\"):a;for(var f=0",
    L";f<d;f++)if(f in e&&b.call(c,e[f],f,a))return true;return false};functi",
    L"on z(){return w.concat.apply(w,arguments)}function ca(a){if(k(a)==\"arr",
    L"ay\")return z(a);if(k(a)==\"array\")a=z(a);else{var b=[],c=0;for(var d=",
    L"a.length;c<d;c++)b[c]=a[c];a=b}return a};var A,B,C,D;function da(){retu",
    L"rn j.navigator?j.navigator.userAgent:null}D=C=B=A=false;var E;if(E=da()",
    L"){var ea=j.navigator;A=E.indexOf(\"Opera\")==0;B=!A&&E.indexOf(\"MSIE\"",
    L")!=-1;C=!A&&E.indexOf(\"WebKit\")!=-1;D=!A&&!C&&ea.product==\"Gecko\"}v",
    L"ar fa=A,F=B,ga=D,ha=C,G;\na:{var H=\"\",I;if(fa&&j.opera){var J=j.opera",
    L".version;H=typeof J==\"function\"?J():J}else{if(ga)I=/rv\\:([^\\);]+)(",
    L"\\)|;)/;else if(F)I=/MSIE\\s+([^\\);]+)(\\)|;)/;else if(ha)I=/WebKit\\/",
    L"(\\S+)/;if(I){var ia=I.exec(da());H=ia?ia[1]:\"\"}}if(F){var L,ja=j.doc",
    L"ument;L=ja?ja.documentMode:undefined;if(L>parseFloat(H)){G=String(L);br",
    L"eak a}}G=H}var ka={};\nfunction M(a){var b;if(!(b=ka[a])){b=0;var c=r(S",
    L"tring(G)).split(\".\"),d=r(String(a)).split(\".\"),e=Math.max(c.length,",
    L"d.length);for(var f=0;b==0&&f<e;f++){var i=c[f]||\"\",K=d[f]||\"\",g=Re",
    L"gExp(\"(\\\\d*)(\\\\D*)\",\"g\"),h=RegExp(\"(\\\\d*)(\\\\D*)\",\"g\");d",
    L"o{var l=g.exec(i)||[\"\",\"\",\"\"],v=h.exec(K)||[\"\",\"\",\"\"];if(l[",
    L"0].length==0&&v[0].length==0)break;b=s(l[1].length==0?0:parseInt(l[1],1",
    L"0),v[1].length==0?0:parseInt(v[1],10))||s(l[2].length==0,v[2].length==0",
    L")||s(l[2],v[2])}while(b==0)}b=ka[a]=b>=0}return b};!F||M(\"9\");F&&M(\"",
    L"9\");function N(a,b){this.width=a;this.height=b}N.prototype.toString=fu",
    L"nction(){return\"(\"+this.width+\" x \"+this.height+\")\"};function O(a",
    L"){return a.nodeType==9?a:a.ownerDocument||a.document}function la(a,b){v",
    L"ar c=[];return ma(a,b,c,true)?c[0]:undefined}function ma(a,b,c,d){if(a!",
    L"=null){var e=0;for(var f;f=a.childNodes[e];e++){if(b(f)){c.push(f);if(d",
    L")return true}if(ma(f,b,c,d))return true}}return false}function na(a,b,c",
    L",d){if(!c)a=a.parentNode;c=d==null;for(var e=0;a&&(c||e<=d);){if(b(a))r",
    L"eturn a;a=a.parentNode;e++}return null};function oa(a,b){var c;if(typeo",
    L"f b.selectSingleNode!=\"undefined\"){c=O(b);typeof c.setProperty!=\"und",
    L"efined\"&&c.setProperty(\"SelectionLanguage\",\"XPath\");c=b.selectSing",
    L"leNode(a)}else if(document.implementation.hasFeature(\"XPath\",\"3.0\")",
    L"){c=O(b);var d=c.createNSResolver(c.documentElement);c=c.evaluate(a,b,d",
    L",XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue}else c=null;",
    L"if(!c)return null;if(c.nodeType!=1)throw Error(\"Returned node is not a",
    L"n element: \"+a);return c};var P=\"StopIteration\"in j?j.StopIteration:",
    L"Error(\"StopIteration\");function Q(){}Q.prototype.next=function(){thro",
    L"w P;};Q.prototype.e=function(){return this};function pa(a){if(a instanc",
    L"eof Q)return a;if(typeof a.e==\"function\")return a.e(false);if(m(a)){v",
    L"ar b=0,c=new Q;c.next=function(){for(;;){if(b>=a.length)throw P;if(b in",
    L" a)return a[b++];else b++}};return c}throw Error(\"Not implemented\");}",
    L"\nfunction qa(a,b,c){if(m(a))try{y(a,b,c)}catch(d){if(d!==P)throw d;}el",
    L"se{a=pa(a);try{for(;;)b.call(c,a.next(),undefined,a)}catch(e){if(e!==P)",
    L"throw e;}}}function ra(a){if(m(a))return ca(a);a=pa(a);var b=[];qa(a,fu",
    L"nction(c){b.push(c)});return b};function R(a,b,c,d,e){this.a=!!b;a&&S(t",
    L"his,a,d);this.d=e!=undefined?e:this.c||0;if(this.a)this.d*=-1;this.g=!c",
    L"}o(R,Q);R.prototype.b=null;R.prototype.c=0;R.prototype.f=false;function",
    L" S(a,b,c,d){if(a.b=b)a.c=typeof c==\"number\"?c:a.b.nodeType!=1?0:a.a?-",
    L"1:1;if(typeof d==\"number\")a.d=d}\nR.prototype.next=function(){var a;i",
    L"f(this.f){if(!this.b||this.g&&this.d==0)throw P;a=this.b;var b=this.a?-",
    L"1:1;if(this.c==b){var c=this.a?a.lastChild:a.firstChild;c?S(this,c):S(t",
    L"his,a,b*-1)}else(c=this.a?a.previousSibling:a.nextSibling)?S(this,c):S(",
    L"this,a.parentNode,b*-1);this.d+=this.c*(this.a?-1:1)}else this.f=true;a",
    L"=this.b;if(!this.b)throw P;return a};\nR.prototype.splice=function(){va",
    L"r a=this.b,b=this.a?1:-1;if(this.c==b){this.c=b*-1;this.d+=this.c*(this",
    L".a?-1:1)}this.a=!this.a;R.prototype.next.call(this);this.a=!this.a;b=m(",
    L"arguments[0])?arguments[0]:arguments;for(var c=b.length-1;c>=0;c--)a.pa",
    L"rentNode&&a.parentNode.insertBefore(b[c],a.nextSibling);a&&a.parentNode",
    L"&&a.parentNode.removeChild(a)};function T(a,b,c,d){R.call(this,a,b,c,nu",
    L"ll,d)}o(T,R);T.prototype.next=function(){do T.h.next.call(this);while(t",
    L"his.c==-1);return this.b};function sa(a,b){var c=O(a);if(c.defaultView&",
    L"&c.defaultView.getComputedStyle)if(c=c.defaultView.getComputedStyle(a,n",
    L"ull))return c[b]||c.getPropertyValue(b);return\"\"}var ta={};function u",
    L"a(a){return ta[a]||(ta[a]=String(a).replace(/\\-([a-z])/g,function(b,c)",
    L"{return c.toUpperCase()}))};function U(a,b){return!!a&&a.nodeType==1&&(",
    L"!b||a.tagName.toUpperCase()==b)}\nvar va=[\"async\",\"autofocus\",\"aut",
    L"oplay\",\"checked\",\"compact\",\"complete\",\"controls\",\"declare\",",
    L"\"defaultchecked\",\"defaultselected\",\"defer\",\"disabled\",\"draggab",
    L"le\",\"ended\",\"formnovalidate\",\"hidden\",\"indeterminate\",\"iscont",
    L"enteditable\",\"ismap\",\"itemscope\",\"loop\",\"multiple\",\"muted\",",
    L"\"nohref\",\"noresize\",\"noshade\",\"novalidate\",\"nowrap\",\"open\",",
    L"\"paused\",\"pubdate\",\"readonly\",\"required\",\"reversed\",\"scoped",
    L"\",\"seamless\",\"seeking\",\"selected\",\"spellcheck\",\"truespeed\",",
    L"\"willvalidate\"];\nfunction wa(a,b){if(8==a.nodeType)return null;b=b.t",
    L"oLowerCase();if(b==\"style\"){var c=r(a.style.cssText).toLowerCase();re",
    L"turn c.charAt(c.length-1)==\";\"?c:c+\";\"}c=a.getAttributeNode(b);if(F",
    L")if(!c&&M(8)&&x(va,b)>=0)c=a[b];if(!c)return null;if(x(va,b)>=0)return ",
    L"F&&c.value==\"false\"?null:\"true\";return c.specified?c.value:null}fun",
    L"ction V(a){for(a=a.parentNode;a&&a.nodeType!=1&&a.nodeType!=9&&a.nodeTy",
    L"pe!=11;)a=a.parentNode;return U(a)?a:null}function W(a,b){b=ua(b);retur",
    L"n sa(a,b)||xa(a,b)}\nfunction xa(a,b){var c=(a.currentStyle||a.style)[b",
    L"];if(c!=\"inherit\")return c!==undefined?c:null;return(c=V(a))?xa(c,b):",
    L"null}\nfunction ya(a){if(k(a.getBBox)==\"function\")return a.getBBox();",
    L"var b;var c=fa&&!M(\"10\");if((sa(a,\"display\")||(a.currentStyle?a.cur",
    L"rentStyle.display:null)||a.style.display)!=\"none\")b=c?new N(a.offsetW",
    L"idth||a.clientWidth,a.offsetHeight||a.clientHeight):new N(a.offsetWidth",
    L",a.offsetHeight);else{b=a.style;var d=b.display,e=b.visibility,f=b.posi",
    L"tion;b.visibility=\"hidden\";b.position=\"absolute\";b.display=\"inline",
    L"\";if(c){c=a.offsetWidth||a.clientWidth;a=a.offsetHeight||a.clientHeigh",
    L"t}else{c=a.offsetWidth;a=\na.offsetHeight}b.display=d;b.position=f;b.vi",
    L"sibility=e;b=new N(c,a)}return b}\nfunction X(a){function b(e){if(W(e,",
    L"\"display\")==\"none\")return false;e=V(e);return!e||b(e)}function c(e)",
    L"{var f=ya(e);if(f.height>0&&f.width>0)return true;return ha&&ba(e.child",
    L"Nodes,function(i){return U(i)&&c(i)})}if(!U(a))throw Error(\"Argument t",
    L"o isShown must be of type Element\");if(U(a,\"OPTION\")||U(a,\"OPTGROUP",
    L"\")){var d=na(a,function(e){return U(e,\"SELECT\")});return!!d&&X(d)}if",
    L"(U(a,\"MAP\")){if(!a.name)return false;d=O(a);d=d.evaluate?oa('/descend",
    L"ant::*[@usemap = \"#'+a.name+'\"]',d):la(d,function(e){return U(e)&&\nw",
    L"a(e,\"usemap\")==\"#\"+a.name});return!!d&&X(d)}if(U(a,\"AREA\")){d=na(",
    L"a,function(e){return U(e,\"MAP\")});return!!d&&X(d)}if(U(a,\"INPUT\")&&",
    L"a.type.toLowerCase()==\"hidden\")return false;if(W(a,\"visibility\")==",
    L"\"hidden\")return false;if(!b(a))return false;if(za(a)==0)return false;",
    L"if(!c(a))return false;return true}\nfunction Aa(a){var b=\"\",c=Ba(a),d",
    L"=RegExp(String.fromCharCode(160)+\"$\",\"gm\"),e=RegExp(\"^\"+String.fr",
    L"omCharCode(160),\"gm\"),f=false;y(c,function(i,K){if(i.nodeType==3){var",
    L" g;if(i.nodeType!=3)throw Error(\"Cannot extract text from a node whose",
    L" type is not #text\");if(q(i.nodeValue)==\" \")g=\" \";else if((g=V(i))",
    L"&&X(g)){g=i.nodeValue;g=g.replace(RegExp(String.fromCharCode(160),\"gm",
    L"\"),\" \");g=g=q(g)}else g=\"\";g=r(g);if(g.length){var h;a:{for(h=K-1;",
    L"h>=0;h--){var l=c[h];if(l.nodeType!=3){if(U(l,\"BR\"))h=true;else if(U(",
    L"l)){h=\nW(l,\"display\");h=h==\"block\"||h==\"inline-block\"}else h=fal",
    L"se;break a}}h=false}if(h)g=\"\\n\"+g;else if(K!=0){h=i.nodeValue.match(",
    L"/^\\s/)||i.nodeValue.match(e);if(f||h)g=\" \"+g}}f=i.nodeValue.match(/",
    L"\\s$/)||i.nodeValue.match(d);b+=g}});return b=r(b.replace(/ +/g,\" \"))",
    L"}function Ba(a){a=new T(a);try{a.next();return ra(a)}catch(b){}return[]",
    L"}\nfunction za(a){if(F){if(W(a,\"position\")==\"relative\")return 1;a=W",
    L"(a,\"filter\");return(a=a.match(/^alpha\\(opacity=(\\d*)\\)/)||a.match(",
    L"/^progid:DXImageTransform.Microsoft.Alpha\\(Opacity=(\\d*)\\)/))?Number",
    L"(a[1])/100:1}else return Ca(a)}function Ca(a){var b=1,c=W(a,\"opacity\"",
    L");if(c)b=Number(c);if(a=V(a))b*=Ca(a);return b};\nfunction Da(a){for(;a",
    L";){if(a.tagName&&a.tagName.toLowerCase()==\"head\")return true;try{a=a.",
    L"parentNode}catch(b){return false}}return false};function Ea(a){if(Da(a)",
    L"){var b=O(a);if(a.tagName.toUpperCase()==\"TITLE\"&&(b?b.parentWindow||",
    L"b.defaultView:window)==j.top)return r(b.title);return\"\"}return Aa(a)}",
    L"var Y=\"_\".split(\".\"),Z=j;!(Y[0]in Z)&&Z.execScript&&Z.execScript(\"",
    L"var \"+Y[0]);for(var $;Y.length&&($=Y.shift());)if(!Y.length&&Ea!==unde",
    L"fined)Z[$]=Ea;else Z=Z[$]?Z[$]:Z[$]={};; return _.apply(null,arguments)",
    L";}",
    NULL
};

const wchar_t* const FIND_ELEMENT[] = {
    L"function(){var j=this;\nfunction k(a){var b=typeof a;if(b==\"object\")i",
    L"f(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.to",
    L"String.call(a)==\"[object Array]\"||typeof a.length==\"number\"&&typeof",
    L" a.splice!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"&",
    L"&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(!(a instanceof ",
    L"Object)&&(Object.prototype.toString.call(a)==\"[object Function]\"||typ",
    L"eof a.call!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"",
    L"&&!a.propertyIsEnumerable(\"call\")))return\"function\"}else return\"nu",
    L"ll\";else if(b==\n\"function\"&&typeof a.call==\"undefined\")return\"ob",
    L"ject\";return b}function l(a){var b=k(a);return b==\"array\"||b==\"obje",
    L"ct\"&&typeof a.length==\"number\"}function o(a){return typeof a==\"stri",
    L"ng\"}function p(a){return k(a)==\"function\"}function aa(a){a=k(a);retu",
    L"rn a==\"object\"||a==\"array\"||a==\"function\"}function q(a,b){functio",
    L"n c(){}c.prototype=b.prototype;a.m=b.prototype;a.prototype=new c};funct",
    L"ion r(a){this.stack=Error().stack||\"\";if(a)this.message=String(a)}q(r",
    L",Error);r.prototype.name=\"CustomError\";function ba(a){for(var b=1;b<a",
    L"rguments.length;b++){var c=String(arguments[b]).replace(/\\$/g,\"$$$$\"",
    L");a=a.replace(/\\%s/,c)}return a}function ca(a){return a.replace(/[\\s",
    L"\\xa0]+/g,\" \").replace(/^\\s+|\\s+$/g,\"\")}function s(a){return a.re",
    L"place(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\")}function t(a,b){if(a<b)return-",
    L"1;else if(a>b)return 1;return 0};function u(a,b){b.unshift(a);r.call(th",
    L"is,ba.apply(null,b));b.shift();this.n=a}q(u,r);u.prototype.name=\"Asser",
    L"tionError\";function v(a,b){if(!a){var c=Array.prototype.slice.call(arg",
    L"uments,2),d=\"Assertion failed\";if(b){d+=\": \"+b;var e=c}throw new u(",
    L"\"\"+d,e||[]);}return a};var w=Array.prototype,x=w.indexOf?function(a,b",
    L",c){v(a.length!=null);return w.indexOf.call(a,b,c)}:function(a,b,c){c=c",
    L"==null?0:c<0?Math.max(0,a.length+c):c;if(o(a)){if(!o(b)||b.length!=1)re",
    L"turn-1;return a.indexOf(b,c)}for(c=c;c<a.length;c++)if(c in a&&a[c]===b",
    L")return c;return-1},y=w.forEach?function(a,b,c){v(a.length!=null);w.for",
    L"Each.call(a,b,c)}:function(a,b,c){var d=a.length,e=o(a)?a.split(\"\"):a",
    L";for(var f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},z=w.filter?function(a,",
    L"b,c){v(a.length!=null);return w.filter.call(a,\nb,c)}:function(a,b,c){v",
    L"ar d=a.length,e=[],f=0,g=o(a)?a.split(\"\"):a;for(var m=0;m<d;m++)if(m ",
    L"in g){var h=g[m];if(b.call(c,h,m,a))e[f++]=h}return e},da=w.some?functi",
    L"on(a,b,c){v(a.length!=null);return w.some.call(a,b,c)}:function(a,b,c){",
    L"var d=a.length,e=o(a)?a.split(\"\"):a;for(var f=0;f<d;f++)if(f in e&&b.",
    L"call(c,e[f],f,a))return true;return false};\nfunction A(a,b,c){a:{var d",
    L"=a.length,e=o(a)?a.split(\"\"):a;for(var f=0;f<d;f++)if(f in e&&b.call(",
    L"c,e[f],f,a)){b=f;break a}b=-1}return b<0?null:o(a)?a.charAt(b):a[b]}fun",
    L"ction ea(){return w.concat.apply(w,arguments)}function fa(a){if(k(a)==",
    L"\"array\")return ea(a);if(k(a)==\"array\")a=ea(a);else{var b=[],c=0;for",
    L"(var d=a.length;c<d;c++)b[c]=a[c];a=b}return a};var B,ga,C,ha;function ",
    L"ia(){return j.navigator?j.navigator.userAgent:null}ha=C=ga=B=false;var ",
    L"E;if(E=ia()){var ja=j.navigator;B=E.indexOf(\"Opera\")==0;ga=!B&&E.inde",
    L"xOf(\"MSIE\")!=-1;C=!B&&E.indexOf(\"WebKit\")!=-1;ha=!B&&!C&&ja.product",
    L"==\"Gecko\"}var ka=B,F=ga,la=ha,ma=C,na;\na:{var G=\"\",H;if(ka&&j.oper",
    L"a){var oa=j.opera.version;G=typeof oa==\"function\"?oa():oa}else{if(la)",
    L"H=/rv\\:([^\\);]+)(\\)|;)/;else if(F)H=/MSIE\\s+([^\\);]+)(\\)|;)/;else",
    L" if(ma)H=/WebKit\\/(\\S+)/;if(H){var pa=H.exec(ia());G=pa?pa[1]:\"\"}}i",
    L"f(F){var qa,ra=j.document;qa=ra?ra.documentMode:undefined;if(qa>parseFl",
    L"oat(G)){na=String(qa);break a}}na=G}var sa={};\nfunction I(a){var b;if(",
    L"!(b=sa[a])){b=0;var c=s(String(na)).split(\".\"),d=s(String(a)).split(",
    L"\".\"),e=Math.max(c.length,d.length);for(var f=0;b==0&&f<e;f++){var g=c",
    L"[f]||\"\",m=d[f]||\"\",h=RegExp(\"(\\\\d*)(\\\\D*)\",\"g\"),i=RegExp(\"",
    L"(\\\\d*)(\\\\D*)\",\"g\");do{var n=h.exec(g)||[\"\",\"\",\"\"],D=i.exec",
    L"(m)||[\"\",\"\",\"\"];if(n[0].length==0&&D[0].length==0)break;b=t(n[1].",
    L"length==0?0:parseInt(n[1],10),D[1].length==0?0:parseInt(D[1],10))||t(n[",
    L"2].length==0,D[2].length==0)||t(n[2],D[2])}while(b==0)}b=sa[a]=b>=0}ret",
    L"urn b};var ta;!F||I(\"9\");F&&I(\"9\");function J(a,b){this.width=a;thi",
    L"s.height=b}J.prototype.toString=function(){return\"(\"+this.width+\" x ",
    L"\"+this.height+\")\"};function K(a){return a?new ua(L(a)):ta||(ta=new u",
    L"a)}function va(a,b){if(a.contains&&b.nodeType==1)return a==b||a.contain",
    L"s(b);if(typeof a.compareDocumentPosition!=\"undefined\")return a==b||Bo",
    L"olean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;ret",
    L"urn b==a}function L(a){return a.nodeType==9?a:a.ownerDocument||a.docume",
    L"nt}function wa(a,b){var c=[];return xa(a,b,c,true)?c[0]:undefined}\nfun",
    L"ction xa(a,b,c,d){if(a!=null){var e=0;for(var f;f=a.childNodes[e];e++){",
    L"if(b(f)){c.push(f);if(d)return true}if(xa(f,b,c,d))return true}}return ",
    L"false}function ya(a,b,c,d){if(!c)a=a.parentNode;c=d==null;for(var e=0;a",
    L"&&(c||e<=d);){if(b(a))return a;a=a.parentNode;e++}return null}function ",
    L"ua(a){this.h=a||j.document||document}\nfunction M(a,b,c,d){a=d||a.h;b=b",
    L"&&b!=\"*\"?b.toUpperCase():\"\";if(a.querySelectorAll&&a.querySelector&",
    L"&(!ma||document.compatMode==\"CSS1Compat\"||I(\"528\"))&&(b||c))c=a.que",
    L"rySelectorAll(b+(c?\".\"+c:\"\"));else if(c&&a.getElementsByClassName){",
    L"a=a.getElementsByClassName(c);if(b){d={};var e=0,f=0;for(var g;g=a[f];f",
    L"++)if(b==g.nodeName)d[e++]=g;d.length=e;c=d}else c=a}else{a=a.getElemen",
    L"tsByTagName(b||\"*\");if(c){d={};e=0;for(f=0;g=a[f];f++){b=g.className;",
    L"if(typeof b.split==\"function\"&&x(b.split(/\\s+/),c)>=0)d[e++]=\ng}d.l",
    L"ength=e;c=d}else c=a}return c}ua.prototype.contains=va;var za={};za.b=f",
    L"unction(a,b){if(!a)throw Error(\"No class name specified\");a=s(a);if(a",
    L".split(/\\s+/).length>1)throw Error(\"Compound class names not permitte",
    L"d\");var c=M(K(b),\"*\",a,b);return c.length?c[0]:null};za.e=function(a",
    L",b){if(!a)throw Error(\"No class name specified\");a=s(a);if(a.split(/",
    L"\\s+/).length>1)throw Error(\"Compound class names not permitted\");ret",
    L"urn M(K(b),\"*\",a,b)};var Aa={};Aa.b=function(a,b){if(!p(b.querySelect",
    L"or)&&F&&I(8)&&!aa(b.querySelector))throw Error(\"CSS selection is not s",
    L"upported\");if(!a)throw Error(\"No selector specified\");if(a.split(/,/",
    L").length>1)throw Error(\"Compound selectors not permitted\");a=s(a);var",
    L" c=b.querySelector(a);return c&&c.nodeType==1?c:null};\nAa.e=function(a",
    L",b){if(!p(b.querySelectorAll)&&F&&I(8)&&!aa(b.querySelector))throw Erro",
    L"r(\"CSS selection is not supported\");if(!a)throw Error(\"No selector s",
    L"pecified\");if(a.split(/,/).length>1)throw Error(\"Compound selectors n",
    L"ot permitted\");a=s(a);return b.querySelectorAll(a)};var Ba={};Ba.b=fun",
    L"ction(a,b){var c=K(b),d=o(a)?c.h.getElementById(a):a;if(!d)return null;",
    L"if(d.id==a&&va(b,d))return d;c=M(c,\"*\");return A(c,function(e){return",
    L" e.id==a&&va(b,e)})};Ba.e=function(a,b){var c=M(K(b),\"*\",null,b);retu",
    L"rn z(c,function(d){return d.id==a})};function Ca(a,b){if(typeof a.selec",
    L"tNodes!=\"undefined\"){var c=L(a);typeof c.setProperty!=\"undefined\"&&",
    L"c.setProperty(\"SelectionLanguage\",\"XPath\");return a.selectNodes(b)}",
    L"else if(document.implementation.hasFeature(\"XPath\",\"3.0\")){c=L(a);v",
    L"ar d=c.createNSResolver(c.documentElement);c=c.evaluate(b,a,d,XPathResu",
    L"lt.ORDERED_NODE_SNAPSHOT_TYPE,null);d=[];var e=c.snapshotLength;for(var",
    L" f=0;f<e;f++)d.push(c.snapshotItem(f));return d}else return[]};var N={}",
    L";N.b=function(a,b){var c;if(typeof b.selectSingleNode!=\"undefined\"){c",
    L"=L(b);typeof c.setProperty!=\"undefined\"&&c.setProperty(\"SelectionLan",
    L"guage\",\"XPath\");c=b.selectSingleNode(a)}else if(document.implementat",
    L"ion.hasFeature(\"XPath\",\"3.0\")){c=L(b);var d=c.createNSResolver(c.do",
    L"cumentElement);c=c.evaluate(a,b,d,XPathResult.FIRST_ORDERED_NODE_TYPE,n",
    L"ull).singleNodeValue}else c=null;if(!c)return null;if(c.nodeType!=1)thr",
    L"ow Error(\"Returned node is not an element: \"+a);return c};\nN.e=funct",
    L"ion(a,b){var c=Ca(b,a);y(c,function(d){if(d.nodeType!=1)throw Error(\"R",
    L"eturned nodes must be elements: \"+a);});return c};var O=\"StopIteratio",
    L"n\"in j?j.StopIteration:Error(\"StopIteration\");function P(){}P.protot",
    L"ype.next=function(){throw O;};P.prototype.g=function(){return this};fun",
    L"ction Da(a){if(a instanceof P)return a;if(typeof a.g==\"function\")retu",
    L"rn a.g(false);if(l(a)){var b=0,c=new P;c.next=function(){for(;;){if(b>=",
    L"a.length)throw O;if(b in a)return a[b++];else b++}};return c}throw Erro",
    L"r(\"Not implemented\");}\nfunction Ea(a,b,c){if(l(a))try{y(a,b,c)}catch",
    L"(d){if(d!==O)throw d;}else{a=Da(a);try{for(;;)b.call(c,a.next(),undefin",
    L"ed,a)}catch(e){if(e!==O)throw e;}}}function Fa(a){if(l(a))return fa(a);",
    L"a=Da(a);var b=[];Ea(a,function(c){b.push(c)});return b};function Q(a,b,",
    L"c,d,e){this.a=!!b;a&&R(this,a,d);this.f=e!=undefined?e:this.d||0;if(thi",
    L"s.a)this.f*=-1;this.l=!c}q(Q,P);Q.prototype.c=null;Q.prototype.d=0;Q.pr",
    L"ototype.k=false;function R(a,b,c,d){if(a.c=b)a.d=typeof c==\"number\"?c",
    L":a.c.nodeType!=1?0:a.a?-1:1;if(typeof d==\"number\")a.f=d}\nQ.prototype",
    L".next=function(){var a;if(this.k){if(!this.c||this.l&&this.f==0)throw O",
    L";a=this.c;var b=this.a?-1:1;if(this.d==b){var c=this.a?a.lastChild:a.fi",
    L"rstChild;c?R(this,c):R(this,a,b*-1)}else(c=this.a?a.previousSibling:a.n",
    L"extSibling)?R(this,c):R(this,a.parentNode,b*-1);this.f+=this.d*(this.a?",
    L"-1:1)}else this.k=true;a=this.c;if(!this.c)throw O;return a};\nQ.protot",
    L"ype.splice=function(){var a=this.c,b=this.a?1:-1;if(this.d==b){this.d=b",
    L"*-1;this.f+=this.d*(this.a?-1:1)}this.a=!this.a;Q.prototype.next.call(t",
    L"his);this.a=!this.a;b=l(arguments[0])?arguments[0]:arguments;for(var c=",
    L"b.length-1;c>=0;c--)a.parentNode&&a.parentNode.insertBefore(b[c],a.next",
    L"Sibling);a&&a.parentNode&&a.parentNode.removeChild(a)};function S(a,b,c",
    L",d){Q.call(this,a,b,c,null,d)}q(S,Q);S.prototype.next=function(){do S.m",
    L".next.call(this);while(this.d==-1);return this.c};function Ga(a,b){var ",
    L"c=L(a);if(c.defaultView&&c.defaultView.getComputedStyle)if(c=c.defaultV",
    L"iew.getComputedStyle(a,null))return c[b]||c.getPropertyValue(b);return",
    L"\"\"}var Ha={};function Ia(a){return Ha[a]||(Ha[a]=String(a).replace(/",
    L"\\-([a-z])/g,function(b,c){return c.toUpperCase()}))};function T(a,b){r",
    L"eturn!!a&&a.nodeType==1&&(!b||a.tagName.toUpperCase()==b)}\nvar Ja=[\"a",
    L"sync\",\"autofocus\",\"autoplay\",\"checked\",\"compact\",\"complete\",",
    L"\"controls\",\"declare\",\"defaultchecked\",\"defaultselected\",\"defer",
    L"\",\"disabled\",\"draggable\",\"ended\",\"formnovalidate\",\"hidden\",",
    L"\"indeterminate\",\"iscontenteditable\",\"ismap\",\"itemscope\",\"loop",
    L"\",\"multiple\",\"muted\",\"nohref\",\"noresize\",\"noshade\",\"novalid",
    L"ate\",\"nowrap\",\"open\",\"paused\",\"pubdate\",\"readonly\",\"require",
    L"d\",\"reversed\",\"scoped\",\"seamless\",\"seeking\",\"selected\",\"spe",
    L"llcheck\",\"truespeed\",\"willvalidate\"];\nfunction Ka(a,b){if(8==a.no",
    L"deType)return null;b=b.toLowerCase();if(b==\"style\"){var c=s(a.style.c",
    L"ssText).toLowerCase();return c.charAt(c.length-1)==\";\"?c:c+\";\"}c=a.",
    L"getAttributeNode(b);if(F)if(!c&&I(8)&&x(Ja,b)>=0)c=a[b];if(!c)return nu",
    L"ll;if(x(Ja,b)>=0)return F&&c.value==\"false\"?null:\"true\";return c.sp",
    L"ecified?c.value:null}function U(a){for(a=a.parentNode;a&&a.nodeType!=1&",
    L"&a.nodeType!=9&&a.nodeType!=11;)a=a.parentNode;return T(a)?a:null}funct",
    L"ion V(a,b){b=Ia(b);return Ga(a,b)||La(a,b)}\nfunction La(a,b){var c=(a.",
    L"currentStyle||a.style)[b];if(c!=\"inherit\")return c!==undefined?c:null",
    L";return(c=U(a))?La(c,b):null}\nfunction Ma(a){if(p(a.getBBox))return a.",
    L"getBBox();var b;var c=ka&&!I(\"10\");if((Ga(a,\"display\")||(a.currentS",
    L"tyle?a.currentStyle.display:null)||a.style.display)!=\"none\")b=c?new J",
    L"(a.offsetWidth||a.clientWidth,a.offsetHeight||a.clientHeight):new J(a.o",
    L"ffsetWidth,a.offsetHeight);else{b=a.style;var d=b.display,e=b.visibilit",
    L"y,f=b.position;b.visibility=\"hidden\";b.position=\"absolute\";b.displa",
    L"y=\"inline\";if(c){c=a.offsetWidth||a.clientWidth;a=a.offsetHeight||a.c",
    L"lientHeight}else{c=a.offsetWidth;a=a.offsetHeight}b.display=\nd;b.posit",
    L"ion=f;b.visibility=e;b=new J(c,a)}return b}\nfunction W(a){function b(e",
    L"){if(V(e,\"display\")==\"none\")return false;e=U(e);return!e||b(e)}func",
    L"tion c(e){var f=Ma(e);if(f.height>0&&f.width>0)return true;return ma&&d",
    L"a(e.childNodes,function(g){return T(g)&&c(g)})}if(!T(a))throw Error(\"A",
    L"rgument to isShown must be of type Element\");if(T(a,\"OPTION\")||T(a,",
    L"\"OPTGROUP\")){var d=ya(a,function(e){return T(e,\"SELECT\")});return!!",
    L"d&&W(d)}if(T(a,\"MAP\")){if(!a.name)return false;d=L(a);d=d.evaluate?N.",
    L"b('/descendant::*[@usemap = \"#'+a.name+'\"]',d):wa(d,function(e){retur",
    L"n T(e)&&\nKa(e,\"usemap\")==\"#\"+a.name});return!!d&&W(d)}if(T(a,\"ARE",
    L"A\")){d=ya(a,function(e){return T(e,\"MAP\")});return!!d&&W(d)}if(T(a,",
    L"\"INPUT\")&&a.type.toLowerCase()==\"hidden\")return false;if(V(a,\"visi",
    L"bility\")==\"hidden\")return false;if(!b(a))return false;if(Na(a)==0)re",
    L"turn false;if(!c(a))return false;return true}\nfunction Oa(a){var b=\"",
    L"\",c=Pa(a),d=RegExp(String.fromCharCode(160)+\"$\",\"gm\"),e=RegExp(\"^",
    L"\"+String.fromCharCode(160),\"gm\"),f=false;y(c,function(g,m){if(g.node",
    L"Type==3){var h;if(g.nodeType!=3)throw Error(\"Cannot extract text from ",
    L"a node whose type is not #text\");if(ca(g.nodeValue)==\" \")h=\" \";els",
    L"e if((h=U(g))&&W(h)){h=g.nodeValue;h=h.replace(RegExp(String.fromCharCo",
    L"de(160),\"gm\"),\" \");h=h=ca(h)}else h=\"\";h=s(h);if(h.length){var i;",
    L"a:{for(i=m-1;i>=0;i--){var n=c[i];if(n.nodeType!=3){if(T(n,\"BR\"))i=tr",
    L"ue;else if(T(n)){i=\nV(n,\"display\");i=i==\"block\"||i==\"inline-block",
    L"\"}else i=false;break a}}i=false}if(i)h=\"\\n\"+h;else if(m!=0){i=g.nod",
    L"eValue.match(/^\\s/)||g.nodeValue.match(e);if(f||i)h=\" \"+h}}f=g.nodeV",
    L"alue.match(/\\s$/)||g.nodeValue.match(d);b+=h}});return b=s(b.replace(/",
    L" +/g,\" \"))}function Pa(a){a=new S(a);try{a.next();return Fa(a)}catch(",
    L"b){}return[]}\nfunction Na(a){if(F){if(V(a,\"position\")==\"relative\")",
    L"return 1;a=V(a,\"filter\");return(a=a.match(/^alpha\\(opacity=(\\d*)\\)",
    L"/)||a.match(/^progid:DXImageTransform.Microsoft.Alpha\\(Opacity=(\\d*)",
    L"\\)/))?Number(a[1])/100:1}else return Qa(a)}function Qa(a){var b=1,c=V(",
    L"a,\"opacity\");if(c)b=Number(c);if(a=U(a))b*=Qa(a);return b};var X={},R",
    L"a={};X.j=function(a,b,c){b=M(K(b),\"A\",null,b);return A(b,function(d){",
    L"d=Oa(d);return c&&d.indexOf(a)!=-1||d==a})};X.i=function(a,b,c){b=M(K(b",
    L"),\"A\",null,b);return z(b,function(d){d=Oa(d);return c&&d.indexOf(a)!=",
    L"-1||d==a})};X.b=function(a,b){return X.j(a,b,false)};X.e=function(a,b){",
    L"return X.i(a,b,false)};Ra.b=function(a,b){return X.j(a,b,true)};Ra.e=fu",
    L"nction(a,b){return X.i(a,b,true)};var Sa={};Sa.b=function(a,b){var c=M(",
    L"K(b),\"*\",null,b);return A(c,function(d){return d.getAttribute(\"name",
    L"\")==a||d.name==a})};Sa.e=function(a,b){var c=M(K(b),\"*\",null,b);retu",
    L"rn z(c,function(d){return d.getAttribute(\"name\")==a||d.name==a})};var",
    L" Ta={};Ta.b=function(a,b){return M(K(b),a,null,b)[0]||null};Ta.e=functi",
    L"on(a,b){return M(K(b),a,null,b)};var Ua={className:za,css:Aa,id:Ba,link",
    L"Text:X,name:Sa,partialLinkText:Ra,tagName:Ta,xpath:N};function Va(a,b){",
    L"var c;a:{for(c in a){c=c;break a}c=void 0}if(c){var d=Ua[c];if(d&&p(d.b",
    L"))return d.b(a[c],b||L(j))}throw Error(\"Unsupported locator strategy: ",
    L"\"+c);}var Y=\"_\".split(\".\"),Z=j;!(Y[0]in Z)&&Z.execScript&&Z.execSc",
    L"ript(\"var \"+Y[0]);for(var $;Y.length&&($=Y.shift());)if(!Y.length&&Va",
    L"!==undefined)Z[$]=Va;else Z=Z[$]?Z[$]:Z[$]={};; return _.apply(null,arg",
    L"uments);}",
    NULL
};

const wchar_t* const FIND_ELEMENTS[] = {
    L"function(){var j=this;\nfunction k(a){var b=typeof a;if(b==\"object\")i",
    L"f(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.to",
    L"String.call(a)==\"[object Array]\"||typeof a.length==\"number\"&&typeof",
    L" a.splice!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"&",
    L"&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(!(a instanceof ",
    L"Object)&&(Object.prototype.toString.call(a)==\"[object Function]\"||typ",
    L"eof a.call!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"",
    L"&&!a.propertyIsEnumerable(\"call\")))return\"function\"}else return\"nu",
    L"ll\";else if(b==\n\"function\"&&typeof a.call==\"undefined\")return\"ob",
    L"ject\";return b}function l(a){var b=k(a);return b==\"array\"||b==\"obje",
    L"ct\"&&typeof a.length==\"number\"}function o(a){return typeof a==\"stri",
    L"ng\"}function p(a){return k(a)==\"function\"}function aa(a){a=k(a);retu",
    L"rn a==\"object\"||a==\"array\"||a==\"function\"}function q(a,b){functio",
    L"n c(){}c.prototype=b.prototype;a.m=b.prototype;a.prototype=new c};funct",
    L"ion r(a){this.stack=Error().stack||\"\";if(a)this.message=String(a)}q(r",
    L",Error);r.prototype.name=\"CustomError\";function ba(a){for(var b=1;b<a",
    L"rguments.length;b++){var c=String(arguments[b]).replace(/\\$/g,\"$$$$\"",
    L");a=a.replace(/\\%s/,c)}return a}function ca(a){return a.replace(/[\\s",
    L"\\xa0]+/g,\" \").replace(/^\\s+|\\s+$/g,\"\")}function s(a){return a.re",
    L"place(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\")}function t(a,b){if(a<b)return-",
    L"1;else if(a>b)return 1;return 0};function u(a,b){b.unshift(a);r.call(th",
    L"is,ba.apply(null,b));b.shift();this.n=a}q(u,r);u.prototype.name=\"Asser",
    L"tionError\";function v(a,b){if(!a){var c=Array.prototype.slice.call(arg",
    L"uments,2),d=\"Assertion failed\";if(b){d+=\": \"+b;var e=c}throw new u(",
    L"\"\"+d,e||[]);}return a};var w=Array.prototype,x=w.indexOf?function(a,b",
    L",c){v(a.length!=null);return w.indexOf.call(a,b,c)}:function(a,b,c){c=c",
    L"==null?0:c<0?Math.max(0,a.length+c):c;if(o(a)){if(!o(b)||b.length!=1)re",
    L"turn-1;return a.indexOf(b,c)}for(c=c;c<a.length;c++)if(c in a&&a[c]===b",
    L")return c;return-1},y=w.forEach?function(a,b,c){v(a.length!=null);w.for",
    L"Each.call(a,b,c)}:function(a,b,c){var d=a.length,e=o(a)?a.split(\"\"):a",
    L";for(var f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},z=w.filter?function(a,",
    L"b,c){v(a.length!=null);return w.filter.call(a,\nb,c)}:function(a,b,c){v",
    L"ar d=a.length,e=[],f=0,g=o(a)?a.split(\"\"):a;for(var m=0;m<d;m++)if(m ",
    L"in g){var h=g[m];if(b.call(c,h,m,a))e[f++]=h}return e},da=w.some?functi",
    L"on(a,b,c){v(a.length!=null);return w.some.call(a,b,c)}:function(a,b,c){",
    L"var d=a.length,e=o(a)?a.split(\"\"):a;for(var f=0;f<d;f++)if(f in e&&b.",
    L"call(c,e[f],f,a))return true;return false};\nfunction A(a,b,c){a:{var d",
    L"=a.length,e=o(a)?a.split(\"\"):a;for(var f=0;f<d;f++)if(f in e&&b.call(",
    L"c,e[f],f,a)){b=f;break a}b=-1}return b<0?null:o(a)?a.charAt(b):a[b]}fun",
    L"ction ea(){return w.concat.apply(w,arguments)}function fa(a){if(k(a)==",
    L"\"array\")return ea(a);if(k(a)==\"array\")a=ea(a);else{var b=[],c=0;for",
    L"(var d=a.length;c<d;c++)b[c]=a[c];a=b}return a};var B,ga,C,ha;function ",
    L"ia(){return j.navigator?j.navigator.userAgent:null}ha=C=ga=B=false;var ",
    L"E;if(E=ia()){var ja=j.navigator;B=E.indexOf(\"Opera\")==0;ga=!B&&E.inde",
    L"xOf(\"MSIE\")!=-1;C=!B&&E.indexOf(\"WebKit\")!=-1;ha=!B&&!C&&ja.product",
    L"==\"Gecko\"}var ka=B,F=ga,la=ha,ma=C,na;\na:{var G=\"\",H;if(ka&&j.oper",
    L"a){var oa=j.opera.version;G=typeof oa==\"function\"?oa():oa}else{if(la)",
    L"H=/rv\\:([^\\);]+)(\\)|;)/;else if(F)H=/MSIE\\s+([^\\);]+)(\\)|;)/;else",
    L" if(ma)H=/WebKit\\/(\\S+)/;if(H){var pa=H.exec(ia());G=pa?pa[1]:\"\"}}i",
    L"f(F){var qa,ra=j.document;qa=ra?ra.documentMode:undefined;if(qa>parseFl",
    L"oat(G)){na=String(qa);break a}}na=G}var sa={};\nfunction I(a){var b;if(",
    L"!(b=sa[a])){b=0;var c=s(String(na)).split(\".\"),d=s(String(a)).split(",
    L"\".\"),e=Math.max(c.length,d.length);for(var f=0;b==0&&f<e;f++){var g=c",
    L"[f]||\"\",m=d[f]||\"\",h=RegExp(\"(\\\\d*)(\\\\D*)\",\"g\"),i=RegExp(\"",
    L"(\\\\d*)(\\\\D*)\",\"g\");do{var n=h.exec(g)||[\"\",\"\",\"\"],D=i.exec",
    L"(m)||[\"\",\"\",\"\"];if(n[0].length==0&&D[0].length==0)break;b=t(n[1].",
    L"length==0?0:parseInt(n[1],10),D[1].length==0?0:parseInt(D[1],10))||t(n[",
    L"2].length==0,D[2].length==0)||t(n[2],D[2])}while(b==0)}b=sa[a]=b>=0}ret",
    L"urn b};var ta;!F||I(\"9\");F&&I(\"9\");function J(a,b){this.width=a;thi",
    L"s.height=b}J.prototype.toString=function(){return\"(\"+this.width+\" x ",
    L"\"+this.height+\")\"};function K(a){return a?new ua(L(a)):ta||(ta=new u",
    L"a)}function va(a,b){if(a.contains&&b.nodeType==1)return a==b||a.contain",
    L"s(b);if(typeof a.compareDocumentPosition!=\"undefined\")return a==b||Bo",
    L"olean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;ret",
    L"urn b==a}function L(a){return a.nodeType==9?a:a.ownerDocument||a.docume",
    L"nt}function wa(a,b){var c=[];return xa(a,b,c,true)?c[0]:undefined}\nfun",
    L"ction xa(a,b,c,d){if(a!=null){var e=0;for(var f;f=a.childNodes[e];e++){",
    L"if(b(f)){c.push(f);if(d)return true}if(xa(f,b,c,d))return true}}return ",
    L"false}function ya(a,b,c,d){if(!c)a=a.parentNode;c=d==null;for(var e=0;a",
    L"&&(c||e<=d);){if(b(a))return a;a=a.parentNode;e++}return null}function ",
    L"ua(a){this.h=a||j.document||document}\nfunction M(a,b,c,d){a=d||a.h;b=b",
    L"&&b!=\"*\"?b.toUpperCase():\"\";if(a.querySelectorAll&&a.querySelector&",
    L"&(!ma||document.compatMode==\"CSS1Compat\"||I(\"528\"))&&(b||c))c=a.que",
    L"rySelectorAll(b+(c?\".\"+c:\"\"));else if(c&&a.getElementsByClassName){",
    L"a=a.getElementsByClassName(c);if(b){d={};var e=0,f=0;for(var g;g=a[f];f",
    L"++)if(b==g.nodeName)d[e++]=g;d.length=e;c=d}else c=a}else{a=a.getElemen",
    L"tsByTagName(b||\"*\");if(c){d={};e=0;for(f=0;g=a[f];f++){b=g.className;",
    L"if(typeof b.split==\"function\"&&x(b.split(/\\s+/),c)>=0)d[e++]=\ng}d.l",
    L"ength=e;c=d}else c=a}return c}ua.prototype.contains=va;var za={};za.d=f",
    L"unction(a,b){if(!a)throw Error(\"No class name specified\");a=s(a);if(a",
    L".split(/\\s+/).length>1)throw Error(\"Compound class names not permitte",
    L"d\");var c=M(K(b),\"*\",a,b);return c.length?c[0]:null};za.b=function(a",
    L",b){if(!a)throw Error(\"No class name specified\");a=s(a);if(a.split(/",
    L"\\s+/).length>1)throw Error(\"Compound class names not permitted\");ret",
    L"urn M(K(b),\"*\",a,b)};var Aa={};Aa.d=function(a,b){if(!p(b.querySelect",
    L"or)&&F&&I(8)&&!aa(b.querySelector))throw Error(\"CSS selection is not s",
    L"upported\");if(!a)throw Error(\"No selector specified\");if(a.split(/,/",
    L").length>1)throw Error(\"Compound selectors not permitted\");a=s(a);var",
    L" c=b.querySelector(a);return c&&c.nodeType==1?c:null};\nAa.b=function(a",
    L",b){if(!p(b.querySelectorAll)&&F&&I(8)&&!aa(b.querySelector))throw Erro",
    L"r(\"CSS selection is not supported\");if(!a)throw Error(\"No selector s",
    L"pecified\");if(a.split(/,/).length>1)throw Error(\"Compound selectors n",
    L"ot permitted\");a=s(a);return b.querySelectorAll(a)};var Ba={};Ba.d=fun",
    L"ction(a,b){var c=K(b),d=o(a)?c.h.getElementById(a):a;if(!d)return null;",
    L"if(d.id==a&&va(b,d))return d;c=M(c,\"*\");return A(c,function(e){return",
    L" e.id==a&&va(b,e)})};Ba.b=function(a,b){var c=M(K(b),\"*\",null,b);retu",
    L"rn z(c,function(d){return d.id==a})};function Ca(a,b){if(typeof a.selec",
    L"tNodes!=\"undefined\"){var c=L(a);typeof c.setProperty!=\"undefined\"&&",
    L"c.setProperty(\"SelectionLanguage\",\"XPath\");return a.selectNodes(b)}",
    L"else if(document.implementation.hasFeature(\"XPath\",\"3.0\")){c=L(a);v",
    L"ar d=c.createNSResolver(c.documentElement);c=c.evaluate(b,a,d,XPathResu",
    L"lt.ORDERED_NODE_SNAPSHOT_TYPE,null);d=[];var e=c.snapshotLength;for(var",
    L" f=0;f<e;f++)d.push(c.snapshotItem(f));return d}else return[]};var N={}",
    L";N.d=function(a,b){var c;if(typeof b.selectSingleNode!=\"undefined\"){c",
    L"=L(b);typeof c.setProperty!=\"undefined\"&&c.setProperty(\"SelectionLan",
    L"guage\",\"XPath\");c=b.selectSingleNode(a)}else if(document.implementat",
    L"ion.hasFeature(\"XPath\",\"3.0\")){c=L(b);var d=c.createNSResolver(c.do",
    L"cumentElement);c=c.evaluate(a,b,d,XPathResult.FIRST_ORDERED_NODE_TYPE,n",
    L"ull).singleNodeValue}else c=null;if(!c)return null;if(c.nodeType!=1)thr",
    L"ow Error(\"Returned node is not an element: \"+a);return c};\nN.b=funct",
    L"ion(a,b){var c=Ca(b,a);y(c,function(d){if(d.nodeType!=1)throw Error(\"R",
    L"eturned nodes must be elements: \"+a);});return c};var O=\"StopIteratio",
    L"n\"in j?j.StopIteration:Error(\"StopIteration\");function P(){}P.protot",
    L"ype.next=function(){throw O;};P.prototype.g=function(){return this};fun",
    L"ction Da(a){if(a instanceof P)return a;if(typeof a.g==\"function\")retu",
    L"rn a.g(false);if(l(a)){var b=0,c=new P;c.next=function(){for(;;){if(b>=",
    L"a.length)throw O;if(b in a)return a[b++];else b++}};return c}throw Erro",
    L"r(\"Not implemented\");}\nfunction Ea(a,b,c){if(l(a))try{y(a,b,c)}catch",
    L"(d){if(d!==O)throw d;}else{a=Da(a);try{for(;;)b.call(c,a.next(),undefin",
    L"ed,a)}catch(e){if(e!==O)throw e;}}}function Fa(a){if(l(a))return fa(a);",
    L"a=Da(a);var b=[];Ea(a,function(c){b.push(c)});return b};function Q(a,b,",
    L"c,d,e){this.a=!!b;a&&R(this,a,d);this.f=e!=undefined?e:this.e||0;if(thi",
    L"s.a)this.f*=-1;this.l=!c}q(Q,P);Q.prototype.c=null;Q.prototype.e=0;Q.pr",
    L"ototype.k=false;function R(a,b,c,d){if(a.c=b)a.e=typeof c==\"number\"?c",
    L":a.c.nodeType!=1?0:a.a?-1:1;if(typeof d==\"number\")a.f=d}\nQ.prototype",
    L".next=function(){var a;if(this.k){if(!this.c||this.l&&this.f==0)throw O",
    L";a=this.c;var b=this.a?-1:1;if(this.e==b){var c=this.a?a.lastChild:a.fi",
    L"rstChild;c?R(this,c):R(this,a,b*-1)}else(c=this.a?a.previousSibling:a.n",
    L"extSibling)?R(this,c):R(this,a.parentNode,b*-1);this.f+=this.e*(this.a?",
    L"-1:1)}else this.k=true;a=this.c;if(!this.c)throw O;return a};\nQ.protot",
    L"ype.splice=function(){var a=this.c,b=this.a?1:-1;if(this.e==b){this.e=b",
    L"*-1;this.f+=this.e*(this.a?-1:1)}this.a=!this.a;Q.prototype.next.call(t",
    L"his);this.a=!this.a;b=l(arguments[0])?arguments[0]:arguments;for(var c=",
    L"b.length-1;c>=0;c--)a.parentNode&&a.parentNode.insertBefore(b[c],a.next",
    L"Sibling);a&&a.parentNode&&a.parentNode.removeChild(a)};function S(a,b,c",
    L",d){Q.call(this,a,b,c,null,d)}q(S,Q);S.prototype.next=function(){do S.m",
    L".next.call(this);while(this.e==-1);return this.c};function Ga(a,b){var ",
    L"c=L(a);if(c.defaultView&&c.defaultView.getComputedStyle)if(c=c.defaultV",
    L"iew.getComputedStyle(a,null))return c[b]||c.getPropertyValue(b);return",
    L"\"\"}var Ha={};function Ia(a){return Ha[a]||(Ha[a]=String(a).replace(/",
    L"\\-([a-z])/g,function(b,c){return c.toUpperCase()}))};function T(a,b){r",
    L"eturn!!a&&a.nodeType==1&&(!b||a.tagName.toUpperCase()==b)}\nvar Ja=[\"a",
    L"sync\",\"autofocus\",\"autoplay\",\"checked\",\"compact\",\"complete\",",
    L"\"controls\",\"declare\",\"defaultchecked\",\"defaultselected\",\"defer",
    L"\",\"disabled\",\"draggable\",\"ended\",\"formnovalidate\",\"hidden\",",
    L"\"indeterminate\",\"iscontenteditable\",\"ismap\",\"itemscope\",\"loop",
    L"\",\"multiple\",\"muted\",\"nohref\",\"noresize\",\"noshade\",\"novalid",
    L"ate\",\"nowrap\",\"open\",\"paused\",\"pubdate\",\"readonly\",\"require",
    L"d\",\"reversed\",\"scoped\",\"seamless\",\"seeking\",\"selected\",\"spe",
    L"llcheck\",\"truespeed\",\"willvalidate\"];\nfunction Ka(a,b){if(8==a.no",
    L"deType)return null;b=b.toLowerCase();if(b==\"style\"){var c=s(a.style.c",
    L"ssText).toLowerCase();return c.charAt(c.length-1)==\";\"?c:c+\";\"}c=a.",
    L"getAttributeNode(b);if(F)if(!c&&I(8)&&x(Ja,b)>=0)c=a[b];if(!c)return nu",
    L"ll;if(x(Ja,b)>=0)return F&&c.value==\"false\"?null:\"true\";return c.sp",
    L"ecified?c.value:null}function U(a){for(a=a.parentNode;a&&a.nodeType!=1&",
    L"&a.nodeType!=9&&a.nodeType!=11;)a=a.parentNode;return T(a)?a:null}funct",
    L"ion V(a,b){b=Ia(b);return Ga(a,b)||La(a,b)}\nfunction La(a,b){var c=(a.",
    L"currentStyle||a.style)[b];if(c!=\"inherit\")return c!==undefined?c:null",
    L";return(c=U(a))?La(c,b):null}\nfunction Ma(a){if(p(a.getBBox))return a.",
    L"getBBox();var b;var c=ka&&!I(\"10\");if((Ga(a,\"display\")||(a.currentS",
    L"tyle?a.currentStyle.display:null)||a.style.display)!=\"none\")b=c?new J",
    L"(a.offsetWidth||a.clientWidth,a.offsetHeight||a.clientHeight):new J(a.o",
    L"ffsetWidth,a.offsetHeight);else{b=a.style;var d=b.display,e=b.visibilit",
    L"y,f=b.position;b.visibility=\"hidden\";b.position=\"absolute\";b.displa",
    L"y=\"inline\";if(c){c=a.offsetWidth||a.clientWidth;a=a.offsetHeight||a.c",
    L"lientHeight}else{c=a.offsetWidth;a=a.offsetHeight}b.display=\nd;b.posit",
    L"ion=f;b.visibility=e;b=new J(c,a)}return b}\nfunction W(a){function b(e",
    L"){if(V(e,\"display\")==\"none\")return false;e=U(e);return!e||b(e)}func",
    L"tion c(e){var f=Ma(e);if(f.height>0&&f.width>0)return true;return ma&&d",
    L"a(e.childNodes,function(g){return T(g)&&c(g)})}if(!T(a))throw Error(\"A",
    L"rgument to isShown must be of type Element\");if(T(a,\"OPTION\")||T(a,",
    L"\"OPTGROUP\")){var d=ya(a,function(e){return T(e,\"SELECT\")});return!!",
    L"d&&W(d)}if(T(a,\"MAP\")){if(!a.name)return false;d=L(a);d=d.evaluate?N.",
    L"d('/descendant::*[@usemap = \"#'+a.name+'\"]',d):wa(d,function(e){retur",
    L"n T(e)&&\nKa(e,\"usemap\")==\"#\"+a.name});return!!d&&W(d)}if(T(a,\"ARE",
    L"A\")){d=ya(a,function(e){return T(e,\"MAP\")});return!!d&&W(d)}if(T(a,",
    L"\"INPUT\")&&a.type.toLowerCase()==\"hidden\")return false;if(V(a,\"visi",
    L"bility\")==\"hidden\")return false;if(!b(a))return false;if(Na(a)==0)re",
    L"turn false;if(!c(a))return false;return true}\nfunction Oa(a){var b=\"",
    L"\",c=Pa(a),d=RegExp(String.fromCharCode(160)+\"$\",\"gm\"),e=RegExp(\"^",
    L"\"+String.fromCharCode(160),\"gm\"),f=false;y(c,function(g,m){if(g.node",
    L"Type==3){var h;if(g.nodeType!=3)throw Error(\"Cannot extract text from ",
    L"a node whose type is not #text\");if(ca(g.nodeValue)==\" \")h=\" \";els",
    L"e if((h=U(g))&&W(h)){h=g.nodeValue;h=h.replace(RegExp(String.fromCharCo",
    L"de(160),\"gm\"),\" \");h=h=ca(h)}else h=\"\";h=s(h);if(h.length){var i;",
    L"a:{for(i=m-1;i>=0;i--){var n=c[i];if(n.nodeType!=3){if(T(n,\"BR\"))i=tr",
    L"ue;else if(T(n)){i=\nV(n,\"display\");i=i==\"block\"||i==\"inline-block",
    L"\"}else i=false;break a}}i=false}if(i)h=\"\\n\"+h;else if(m!=0){i=g.nod",
    L"eValue.match(/^\\s/)||g.nodeValue.match(e);if(f||i)h=\" \"+h}}f=g.nodeV",
    L"alue.match(/\\s$/)||g.nodeValue.match(d);b+=h}});return b=s(b.replace(/",
    L" +/g,\" \"))}function Pa(a){a=new S(a);try{a.next();return Fa(a)}catch(",
    L"b){}return[]}\nfunction Na(a){if(F){if(V(a,\"position\")==\"relative\")",
    L"return 1;a=V(a,\"filter\");return(a=a.match(/^alpha\\(opacity=(\\d*)\\)",
    L"/)||a.match(/^progid:DXImageTransform.Microsoft.Alpha\\(Opacity=(\\d*)",
    L"\\)/))?Number(a[1])/100:1}else return Qa(a)}function Qa(a){var b=1,c=V(",
    L"a,\"opacity\");if(c)b=Number(c);if(a=U(a))b*=Qa(a);return b};var X={},R",
    L"a={};X.j=function(a,b,c){b=M(K(b),\"A\",null,b);return A(b,function(d){",
    L"d=Oa(d);return c&&d.indexOf(a)!=-1||d==a})};X.i=function(a,b,c){b=M(K(b",
    L"),\"A\",null,b);return z(b,function(d){d=Oa(d);return c&&d.indexOf(a)!=",
    L"-1||d==a})};X.d=function(a,b){return X.j(a,b,false)};X.b=function(a,b){",
    L"return X.i(a,b,false)};Ra.d=function(a,b){return X.j(a,b,true)};Ra.b=fu",
    L"nction(a,b){return X.i(a,b,true)};var Sa={};Sa.d=function(a,b){var c=M(",
    L"K(b),\"*\",null,b);return A(c,function(d){return d.getAttribute(\"name",
    L"\")==a||d.name==a})};Sa.b=function(a,b){var c=M(K(b),\"*\",null,b);retu",
    L"rn z(c,function(d){return d.getAttribute(\"name\")==a||d.name==a})};var",
    L" Ta={};Ta.d=function(a,b){return M(K(b),a,null,b)[0]||null};Ta.b=functi",
    L"on(a,b){return M(K(b),a,null,b)};var Ua={className:za,css:Aa,id:Ba,link",
    L"Text:X,name:Sa,partialLinkText:Ra,tagName:Ta,xpath:N};function Va(a,b){",
    L"var c;a:{for(c in a){c=c;break a}c=void 0}if(c){var d=Ua[c];if(d&&p(d.b",
    L"))return d.b(a[c],b||L(j))}throw Error(\"Unsupported locator strategy: ",
    L"\"+c);}var Y=\"_\".split(\".\"),Z=j;!(Y[0]in Z)&&Z.execScript&&Z.execSc",
    L"ript(\"var \"+Y[0]);for(var $;Y.length&&($=Y.shift());)if(!Y.length&&Va",
    L"!==undefined)Z[$]=Va;else Z=Z[$]?Z[$]:Z[$]={};; return _.apply(null,arg",
    L"uments);}",
    NULL
};

const wchar_t* const IS_DISPLAYED[] = {
    L"function(){var g=this;\nfunction h(a){var b=typeof a;if(b==\"object\")i",
    L"f(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.to",
    L"String.call(a)==\"[object Array]\"||typeof a.length==\"number\"&&typeof",
    L" a.splice!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"&",
    L"&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(!(a instanceof ",
    L"Object)&&(Object.prototype.toString.call(a)==\"[object Function]\"||typ",
    L"eof a.call!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"",
    L"&&!a.propertyIsEnumerable(\"call\")))return\"function\"}else return\"nu",
    L"ll\";else if(b==\n\"function\"&&typeof a.call==\"undefined\")return\"ob",
    L"ject\";return b}function i(a,b){function c(){}c.prototype=b.prototype;a",
    L".g=b.prototype;a.prototype=new c};function j(a){this.stack=Error().stac",
    L"k||\"\";if(a)this.message=String(a)}i(j,Error);j.prototype.name=\"Custo",
    L"mError\";function aa(a){for(var b=1;b<arguments.length;b++){var c=Strin",
    L"g(arguments[b]).replace(/\\$/g,\"$$$$\");a=a.replace(/\\%s/,c)}return a",
    L"}function k(a){return a.replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\")}func",
    L"tion l(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};function m(a",
    L",b){b.unshift(a);j.call(this,aa.apply(null,b));b.shift();this.h=a}i(m,j",
    L");m.prototype.name=\"AssertionError\";function p(a,b){if(!a){var c=Arra",
    L"y.prototype.slice.call(arguments,2),d=\"Assertion failed\";if(b){d+=\":",
    L" \"+b;var e=c}throw new m(\"\"+d,e||[]);}return a};var q=Array.prototyp",
    L"e,r=q.indexOf?function(a,b,c){p(a.length!=null);return q.indexOf.call(a",
    L",b,c)}:function(a,b,c){c=c==null?0:c<0?Math.max(0,a.length+c):c;if(type",
    L"of a==\"string\"){if(typeof b!=\"string\"||b.length!=1)return-1;return ",
    L"a.indexOf(b,c)}for(c=c;c<a.length;c++)if(c in a&&a[c]===b)return c;retu",
    L"rn-1},ba=q.some?function(a,b,c){p(a.length!=null);return q.some.call(a,",
    L"b,c)}:function(a,b,c){var d=a.length,e=typeof a==\"string\"?a.split(\"",
    L"\"):a;for(var f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return true;\nr",
    L"eturn false};var s,t,u,v;function w(){return g.navigator?g.navigator.us",
    L"erAgent:null}v=u=t=s=false;var x;if(x=w()){var ca=g.navigator;s=x.index",
    L"Of(\"Opera\")==0;t=!s&&x.indexOf(\"MSIE\")!=-1;u=!s&&x.indexOf(\"WebKit",
    L"\")!=-1;v=!s&&!u&&ca.product==\"Gecko\"}var y=s,z=t,da=v,B=u,C;\na:{var",
    L" D=\"\",E;if(y&&g.opera){var F=g.opera.version;D=typeof F==\"function\"",
    L"?F():F}else{if(da)E=/rv\\:([^\\);]+)(\\)|;)/;else if(z)E=/MSIE\\s+([^",
    L"\\);]+)(\\)|;)/;else if(B)E=/WebKit\\/(\\S+)/;if(E){var G=E.exec(w());D",
    L"=G?G[1]:\"\"}}if(z){var H,I=g.document;H=I?I.documentMode:undefined;if(",
    L"H>parseFloat(D)){C=String(H);break a}}C=D}var J={};\nfunction K(a){var ",
    L"b;if(!(b=J[a])){b=0;var c=k(String(C)).split(\".\"),d=k(String(a)).spli",
    L"t(\".\"),e=Math.max(c.length,d.length);for(var f=0;b==0&&f<e;f++){var A",
    L"=c[f]||\"\",ka=d[f]||\"\",la=RegExp(\"(\\\\d*)(\\\\D*)\",\"g\"),ma=RegE",
    L"xp(\"(\\\\d*)(\\\\D*)\",\"g\");do{var n=la.exec(A)||[\"\",\"\",\"\"],o=",
    L"ma.exec(ka)||[\"\",\"\",\"\"];if(n[0].length==0&&o[0].length==0)break;b",
    L"=l(n[1].length==0?0:parseInt(n[1],10),o[1].length==0?0:parseInt(o[1],10",
    L"))||l(n[2].length==0,o[2].length==0)||l(n[2],o[2])}while(b==0)}b=J[a]=b",
    L">=0}return b};!z||K(\"9\");z&&K(\"9\");function L(a,b){this.width=a;thi",
    L"s.height=b}L.prototype.toString=function(){return\"(\"+this.width+\" x ",
    L"\"+this.height+\")\"};function M(a){return a.nodeType==9?a:a.ownerDocum",
    L"ent||a.document}function ea(a,b){var c=[];return N(a,b,c,true)?c[0]:und",
    L"efined}function N(a,b,c,d){if(a!=null){var e=0;for(var f;f=a.childNodes",
    L"[e];e++){if(b(f)){c.push(f);if(d)return true}if(N(f,b,c,d))return true}",
    L"}return false}function O(a,b,c,d){if(!c)a=a.parentNode;c=d==null;for(va",
    L"r e=0;a&&(c||e<=d);){if(b(a))return a;a=a.parentNode;e++}return null};f",
    L"unction fa(a,b){var c;if(typeof b.selectSingleNode!=\"undefined\"){c=M(",
    L"b);typeof c.setProperty!=\"undefined\"&&c.setProperty(\"SelectionLangua",
    L"ge\",\"XPath\");c=b.selectSingleNode(a)}else if(document.implementation",
    L".hasFeature(\"XPath\",\"3.0\")){c=M(b);var d=c.createNSResolver(c.docum",
    L"entElement);c=c.evaluate(a,b,d,XPathResult.FIRST_ORDERED_NODE_TYPE,null",
    L").singleNodeValue}else c=null;if(!c)return null;if(c.nodeType!=1)throw ",
    L"Error(\"Returned node is not an element: \"+a);return c};var P=\"StopIt",
    L"eration\"in g?g.StopIteration:Error(\"StopIteration\");function Q(){}Q.",
    L"prototype.next=function(){throw P;};function R(a,b,c,d,e){this.a=!!b;a&",
    L"&S(this,a,d);this.d=e!=undefined?e:this.c||0;if(this.a)this.d*=-1;this.",
    L"f=!c}i(R,Q);R.prototype.b=null;R.prototype.c=0;R.prototype.e=false;func",
    L"tion S(a,b,c,d){if(a.b=b)a.c=typeof c==\"number\"?c:a.b.nodeType!=1?0:a",
    L".a?-1:1;if(typeof d==\"number\")a.d=d}\nR.prototype.next=function(){var",
    L" a;if(this.e){if(!this.b||this.f&&this.d==0)throw P;a=this.b;var b=this",
    L".a?-1:1;if(this.c==b){var c=this.a?a.lastChild:a.firstChild;c?S(this,c)",
    L":S(this,a,b*-1)}else(c=this.a?a.previousSibling:a.nextSibling)?S(this,c",
    L"):S(this,a.parentNode,b*-1);this.d+=this.c*(this.a?-1:1)}else this.e=tr",
    L"ue;a=this.b;if(!this.b)throw P;return a};\nR.prototype.splice=function(",
    L"){var a=this.b,b=this.a?1:-1;if(this.c==b){this.c=b*-1;this.d+=this.c*(",
    L"this.a?-1:1)}this.a=!this.a;R.prototype.next.call(this);this.a=!this.a;",
    L"b=arguments[0];var c=h(b);b=c==\"array\"||c==\"object\"&&typeof b.lengt",
    L"h==\"number\"?arguments[0]:arguments;for(c=b.length-1;c>=0;c--)a.parent",
    L"Node&&a.parentNode.insertBefore(b[c],a.nextSibling);a&&a.parentNode&&a.",
    L"parentNode.removeChild(a)};function T(a,b,c,d){R.call(this,a,b,c,null,d",
    L")}i(T,R);T.prototype.next=function(){do T.g.next.call(this);while(this.",
    L"c==-1);return this.b};function ga(a,b){var c=M(a);if(c.defaultView&&c.d",
    L"efaultView.getComputedStyle)if(c=c.defaultView.getComputedStyle(a,null)",
    L")return c[b]||c.getPropertyValue(b);return\"\"}var ha={};function ia(a)",
    L"{return ha[a]||(ha[a]=String(a).replace(/\\-([a-z])/g,function(b,c){ret",
    L"urn c.toUpperCase()}))};function U(a,b){return!!a&&a.nodeType==1&&(!b||",
    L"a.tagName.toUpperCase()==b)}\nvar ja=[\"async\",\"autofocus\",\"autopla",
    L"y\",\"checked\",\"compact\",\"complete\",\"controls\",\"declare\",\"def",
    L"aultchecked\",\"defaultselected\",\"defer\",\"disabled\",\"draggable\",",
    L"\"ended\",\"formnovalidate\",\"hidden\",\"indeterminate\",\"iscontented",
    L"itable\",\"ismap\",\"itemscope\",\"loop\",\"multiple\",\"muted\",\"nohr",
    L"ef\",\"noresize\",\"noshade\",\"novalidate\",\"nowrap\",\"open\",\"paus",
    L"ed\",\"pubdate\",\"readonly\",\"required\",\"reversed\",\"scoped\",\"se",
    L"amless\",\"seeking\",\"selected\",\"spellcheck\",\"truespeed\",\"willva",
    L"lidate\"];\nfunction na(a,b){if(8==a.nodeType)return null;b=b.toLowerCa",
    L"se();if(b==\"style\"){var c=k(a.style.cssText).toLowerCase();return c.c",
    L"harAt(c.length-1)==\";\"?c:c+\";\"}c=a.getAttributeNode(b);if(z)if(!c&&",
    L"K(8)&&r(ja,b)>=0)c=a[b];if(!c)return null;if(r(ja,b)>=0)return z&&c.val",
    L"ue==\"false\"?null:\"true\";return c.specified?c.value:null}function V(",
    L"a){for(a=a.parentNode;a&&a.nodeType!=1&&a.nodeType!=9&&a.nodeType!=11;)",
    L"a=a.parentNode;return U(a)?a:null}function W(a,b){b=ia(b);return ga(a,b",
    L")||oa(a,b)}\nfunction oa(a,b){var c=(a.currentStyle||a.style)[b];if(c!=",
    L"\"inherit\")return c!==undefined?c:null;return(c=V(a))?oa(c,b):null}\nf",
    L"unction pa(a){if(h(a.getBBox)==\"function\")return a.getBBox();var b;va",
    L"r c=y&&!K(\"10\");if((ga(a,\"display\")||(a.currentStyle?a.currentStyle",
    L".display:null)||a.style.display)!=\"none\")b=c?new L(a.offsetWidth||a.c",
    L"lientWidth,a.offsetHeight||a.clientHeight):new L(a.offsetWidth,a.offset",
    L"Height);else{b=a.style;var d=b.display,e=b.visibility,f=b.position;b.vi",
    L"sibility=\"hidden\";b.position=\"absolute\";b.display=\"inline\";if(c){",
    L"c=a.offsetWidth||a.clientWidth;a=a.offsetHeight||a.clientHeight}else{c=",
    L"a.offsetWidth;a=a.offsetHeight}b.display=\nd;b.position=f;b.visibility=",
    L"e;b=new L(c,a)}return b}\nfunction X(a){function b(e){if(W(e,\"display",
    L"\")==\"none\")return false;e=V(e);return!e||b(e)}function c(e){var f=pa",
    L"(e);if(f.height>0&&f.width>0)return true;return B&&ba(e.childNodes,func",
    L"tion(A){return U(A)&&c(A)})}if(!U(a))throw Error(\"Argument to isShown ",
    L"must be of type Element\");if(U(a,\"OPTION\")||U(a,\"OPTGROUP\")){var d",
    L"=O(a,function(e){return U(e,\"SELECT\")});return!!d&&X(d)}if(U(a,\"MAP",
    L"\")){if(!a.name)return false;d=M(a);d=d.evaluate?fa('/descendant::*[@us",
    L"emap = \"#'+a.name+'\"]',d):ea(d,function(e){return U(e)&&\nna(e,\"usem",
    L"ap\")==\"#\"+a.name});return!!d&&X(d)}if(U(a,\"AREA\")){d=O(a,function(",
    L"e){return U(e,\"MAP\")});return!!d&&X(d)}if(U(a,\"INPUT\")&&a.type.toLo",
    L"werCase()==\"hidden\")return false;if(W(a,\"visibility\")==\"hidden\")r",
    L"eturn false;if(!b(a))return false;if(qa(a)==0)return false;if(!c(a))ret",
    L"urn false;return true}\nfunction qa(a){if(z){if(W(a,\"position\")==\"re",
    L"lative\")return 1;a=W(a,\"filter\");return(a=a.match(/^alpha\\(opacity=",
    L"(\\d*)\\)/)||a.match(/^progid:DXImageTransform.Microsoft.Alpha\\(Opacit",
    L"y=(\\d*)\\)/))?Number(a[1])/100:1}else return ra(a)}function ra(a){var ",
    L"b=1,c=W(a,\"opacity\");if(c)b=Number(c);if(a=V(a))b*=ra(a);return b};va",
    L"r sa=X,Y=\"_\".split(\".\"),Z=g;!(Y[0]in Z)&&Z.execScript&&Z.execScript",
    L"(\"var \"+Y[0]);for(var $;Y.length&&($=Y.shift());)if(!Y.length&&sa!==u",
    L"ndefined)Z[$]=sa;else Z=Z[$]?Z[$]:Z[$]={};; return _.apply(null,argumen",
    L"ts);}",
    NULL
};

const wchar_t* const IS_ENABLED[] = {
    L"function(){var e=this;function f(a,b){function c(){}c.prototype=b.proto",
    L"type;a.g=b.prototype;a.prototype=new c};function h(a){this.stack=Error(",
    L").stack||\"\";if(a)this.message=String(a)}f(h,Error);function i(a){for(",
    L"var b=1;b<arguments.length;b++){var c=String(arguments[b]).replace(/\\$",
    L"/g,\"$$$$\");a=a.replace(/\\%s/,c)}return a}function j(a){return a.repl",
    L"ace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\")}function m(a,b){if(a<b)return-1;",
    L"else if(a>b)return 1;return 0};function n(a,b){b.unshift(a);h.call(this",
    L",i.apply(null,b));b.shift();this.f=a}f(n,h);function o(a,b){if(!a){var ",
    L"c=Array.prototype.slice.call(arguments,2),d=\"Assertion failed\";if(b){",
    L"d+=\": \"+b;var g=c}throw new n(\"\"+d,g||[]);}return a};var p=Array.pr",
    L"ototype,q=p.indexOf?function(a,b,c){o(a.length!=null);return p.indexOf.",
    L"call(a,b,c)}:function(a,b,c){c=c==null?0:c<0?Math.max(0,a.length+c):c;i",
    L"f(typeof a==\"string\"){if(typeof b!=\"string\"||b.length!=1)return-1;r",
    L"eturn a.indexOf(b,c)}for(c=c;c<a.length;c++)if(c in a&&a[c]===b)return ",
    L"c;return-1};var r,s,u,v;function w(){return e.navigator?e.navigator.use",
    L"rAgent:null}v=u=s=r=false;var x;if(x=w()){var y=e.navigator;r=x.indexOf",
    L"(\"Opera\")==0;s=!r&&x.indexOf(\"MSIE\")!=-1;u=!r&&x.indexOf(\"WebKit\"",
    L")!=-1;v=!r&&!u&&y.product==\"Gecko\"}var z=s,A=v,B=u,C;\na:{var D=\"\",",
    L"E;if(r&&e.opera){var F=e.opera.version;D=typeof F==\"function\"?F():F}e",
    L"lse{if(A)E=/rv\\:([^\\);]+)(\\)|;)/;else if(z)E=/MSIE\\s+([^\\);]+)(\\)",
    L"|;)/;else if(B)E=/WebKit\\/(\\S+)/;if(E){var G=E.exec(w());D=G?G[1]:\"",
    L"\"}}if(z){var H,I=e.document;H=I?I.documentMode:undefined;if(H>parseFlo",
    L"at(D)){C=String(H);break a}}C=D}var J={};\nfunction K(a){var b;if(!(b=J",
    L"[a])){b=0;var c=j(String(C)).split(\".\"),d=j(String(a)).split(\".\"),g",
    L"=Math.max(c.length,d.length);for(var t=0;b==0&&t<g;t++){var S=c[t]||\"",
    L"\",T=d[t]||\"\",U=RegExp(\"(\\\\d*)(\\\\D*)\",\"g\"),V=RegExp(\"(\\\\d*",
    L")(\\\\D*)\",\"g\");do{var k=U.exec(S)||[\"\",\"\",\"\"],l=V.exec(T)||[",
    L"\"\",\"\",\"\"];if(k[0].length==0&&l[0].length==0)break;b=m(k[1].length",
    L"==0?0:parseInt(k[1],10),l[1].length==0?0:parseInt(l[1],10))||m(k[2].len",
    L"gth==0,l[2].length==0)||m(k[2],l[2])}while(b==0)}b=J[a]=b>=0}return b};",
    L"!z||K(\"9\");z&&K(\"9\");function L(a,b,c,d,g){this.c=!!b;if(a){if(this",
    L".b=a)this.d=typeof d==\"number\"?d:this.b.nodeType!=1?0:this.c?-1:1;if(",
    L"typeof void 0==\"number\")this.a=void 0}this.a=g!=undefined?g:this.d||0",
    L";if(this.c)this.a*=-1;this.e=!c}f(L,function(){});L.prototype.b=null;L.",
    L"prototype.d=0;f(function(a,b,c,d){L.call(this,a,b,c,null,d)},L);var M=[",
    L"\"async\",\"autofocus\",\"autoplay\",\"checked\",\"compact\",\"complete",
    L"\",\"controls\",\"declare\",\"defaultchecked\",\"defaultselected\",\"de",
    L"fer\",\"disabled\",\"draggable\",\"ended\",\"formnovalidate\",\"hidden",
    L"\",\"indeterminate\",\"iscontenteditable\",\"ismap\",\"itemscope\",\"lo",
    L"op\",\"multiple\",\"muted\",\"nohref\",\"noresize\",\"noshade\",\"noval",
    L"idate\",\"nowrap\",\"open\",\"paused\",\"pubdate\",\"readonly\",\"requi",
    L"red\",\"reversed\",\"scoped\",\"seamless\",\"seeking\",\"selected\",\"s",
    L"pellcheck\",\"truespeed\",\"willvalidate\"];\nfunction N(a,b){if(8==a.n",
    L"odeType)return null;b=b.toLowerCase();if(b==\"style\"){var c=j(a.style.",
    L"cssText).toLowerCase();return c.charAt(c.length-1)==\";\"?c:c+\";\"}c=a",
    L".getAttributeNode(b);if(z)if(!c&&K(8)&&q(M,b)>=0)c=a[b];if(!c)return nu",
    L"ll;if(q(M,b)>=0)return z&&c.value==\"false\"?null:\"true\";return c.spe",
    L"cified?c.value:null}var O=[\"BUTTON\",\"INPUT\",\"OPTGROUP\",\"OPTION\"",
    L",\"SELECT\",\"TEXTAREA\"];\nfunction P(a){var b=a.tagName.toUpperCase()",
    L";if(!(q(O,b)>=0))return true;if(N(a,\"disabled\"))return false;if(a.par",
    L"entNode&&a.parentNode.nodeType==1&&\"OPTGROUP\"==b||\"OPTION\"==b)retur",
    L"n P(a.parentNode);return true};var Q=P,R=\"_\".split(\".\"),W=e;!(R[0]i",
    L"n W)&&W.execScript&&W.execScript(\"var \"+R[0]);for(var X;R.length&&(X=",
    L"R.shift());)if(!R.length&&Q!==undefined)W[X]=Q;else W=W[X]?W[X]:W[X]={}",
    L";; return _.apply(null,arguments);}",
    NULL
};

const wchar_t* const IS_SELECTED[] = {
    L"function(){var e=this;function f(a,b){function c(){}c.prototype=b.proto",
    L"type;a.g=b.prototype;a.prototype=new c};function h(a){this.stack=Error(",
    L").stack||\"\";if(a)this.message=String(a)}f(h,Error);function k(a){for(",
    L"var b=1;b<arguments.length;b++){var c=String(arguments[b]).replace(/\\$",
    L"/g,\"$$$$\");a=a.replace(/\\%s/,c)}return a}\nfunction l(a,b){var c=0,d",
    L"=String(a).replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").split(\".\"),g=St",
    L"ring(b).replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").split(\".\"),K=Math.",
    L"max(d.length,g.length);for(var p=0;c==0&&p<K;p++){var L=d[p]||\"\",M=g[",
    L"p]||\"\",N=RegExp(\"(\\\\d*)(\\\\D*)\",\"g\"),O=RegExp(\"(\\\\d*)(\\\\D",
    L"*)\",\"g\");do{var i=N.exec(L)||[\"\",\"\",\"\"],j=O.exec(M)||[\"\",\"",
    L"\",\"\"];if(i[0].length==0&&j[0].length==0)break;c=m(i[1].length==0?0:p",
    L"arseInt(i[1],10),j[1].length==0?0:parseInt(j[1],10))||m(i[2].length==0,",
    L"j[2].length==0)||m(i[2],j[2])}while(c==\n0)}return c}function m(a,b){if",
    L"(a<b)return-1;else if(a>b)return 1;return 0};function n(a,b){b.unshift(",
    L"a);h.call(this,k.apply(null,b));b.shift();this.f=a}f(n,h);function o(a,",
    L"b){if(!a){var c=Array.prototype.slice.call(arguments,2),d=\"Assertion f",
    L"ailed\";if(b){d+=\": \"+b;var g=c}throw new n(\"\"+d,g||[]);}return a};",
    L"var q=Array.prototype,r=q.indexOf?function(a,b,c){o(a.length!=null);ret",
    L"urn q.indexOf.call(a,b,c)}:function(a,b,c){c=c==null?0:c<0?Math.max(0,a",
    L".length+c):c;if(typeof a==\"string\"){if(typeof b!=\"string\"||b.length",
    L"!=1)return-1;return a.indexOf(b,c)}for(c=c;c<a.length;c++)if(c in a&&a[",
    L"c]===b)return c;return-1};var s,t,u,v;function w(){return e.navigator?e",
    L".navigator.userAgent:null}v=u=t=s=false;var x;if(x=w()){var y=e.navigat",
    L"or;s=x.indexOf(\"Opera\")==0;t=!s&&x.indexOf(\"MSIE\")!=-1;u=!s&&x.inde",
    L"xOf(\"WebKit\")!=-1;v=!s&&!u&&y.product==\"Gecko\"}var z=t,A=v,B=u,C;\n",
    L"a:{var D=\"\",E;if(s&&e.opera){var F=e.opera.version;D=typeof F==\"func",
    L"tion\"?F():F}else{if(A)E=/rv\\:([^\\);]+)(\\)|;)/;else if(z)E=/MSIE\\s+",
    L"([^\\);]+)(\\)|;)/;else if(B)E=/WebKit\\/(\\S+)/;if(E){var G=E.exec(w()",
    L");D=G?G[1]:\"\"}}if(z){var H,I=e.document;H=I?I.documentMode:undefined;",
    L"if(H>parseFloat(D)){C=String(H);break a}}C=D}var J={};!z||J[\"9\"]||(J[",
    L"\"9\"]=l(C,\"9\")>=0);z&&(J[\"9\"]||(J[\"9\"]=l(C,\"9\")>=0));function ",
    L"P(a,b,c,d,g){this.c=!!b;if(a){if(this.b=a)this.d=typeof d==\"number\"?d",
    L":this.b.nodeType!=1?0:this.c?-1:1;if(typeof void 0==\"number\")this.a=v",
    L"oid 0}this.a=g!=undefined?g:this.d||0;if(this.c)this.a*=-1;this.e=!c}f(",
    L"P,function(){});P.prototype.b=null;P.prototype.d=0;f(function(a,b,c,d){",
    L"P.call(this,a,b,c,null,d)},P);\nvar Q=[\"checkbox\",\"radio\"];function",
    L" R(a){var b;a:{b=a.tagName.toUpperCase();if(b==\"OPTION\")b=true;else{i",
    L"f(b==\"INPUT\")if(r(Q,a.type)>=0){b=true;break a}b=false}}if(!b)return ",
    L"false;b=\"selected\";var c=a.type&&a.type.toLowerCase();if(\"checkbox\"",
    L"==c||\"radio\"==c)b=\"checked\";return!!a[b]}var S=\"_\".split(\".\"),T",
    L"=e;!(S[0]in T)&&T.execScript&&T.execScript(\"var \"+S[0]);for(var U;S.l",
    L"ength&&(U=S.shift());)if(!S.length&&R!==undefined)T[U]=R;else T=T[U]?T[",
    L"U]:T[U]={};; return _.apply(null,arguments);}",
    NULL
};

const wchar_t* const SUBMIT[] = {
    L"function(){var g=this;\nfunction h(a){var c=typeof a;if(c==\"object\")i",
    L"f(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.to",
    L"String.call(a)==\"[object Array]\"||typeof a.length==\"number\"&&typeof",
    L" a.splice!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"&",
    L"&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(!(a instanceof ",
    L"Object)&&(Object.prototype.toString.call(a)==\"[object Function]\"||typ",
    L"eof a.call!=\"undefined\"&&typeof a.propertyIsEnumerable!=\"undefined\"",
    L"&&!a.propertyIsEnumerable(\"call\")))return\"function\"}else return\"nu",
    L"ll\";else if(c==\n\"function\"&&typeof a.call==\"undefined\")return\"ob",
    L"ject\";return c}function k(a,c){function b(){}b.prototype=c.prototype;a",
    L".g=c.prototype;a.prototype=new b};function m(a){this.stack=Error().stac",
    L"k||\"\";if(a)this.message=String(a)}k(m,Error);m.prototype.name=\"Custo",
    L"mError\";function o(a,c){m.call(this,c);this.code=a;this.name=p[a]||p[1",
    L"3]}k(o,m);var p,q={NoSuchElementError:7,NoSuchFrameError:8,UnknownComma",
    L"ndError:9,StaleElementReferenceError:10,ElementNotVisibleError:11,Inval",
    L"idElementStateError:12,UnknownError:13,ElementNotSelectableError:15,XPa",
    L"thLookupError:19,NoSuchWindowError:23,InvalidCookieDomainError:24,Unabl",
    L"eToSetCookieError:25,ModalDialogOpenedError:26,ModalDialogOpenError:27,",
    L"ScriptTimeoutError:28},r={};for(var s in q)r[q[s]]=s;p=r;\no.prototype.",
    L"toString=function(){return\"[\"+this.name+\"] \"+this.message};function",
    L" aa(a){for(var c=1;c<arguments.length;c++){var b=String(arguments[c]).r",
    L"eplace(/\\$/g,\"$$$$\");a=a.replace(/\\%s/,b)}return a}\nfunction t(a,c",
    L"){var b=0,d=String(a).replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").split(",
    L"\".\"),e=String(c).replace(/^[\\s\\xa0]+|[\\s\\xa0]+$/g,\"\").split(\".",
    L"\"),n=Math.max(d.length,e.length);for(var f=0;b==0&&f<n;f++){var l=d[f]",
    L"||\"\",A=e[f]||\"\",u=RegExp(\"(\\\\d*)(\\\\D*)\",\"g\"),v=RegExp(\"(",
    L"\\\\d*)(\\\\D*)\",\"g\");do{var i=u.exec(l)||[\"\",\"\",\"\"],j=v.exec(",
    L"A)||[\"\",\"\",\"\"];if(i[0].length==0&&j[0].length==0)break;b=w(i[1].l",
    L"ength==0?0:parseInt(i[1],10),j[1].length==0?0:parseInt(j[1],10))||w(i[2",
    L"].length==0,j[2].length==0)||w(i[2],j[2])}while(b==\n0)}return b}functi",
    L"on w(a,c){if(a<c)return-1;else if(a>c)return 1;return 0};function x(a,c",
    L"){c.unshift(a);m.call(this,aa.apply(null,c));c.shift();this.j=a}k(x,m);",
    L"x.prototype.name=\"AssertionError\";function ba(a,c){if(!a){var b=Array",
    L".prototype.slice.call(arguments,2),d=\"Assertion failed\";if(c){d+=\": ",
    L"\"+c;var e=b}throw new x(\"\"+d,e||[]);}return a};var y=Array.prototype",
    L",ca=y.indexOf?function(a,c,b){ba(a.length!=null);return y.indexOf.call(",
    L"a,c,b)}:function(a,c,b){b=b==null?0:b<0?Math.max(0,a.length+b):b;if(typ",
    L"eof a==\"string\"){if(typeof c!=\"string\"||c.length!=1)return-1;return",
    L" a.indexOf(c,b)}for(b=b;b<a.length;b++)if(b in a&&a[b]===c)return b;ret",
    L"urn-1};var z,B,C,D;function E(){return g.navigator?g.navigator.userAgen",
    L"t:null}D=C=B=z=false;var F;if(F=E()){var da=g.navigator;z=F.indexOf(\"O",
    L"pera\")==0;B=!z&&F.indexOf(\"MSIE\")!=-1;C=!z&&F.indexOf(\"WebKit\")!=-",
    L"1;D=!z&&!C&&da.product==\"Gecko\"}var G=B,H=D,ea=C,I;\na:{var J=\"\",K;",
    L"if(z&&g.opera){var L=g.opera.version;J=typeof L==\"function\"?L():L}els",
    L"e{if(H)K=/rv\\:([^\\);]+)(\\)|;)/;else if(G)K=/MSIE\\s+([^\\);]+)(\\)|;",
    L")/;else if(ea)K=/WebKit\\/(\\S+)/;if(K){var M=K.exec(E());J=M?M[1]:\"\"",
    L"}}if(G){var N,O=g.document;N=O?O.documentMode:undefined;if(N>parseFloat",
    L"(J)){I=String(N);break a}}I=J}var P={};!G||P[\"9\"]||(P[\"9\"]=t(I,\"9",
    L"\")>=0);G&&(P[\"9\"]||(P[\"9\"]=t(I,\"9\")>=0));function Q(a){return a.",
    L"nodeType==9?a:a.ownerDocument||a.document};var R=\"StopIteration\"in g?",
    L"g.StopIteration:Error(\"StopIteration\");function fa(){}fa.prototype.ne",
    L"xt=function(){throw R;};function S(a,c,b,d,e){this.a=!!c;a&&T(this,a,d)",
    L";this.d=e!=undefined?e:this.c||0;if(this.a)this.d*=-1;this.f=!b}k(S,fa)",
    L";S.prototype.b=null;S.prototype.c=0;S.prototype.e=false;function T(a,c,",
    L"b,d){if(a.b=c)a.c=typeof b==\"number\"?b:a.b.nodeType!=1?0:a.a?-1:1;if(",
    L"typeof d==\"number\")a.d=d}\nS.prototype.next=function(){var a;if(this.",
    L"e){if(!this.b||this.f&&this.d==0)throw R;a=this.b;var c=this.a?-1:1;if(",
    L"this.c==c){var b=this.a?a.lastChild:a.firstChild;b?T(this,b):T(this,a,c",
    L"*-1)}else(b=this.a?a.previousSibling:a.nextSibling)?T(this,b):T(this,a.",
    L"parentNode,c*-1);this.d+=this.c*(this.a?-1:1)}else this.e=true;a=this.b",
    L";if(!this.b)throw R;return a};\nS.prototype.splice=function(){var a=thi",
    L"s.b,c=this.a?1:-1;if(this.c==c){this.c=c*-1;this.d+=this.c*(this.a?-1:1",
    L")}this.a=!this.a;S.prototype.next.call(this);this.a=!this.a;c=arguments",
    L"[0];var b=h(c);c=b==\"array\"||b==\"object\"&&typeof c.length==\"number",
    L"\"?arguments[0]:arguments;for(b=c.length-1;b>=0;b--)a.parentNode&&a.par",
    L"entNode.insertBefore(c[b],a.nextSibling);a&&a.parentNode&&a.parentNode.",
    L"removeChild(a)};function U(a,c,b,d){S.call(this,a,c,b,null,d)}k(U,S);U.",
    L"prototype.next=function(){do U.g.next.call(this);while(this.c==-1);retu",
    L"rn this.b};var ga=G?1:0,ha=[\"dragstart\",\"dragexit\",\"mouseover\",\"",
    L"mouseout\"];\nfunction V(a,c,b){var d=Q(a),e=d?d.parentWindow||d.defaul",
    L"tView:window;b=b||{};var n=b.x||0,f=b.y||0,l=b.button||ga,A=b.bubble||t",
    L"rue,u=null;if(ca(ha,c)>=0)u=b.related||null;var v=!!b.alt,i=!!b.control",
    L",j=!!b.shift;b=!!b.meta;if(a.fireEvent&&d&&d.createEventObject){a=d.cre",
    L"ateEventObject();a.altKey=v;a.h=i;a.metaKey=b;a.shiftKey=j;a.clientX=n;",
    L"a.clientY=f;a.button=l;a.relatedTarget=u}else{a=d.createEvent(\"MouseEv",
    L"ents\");if(a.initMouseEvent)a.initMouseEvent(c,A,true,e,1,0,0,n,f,i,v,j",
    L",b,l,u);else{a.initEvent(c,\nA,true);a.shiftKey=j;a.metaKey=b;a.altKey=",
    L"v;a.ctrlKey=i;a.button=l}}return a}function W(a,c,b){var d=b.keyCode||0",
    L";b=b.charCode||0;var e=Q(a);a=e?e.parentWindow||e.defaultView:window;if",
    L"(H){e=e.createEvent(\"KeyboardEvent\");e.initKeyEvent(c,true,true,a,fal",
    L"se,false,false,false,d,b)}else{if(G)e=e.createEventObject();else{e=e.cr",
    L"eateEvent(\"Events\");e.initEvent(c,true,true);e.charCode=b}e.keyCode=d",
    L"}return e}\nfunction ia(a,c,b){var d=Q(a);b=b||{};var e=b.bubble!==fals",
    L"e,n=!!b.alt,f=!!b.control,l=!!b.shift;b=!!b.meta;if(a.fireEvent&&d&&d.c",
    L"reateEventObject){a=d.createEventObject();a.altKey=n;a.i=f;a.metaKey=b;",
    L"a.shiftKey=l}else{a=d.createEvent(\"HTMLEvents\");a.initEvent(c,e,true)",
    L";a.shiftKey=l;a.metaKey=b;a.altKey=n;a.ctrlKey=f}return a}var X={};X.mo",
    L"usedown=V;X.mousemove=V;X.mouseout=V;X.mouseover=V;X.mouseup=V;X.click=",
    L"V;X.keydown=W;X.keypress=W;X.keyup=W;function ja(a){a:{a=a;for(var c=0;",
    L"a;){if(a&&a.nodeType==1&&a.tagName.toUpperCase()==\"FORM\"){a=a;break a",
    L"}a=a.parentNode;c++}a=null}if(!a)throw new o(12,\"Element was not in a ",
    L"form, so could not submit.\");c=a;var b=(X.submit||ia)(c,\"submit\",voi",
    L"d 0),d;if(!(d=h(c.fireEvent)==\"function\")){d=h(c.fireEvent);d=d==\"ob",
    L"ject\"||d==\"array\"||d==\"function\"}if(d){try{(Q(c)?Q(c).parentWindow",
    L"||Q(c).defaultView:window).event=b}catch(e){}c=c.fireEvent(\"onsubmit\"",
    L",b)}else c=c.dispatchEvent(b);c&&a.submit()}\nvar Y=\"_\".split(\".\"),",
    L"Z=g;!(Y[0]in Z)&&Z.execScript&&Z.execScript(\"var \"+Y[0]);for(var $;Y.",
    L"length&&($=Y.shift());)if(!Y.length&&ja!==undefined)Z[$]=ja;else Z=Z[$]",
    L"?Z[$]:Z[$]={};; return _.apply(null,arguments);}",
    NULL
};
}
#endif  // ATOMS_H__
