java_library(
  name = 'io',
  srcs = glob(['*.java']),
  deps = [
    '//java/client/src/org/openqa/selenium:codecs',
    '//java/client/src/org/openqa/selenium:exceptions',
    '//java/client/src/org/openqa/selenium:platform',
    '//third_party/java/guava-libraries:guava-libraries',
  ],
  visibility = ['PUBLIC'],
)

