java_library(
    name = "io",
    srcs = glob(["*.java"]),
    deps = [
        "//java/client/src/org/openqa/selenium:core",
    ],
    visibility = [
        "//java/client/src/org/openqa/selenium:selenium",
        "//java/client/src/org/openqa/selenium/os:os",
    ],
)
