java_library(
  name = 'io',
  srcs = glob(['*.java']),
  deps = [
    '//java/client/src/org/openqa/selenium:exceptions',
    '//java/client/src/org/openqa/selenium:platform',
    '//third_party/java/guava:guava',
  ],
  visibility = [
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/src/org/openqa/selenium/os:os',
  ],
)

