
java_library(
    name = "node",
    srcs = glob(["*.java"]),
    exported_deps = [
        # Because session id is exposed as part of our APIs
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/server/src/org/openqa/selenium/grid/data:data",
    ],
    deps = [
        "//java/server/src/org/openqa/selenium/grid/sessionmap:sessionmap",
        "//java/server/src/org/openqa/selenium/grid/web:web",
        "//java/server/src/org/openqa/selenium/injector:injector",
        "//third_party/java/guava:guava",
    ],
    visibility = [
        "//java/server/src/org/openqa/selenium/grid/...",
        "//java/server/test/org/openqa/selenium/grid/...",
    ],
)