java_binary(name = 'selenium',
  main_class = 'org.openqa.grid.selenium.GridLauncherV3',
  deps = [
    ':classes',
  ],
)

java_library(name = 'classes',
  srcs = glob(['**/*.java']),
  deps = [
    '//java/client/src/com/thoughtworks/selenium/webdriven:webdriven',
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/src/org/openqa/selenium/chrome:chrome',
    '//java/client/src/org/openqa/selenium/firefox:firefox',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//java/server/src/org/openqa/grid:grid',
    '//java/server/src/org/openqa/selenium/remote/server/log:log',
    '//java/server/src/org/openqa/selenium/remote/server:standalone-server-lib',
    '//java/server/src/org/openqa/selenium/remote/server:server',
    '//third_party/java/gson:gson',
    '//third_party/java/guava:guava',
    '//third_party/java/servlet:servlet-api',
    '//third_party/java/beust:jcommander',
  ],
  visibility = [
    '//java/server/test/org/openqa/grid/e2e:tests',
  ],
)
