package(
    default_visibility = [
        "//dotnet/src/webdriver:__pkg__",
        "//dotnet/test/common:__pkg__",
        "//java/src/org/openqa/selenium/manager:__pkg__",
        "//javascript/selenium-webdriver:__pkg__",
        "//py:__pkg__",
        "//rb:__pkg__",
    ],
)

alias(
    name = "selenium-manager-linux",
    actual = select({
        "//common:use_pinned_browser": "@download_sm_linux//file",
        "//common:stamp": "@download_sm_linux//file",
        "//common:linux": "//rust:selenium-manager-linux",
        "//conditions:default": "@download_sm_linux//file",
    }),
)

alias(
    name = "selenium-manager-macos",
    actual = select({
        "//common:use_pinned_browser": "@download_sm_macos//file",
        "//common:stamp": "@download_sm_macos//file",
        "//common:macos": "//rust:selenium-manager-macos",
        "//conditions:default": "@download_sm_macos//file",
    }),
)

alias(
    name = "selenium-manager-windows",
    actual = select({
        "//common:use_pinned_browser": "@download_sm_windows//file",
        "//common:stamp": "@download_sm_windows//file",
        "//common:windows": "//rust:selenium-manager-windows",
        "//conditions:default": "@download_sm_windows//file",
    }),
)
