
java_library(name = 'commands',
  srcs = glob(['*.java']),
  deps = [
    '//java/client/src/com/thoughtworks/selenium:api',
    '//java/client/src/com/thoughtworks/selenium/webdriven:emulation-api',
    '//java/client/src/org/openqa/selenium:webdriver-api',
    '//java/client/src/org/openqa/selenium/io:io',
    '//third_party/java/guava-libraries:guava-libraries',
  ],
  visibility = [
    '//java/client/src/com/thoughtworks/selenium/webdriven:webdriven',
  ],
)