java_library(
    name = "local",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//java/server/src/org/openqa/selenium/events:events",
        "//java/server/src/org/openqa/selenium/grid/config:config",
    ],
    deps = [
        "//third_party/java/guava:guava",
    ],
    visibility = [
        "//java/server/src/org/openqa/selenium/grid/...",
        "//java/server/test/org/openqa/selenium/events:",
        "//java/server/test/org/openqa/selenium/grid/...",
    ],
)
