
export_file(name = 'previous-esr',
  src = 'prebuilt/Win32/Release/webdriver-firefox-esr-previous.dll',
  out = 'webdriver-firefox-esr-previous.dll',
  visibility = [
    '//javascript/firefox-driver:win-components',
  ],
)

export_file(name = 'latest-esr',
  src = 'prebuilt/Win32/Release/webdriver-firefox-esr-latest.dll',
  out = 'webdriver-firefox-esr-latest.dll',
  visibility = [
    '//javascript/firefox-driver:win-components',
  ],
)

export_file(name = 'previous',
  src = 'prebuilt/Win32/Release/webdriver-firefox-previous.dll',
  out = 'webdriver-firefox-previous.dll',
  visibility = [
    '//javascript/firefox-driver:win-components',
  ],
)

export_file(name = 'latest',
  src = 'prebuilt/Win32/Release/webdriver-firefox-latest.dll',
  out = 'webdriver-firefox-latest.dll',
  visibility = [
    '//javascript/firefox-driver:win-components',
  ],
)

mozilla_xpt(name = 'native-events-xpt',
  src = 'nsINativeEvents.idl',
  fallback = '//cpp/prebuilt:nsINativeEvents.xpt',
  visibility = [ '//javascript/firefox-driver:webdriver' ],
)

mozilla_xpt(name = 'native-mouse-xpt',
  src = 'nsINativeMouse.idl',
  fallback = '//cpp/prebuilt:nsINativeMouse.xpt',
  visibility = [ '//javascript/firefox-driver:webdriver' ],
)

mozilla_xpt(name = 'native-keyboard-xpt',
  src = 'nsINativeKeyboard.idl',
  fallback = '//cpp/prebuilt:nsINativeKeyboard.xpt',
  visibility = [ '//javascript/firefox-driver:webdriver' ],
)

mozilla_xpt(name = 'native-ime-xpt',
  src = 'nsINativeIME.idl',
  fallback = '//cpp/prebuilt:nsINativeIME.xpt',
  visibility = [ '//javascript/firefox-driver:webdriver' ],
)

