#include "nsIArray.idl"
#include "nsIMutableArray.idl"
#include "nsISupportsPrimitives.idl"

[scriptable, uuid(475D9D96-C3D7-4F93-BB30-69B04A39BA04)]
interface nsINativeIME : nsISupports
{
/* Input methods interactions */
/* List of IME engines available for use on this machine (comma-separated) */
void imeGetAvailableEngines(out nsIArray enginesList);

/* Activate the engine - cause it to produce IME input. */
void imeActivateEngine(in string engine, out boolean activationSucceeded);

/* Query whether IME input is active or not. */
void imeIsActivated(out boolean isActive);

/* Get the active engine. May return a value even if the engine is not
 * activated. */
void imeGetActiveEngine(out AString activeEngine);

/* De-activate IME input. */
void imeDeactivate();
};
