#include "nsISupports.idl"
#include "nsISupportsPrimitives.idl"

[scriptable, uuid(EB9123FC-0FDC-4164-BFF5-03B3243931D1)]
interface nsINativeMouse : nsISupports
{
/* Move the mouse from start to end */
void mouseMove(in nsISupports aNode, in long startX, in long startY, in long endX, in long endY);

/* Click the mouse at this point */
void click(in nsISupports aNode, in long x, in long y, in long button);

/* Press a mouse button down */
void mousePress(in nsISupports aNode, in long x, in long y, in long button);

/* Release a mouse button */
void mouseRelease(in nsISupports anode, in long x, in long y, in long button);

/* Double click the mouse at this point */
void doubleClick(in nsISupports aNode, in long x, in long y);
};
