#include "nsISupports.idl"
#include "nsISupportsPrimitives.idl"

[scriptable, uuid(50380A2D-AB4F-4B3F-9A27-CC7DBBA07EE7)]
interface nsINativeKeyboard : nsISupports
{
/* Send keyboard input to the window of this element. May release
 * the modifier keys, depending on the last parameter. */
void sendKeys(in nsISupports aNode, in wstring value, in boolean releaseModifiers);
};
