#include "nsISupports.idl"
#include "nsIArray.idl"
#include "nsIMutableArray.idl"
#include "nsISupportsPrimitives.idl"

[scriptable, uuid(5A86850B-F376-4ae6-860D-53A441CAFCE4)]
interface nsINativeEvents : nsISupports
{
/* Check if there are unhandled keyboard events. */
void hasUnhandledEvents(in nsISupports aNode, out boolean hasEvents);

/* Notifies the x_ignore_nofocus library of switch window events. */
void notifyOfSwitchToWindow(in long windowId);

/* Notifies the x_ignore_nofocus library of close window events. */
void notifyOfCloseWindow(in long windowId);
};
