java_library(
    name = "config",
    srcs = glob(["*.java"]),
    exported_deps = [
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/server/src/org/openqa/selenium/grid/config:config",
        "//java/server/src/org/openqa/selenium/grid/sessionmap:sessionmap",
    ],
    deps = [
        "//java/server/src/org/openqa/selenium/grid/sessionmap/remote:remote",
        "//third_party/java/beust:jcommander",
    ],
    visibility = [
        "//java/server/src/org/openqa/selenium/grid/...",
    ],
)
