SUITES = glob(['**/*Tests.java'])

java_test(name = 'e2e',
  srcs = SUITES,
  deps = [
    ':tests',
    '//third_party/java/junit:junit',
  ],
)

java_library(name = 'tests',
  srcs = glob(['**/*.java'], excludes = SUITES),
  deps = [
    '//java/client/src/com/thoughtworks/selenium:leg-rc',
    '//java/client/src/org/openqa/selenium/chrome:chrome',
    '//java/client/src/org/openqa/selenium/firefox:firefox',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//java/server/src/org/openqa/selenium/remote/server:standalone-server-lib',
    '//java/client/src/org/openqa/selenium/support/ui:wait',
    '//java/server/src/org/openqa/grid:grid',
    '//java/server/src/org/openqa/grid/selenium:classes',
    '//third_party/java/beust:jcommander',
    '//third_party/java/guava:guava',
    '//third_party/java/httpcomponents:httpclient',
    '//third_party/java/junit:junit',
    '//third_party/java/mockito:mockito',
    '//third_party/java/selenium:htmlunit-driver',
    '//third_party/java/servlet:servlet-api',
  ],
)
