SUITES = glob(['**/*Tests.java'])

java_test(name = 'e2e',
  srcs = SUITES,
  deps = [
    ':tests',
    '//third_party/java/junit:junit',
  ],
)

java_library(name = 'tests',
  srcs = glob(['**/*.java'], excludes = SUITES),
  deps = [
    '//java/client/src/com/thoughtworks/selenium:selenium',
    '//java/client/src/org/openqa/selenium/chrome:chrome',
    '//java/client/src/org/openqa/selenium/htmlunit:htmlunit',
    '//java/client/src/org/openqa/selenium/firefox:firefox',
    '//java/client/src/org/openqa/selenium/net:net',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//java/client/src/org/openqa/selenium/support/ui:wait',
    '//java/server/src/org/openqa/selenium/server:server',
    '//java/server/src/org/openqa/grid:grid',
    '//java/server/src/org/openqa/grid/common:common',
    '//java/server/src/org/openqa/grid/selenium:classes',
    '//java/server/src/org/openqa/grid/shared:interfaces',
    '//third_party/java/guava:guava',
    '//third_party/java/httpcomponents:httpclient',
    '//third_party/java/junit:junit',
    '//third_party/java/mockito:mockito',
    '//third_party/java/servlet:servlet-api',
  ],
)
