name: CI - .NET

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build
    uses: ./.github/workflows/bazel.yml
    with:
      name: Build
      os: windows
      run: bazel build //dotnet:all

  integration-tests:
    name: Browser Tests
    uses: ./.github/workflows/bazel.yml
    with:
      name: Browser Tests
      os: windows
      run: |
        bazel test //dotnet/test/common:ElementFindingTest-firefox //dotnet/test/common:ElementFindingTest-chrome
