name: CI - Python

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build
    uses: ./.github/workflows/bazel.yml
    with:
      name: Build
      run: |
        bazel build //py:selenium-wheel //py:selenium-sdist

  unit-tests:
    name: Unit Tests
    needs: build
    uses: ./.github/workflows/bazel.yml
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.14']
        os: [ubuntu, macos, windows]
    with:
      name: Unit Tests (${{ matrix.python-version }}, ${{ matrix.os }})
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      run: bazel test --local_test_jobs 1 //py:unit
