name: CI - Renovate - RBE

on:
  push:
    branches:
      - renovate/*
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pin:
    name: Repin Dependencies
    if: github.event.repository.fork == false
    uses: ./.github/workflows/bazel.yml
    with:
      name: Repin Dependencies
      run: |
        COMMITS="${{ join(github.event.commits.*.message, ' ') }}"
        if [[ "$COMMITS" == *"[java]"* ]]; then
          RULES_JVM_EXTERNAL_REPIN=1 bazel run @maven//:pin
        fi
        if [[ "$COMMITS" == *"[rust]"* ]]; then
          CARGO_BAZEL_REPIN=true bazel run @crates//:all
        fi
        if [[ "$COMMITS" == *"[js]"* ]]; then
          bazel run -- @pnpm//:pnpm install --dir "$PWD" --lockfile-only
        fi
        if [[ "$COMMITS" == *"[dotnet]"* ]]; then
          ./dotnet/update-deps.sh
        fi
        if [[ "$COMMITS" == *"[py]"* ]]; then
          bazel run //py:requirements.update
        fi
        if [[ "$COMMITS" == *"[rb]"* ]]; then
          ./go rb:pin
        fi
      artifact-name: repin-changes

  commit-repins:
    name: Commit Repins
    needs: pin
    if: github.event.repository.fork == false
    uses: ./.github/workflows/commit-changes.yml
    with:
      artifact-name: repin-changes
      commit-message: "Repin dependencies"

  check-format:
    needs: commit-repins
    name: Check format
    if: github.event.repository.fork == false
    uses: ./.github/workflows/bazel.yml
    with:
      name: Check format script run
      caching: false
      ruby-version: jruby-10.0.0.0
      run: ./scripts/github-actions/check-format.sh

  test:
    name: Test
    needs: commit-repins
    if: github.event.repository.fork == false
    uses: ./.github/workflows/bazel.yml
    with:
      name: All RBE tests
      caching: false
      ruby-version: jruby-10.0.0.0
      run: ./scripts/github-actions/ci-build.sh

  ci-gh:
    name: CI - GitHub
    needs: commit-repins
    if: github.event.repository.fork == false
    uses: ./.github/workflows/ci.yml
