name: CI - Rust

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/bazel.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos
          - os: ubuntu
          - os: ubuntu-24.04-arm
          - os: windows
    with:
      name: Tests (${{ matrix.os }})
      os: ${{ matrix.os }}
      rerun-with-debug: true
      run: bazel test --test_env=RUST_BACKTRACE=full --test_env=RUST_TEST_NOCAPTURE=1 --flaky_test_attempts=3 //rust/...
