name: Get Approval

permissions: {}

on:
  workflow_call:
    inputs:
      title:
        description: 'Notification title'
        required: true
        type: string
      message:
        description: 'Notification message'
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  notify:
    name: Send Notification
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_ICON_EMOJI: ":key:"
          SLACK_COLOR: warning
          SLACK_CHANNEL: selenium-tlc
          SLACK_USERNAME: GitHub Workflows
          SLACK_TITLE: ${{ inputs.title }}
          SLACK_MESSAGE: ${{ inputs.message }}
          MSG_MINIMAL: actions url
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

  authorize:
    name: Authorize
    needs: notify
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Approved
        run: echo "Approved"
