name: Release Ready Alert

on:
  pull_request:
    types: [closed]
    paths:
      - 'common/devtools/**'

permissions: {}

jobs:
  notify:
    name: Notify Release Ready
    if: >
      github.event.repository.fork == false &&
      github.event.pull_request.merged == true &&
      github.event.pull_request.head.ref == 'pinned-browser-updates' &&
      contains(github.event.pull_request.title, 'with CDP')
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_ICON_EMOJI: ':rocket:'
          SLACK_COLOR: good
          SLACK_CHANNEL: selenium-tlc
          SLACK_USERNAME: GitHub Workflows
          SLACK_TITLE: Ready for Release
          SLACK_MESSAGE: "CDP was updated in #${{ github.event.pull_request.number }}. Selenium is ready for the next release."
          MSG_MINIMAL: actions url
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
