java_test(
    name = "router",
    srcs = glob(["*.java"]),
    labels = [
        "small",
    ],
    deps = [
        "//java/client/src/org/openqa/selenium/remote/tracing:tracing",
        "//java/client/src/org/openqa/selenium/support:support",
        "//java/server/src/org/openqa/selenium/grid:grid",
        "//java/server/test/org/openqa/selenium/grid/testing:testing",
        "//third_party/java/assertj:assertj",
        "//third_party/java/guava:guava",
        "//third_party/java/junit:junit",
    ],
)
