
java_test(
    name = "router",
    srcs = glob(["*.java"]),
    deps = [
        "//java/server/src/org/openqa/selenium/grid/config:config",
        "//java/server/src/org/openqa/selenium/grid/distributor:distributor",
        "//java/server/src/org/openqa/selenium/grid/distributor/local:local",
        "//java/server/src/org/openqa/selenium/grid/distributor/remote:remote",
        "//java/server/src/org/openqa/selenium/grid/node:node",
        "//java/server/src/org/openqa/selenium/grid/node/local:local",
        "//java/server/src/org/openqa/selenium/grid/node/remote:remote",
        "//java/server/src/org/openqa/selenium/grid/router:router",
        "//java/server/src/org/openqa/selenium/grid/server:server",
        "//java/server/src/org/openqa/selenium/grid/sessionmap:sessionmap",
        "//java/server/src/org/openqa/selenium/grid/sessionmap/local:local",
        "//java/server/src/org/openqa/selenium/grid/sessionmap/remote:remote",
        "//java/server/src/org/openqa/selenium/grid/web:web",
        "//java/server/src/org/openqa/selenium/injector:injector",
        "//third_party/java/guava:guava",
        "//third_party/java/junit:junit",
    ]
)